### PR TITLE
fix debug lib name for libpng

### PR DESCRIPTION
**Pull request by yxlao**
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4055)

### CODE REVIEW

**Review by benjaminum — APPROVED** [review]
Thanks for the quick fix! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4055#-:-MjnfumjDtA_9CzztpmP:b-w3daj9)* status: 0 of 1 files reviewed, all discussions resolved

**Review by benjaminum — CHANGES_REQUESTED** [review]
Please check CI failures. One of them might be related to the BUILD_BYPRODUCTS

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4055#-:-MjngZ5sBA3RDBe9dI6p:bn7p9dk)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by yxlao** [comment]
> Please check CI failures. One of them might be related to the BUILD_BYPRODUCTS
> 
> > _[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4055#-:-MjngZ5sBA3RDBe9dI6p:bn7p9dk)_ status: 0 of 1 files reviewed, all discussions resolved

@barnjamin Right. Reverted back the `BUILD_BYPRODUCTS`. The `Debug` build is tested locally. The CI also seems to be happy now.

**Review by benjaminum — APPROVED** [review]
OK, let's merge after the remaining CI jobs finish :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4055#-:-MkIdDB11sfWM88ju-4W:bq0c4sq)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
