### PR TITLE
Tensor TriangleMesh IO

### PR DESCRIPTION
**Pull request by reyanshsolis**
New behavior:

- `ply`: wrapped legacy custom reader. This is to handle the duplicated vertex issue by Assimp.
- `stl`, `obj`, `off`, `gltf`, `glb`, `fbx`: ready by Assimp directly, not wrapped from legacy. Although they may still have the duplicated vertex issue, they match the behavior of the legacy code.

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5415)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5415)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[`cpp/open3d/t/io/file_format/FileASSIMP.cpp` line 112 at r2](https://reviewable.io/reviews/isl-org/open3d/5415#-NAEY55a7O9CwkQB1pWo:-NANebqjE4DRw1rukUek:b-i97apr) ([raw file](https://github.com/isl-org/open3d/blob/61be815b3b968860568b3afcf394a46641b28fc0/cpp/open3d/t/io/file_format/FileASSIMP.cpp#L112)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

If we are already using single precision in assimp, it's likely that we can directly do a memory copy of the whole vertex and triangle buffer from Assimp. 
</blockquote></details>

`std::memcpy`

**Comment by ZhengyuDiao** [comment]
Now I directly do a memory copy of the whole vertex buffer from assimp, but the triangle in assimp is stored as a struct and can not use memcpy to create triangle tensor in open3d.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5415)* status: all files reviewed, 4 unresolved discussions (waiting on @reyanshsolis and @ZhengyuDiao)

___
*[`cpp/benchmarks/t/io/TriangleMeshIO.cpp` line 61 at r3](https://reviewable.io/reviews/isl-org/open3d/5415#-NAwB2qK5h0CVnwp-87a:-NAwB2qK5h0CVnwp-87b:b3k0nfb) ([raw file](https://github.com/isl-org/open3d/blob/3f69ff75c48164580c3e845a4a70312d55e33790/cpp/benchmarks/t/io/TriangleMeshIO.cpp#L61)):*
> ```cpp
> }
> 
> BENCHMARK_CAPTURE(IOReadLegacyTriangleMesh, CPU, knot_data.GetPath())
> ```

`data::KnotMesh().GetPath()`



_Code quote:_
```cpp
data::KnotMesh
```
___
*[`cpp/benchmarks/t/io/TriangleMeshIO.cpp` line 64 at r3](https://reviewable.io/reviews/isl-org/open3d/5415#-NAwB76e-Zr7WtxiwdXQ:-NAwB76e-Zr7WtxiwdXR:b3k0nfb) ([raw file](https://github.com/isl-org/open3d/blob/3f69ff75c48164580c3e845a4a70312d55e33790/cpp/benchmarks/t/io/TriangleMeshIO.cpp#L64)):*
> ```cpp
>         ->Unit(benchmark::kMillisecond);
> 
> BENCHMARK_CAPTURE(IOReadTensorTriangleMesh, CPU, knot_data.GetPath())
> ```

`data::KnotMesh().GetPath()`
___
*[`cpp/open3d/t/io/file_format/FileASSIMP.cpp` line 31 at r3](https://reviewable.io/reviews/isl-org/open3d/5415#-NAwBJC24TqJKuQcu3qd:-NAwBJC24TqJKuQcu3qe:b90bpd3) ([raw file](https://github.com/isl-org/open3d/blob/3f69ff75c48164580c3e845a4a70312d55e33790/cpp/open3d/t/io/file_format/FileASSIMP.cpp#L31)):*
> ```cpp
> #include <vector>
> 
> #include "assimp/GltfMaterial.h"
> ```

`#include <>` for third-party libs.
___
*[`cpp/open3d/t/io/file_format/FileASSIMP.cpp` line 43 at r3](https://reviewable.io/reviews/isl-org/open3d/5415#-NAwBNjb6gYHV-T8_eWR:-NAwBNjb6gYHV-T8_eWS:b-iiwqbr) ([raw file](https://github.com/isl-org/open3d/blob/3f69ff75c48164580c3e845a4a70312d55e33790/cpp/open3d/t/io/file_format/FileASSIMP.cpp#L43)):*
> ```cpp
> #include "open3d/utility/ProgressReporters.h"
> 
> #define AI_MATKEY_CLEARCOAT_THICKNESS "$mat.clearcoatthickness", 0, 0
> ```

move these before the Assimp header

**Review by ZhengyuDiao — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5415)* status: all files reviewed, 4 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[`cpp/benchmarks/t/io/TriangleMeshIO.cpp` line 61 at r3](https://reviewable.io/reviews/isl-org/open3d/5415#-NAwB2qK5h0CVnwp-87a:-NAx8kdhCsIwrlou3O0d:b-c2ab1w) ([raw file](https://github.com/isl-org/open3d/blob/3f69ff75c48164580c3e845a4a70312d55e33790/cpp/benchmarks/t/io/TriangleMeshIO.cpp#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`data::KnotMesh().GetPath()`
</blockquote></details>

this way can't compile.
___
*[`cpp/benchmarks/t/io/TriangleMeshIO.cpp` line 64 at r3](https://reviewable.io/reviews/isl-org/open3d/5415#-NAwB76e-Zr7WtxiwdXQ:-NAx9CW_C5ZVz6Owr4Z6:b-vztevx) ([raw file](https://github.com/isl-org/open3d/blob/3f69ff75c48164580c3e845a4a70312d55e33790/cpp/benchmarks/t/io/TriangleMeshIO.cpp#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`data::KnotMesh().GetPath()`
</blockquote></details>

can't compile.

**Review by yxlao — APPROVED** [review]

**Comment by yxlao** [comment]
Material and UV support remain to be added. LGTM after CI.

**Pull request merged**
