### PR TITLE
:sparkles: Support multi-threading in the RayCastingScene function to commit scene

### LINKED ISSUE #6050: Support multi-threading in RaycastingScene::CastRays()
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

# Motivation
As casting rays is expensive, it is relevent to call this on multiple thread in parallel for the same scene.
Nevertheless, it is not supported by the current implementation.

# Issue
It raises an error because of the use of rtcCommitScene function.

rtcCommitScene is a function in the Embree ray tracing library used to finalize construction of a scene and make it ready for rendering. The function commits all changes, such as adding or removing geometries or lights, and optimizes the scene for rendering. rtcCommitScene is a crucial step in the ray tracing process, as it allows for efficient traversal of the scene for ray intersection tests. Without the use of rtcCommitScene, the quality and performance of the rendered image may be impacted. 

# Solution
Instead, we could use rtcJoinCommitScene.

rtcJoinCommitScene is useful for multi-threaded rendering, where different threads can update a scene in parallel. rtcJoinCommitScene allows multiple threads to wait for all updates to the scene to complete before continuing with the rendering.

### References

https://man.archlinux.org/man/community/embree/rtcJoinCommitScene.3embree3.en

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sebastienmascha**
Support multi-threading in the RayCastingScene function to commit scene.

## Type

-   [ ] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [x] New feature (non-breaking change which adds functionality). Resolves #6050
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

See #6050 

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [x] This PR changes Open3D behavior or adds new functionality.
    -   [x] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [x] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

See #6050 

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6051)

### CODE REVIEW

**Review by benjaminum — CHANGES_REQUESTED** [review]
@sebastienmascha Can you add a unit test checking if RayCastingScene is threadsafe?

> *[Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6051#-:-NS6XM5f22MUttbOnL3R:b-p7n0f9)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by ssheorey** [comment]
Hi @sebastienmascha thanks for submitting this PR! Gentle reminder about addressing @benjaminum 's comment (add unit test).

**Comment by benjaminum** [comment]
@sebastienmascha Let us know if help is needed with the unit test

**Review by benjaminum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6051#-:-Nd137Go2mn1PFYpsOYu:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by ssheorey** [comment]
Strange unit test error in WIndows  (OFF, ON, OFF, Release). Will check if this re-occurs:

```
D:\a\Open3D\Open3D\cpp\tests\t\pipelines\registration\Registration.cpp(280): error: The difference between reg_colored_t.fitness_ and reg_colored_l.fitness_ is 0.20490959870645309, which exceeds 0.05, where
reg_colored_t.fitness_ evaluates to 0.71993973247096865,
reg_colored_l.fitness_ evaluates to 0.92484933117742174, and
0.05 evaluates to 0.050000000000000003.
D:\a\Open3D\Open3D\cpp\tests\t\pipelines\registration\Registration.cpp(282): error: The difference between reg_colored_t.inlier_rmse_ and reg_colored_l.inlier_rmse_ is 0.13259293800465694, which exceeds 0.02, where
reg_colored_t.inlier_rmse_ evaluates to 0.34763052771474739,
reg_colored_l.inlier_rmse_ evaluates to 0.21503758971009046, and
0.02 evaluates to 0.02.
[  FAILED  ] Registration/RegistrationPermuteDevices.ICPColored/0, where GetParam() = 8-byte object <00-00 00-00 00-00 00-00> (42341 ms)
[ RUN      ] Registration/RegistrationPermuteDevices.ICPPointToPlane/0
```

**Pull request merged**
