### PR TITLE
Fix the textures loading in .glb file

### PR DESCRIPTION
**Pull request by ZhengyuDiao**
Now both .png and .jpg textures are supported.

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5443)

### CODE REVIEW

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5443)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @errissa and @ZhengyuDiao)

___
*[`cpp/open3d/io/ImageIO.h` line 55 at r1](https://reviewable.io/reviews/isl-org/open3d/5443#-N9gDh1I5N_8WocTU3Xi:-N9gDh1I5N_8WocTU3Xj:bl6c7t4) ([raw file](https://github.com/isl-org/open3d/blob/9e35b7759b81e7c0dcc667c938f0ec3ec1b13b77/cpp/open3d/io/ImageIO.h#L55)):*
> ```objc
> /// The function calls read functions based on format of image.
> /// \return return true if the read function is successful, false otherwise.
> bool ReadImageFromMemroy(const std::string &image_format,
> ```

Spelling error with `Memroy` -> `Memory`
___
*[`cpp/open3d/io/ImageIO.cpp` line 114 at r1](https://reviewable.io/reviews/isl-org/open3d/5443#-N9gE41uDCPj2G6yMucR:-N9gE41uDCPj2G6yMucS:by24eu2) ([raw file](https://github.com/isl-org/open3d/blob/9e35b7759b81e7c0dcc667c938f0ec3ec1b13b77/cpp/open3d/io/ImageIO.cpp#L114)):*
> ```cpp
> }
> 
> bool ReadImageFromMemroy(const std::string &image_format,
> ```

Same spelling error - see above.

**Review by ZhengyuDiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5443)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @errissa)

___
*[`cpp/open3d/io/ImageIO.h` line 55 at r1](https://reviewable.io/reviews/isl-org/open3d/5443#-N9gDh1I5N_8WocTU3Xi:-N9gZ7ebB_kO29zuw7gL:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/9e35b7759b81e7c0dcc667c938f0ec3ec1b13b77/cpp/open3d/io/ImageIO.h#L55)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Spelling error with `Memroy` -> `Memory`
</blockquote></details>

Done.
___
*[`cpp/open3d/io/ImageIO.cpp` line 114 at r1](https://reviewable.io/reviews/isl-org/open3d/5443#-N9gE41uDCPj2G6yMucR:-N9gZ8GDDpPTg13KEtcF:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/9e35b7759b81e7c0dcc667c938f0ec3ec1b13b77/cpp/open3d/io/ImageIO.cpp#L114)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Same spelling error - see above.
</blockquote></details>

Done.

**Review by yxlao — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5443)* status: all files reviewed, 5 unresolved discussions (waiting on @errissa and @ZhengyuDiao)

___
*[`cpp/open3d/io/ImageIO.h` line 55 at r2](https://reviewable.io/reviews/isl-org/open3d/5443#-N9iGVaI6kCdZs6zgN0l:-N9iGVaI6kCdZs6zgN0m:b-cmam56) ([raw file](https://github.com/isl-org/open3d/blob/405ac4717ef781ad78bac1efe907c5152fc669a2/cpp/open3d/io/ImageIO.h#L55)):*
> ```objc
> /// The function calls read functions based on format of image.
> /// \return return true if the read function is successful, false otherwise.
> bool ReadImageFromMemory(const std::string &image_format,
> ```

- Use the `\param` tag to describe each parameter.
- I would also specify what `image_format` can be in the doc strings.
___
*[`cpp/open3d/io/file_format/FileASSIMP.cpp` line 27 at r2](https://reviewable.io/reviews/isl-org/open3d/5443#-N9iH8iR6AuB2D8mEHp8:-N9iH8iR6AuB2D8mEHp9:bgxvlgn) ([raw file](https://github.com/isl-org/open3d/blob/405ac4717ef781ad78bac1efe907c5152fc669a2/cpp/open3d/io/file_format/FileASSIMP.cpp#L27)):*
> ```cpp
> // ----------------------------------------------------------------------------
> 
> #include <png.h>
> ```

we can move this header to the image reader function, it should be possible to remove the header in fileassimp.cpp
___
*[`cpp/open3d/io/file_format/FileASSIMP.cpp` line 101 at r2](https://reviewable.io/reviews/isl-org/open3d/5443#-N9iHH0v76EjE41UvdhS:-N9iHH0v76EjE41UvdhT:btu04nw) ([raw file](https://github.com/isl-org/open3d/blob/405ac4717ef781ad78bac1efe907c5152fc669a2/cpp/open3d/io/file_format/FileASSIMP.cpp#L101)):*
> ```cpp
>                     auto image = io::CreateImageFromMemory(
>                             "png",
>                             reinterpret_cast<const unsigned char*>(
> ```

Pointer cast can be `static_cast`. If `static_cast` works, prefer `static_cast` to `reinterpret_cast`.

**Review by ZhengyuDiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5443)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @errissa and @yxlao)

___
*[`cpp/open3d/io/ImageIO.h` line 55 at r2](https://reviewable.io/reviews/isl-org/open3d/5443#-N9iGVaI6kCdZs6zgN0l:-N9jlTOO79Zk2uRINqWU:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/405ac4717ef781ad78bac1efe907c5152fc669a2/cpp/open3d/io/ImageIO.h#L55)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

- Use the `\param` tag to describe each parameter.
- I would also specify what `image_format` can be in the doc strings.
</blockquote></details>

Done.
___
*[`cpp/open3d/io/file_format/FileASSIMP.cpp` line 27 at r2](https://reviewable.io/reviews/isl-org/open3d/5443#-N9iH8iR6AuB2D8mEHp8:-N9jlVTfAn3g0sEBYbvK:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/405ac4717ef781ad78bac1efe907c5152fc669a2/cpp/open3d/io/file_format/FileASSIMP.cpp#L27)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can move this header to the image reader function, it should be possible to remove the header in fileassimp.cpp
</blockquote></details>

Done.
___
*[`cpp/open3d/io/file_format/FileASSIMP.cpp` line 101 at r2](https://reviewable.io/reviews/isl-org/open3d/5443#-N9iHH0v76EjE41UvdhS:-N9jlYNA5RY7pZzmMAfP:blri90i) ([raw file](https://github.com/isl-org/open3d/blob/405ac4717ef781ad78bac1efe907c5152fc669a2/cpp/open3d/io/file_format/FileASSIMP.cpp#L101)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Pointer cast can be `static_cast`. If `static_cast` works, prefer `static_cast` to `reinterpret_cast`.
</blockquote></details>

`static_cast` doesn't work here.

**Comment by yxlao** [comment]
1. Find jpg and png data from GLTF samples
2. Upload dataset to https://github.com/isl-org/open3d_downloads/releases/tag/20220301-data
3. Add two datasets to `cpp/open3d/data/Dataset.h` `cpp/pybind/data/data.cpp`
4. Add docs for loading this dataset in `docs/tutorial/data/index.rst`
5. Add a unit test to load this dataset

**Review by yxlao — APPROVED** [review]

**Pull request merged**
