### PR TITLE
Simplify data_ and data_interface_ in KDTreeFlann.

### LINKED ISSUE #6235: KDTreeFlann search error with step by step run
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I have a raw points (Point Cloud):

```
pts.shape, pts.dtype, pts
((16384, 3), dtype('float64'), array([[-31.31369972...9332435]]))
```

First, I create a KDTree with those pts:

```python
tree = o3d.geometry.KDTreeFlann(pts.T)  # pts: Nx3 PointCloud
```

Second, I search the first point of pts 4 time and print the search result:

```python
for i in range(4):
    [_, idx, _] = tree.search_radius_vector_3d(pts[1], 1.0)
    print(idx)
```

And I get the right output:

```
IntVector[394, 8041, 13635, 8113, 8973, 8188, 7123, 12216, 10548, 4917, 12064, 7143, 12259, 10308, 7851, 11758, 7895, 6135, 6029, 15343, 13311, 900, 13522, 1754, 15737, 15095, 13257, 16065, 8997, 2104, 7788, 15170, 16380, 11741, 10534, 11297, 14786, 2958, 12394, 13639, 2518, 8299, 8166, 2005, 11585, 11278, 3435, 138, 3111, 14269, 3733, 4541, 12016, 15167, 708, 9356, 5590, 1720, 8538, 14302, 1021, 7559, 6001, 6838, 7665, 1514, 4528, 11021, 6099, 3882, 3538, 8620, 5909, 11504, 1418, 4362]
IntVector[394, 8041, 13635, 8113, 8973, 8188, 7123, 12216, 10548, 4917, 12064, 7143, 12259, 10308, 7851, 11758, 7895, 6135, 6029, 15343, 13311, 900, 13522, 1754, 15737, 15095, 13257, 16065, 8997, 2104, 7788, 15170, 16380, 11741, 10534, 11297, 14786, 2958, 12394, 13639, 2518, 8299, 8166, 2005, 11585, 11278, 3435, 138, 3111, 14269, 3733, 4541, 12016, 15167, 708, 9356, 5590, 1720, 8538, 14302, 1021, 7559, 6001, 6838, 7665, 1514, 4528, 11021, 6099, 3882, 3538, 8620, 5909, 11504, 1418, 4362]
IntVector[394, 8041, 13635, 8113, 8973, 8188, 7123, 12216, 10548, 4917, 12064, 7143, 12259, 10308, 7851, 11758, 7895, 6135, 6029, 15343, 13311, 900, 13522, 1754, 15737, 15095, 13257, 16065, 8997, 2104, 7788, 15170, 16380, 11741, 10534, 11297, 14786, 2958, 12394, 13639, 2518, 8299, 8166, 2005, 11585, 11278, 3435, 138, 3111, 14269, 3733, 4541, 12016, 15167, 708, 9356, 5590, 1720, 8538, 14302, 1021, 7559, 6001, 6838, 7665, 1514, 4528, 11021, 6099, 3882, 3538, 8620, 5909, 11504, 1418, 4362]
IntVector[394, 8041, 13635, 8113, 8973, 8188, 7123, 12216, 10548, 4917, 12064, 7143, 12259, 10308, 7851, 11758, 7895, 6135, 6029, 15343, 13311, 900, 13522, 1754, 15737, 15095, 13257, 16065, 8997, 2104, 7788, 15170, 16380, 11741, 10534, 11297, 14786, 2958, 12394, 13639, 2518, 8299, 8166, 2005, 11585, 11278, 3435, 138, 3111, 14269, 3733, 4541, 12016, 15167, 708, 9356, 5590, 1720, 8538, 14302, 1021, 7559, 6001, 6838, 7665, 1514, 4528, 11021, 6099, 3882, 3538, 8620, 5909, 11504, 1418, 4362]
```

However, when I next execute the search code again, it is wrong as:

image
 You can see, when I execute the same code second time, it return null idx!

### Steps to reproduce the bug

```python
This happen occasional.
```

### Error message

I have a raw points (Point Cloud):

```
pts.shape, pts.dtype, pts
((16384, 3), dtype('float64'), array([[-31.31369972...9332435]]))
```

First, I create a KDTree with those pts:

```python
tree = o3d.geometry.KDTreeFlann(pts.T)  # pts: Nx3 PointCloud
```

Second, I search the first point of pts 4 time and print the search result:

```python
for i in range(4):
    [_, idx, _] = tree.search_radius_vector_3d(pts[1], 1.0)
    print(idx)
```

And I get the right output:

```
IntVector[394, 8041, 13635, 8113, 8973, 8188, 7123, 12216, 10548, 4917, 12064, 7143, 12259, 10308, 7851, 11758, 7895, 6135, 6029, 15343, 13311, 900, 13522, 1754, 15737, 15095, 13257, 16065, 8997, 2104, 7788, 15170, 16380, 11741, 10534, 11297, 14786, 2958, 12394, 13639, 2518, 8299, 8166, 2005, 11585, 11278, 3435, 138, 3111, 14269, 3733, 4541, 12016, 15167, 708, 9356, 5590, 1720, 8538, 14302, 1021, 7559, 6001, 6838, 7665, 1514, 4528, 11021, 6099, 3882, 3538, 8620, 5909, 11504, 1418, 4362]
IntVector[394, 8041, 13635, 8113, 8973, 8188, 7123, 12216, 10548, 4917, 12064, 7143, 12259, 10308, 7851, 11758, 7895, 6135, 6029, 15343, 13311, 900, 13522, 1754, 15737, 15095, 13257, 16065, 8997, 2104, 7788, 15170, 16380, 11741, 10534, 11297, 14786, 2958, 12394, 13639, 2518, 8299, 8166, 2005, 11585, 11278, 3435, 138, 3111, 14269, 3733, 4541, 12016, 15167, 708, 9356, 5590, 1720, 8538, 14302, 1021, 7559, 6001, 6838, 7665, 1514, 4528, 11021, 6099, 3882, 3538, 8620, 5909, 11504, 1418, 4362]
IntVector[394, 8041, 13635, 8113, 8973, 8188, 7123, 12216, 10548, 4917, 12064, 7143, 12259, 10308, 7851, 11758, 7895, 6135, 6029, 15343, 13311, 900, 13522, 1754, 15737, 15095, 13257, 16065, 8997, 2104, 7788, 15170, 16380, 11741, 10534, 11297, 14786, 2958, 12394, 13639, 2518, 8299, 8166, 2005, 11585, 11278, 3435, 138, 3111, 14269, 3733, 4541, 12016, 15167, 708, 9356, 5590, 1720, 8538, 14302, 1021, 7559, 6001, 6838, 7665, 1514, 4528, 11021, 6099, 3882, 3538, 8620, 5909, 11504, 1418, 4362]
IntVector[394, 8041, 13635, 8113, 8973, 8188, 7123, 12216, 10548, 4917, 12064, 7143, 12259, 10308, 7851, 11758, 7895, 6135, 6029, 15343, 13311, 900, 13522, 1754, 15737, 15095, 13257, 16065, 8997, 2104, 7788, 15170, 16380, 11741, 10534, 11297, 14786, 2958, 12394, 13639, 2518, 8299, 8166, 2005, 11585, 11278, 3435, 138, 3111, 14269, 3733, 4541, 12016, 15167, 708, 9356, 5590, 1720, 8538, 14302, 1021, 7559, 6001, 6838, 7665, 1514, 4528, 11021, 6099, 3882, 3538, 8620, 5909, 11504, 1418, 4362]
```

However, when I next execute the search code again, it is wrong as:

image
 You can see, when I execute the same code second time, it return null idx!

### Expected behavior

_No response_

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.7
- Open3D version: 0.17.0
- System architecture: x86
- Is this a remote workstation?: My wsl2
- How did you install Open3D?: pip
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by PieroV**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6235 (there might be others related)
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

`KDTreeFlann::SetRawData` had some confusion around `data`, `data_`, and `data_interface_`.

As a result, the data from the parameter was copied to the member `std::vector`, but the interface (which uses an `Eigen::Map`) used the data passed as an argument to the method.
As a result, the searches risked to be run on a dangling pointer, instead of the intended internal storage.

This produced unexpected/wrong results sometimes.

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
    - I have not updated any documentation, because I'm fixing a bug
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

The most surgical change would make change the existing `Eigen::Map` to refer the internal storage.

However, I noticed that the 4 members (`data_`, `data_interface_`, `dimension_`, `dataset_size_`) were all to be kept in sync.
So, I preferred simplifying the code, copy the argument to an `Eigen::MatrixXd` and remove everything else (I replaced the dataset size and dimension with the rows and cols of the new matrix, and the matrix itself is the owner of the storage).

I noticed the data was `protected`, rather than `private`, but the build didn't break.
I will update the fix if subclasses are borken.

### CODE REVIEW

**Comment by PieroV** [comment]
> I have some problems in getting clang-format-10, so I didn't

Seriously though, the CI could at least give a patch to apply to make the formatting pass :sweat_smile:.

**Comment by ssheorey** [comment]
> > I have some problems in getting clang-format-10, so I didn't
> 
> Seriously though, the CI could at least give a patch to apply to make the formatting pass 😅.

Sorry about that - the CI script can actually fix the formatting for you:

`cd build; make apply-style` or 
`python util/check_style.py --apply`

A great quality of life improvement would be to make an automatic bot commit this in the CI.

**Comment by PieroV** [comment]
No worries, eventually I managed to format :smile:.

> clang-format-10 should be (perpetually?) available through `pip install clang-format~=10.0`

Thanks, I didn't know this!
I ran `clang-format-10` in an Ubuntu live VM creted on the fly instead :joy:. Installing with `pip` should be definitely easier :slightly_smiling_face:.

**Review by ssheorey — APPROVED** [review]
Thanks @PieroV . Looks good!

**Pull request merged**
