### PR TITLE
[CodeStyle] Update license header

### PR DESCRIPTION
**Pull request by BeingGod**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

Update license header years from 2023 to 2024.

### CODE REVIEW

**Comment by ssheorey** [comment]
Hi @BeingGod thanks for the license update. Can you update it in all the files? Otherwise the style check will not pass.

**Comment by BeingGod** [comment]
> Hi @BeingGod thanks for the license update. Can you update it in all the files? Otherwise the style check will not pass.

Acknowledge. Thanks a lot.

**Comment by BeingGod** [comment]
@ssheorey Can you help me to trigger CI ？

**Comment by BeingGod** [comment]
@ssheorey This PR is ready. Can you help me merge it ?

**Review by ssheorey — APPROVED** [review]
Thank you @BeingGod looks good. I also replaced some license text with the SPDX license identifier.

**Pull request merged**
