### PR TITLE
ICP Tutorial (Tensor Pipeline Registration)

### PR DESCRIPTION
**Pull request by reyanshsolis**
Changes in ICP:
- `ICP` function gets optional `voxel_size` parameter. 
- `save_debug_info` option to save values of parameters such as `fitness`, `inlier_rmse`, to plot convergence graph (helps in tuning performance). 

Resolves 
- #1257, 
- #3571, 
- #3570, 
- #3559, 
- #2901

- For `no_correspondence` case, ICP does not throw `Warning` instead of `Error` and the `RegistrationResult` saves `fitness` and `inlier_rmse` as `0.0`, and `transformation` as `Identity`. Resolves 
- #4041

Added Tutorials. 
Resolves 
- #4170

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4271)

### CODE REVIEW

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4271)* status: all files reviewed, 7 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 89 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo76hmb8J6fehPVbB64:-Mo76hmb8J6fehPVbB65:b8l13io) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.h#L89)):*
> ```objc
>     ///
>     /// \param transformation The estimated transformation matrix of dtype
>     /// Float64 on CPU device.
> ```

add doc for save_info_map. Could be a bit confusing as ICP is also related to the information matrix. Consider something like save_loss_log?
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 215 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77O_l1Z6_G8-Gagqc:-Mo77O_l1Z6_G8-Gagqd:b-8eicpj) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L215)):*
> ```cpp
>     std::vector<t::geometry::PointCloud> target_down_pyramid(num_iterations);
> 
>     if (voxel_sizes[num_iterations - 1] < 0) {
> ```

<= 0?
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 229 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77QT77fCXcCFFnD3Y:-Mo77QT77fCXcCFFnD3Z:bb7od0r) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L229)):*
> ```cpp
>                 TransformationEstimationType::ColoredICP &&
>         !target.HasPointAttr("color_gradients")) {
>         if (voxel_sizes[num_iterations - 1] < 0) {
> ```

same
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 237 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77S8tAqyewAtwiCWS:-Mo77S8u6Mxanho6up-W:b-xlkrnx) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L237)):*
> ```cpp
>         } else {
>             target_down_pyramid[num_iterations - 1].EstimateColorGradients(
>                     30, voxel_sizes[num_iterations - 1] * 4.0);
> ```

Any comment on why it is changed here? Bug fix?
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 271 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo785Mc35N7tBsuqZb9:-Mo785Mc35N7tBsuqZbA:b-7rkc9a) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L271)):*
> ```cpp
> 
>         if (result.fitness_ < 1e-5) {
>             return;
> ```

Consider defining a constant somewhere.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 324 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77rBg6IQCE2_I3GI9:-Mo77rBg6IQCE2_I3GIA:bvwkax) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L324)):*
> ```cpp
> 
>                 // Concatenate the result of this iteration to the existing
>                 // TensorMap.
> ```

Good, this will be helpful for postprocessing
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 364 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77wae9VwgA6HJqaCh:-Mo77wae9VwgA6HJqaCi:b-smm50d) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L364)):*
> ```cpp
>         const core::Tensor &init_source_to_target,
>         const TransformationEstimation &estimation,
>         const bool save_info_map) {
> ```

Same, consider renaming

**Comment by theNded** [comment]
Finished 1st pass of review wrt API. Tutorial content review TBD.

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4271)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/pipelines/registration/Registration.h, line 89 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo76hmb8J6fehPVbB64:-Mo9dLKPAOGSmV7qP5jW:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.h#L89)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

add doc for save_info_map. Could be a bit confusing as ICP is also related to the information matrix. Consider something like save_loss_log?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 215 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77O_l1Z6_G8-Gagqc:-Mo9YwIU9-i2pcv3GkX0:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L215)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

<= 0?
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 229 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77QT77fCXcCFFnD3Y:-Mo9Y_iv7XU-zBklkMtE:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L229)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 237 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77S8tAqyewAtwiCWS:-Mo9XK3a5hQTuzOt_muA:bdf08e1) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L237)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Any comment on why it is changed here? Bug fix?
</blockquote></details>

`EstimateColorGradients` should ideally use `KNN` search with `k = 30`, but for performance reasons, we are using this estimation for using `hybrid search`.

Legacy only uses `max_correspondence_distance * 2.0`, since there is no `voxel_size` parameter there, however, the distance between two point cloud does not sound to be a reasonable assumption for computing attribute in the target point cloud, therefore using `voxel_size` is much better. Generally we take `voxel_size ~= 2 * max_correspondence_distance`, and `max_correspondence_distance * 2.0` seems to be working fine for legacy, therefore changed it to `voxel_size * 4` (experimentally it got me similar results to legacy). 

Added a note in the comment, that users may pre-compute gradient using the function, for better performance and control. 
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 271 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo785Mc35N7tBsuqZb9:-Mo9dCmJ-XsfKmM5RNeD:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L271)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Consider defining a constant somewhere.
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 324 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77rBg6IQCE2_I3GI9:-Mo9dDcB1rPJEH_cUCvx:b-g2cnny) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L324)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Good, this will be helpful for postprocessing
</blockquote></details>

Thanks, there were some feature requests for this.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 364 at r1](https://reviewable.io/reviews/isl-org/open3d/4271#-Mo77wae9VwgA6HJqaCh:-Mo9Ytgs-X2ydK90Ltgd:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/550608083ba8a2c1f6cff84f4ea116fdbd7b7832/cpp/open3d/t/pipelines/registration/Registration.cpp#L364)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Same, consider renaming
</blockquote></details>

Done.

**Comment by theNded** [comment]
Updated comments in ReviewNB.

**Comment by reyanshsolis** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/isl-org/Open3D/pull/4271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by reyanshsolis** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/isl-org/Open3D/pull/4271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by reyanshsolis** [comment]
<p>Updated. </p>

**Review by theNded — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4271)* status: all files reviewed, 7 unresolved discussions (waiting on @theNded and @yxlao)

**Comment by nachovizzo** [comment]
It's a bit sad to see that the tutorial on the robust kernel is a copy-paste of what I did but the only part that was removed it's my name...

image

**Comment by theNded** [comment]
@nachovizzo sorry I didn't realize this. Your original contribution was still preserved [here](http://www.open3d.org/docs/latest/tutorial/pipelines/robust_kernels.html), but a direct duplicate without reference is inappropriate from our side. @reyanshsolis let's pay more attention next time.

In general, open3d does not explicitly mention the contributor names in tutorials. The major places as of now are comments, paper citations, and release notes. I will bring this up in the meeting and see what could be the best practice to pay tributes to the valuable contributors like you. Thanks again for the contribution!

**Comment by nachovizzo** [comment]
I think you are right, I'm the only one on the tutorials. In my case I benefit enough from having Open3D as an open-source tool, so that's the best payback I get from the team, so please, don't be forced to add back my name there ;)
Although it would be nice to give contributors(maybe not casual like myself) more acknowledgment in the project. This might also attract more contributions from the open-source community(if this is what the Open3D folk desire).

PS: I don't do contributions to have my name on it :P It's just nice to have.

**Comment by theNded** [comment]
@nachovizzo Hey thanks for the feedback! We have discussed in the meeting and the decision is to keep all the contributor names as they wish. Names are as important as contributions!
BTW we have added back your name in the master branch following this PR.

**Pull request merged**
