### PR TITLE
Tensor reconstruction system upgrade: make fragments

### PR DESCRIPTION
**Pull request by theNded**
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5181)

This PR implements 
- Information matrix computation for RGB-D odometry
- Easier-to-use pose graph wrapper in t-reconstruction system
- Explicit Long sequence splitter (into fragments)
- Module: RGB-D odometry, pose graph construction, and optimization
- Module: RGB-D integration

For the copyroom scene (5490 frames), on RTX 3060 & i7-11700 @ 2.5Hz
- Pose graph generation and optimization takes 107.961s for 55 fragments. (~ avg 50 FPS)
- TSDF integration takes 47.590s for 55 fragments. (~ avg 120 FPS)
- Example fragments:
image
image

To run the system, call
```
python examples/python/t_reconstruction_system/run_system.py --split_fragments --fragment_odometry --fragment_integration --path_dataset /path/to/dataset
```

### CODE REVIEW

**Comment by theNded** [comment]
@reyanshsolis Would you please help me 
- [ ] fix the docs (mainly for the information matrix), 
- [ ] verify the system on your machine on the lounge dataset,
- [ ] make the config options consistent across files (`rgbd_odometry, integrate, split_fragments, run_system`),
- [ ] clean up the aforementioned files and make sure that they still function alone if the users directly use them.
In the mean time I will be working on global registration.

**Comment by reyanshsolis** [comment]
Thanks for the PR @theNded. 

I will take care of the mentioned list. Also, I was trying to come up with a new design if possible such as:
- Currently, Registration::ICP and Odometry::RGBDOdometry basically compute transforms between two frames (btw unorganized pcd, or btw rgbd-image). If we can unify of make it more consistent, it might also serve as a unified interface for organized point-cloud through rgbd-pipeline. 
- We can completely transfer `PoseGraph`, `Optimization methods` wrapper to CPP tensor and add it as a pybind. Such that future implementation can just keep the component replacing, leaving the API/example code same.

I will continue working on this PR, but it might take some time.

**Comment by theNded** [comment]
@reyanshsolis Please postpone these proposals and finish my list first. These are easy tasks and can be finished soon. I want the system there first. This will make the verification of designs easier.

**Review by reyanshsolis — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 2 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5181)* status: 3 of 22 files reviewed, all discussions resolved (waiting on @reyanshsolis)

**Comment by theNded** [comment]
Finished rebasing, can be merged after double checking #5359.

**Comment by theNded** [comment]
@ssheorey several tests failed, 3 network issues, 1 tensor test error. Should be irrelevant to the PR itself.
We can proceed to merge if possible. Then I can restart working on the registration part.

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5181)* status: 1 of 22 files reviewed, 5 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[`cpp/open3d/t/pipelines/odometry/RGBDOdometry.h` line 319 at r5](https://reviewable.io/reviews/isl-org/open3d/5181#-NMBpPB03i3gDHA3TctD:-NMBpPB03i3gDHA3TctE:b-557nl8) ([raw file](https://github.com/isl-org/open3d/blob/511cb4b1cfaf5594ece6dbba979e7fa8f2d11278/cpp/open3d/t/pipelines/odometry/RGBDOdometry.h#L319)):*
> ```objc
> 
> /// Estimates 6x6 information matrix from a pair of depth images.
> /// The process is akin to information matrix creation for point clouds.
> ```

Add more details on arguments.
___
*[`cpp/pybind/t/pipelines/odometry/odometry.cpp` line 273 at r5](https://reviewable.io/reviews/isl-org/open3d/5181#-NMBpb12BV6FMsRdPYBZ:-NMBpb12BV6FMsRdPYB_:bfc1kvs) ([raw file](https://github.com/isl-org/open3d/blob/511cb4b1cfaf5594ece6dbba979e7fa8f2d11278/cpp/pybind/t/pipelines/odometry/odometry.cpp#L273)):*
> ```cpp
>                                  map_shared_argument_docstrings);
> 
>     m.def("compute_odometry_information_matrix",
> ```

Add documentation.
___
*[`examples/python/t_reconstruction_system/pose_graph_optim.py` line 35 at r5](https://reviewable.io/reviews/isl-org/open3d/5181#-NMBZh1-BXCcwNuSgYkV:-NMBZh1-BXCcwNuSgYkW:bjkwkg1) ([raw file](https://github.com/isl-org/open3d/blob/511cb4b1cfaf5594ece6dbba979e7fa8f2d11278/examples/python/t_reconstruction_system/pose_graph_optim.py#L35)):*
> ```Python
> 
>     def __init__(self, dict_nodes=None, dict_edges=None):
>         '''
> ```

Use sphinx (Google style) docs format.
___
*[`examples/python/t_reconstruction_system/rgbd_odometry.py` line 198 at r5](https://reviewable.io/reviews/isl-org/open3d/5181#-NMBnAJg8zW6AGPjSEfq:-NMBnAJg8zW6AGPjSEfr:b-icdpye) ([raw file](https://github.com/isl-org/open3d/blob/511cb4b1cfaf5594ece6dbba979e7fa8f2d11278/examples/python/t_reconstruction_system/rgbd_odometry.py#L198)):*
> ```Python
>     print(info[5, 5] / (depth_src.columns * depth_src.rows))
> 
>     # Legacy for reference, can be a little bit different due to minor implementation discrepancies
> ```

Can we move comparison with legacy to a test (or make it optional)?
___
*[`examples/python/t_reconstruction_system/run_system.py` line 131 at r5](https://reviewable.io/reviews/isl-org/open3d/5181#-NMBo3h1-NF89TjBFpSw:-NMBo3h1-NF89TjBFpSx:b-wc9pqv) ([raw file](https://github.com/isl-org/open3d/blob/511cb4b1cfaf5594ece6dbba979e7fa8f2d11278/examples/python/t_reconstruction_system/run_system.py#L131)):*
> ```Python
>             pcd = vbg.extract_point_cloud()
> 
>             # Float color does not load correctly in the t.io mode
> ```

This should be fixed now. If not, can you comment in discord?

**Pull request merged**
