### PR TITLE
Add Models with PBR Texture in Data Module

### PR DESCRIPTION
**Pull request by reyanshsolis**
## Example to use the added data:

```python
import open3d as o3d

helmet = o3d.data.FlightHelmetModel()
helmet_model = o3d.io.read_triangle_model(helmet.path)
o3d.visualization.draw(helmet_model)

crate = o3d.data.CrateModel()
crate_model = o3d.io.read_triangle_model(crate.path)
o3d.visualization.draw(crate_model)

monkey = o3d.data.MonkeyModel()
monkey_model = o3d.io.read_triangle_model(monkey.path)
o3d.visualization.draw(monkey_model)

sword = o3d.data.SwordModel()
sword_model = o3d.io.read_triangle_model(sword.path)
o3d.visualization.draw(sword_model)
```

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4994)

### CODE REVIEW

**Comment by yxlao** [comment]
Can we also add:

1. Docs for using the new datasets. This will be helpful for Alex.
2. Python tests.

**Review by yxlao — CHANGES_REQUESTED** [review]
Can we also add:

Docs for using the new datasets. This will be helpful for Alex.
Python tests.

**Comment by AlexZakIntel** [comment]
> 

Rishabh, - awesome work.

I was wondering if we could change naming conventions, like:

```py
helmet_model = o3d.data.FlightHelmetModel()
helmet = o3d.io.read_triangle_model(helmet_model.path)
o3d.visualization.draw(helmet)

crate_model = o3d.data.CrateModel()
crate = o3d.io.read_triangle_model(crate_model.path)
o3d.visualization.draw(crate)

monkey_model = o3d.data.MonkeyModel()
monkey = o3d.io.read_triangle_model(monkey_model.path)
o3d.visualization.draw(monkey)

sword_model = o3d.data.SwordModel()
sword = o3d.io.read_triangle_model(sword_model.path)
o3d.visualization.draw(sword)
```

**Comment by reyanshsolis** [comment]
> > 
> 
> Rishabh, - awesome work.
> 
> I was wondering if we could change naming conventions, like:
> 
> ```python
> helmet_model = o3d.data.FlightHelmetModel()
> helmet = o3d.io.read_triangle_model(helmet_model.path)
> o3d.visualization.draw(helmet)
> 
> crate_model = o3d.data.CrateModel()
> crate = o3d.io.read_triangle_model(crate_model.path)
> o3d.visualization.draw(crate)
> 
> monkey_model = o3d.data.MonkeyModel()
> monkey = o3d.io.read_triangle_model(monkey_model.path)
> o3d.visualization.draw(monkey)
> 
> sword_model = o3d.data.SwordModel()
> sword = o3d.io.read_triangle_model(sword_model.path)
> o3d.visualization.draw(sword)
> ```

Yes, those are just variable names, you can change them to anything you want.

**Comment by reyanshsolis** [comment]
> Can we also add:
> 
> 1. Docs for using the new datasets. This will be helpful for Alex.
> 2. Python tests.

@yxlao Done.

Added Models and Texture datasets. 
Replaced usage of `demo_scene_assets`.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r3, 18 of 27 files at r4.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4994)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @AlexZakIntel and @reyanshsolis)

___
*[docs/tutorial/data/index.rst, line 179 at r3](https://reviewable.io/reviews/isl-org/open3d/4994#-N0DRbYn5IIZ_Q3BsWnY:-N0DRbYn5IIZ_Q3BsWnZ:b-exmoop) ([raw file](https://github.com/isl-org/open3d/blob/ae81d6cb1ed1747bef5ab640c954a26cce96c2e4/docs/tutorial/data/index.rst#L179)):*
> ```reStructuredText
> 
> TriangleModel with PRB Texture
> ~~~~~~~~~~~~
> ```

rst `~~~` length should match the title length. Same for the rest.
___
*[docs/tutorial/data/index.rst, line 197 at r3](https://reviewable.io/reviews/isl-org/open3d/4994#-N0DRjDD9enSG2-hvAZS:-N0DRjDEEOiX0SFRtlok:br8xwce) ([raw file](https://github.com/isl-org/open3d/blob/ae81d6cb1ed1747bef5ab640c954a26cce96c2e4/docs/tutorial/data/index.rst#L197)):*
> ```reStructuredText
>     auto model = io::ReadTriangleModel(dataset.GetPath(), model);
> 
> MonkeyModel
> ```

duplicated monkey model
___
*[docs/tutorial/data/index.rst, line 261 at r3](https://reviewable.io/reviews/isl-org/open3d/4994#-N0DS7r3EEmPyXssDXXB:-N0DS7r3EEmPyXssDXXC:bst6ck0) ([raw file](https://github.com/isl-org/open3d/blob/ae81d6cb1ed1747bef5ab640c954a26cce96c2e4/docs/tutorial/data/index.rst#L261)):*
> ```reStructuredText
>     io::ReadTriangleModel(dataset.GetPath(), model);
> 
> Texture Material Images
> ```

We use lower case for titles. This is to be consistent with the rest of the documentation.

`Texture material images`.

**Review by yxlao — APPROVED** [review]

**Comment by yxlao** [comment]
I have pushed the changes directly. LGTM now.

**Pull request merged**
