### PR TITLE
Add initial patch mesh for hole filling

### PR DESCRIPTION
**Pull request by kongsgard**
This PR adds a starting point for advancing front mesh technique based on [this paper](http://www.cad.zju.edu.cn/home/hwlin/pdf_files/A-robust-hole-filling-algorithm-for-triangular-mesh.pdf), as requested in #2399. Computation and insertion of new vertices in the algorithm is currently not done, but I think it's valuable to get some feedback on the current setup.

Nevertheless, the current implementation is able to produce a watertight mesh of e.g. the Stanford bunny:
ScreenCapture_2020-10-10-11-27-32
ScreenCapture_2020-10-10-11-28-41

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/2460)

### CODE REVIEW

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- cpp/tests/geometry/TriangleMesh.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6319382&bid=20542843)

**Review by kongsgard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 0 of 5 files reviewed, 3 unresolved discussions

___
*[cpp/open3d/geometry/TriangleMesh.h, line 303 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJNSVze3HTIkTHQwNnf:-MJNSVze3HTIkTHQwNng:bu9okcb) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.h#L303)):*
> ```objc
>     /// Function that computes the left angle of three counter-clockwise ordered
>     /// vertices.
>     static double ComputeAngle(const Eigen::Vector3d &p0,
> ```

I'm not sure whether this function fits in the TriangleMesh class. Do you have any preferences on where to place functions such as this one?
___
*[cpp/open3d/geometry/TriangleMesh.cpp, line 1155 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJNSo_55rAYlKOdMoT_:-MJNSo_55rAYlKOdMoTa:b-j8zw76) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.cpp#L1155)):*
> ```cpp
> 
>     const auto v3 = p2 - p0;
>     const Eigen::Vector3d p = {1, 1, 1};
> ```

I think there might be a bug in this function, as I see that the min_angle while filling in the holes for the bunny mesh might sometimes be greater than M_PI.
Perhaps the calculation of the plane_normal could be simplified without the use of an arbitrary point?
___
*[cpp/open3d/geometry/TriangleMeshHoleFill.cpp, line 167 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJNV-_c7ZGcoRl0iB_s:-MJNV-_c7ZGcoRl0iB_t:bd24ggh) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMeshHoleFill.cpp#L167)):*
> ```cpp
>                 } else if (lower_angle_threshold_ < min_angle &&
>                            min_angle <= upper_angle_threshold_) {
>                     // TODO: Compute one vertex candidate
> ```

This corresponds to _Step 3._ in the referenced paper, but I don't see an explicit definition of where the vertex should be placed. That is, v_new should be along the bisector of v_i-1 v_i v_i+1 - but how far along this vector?

**Review by griegler — CHANGES_REQUESTED** [review]
Thanks for the PR. I did a quick look and left a few comments. I will have another, more detailed look at it later this week.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460#-:-MJTBRVX3B5enIe820E3:b56oi5o)* status: all files reviewed, 5 unresolved discussions (waiting on @benjaminum and @kongsgard)

___
*[cpp/open3d/geometry/TriangleMesh.h, line 303 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJNSVze3HTIkTHQwNnf:-MJT9Exm51o-UpTHzgG9:b-31pxff) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.h#L303)):*
<details><summary><i>Previously, kongsgard (Sondre Kongsgård) wrote…</i></summary><blockquote>

I'm not sure whether this function fits in the TriangleMesh class. Do you have any preferences on where to place functions such as this one?
</blockquote></details>

I think the general function can be part of Eigen utils. A private method with indices to the vertices (instead of the `Eigen::Vector3d`) could be part of the mesh class.
___
*[cpp/open3d/geometry/TriangleMesh.h, line 527 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJT9WLw-pwKqm2i6kb4:-MJT9WLw-pwKqm2i6kb5:bnof6qr) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.h#L527)):*
> ```objc
> 
>     /// \brief This function fills in holes in the mesh to make it watertight
>     /// based on the advancing front mesh (AFM) teqhnique.
> ```

A reference to the paper describing the method would be good in the doc string.
___
*[cpp/open3d/geometry/TriangleMesh.cpp, line 1155 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJNSo_55rAYlKOdMoT_:-MJT9ra01A649L2JAttT:bltnu33) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.cpp#L1155)):*
<details><summary><i>Previously, kongsgard (Sondre Kongsgård) wrote…</i></summary><blockquote>

I think there might be a bug in this function, as I see that the min_angle while filling in the holes for the bunny mesh might sometimes be greater than M_PI.
Perhaps the calculation of the plane_normal could be simplified without the use of an arbitrary point?
</blockquote></details>

Instead of the arbitrary point, would it make sense to use a mean point of the opposing triangles vertices?
___
*[cpp/open3d/geometry/TriangleMeshHoleFill.cpp, line 127 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJTB5wA10QeEARg8DhH:-MJTB5wBDicoiL8HTuiF:b4361uz) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMeshHoleFill.cpp#L127)):*
> ```cpp
> 
>         if (het_mesh->IsEmpty()) {
>             utility::LogWarning("The mesh is non-manifold\n");
> ```

`LogError` instead of `LogWarning`?

**Comment by germanros1987** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- cpp/tests/geometry/TriangleMesh.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/intel-isl/Open3D/pullRequest?prid=6319382&bid=20542843)

**Review by kongsgard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @benjaminum and @griegler)

___
*[cpp/open3d/geometry/TriangleMesh.h, line 527 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJT9WLw-pwKqm2i6kb4:-MJlZd7f2KwfjQHnzB55:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.h#L527)):*
<details><summary><i>Previously, griegler (Gernot) wrote…</i></summary><blockquote>

A reference to the paper describing the method would be good in the doc string.
</blockquote></details>

Done.
___
*[cpp/open3d/geometry/TriangleMesh.cpp, line 1155 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJNSo_55rAYlKOdMoT_:-MJlZedEAbJtXPD4HtBr:b-i08kjt) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.cpp#L1155)):*
<details><summary><i>Previously, griegler (Gernot) wrote…</i></summary><blockquote>

Instead of the arbitrary point, would it make sense to use a mean point of the opposing triangles vertices?
</blockquote></details>

As in the vertices of the connected triangles to p0, p1, and p2?
Would that also give the correct result if the mesh would resemble something like a tapered/conical vase with a wider opening than its base, and its opening should be closed?
___
*[cpp/open3d/geometry/TriangleMeshHoleFill.cpp, line 127 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJTB5wA10QeEARg8DhH:-MJla7MP9Vto03QgkZvG:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMeshHoleFill.cpp#L127)):*
<details><summary><i>Previously, griegler (Gernot) wrote…</i></summary><blockquote>

`LogError` instead of `LogWarning`?
</blockquote></details>

Done.

**Review by benjaminum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @benjaminum, @griegler, and @kongsgard)

___
*[cpp/open3d/geometry/TriangleMesh.cpp, line 1155 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJNSo_55rAYlKOdMoT_:-MK-mZ7iArkQnjGR_69Z:bg8bz50) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.cpp#L1155)):*
<details><summary><i>Previously, kongsgard (Sondre Kongsgård) wrote…</i></summary><blockquote>

As in the vertices of the connected triangles to p0, p1, and p2?
Would that also give the correct result if the mesh would resemble something like a tapered/conical vase with a wider opening than its base, and its opening should be closed?
</blockquote></details>

Are these comments about computeTriangleArea?
___
*[cpp/open3d/utility/Eigen.h, line 143 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK-kOeI391bdO2rN-DG:-MK-kOeI391bdO2rN-DH:b-3uu334) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.h#L143)):*
> ```objc
> 
> /// Function to compute the left angle of three counter-clockwise ordered
> /// vertices.
> ```

Which angle does this function compute?

**Review by kongsgard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @benjaminum and @griegler)

___
*[cpp/open3d/geometry/TriangleMesh.cpp, line 1155 at r1](https://reviewable.io/reviews/intel-isl/open3d/2460#-MJNSo_55rAYlKOdMoT_:-MK1Hk5N5Mz_7bPpqkCq:b-smmmjw) ([raw file](https://github.com/intel-isl/open3d/blob/7c2e0c4903d208207a53da9c5ef77734011a76d8/cpp/open3d/geometry/TriangleMesh.cpp#L1155)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Are these comments about computeTriangleArea?
</blockquote></details>

These comments are about the function ComputeAngle, which I moved to Eigen.h/Eigen.cpp.
___
*[cpp/open3d/utility/Eigen.h, line 143 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK-kOeI391bdO2rN-DG:-MK1IARi9IXPOihxc-yh:b-8k5izn) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.h#L143)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Which angle does this function compute?
</blockquote></details>

For three counter-clockwise vertices selected on a boundary of a hole in a mesh, this function should compute the inner angle in the range [0, 2π]

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @benjaminum, @griegler, and @kongsgard)

___
*[cpp/open3d/utility/Eigen.h, line 143 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK-kOeI391bdO2rN-DG:-MK3gvlq0cu7PPZ92APM:b-qf9h0w) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.h#L143)):*
<details><summary><i>Previously, kongsgard (Sondre Kongsgård) wrote…</i></summary><blockquote>

For three counter-clockwise vertices selected on a boundary of a hole in a mesh, this function should compute the inner angle in the range [0, 2π]
</blockquote></details>

There is a lot of context required to understand this. Can we rename the function and improve the documentation? Maybe ComputePolygonInteriorAngle?
___
*[cpp/open3d/utility/Eigen.cpp, line 387 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK3r-jvEVlgzwVuMHCy:-MK3r-jvEVlgzwVuMHCz:b3blhqa) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.cpp#L387)):*
> ```cpp
> 
>     const auto v3 = p2 - p0;
>     const Eigen::Vector3d p = {1, 1, 1};
> ```

Will this fail if v3 == scalar * p?

**Review by kongsgard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @benjaminum and @griegler)

___
*[cpp/open3d/utility/Eigen.h, line 143 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK-kOeI391bdO2rN-DG:-MK45sADACCihXNfC0E5:b8c0h0w) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.h#L143)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

There is a lot of context required to understand this. Can we rename the function and improve the documentation? Maybe ComputePolygonInteriorAngle?
</blockquote></details>

Sounds like a good idea. That will probably make it easier to find this function for other use cases, as well.
___
*[cpp/open3d/utility/Eigen.cpp, line 387 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK3r-jvEVlgzwVuMHCy:-MK466LGE8WP9TJvrHiF:b6ymjne) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.cpp#L387)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Will this fail if v3 == scalar * p?
</blockquote></details>

Yes, most likely. I'm having some issues with finding a good policy for selecting this point. Any ideas?
(Also refer to the discussion with @griegler above.)

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @benjaminum and @griegler)

___
*[cpp/open3d/utility/Eigen.cpp, line 387 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK3r-jvEVlgzwVuMHCy:-MK4OpgZB2W7dZmRjvwc:byarx17) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.cpp#L387)):*
<details><summary><i>Previously, kongsgard (Sondre Kongsgård) wrote…</i></summary><blockquote>

Yes, most likely. I'm having some issues with finding a good policy for selecting this point. Any ideas?
(Also refer to the discussion with @griegler above.)
</blockquote></details>

I see, so there seems to be a problem with the returned angle. Do we know if we have all the information that we need for this function? It seems like we need the polygon normal or more information about v3, e.g., v3 does (not) lie inside the existing surface.

**Review by kongsgard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @benjaminum and @griegler)

___
*[cpp/open3d/utility/Eigen.cpp, line 387 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK3r-jvEVlgzwVuMHCy:-MK5NCrk6WAo_DJds9cy:b6tr9p3) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.cpp#L387)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

I see, so there seems to be a problem with the returned angle. Do we know if we have all the information that we need for this function? It seems like we need the polygon normal or more information about v3, e.g., v3 does (not) lie inside the existing surface.
</blockquote></details>

Based on the resources linked to in the discussion in this issue (#2399), the counter-clockwise ordering could be enough. However, it seems to me that we might need to include some information about the adjacent geometry, such as the options you suggest. I'm not sure how they can be consistently acquired, though.

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @benjaminum and @griegler)

___
*[cpp/open3d/utility/Eigen.cpp, line 387 at r2](https://reviewable.io/reviews/intel-isl/open3d/2460#-MK3r-jvEVlgzwVuMHCy:-MK8XACW0xAa8xO31eDA:b1r3e52) ([raw file](https://github.com/intel-isl/open3d/blob/dd57ca3854f6f316c6de170f4db6a41a09c58c8b/cpp/open3d/utility/Eigen.cpp#L387)):*
<details><summary><i>Previously, kongsgard (Sondre Kongsgård) wrote…</i></summary><blockquote>

Based on the resources linked to in the discussion in this issue (#2399), the counter-clockwise ordering could be enough. However, it seems to me that we might need to include some information about the adjacent geometry, such as the options you suggest. I'm not sure how they can be consistently acquired, though.
</blockquote></details>

I think it boils down to whether 3 ordered points of a 3D polygon are enough information to determine the normal. Intuitively, I would say no because you can flip the normal by changing the position of the 4th point in a tetragon.

**Review by benjaminum — COMMENTED** [review]
Hi @kongsgard I think this PR got stuck because of a problem with the helper function for computing the interior angles. Is there something we can do to move forward with this PR?

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460#-:-MOBRZPD8Meg7TrvbxE1:b-oqlfug)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @benjaminum and @griegler)

**Comment by kongsgard** [comment]
Yes @benjaminum, as you mentioned I encountered two blockers while trying to implement this:

1. Calculation of the interior angle. I've considered an alternative where each edge and their neighboring triangle normal are crossed, and then determine if the angle is convex based on whether the two resulting vectors point towards each other. While computationally expensive due to the required number of cross products, I think that would give the correct result for all cases.

2. Introduction of new vertices along the bisector for obtuse angles - determine how far along the bisector the new vertex should be placed. I couldn't find any resources on how to do this consistently to avoid e.g. self-intersections in the resulting mesh. This is strictly not necessary for the simplest hole filling version, but I would greatly appreciate any pointers on how this could be calculated.

**Review by benjaminum — COMMENTED** [review]
Thanks for your comment @kongsgard .

1. Seems reasonable to include this information from the adjacent triangles.

2. I had a look at the "A robust hole-filling algorithm for triangular mesh" paper and could not find this information either. This type of algorithm does not seem to guarantee that there are no self-intersections. However, the heuristic of going with the vertex with the smallest angle first can still work well to avoid this type of problem.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/2460#-:-MOMgGWY0njQ6vdP88fa:b-il7fg0)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @benjaminum and @griegler)

**Comment by 1939938853** [comment]
Hello kongsgard,

Nice to see mesh hole-filling function.

**Comment by kongsgard** [comment]
> Hello kongsgard,
> 
> Nice to see mesh hole-filling function.
> 
> Just wonder if it is possible to fill the hole (gap) caused by normal direction suddenly change. As shown on the following image. On one side of the gap, the normals are outwards, on the other side of the gap, the normals are inwards.
> 
> thank you!
> 
> image

I've finally set aside some time to work on this, and I'm hoping to finish the initial implementation by the end of this week. Currently it's only a simple patching without the introduction of any new vertices. I had some issues determining vertex concavity/convexity in the general case, so now I ended up with using the averaged hole normal for this calculation. That means that the hole filling algorithm will work as long as the hole doesn't curve more than 180 degrees. The hole also has to be bounded, so for a complete gap you would have to manually add a triangle or two first.

It's a bit hard to see from your sample image whether the mesh would fall outside these restrictions. Could you share it here? I would gladly use it as part of testing while further developing this implementation.

**Comment by 1939938853** [comment]
Hello kongsgard,

**Comment by marcoagbarreto** [comment]
looking forward to this implementation in open3d. What I have been using recently is [PyMeshFix](https://pymeshfix.pyvista.org/index.html) addon for PyVista, But, I would prefer use open3d since my whole pipeline in on open3d. I'm sure you will find it useful on how they implemented theirs.

Keep on the good work.

**Comment by caniko** [comment]
Also very excited for this to be released! And thank you!

**Review by benjaminum — CHANGES_REQUESTED** [review]
@kongsgard There is a TODO in `TriangleMeshHoleFill.cpp`, is something missing or is the hole filling functionality complete?

> Reviewed 1 of 3 files at r3, 2 of 5 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/2460#-:-MuCQvJR4AwRrv7FAed_:b-8j1s62)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @benjaminum, @griegler, and @kongsgard)

___
*[cpp/pybind/geometry/trianglemesh.cpp, line 659 at r5](https://reviewable.io/reviews/isl-org/open3d/2460#-MuCQRBN2wjTVWDgbSZX:-MuCQRBN2wjTVWDgbSZY:b1zjj8x) ([raw file](https://github.com/isl-org/open3d/blob/b4b24746763d7a8323cc7076fa6bc1e98607109a/cpp/pybind/geometry/trianglemesh.cpp#L659)):*
> ```cpp
>               "trade-off parameter for the smoothed energy functional for the "
>               "regularization term."}});
>     docstring::ClassMethodDocInject(m, "TriangleMesh", "fill_holes");
> ```

Please add documentation. A copy of the docstring for C++ is fine.

**Comment by benjaminum** [comment]
We have added a method to fill holes from the vtk library to `t.geometry.TriangleMesh`. 
This PR offers a good alternative algorithm but it is not clear if the PR is complete.
@kongsgard please let me know whether to keep this PR open.

**Pull request closed without merging**
