### PR TITLE
Remove extra documentation build for python examples 

### PR DESCRIPTION
**Pull request by saurabheights**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

Speeds up building C++ documentation during development of C++ code.

Additionally, printing output path allows quick checking from local system. P.S. Will it be ok to print file uri instead of file path, i.e.

`file:///home/sk/workspace/open3d_prs/Open3D/docs/_out/html/index.html` instead of `/home/sk/workspace/open3d_prs/Open3D/docs/_out/html/index.html`. The former will be clickable on bash.

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

### CODE REVIEW

**Review by ssheorey — APPROVED** [review]
Yes, should be fine to replace output docs path with URL.

Thanks! LGTM.

**Review by ssheorey — CHANGES_REQUESTED** [review]
Hi @saurabheights something is not quite right with the updates:
- The generated docs are only 210MB compared to >400MB earlier.
- Core, Geometry (Tensor), Pipelines and Tensor pipelines tutorials are blank.
- There are some Python errors during the sphinx run, starting from:
   + https://github.com/isl-org/Open3D/actions/runs/6908435912/job/18797725788?pr=6487#step:8:7421

**Comment by saurabheights** [comment]
@ssheorey Found the issue, the methods that I put inside `args.sphinx` are actually called without passing sphinx flag - https://github.com/isl-org/Open3D/actions/runs/6908435912/job/18797725788?pr=6487#step:8:5334. Give me a few days.  I will go through workflow files to ensure the fix is done correctly.

Thanks for catching this.

**Comment by saurabheights** [comment]
@ssheorey Well, the fix is to revert that commit. Running `doxygen Doxyfile` is actually the fastest way to generate C++ docs, which was already documented. Apologies for the oversight.

1. I have pushed another minor commit to skip double build of examples. For example, here rst are built twice for examples - 
https://github.com/isl-org/Open3D/actions/runs/6878798533/job/18801576929?pr=6414#step:8:5448
https://github.com/isl-org/Open3D/actions/runs/6878798533/job/18801576929?pr=6414#step:8:7007 

2. Found a stale documentation issue - When the documentation is moved, it seams that the old path of file is not removed -
http://www.open3d.org/docs/latest/tutorial/geometry/voxelization.html#Voxel-carving which has latest 2a11e0e version 
http://www.open3d.org/docs/latest/tutorial/Advanced/voxelization.html#Voxel-carving which has very old 664eff5 version.

```
 * 664eff507 Wed Sep 30 21:30:43 2020 -0700 Yixing Lao Refector some image tests failing on arm simulator (#2393)
```

The [README.md](https://github.com/isl-org/Open3D/blob/master/.github/workflows/README.md#directory-structure) mentions `unpack_docs.sh` but I dont think this file is committed. My guess is on the deployment server, the new docs file are being copied to deployment location without cleaning up old docs in disk.

**Review by ssheorey — APPROVED** [review]

**Pull request merged**
