### PR TITLE
Hashmap upgrade

### PR DESCRIPTION
**Pull request by theNded**
- Rewrite the buffer organization that can support hashmap with multiple value tensors
- Support vanilla hash map, hash map with multiple values that are stored in the structure of array format, and hash set
- Further separate the buffer accessor and the buffer
- Rename the internal structures to be consistent (with the future journal paper)

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3909)

### CODE REVIEW

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 10 of 36 files at r1, 24 of 25 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3909)* status: all files reviewed, 5 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/core/hashmap/Hashmap.h, line 185 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDSPuo7bSPg8zjQ6yC:-MhDSPup4CvMiEfvh5Ng:bnuieas) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/Hashmap.h#L185)):*
> ```objc
> };
> 
> class Hashset : public Hashmap {
> ```

Inheritance is likely chosen here to make this implementation compact and to reduce boiler-plate code. However, this allows users to write highly confusing and error-prone code, e.g.:

1. Every "set" is a "map":
```
Hashmap* my_map = new Hashset(...); // Legal, but confusing.

Hashset set(...);
Hashmap& map = set; // Also legal, but even more confusing.
```
2. Some "maps" are "sets":
```
void DoOnHashMap(Hashmap& map) {
    if (dynamic_cast<Hashset*>(&map) != nullptr) { // Legal check.
        // We got a set.
    } else {
        // We got a map.
    }
}
```
3. Pass sets where maps are expected:
```
void WorksOnlyForHashMap(Hashmap& map) {
    // This function expects a map to some value type.
}

Hashset set(...);
WorksOnlyForHashMap(set); // Compiles perfectly fine and is legal.
```

In summary, I would use composition instead of inheritance:
```
class Hashset {
public:
   // ...
private:
    Hashmap internal_;
};
```
Furthermore, this could be moved to a `hashmap/Hashset.h` file.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 191 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDVbJy79PNv7ZBezVU:-MhDVbJz-_SjSuRcSop-:b-8mudu2) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/Hashmap.h#L191)):*
> ```objc
>             const SizeVector& key_element_shape,
>             const Device& device,
>             const HashmapBackend& backend = HashmapBackend::Default);
> ```

Is `HashmapBackend` still a good name if we also have `Hashset`? We could rename it to `HashBackend`.
___
*[cpp/open3d/core/hashmap/Hashmap.cpp, line 83 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDVtnZBIjkuSxHWAEU:-MhDVtnZBIjkuSxHWAEV:bees7ov) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/Hashmap.cpp#L83)):*
> ```cpp
> 
>     std::vector<const void*> input_values_ptrs;
>     for (auto& input_value : input_values_soa) {
> ```

Can we use `const auto&` here?

Same for the loops below.
___
*[cpp/open3d/core/hashmap/HashmapBuffer.h, line 63 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDWYA_4M-eQxFsC_mD:-MhDWYA_4M-eQxFsC_mE:bhktowi) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/HashmapBuffer.h#L63)):*
> ```objc
> 
> // Buffer index type for the internal heap.
> typedef uint32_t buf_index_t;
> ```

We can use the more modern `using buf_index_t = uint32_t;`.
___
*[cpp/open3d/core/hashmap/CUDA/CUDAHashmapBuffer.cu, line 27 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDXBtB7A4JT5UzEYEo:-MhDXBtB7A4JT5UzEYEp:b9ao6k8) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/CUDA/CUDAHashmapBuffer.cu#L27)):*
> ```Cuda
> // ----------------------------------------------------------------------------
> 
> #include <thrust/device_vector.h>
> ```

`#include <thrust/sequence.h>`

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3909)* status: 2 of 56 files reviewed, 5 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/open3d/core/hashmap/Hashmap.h, line 185 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDSPuo7bSPg8zjQ6yC:-MhEZfz00U23N7bAdM9k:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/Hashmap.h#L185)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Inheritance is likely chosen here to make this implementation compact and to reduce boiler-plate code. However, this allows users to write highly confusing and error-prone code, e.g.:

1. Every "set" is a "map":
```
Hashmap* my_map = new Hashset(...); // Legal, but confusing.

Hashset set(...);
Hashmap& map = set; // Also legal, but even more confusing.
```
2. Some "maps" are "sets":
```
void DoOnHashMap(Hashmap& map) {
    if (dynamic_cast<Hashset*>(&map) != nullptr) { // Legal check.
        // We got a set.
    } else {
        // We got a map.
    }
}
```
3. Pass sets where maps are expected:
```
void WorksOnlyForHashMap(Hashmap& map) {
    // This function expects a map to some value type.
}

Hashset set(...);
WorksOnlyForHashMap(set); // Compiles perfectly fine and is legal.
```

In summary, I would use composition instead of inheritance:
```
class Hashset {
public:
   // ...
private:
    Hashmap internal_;
};
```
Furthermore, this could be moved to a `hashmap/Hashset.h` file.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 191 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDVbJy79PNv7ZBezVU:-MhEZghkCQEEl4-FH-wU:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/Hashmap.h#L191)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Is `HashmapBackend` still a good name if we also have `Hashset`? We could rename it to `HashBackend`.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.cpp, line 83 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDVtnZBIjkuSxHWAEU:-MhE_9sBBoO-OUI0AllM:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/Hashmap.cpp#L83)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Can we use `const auto&` here?

Same for the loops below.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/HashmapBuffer.h, line 63 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDWYA_4M-eQxFsC_mD:-MhEZj0YC7P_ZO9ujfem:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/HashmapBuffer.h#L63)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

We can use the more modern `using buf_index_t = uint32_t;`.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/CUDA/CUDAHashmapBuffer.cu, line 27 at r3](https://reviewable.io/reviews/isl-org/open3d/3909#-MhDXBtB7A4JT5UzEYEo:-MhEZotz2z_WAP_71l2S:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f4b90ba1eb6f138f017614f8ee42fe0b206b0500/cpp/open3d/core/hashmap/CUDA/CUDAHashmapBuffer.cu#L27)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`#include <thrust/sequence.h>`
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]
Add some comments on cosmetic changes.

> Reviewed 1 of 25 files at r2, 53 of 54 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3909#-:-MhHNjgf4iM50nuttzAc:b-vu662p)* status: all files reviewed, 11 unresolved discussions (waiting on @stotko and @theNded)

___
*[cpp/open3d/core/hashmap/DeviceHashBackend.h, line 43 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhFgLEJDEK67NlmE3zB:-MhFgLEJDEK67NlmE3zC:bvbftns) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/open3d/core/hashmap/DeviceHashBackend.h#L43)):*
> ```objc
>     DeviceHashBackend(int64_t init_capacity,
>                       int64_t key_dsize,
>                       std::vector<int64_t> value_dsizes,
> ```

nit: `const vector<>&` to be consistent
___
*[cpp/open3d/core/hashmap/DeviceHashBackend.h, line 61 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhFgPRW3fqEYSbX2R3m:-MhFgPRW3fqEYSbX2R3n:bvbftns) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/open3d/core/hashmap/DeviceHashBackend.h#L61)):*
> ```objc
>     /// Parallel insert contiguous arrays of keys and values.
>     virtual void Insert(const void* input_keys,
>                         const std::vector<const void*> input_values,
> ```

nit: `const vector<>&` to be consistent
___
*[cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu, line 38 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhHMQ9e2deiP7qVqzLH:-MhHMQ9e2deiP7qVqzLI:b-t0959m) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu#L38)):*
> ```Cuda
>     thrust::sequence(thrust::device, heap_ptr, heap_ptr + heap.GetLength(), 0);
>     cuda::Synchronize();
>     OPEN3D_CUDA_CHECK(cudaGetLastError());
> ```

synchronize() already does the error check
___
*[cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu, line 39 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhHMKao1gKjuXF83npl:-MhHMKao1gKjuXF83npm:b-iq0gwg) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu#L39)):*
> ```Cuda
>     cuda::Synchronize();
>     OPEN3D_CUDA_CHECK(cudaGetLastError());
> };
> ```

extra `;`
___
*[cpp/open3d/t/io/HashMapIO.cpp, line 39 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhHMtVj5UWNWpP8KGLK:-MhHMtVj5UWNWpP8KGLL:b4ryuxm) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/open3d/t/io/HashMapIO.cpp#L39)):*
> ```cpp
>     std::vector<core::Tensor> values = hashmap.GetValueTensors();
> 
>     core::Device host;
> ```

it would be better to initialize explicitly
___
*[cpp/tests/core/HashMap.cpp, line 582 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhHNPvnAr-XeEb1XvWg:-MhHNPvo9Ru0unUgDAg-:bq0z1n9) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/tests/core/HashMap.cpp#L582)):*
> ```cpp
> 
>     core::HashMap hashmap(init_capacity, core::Dtype::Int32, {3},
>                           core::Dtype::Int32, {1}, device);
> ```

`core::Int32`. Also, do a search-replace in this file.

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3909)* status: 45 of 58 files reviewed, 9 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu, line 38 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhHMQ9e2deiP7qVqzLH:-MhPkE7L9-2v3y5bbm08:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu#L38)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

synchronize() already does the error check
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu, line 39 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhHMKao1gKjuXF83npl:-MhPkEh20X2kx1G-96kS:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/open3d/core/hashmap/CUDA/CUDAHashBackendBuffer.cu#L39)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

extra `;`
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/HashMapIO.cpp, line 39 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhHMtVj5UWNWpP8KGLK:-MhPkFb04qhoE04HePnO:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/open3d/t/io/HashMapIO.cpp#L39)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

it would be better to initialize explicitly
</blockquote></details>

Done.
___
*[cpp/tests/core/HashMap.cpp, line 582 at r5](https://reviewable.io/reviews/isl-org/open3d/3909#-MhHNPvnAr-XeEb1XvWg:-MhPkGMZBedquWAG9U0h:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/abe089b0b7a5b0f2781a6b111871db779a4dc0c9/cpp/tests/core/HashMap.cpp#L582)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`core::Int32`. Also, do a search-replace in this file.
</blockquote></details>

Done.

**Review by stotko — APPROVED** [review]
> Reviewed 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3909)* status: all files reviewed, 6 unresolved discussions (waiting on @stotko and @yxlao)

**Pull request merged**
