### PR TITLE
Multiple RANSAC/FGR fixes

### LINKED ISSUE #3494: where can I  find the fast_global_registration  Module?
when I run  
https://github.com/intel-isl/Open3D/blob/master/examples/python/benchmark/benchmark_ransac.py
Traceback (most recent call last):
  File "E:\open3d\src\IO\examples\python\benchmark\benchmark_ransac.py", line 20, in <module>
    from fast_global_registration import *
ModuleNotFoundError: No module named 'fast_global_registration'
where can I find the fast_global_registration  Module?  

python 3.6
os windows 7
open3D version 0.12.0

### LINKED ISSUE #4481: running open3d.pipelines.registration.registration_fgr_based_on_feature_matching in a loop crashes
Hi,

I'm trying to register a set of 100 pairs of images using RANSAC followed by ICP using Open3D library in Python (3.7).
For the RANSAC step, I'm using the function [_open3d.pipelines.registration.registration_fgr_based_on_feature_matching_](http://www.open3d.org/docs/release/python_api/open3d.pipelines.registration.registration_fgr_based_on_feature_matching.html) that is in the latest version of the Open3D package (0.14.1).

Running these steps over one pair of images isn't a problem. But, when I'm running it in a loop 100 times, it crashes during one of the iterations when calling the RANSAC function.

The error I get in Python is:

> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

A code example that reproduces the issue is:
```
import numpy as np
import open3d as o3d

# generating the source points
source = o3d.geometry.PointCloud()
source.points = o3d.utility.Vector3dVector(np.arange(20000*3).reshape([20000, 3]))

# generating the target points
target = o3d.geometry.PointCloud()
target.points = o3d.utility.Vector3dVector(np.asarray(source.points) + 1)

# generating the source features
source_fpfh = o3d.pybind.pipelines.registration.Feature()
source_fpfh.data = np.arange(33*20000).reshape([33, 20000])

# generating the target features
target_fpfh = o3d.pybind.pipelines.registration.Feature()
target_fpfh.data = source_fpfh.data + 1

for i in range(100):
    print(i+1)
    o3d.pipelines.registration.registration_fgr_based_on_feature_matching(source, target, source_fpfh, target_fpfh,
    o3d.pipelines.registration.FastGlobalRegistrationOption(maximum_correspondence_distance=0.5))
```

The output, in this case, is:

> 1
> 2
> 3
> 
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

The issue didn't occur in previous versions (when using the function [_open3d.pipelines.registration.registration_fast_based_on_feature_matching_](http://www.open3d.org/docs/0.13.0/python_api/open3d.pipelines.registration.registration_fast_based_on_feature_matching.html)). I'm using the latest version (0.14.1) because of the option to give a seed parameter to [_open3d.pipelines.registration.FastGlobalRegistrationOption_](http://www.open3d.org/docs/release/python_api/open3d.pipelines.registration.FastGlobalRegistrationOption.html) to make the RANSAC algorithm determenistic.

My OS details are:
NAME="Debian GNU/Linux"
VERSION="10 (buster)"

### PR DESCRIPTION
**Pull request by theNded**
- Fix bug of evaluating RANSAC quality introduced in #2636
- Add docs to avoid early termination (consume all iterations) by assigning confidence to 1.0.
- Follow up #4539, provide a python example and more options to the cpp example.
- Fix #4481, #4522 caused by #3849
- Fix #3494 
- Revert several parameter choices in the reconstruction systems brought up in #3108 

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4547)

### CODE REVIEW

**Comment by reyanshsolis** [comment]
Hi @theNded, 
Do you think, in output displaying the non-downsampled point cloud might look better?
or the down-sampled point cloud is more accurate to be displayed as output?

image

For example, we may use the `transformation` obtained from `registration_result`, and apply it to the `original input`, to be displayed as output. I don't have a strong opinion, just wanted to know your opinion on this.

**Comment by reyanshsolis** [comment]
I have verified `cpp` and `python` examples for `fgr` and `ransac`. 
Python benchmark for `ransac` is working, `fgr` is not, I will push the fix soon (just requires `execute_fast_global_registration` and `preprocess_point_cloud` to be moved locally to `benchmark_fgr` file. 
Another concern is that these benchmark examples, does not seem to perform performance benchmark, they are more like examples, so we might want to change that.

**Comment by reyanshsolis** [comment]
Fix benchmark_fgr.py #4566

**Comment by theNded** [comment]
> I have verified `cpp` and `python` examples for `fgr` and `ransac`. Python benchmark for `ransac` is working, `fgr` is not, I will push the fix soon (just requires `execute_fast_global_registration` and `preprocess_point_cloud` to be moved locally to `benchmark_fgr` file. Another concern is that these benchmark examples, does not seem to perform performance benchmark, they are more like examples, so we might want to change that.

Yes, we should reorganize the examples in a separate PR. `benchmark` are not benchmarks, and `misc` should be reorganized into `pipelines` and `geometry`.

**Comment by theNded** [comment]
> Hi @theNded, Do you think, in output displaying the non-downsampled point cloud might look better? or the down-sampled point cloud is more accurate to be displayed as output?
> 
> image
> 
> For example, we may use the `transformation` obtained from `registration_result`, and apply it to the `original input`, to be displayed as output. image
> 
> I don't have a strong opinion, just wanted to know your opinion on this.

Done

**Review by reyanshsolis — APPROVED** [review]

**Comment by theNded** [comment]
@reyanshsolis please do not merge now, the performance of RANSAC seems already affecting the reconstruction system. Need to fix it before merging.

**Comment by theNded** [comment]
Still do not merge -- reconstruction system still has problems.

**Review by yxlao — APPROVED** [review]
> Reviewed 4 of 7 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, 2 of 4 files at r5, 1 of 4 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4547)* status: all files reviewed, 2 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[examples/python/pipelines/registration_fgr.py, line 58 at r7](https://reviewable.io/reviews/isl-org/open3d/4547#-MtRnLfEAYh9MIAQ8lWx:-MtRmP0n0TQn-Xgfm580:b78xi5v) ([raw file](https://github.com/isl-org/open3d/blob/a30ee054a0e0d6a501af210bdc920f523c04702b/examples/python/pipelines/registration_fgr.py#L58)):*
> ```Python
>         default=1.5,
>         help=
>         'multipler used to compute distance threshold between correspondences. Threshold is computed by voxel_size * distance_multiplier.'
> ```

nit: split into multiple lines:
```
help='xxxxxxxxxxxxxxxxx'
     'xxxxxxxxxxxxxxxxx'
```
___
*[examples/python/pipelines/registration_ransac.py, line 58 at r7](https://reviewable.io/reviews/isl-org/open3d/4547#-MtRnU7yBceA6JOYbCCk:-MtRnU7z4WmFKqhxE1vO:b78xi5v) ([raw file](https://github.com/isl-org/open3d/blob/a30ee054a0e0d6a501af210bdc920f523c04702b/examples/python/pipelines/registration_ransac.py#L58)):*
> ```Python
>         default=1.5,
>         help=
>         'multipler used to compute distance threshold between correspondences. Threshold is computed by voxel_size * distance_multiplier.'
> ```

nit: split into multiple lines:
```
help='xxxxxxxxxxxxxxxxx'
     'xxxxxxxxxxxxxxxxx'
```

**Review by reyanshsolis — APPROVED** [review]

**Comment by reyanshsolis** [comment]
TODO: We currently have `function level unit testing`, may need to come up with a mechanism for `pipeline/module level unit testing`, as sometimes the difference in function level performance is not much, but at pipeline level, it results in very poor performance.

**Comment by theNded** [comment]
> TODO: We currently have `function level unit testing`, may need to come up with a mechanism for `pipeline/module level unit testing`, as sometimes the difference in function level performance is not much, but at pipeline level, it results in very poor performance.

Where is the performance drop? Did you use the same parameter set?

**Pull request merged**
