### PR TITLE
VoxelBlockGrid update

### PR DESCRIPTION
**Pull request by theNded**
- Provide `Reset` to address #4759 
- Provide `Prune` to recycle outlier blocks
- Minor parameter adjustment for loading to avoid stdgpu hashmap overflow

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4774)

### CODE REVIEW

**Review by yxlao — APPROVED** [review]

**Comment by yxlao** [comment]
LGTM after fixing unit tests.

**Comment by theNded** [comment]
Unit tests failed on CPU with ISPC turned on.
Reason: when converting the bool result of element-wise boolean operations (`eq`, `le`, `gt`, etc) to scalars, `True` becomes `255` or equivalent while the expected result should be `1`. Awaiting fix before merging.

**Comment by yxlao** [comment]
```bash
python -c "import open3d as o3d; print(o3d.core.Tensor.ones((3), o3d.core.int32).le(1).to(o3d.core.int32))"
```

When computing `Tensor::Le()` with ISPC, ISPC assigns `0b11111111` for the `true` values. If we initialize a fresh tensor, the `true` value will always be `0b00000001`.

**Comment by reyanshsolis** [comment]
> If we initialize a fresh tensor, the true value will always be 0b00000001.

Is this even the case when using ISPC for initializing a new tensor?

**Comment by ssheorey** [comment]
Hi @theNded , do you have an update on this PR?

**Comment by theNded** [comment]
Let me close it for now and reopen after some upgrades.

**Pull request closed without merging**
