### PR TITLE
Apple Silicon support

### PR DESCRIPTION
**Pull request by yxlao**
### Usage

```bash
brew install gfortran

mkdir build && cd build
cmake ..
make install-pip-package -j8

# test filament visualizer
python -c "import open3d as o3d; c = o3d.geometry.TriangleMesh.create_box(); o3d.visualization.draw([c])"

# test opengl visualizer
python -c "import open3d as o3d; c = o3d.geometry.TriangleMesh.create_box(); o3d.visualization.draw_geometries([c])"
```

### Known issues
- [Bug] All new GUI and old visualizer examples:
   ```
   # This error is displayed, but the visualizer still works.
   [error] GLFW error: Cocoa: Failed to find service port for display
   ```
- [Bug] Error when loading GLTF assets, e.g. `examples/python/gui/demo_scene.py`
   ```
   libc++abi: terminating with uncaught exception of type DeadlyImportError: GLTF: Unsupported glTF version: 2.0
   ```
- [Future work] WebRTC is not yet enabled.
- [Future work] Jupyter plugin is not yet enabled

### Reviewing
#4428 and #4348 are related. However, they can be reviewed independently. I'll address the issues separately for these two PRs.

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4428)

### CODE REVIEW

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4428)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[CMakeLists.txt, line 90 at r2](https://reviewable.io/reviews/isl-org/open3d/4428#-Mqu4YKU0CiAczjyGKYw:-Mqu4YKV24__9pJcW8EH:b-qs34fr) ([raw file](https://github.com/isl-org/open3d/blob/952ef75274fd01e8b6630d06df94fdbaebf10552/CMakeLists.txt#L90)):*
> ```CMake
> option(USE_SYSTEM_TINYOBJLOADER   "Use system pre-installed tinyobjloader"   OFF)
> if(LINUX_AARCH64 OR APPLE_AARCH64)
>     option(BUILD_FILAMENT_FROM_SOURCE "Build filament from source"           ON )
> ```

Can we upload compiled versions of filament for LINUX__AARCH64 and APPLE_AARCH64 like the others? That will speed up CI as well.
___
*[3rdparty/find_dependencies.cmake, line 1250 at r2](https://reviewable.io/reviews/isl-org/open3d/4428#-Mqu8j7V-rykWAj8-63w:-Mqu8j7V-rykWAj8-63x:b-le5rot) ([raw file](https://github.com/isl-org/open3d/blob/952ef75274fd01e8b6630d06df94fdbaebf10552/3rdparty/find_dependencies.cmake#L1250)):*
> ```CMake
>                 message(FATAL_ERROR "Failed to run `${gfortran_bin} -print-search-dirs`")
>             endif()
>             message(STATUS "gfortran_search_dirs: ${gfortran_search_dirs}")
> ```

Is this for debugging? Can we remove it?
___
*[3rdparty/find_dependencies.cmake, line 1256 at r2](https://reviewable.io/reviews/isl-org/open3d/4428#-Mqu9-443t4LV2OOn15r:-Mqu9-45C7Cbl45BWAPi:bl8917r) ([raw file](https://github.com/isl-org/open3d/blob/952ef75274fd01e8b6630d06df94fdbaebf10552/3rdparty/find_dependencies.cmake#L1256)):*
> ```
> message(STATUS "gfortran_lib_dirs: ${gfortran_lib_dirs}")
> ```
Remove if only for debugging.
___
*[3rdparty/find_dependencies.cmake, line 1266 at r2](https://reviewable.io/reviews/isl-org/open3d/4428#-Mqu9MTO5OsYvL5uTrny:-Mqu9MTO5OsYvL5uTrnz:b-htkzmg) ([raw file](https://github.com/isl-org/open3d/blob/952ef75274fd01e8b6630d06df94fdbaebf10552/3rdparty/find_dependencies.cmake#L1266)):*
> ```
> # -no_compact_unwind is needed to supress compiler warnings.
> ```
suppress

**Comment by Nicholas-Mitchell** [comment]
Thanks for your work on this!

Not sure where I should mention this: the macos wheel `open3d-0.14.1-cp39-cp39-macosx_11_0_arm64.whl` that installs via `pip install open3d` says that it wasn't built with support for tensorflow:

```
  File "/Users/n1k31t4/miniforge3/envs/ml/lib/python3.9/site-packages/open3d/ml/tf/__init__.py", line 33, in <module>
    raise Exception('Open3D was not built with TensorFlow support!')
```

**Comment by yxlao** [comment]
> Thanks for your work on this!
> 
> Not sure where I should mention this: the macos wheel `open3d-0.14.1-cp39-cp39-macosx_11_0_arm64.whl` that installs via `pip install open3d` says that it wasn't built with support for tensorflow:
> 
> ```
>   File "/Users/n1k31t4/miniforge3/envs/ml/lib/python3.9/site-packages/open3d/ml/tf/__init__.py", line 33, in <module>
>     raise Exception('Open3D was not built with TensorFlow support!')
> ```

Yes. That is expected. We have not yet enabled any Open3D-ML feature for macOS, regardless of x86-64 or ARM64.

**Comment by pratt3000** [comment]
`ImportError: dlopen(/Users/pratt/anaconda3/envs/cs498/lib/python3.9/site-packages/open3d/cpu/pybind.cpython-39-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/libomp/lib/libomp.dylib
  Referenced from: <0718BFA0-280F-3029-A780-D45CF6BB9F0D> /Users/pratt/anaconda3/envs/cs498/lib/python3.9/site-packages/open3d/cpu/pybind.cpython-39-darwin.so
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)`
  
 I am trying to import open3d but I have been getting this error. I am running python3.9 on a Conda environment. 
 
 Not sure what I may be doing wrong here.

**Comment by ssheorey** [comment]
`brew install libomp` is required on macOS.

**Pull request merged**
