### PR TITLE
Add support for python3.11

### LINKED ISSUE #5620: Request to add Python 3.11 support?
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

It might be much faster with the support of Python 3.11.

### References

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by OlivierLDff**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

Fix #5620 

## Checklist:

-   [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [ ] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

- Update the linux/mac/windows CI to handle python 3.11
- Update pybind11

I guess some documentation will also be required to be updated somewhere. I am not familiar with the workspace, I just happened to have python3.11 on my machine so wanted to give a go to the update. Maybe there more stuff to update than what I did. Let's see what the CI have to say.

Companion Open3D-ML PR: https://github.com/isl-org/Open3D-ML/pull/619

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6288)

### CODE REVIEW

**Comment by ssheorey** [comment]
Hi @OlivierLDff thanks for this PR! There is some background info and more tasks required for this PR. The reason we were hesitating with adding Python 3.11 support is an incompatibility between PyTorch and Tensorflow dependencies, that we would also need to update. But I think we can bite the bullet and proceed now. Here are the details:

- Python 3.11 is supported by TF 2.12+ and PyTorch 2.0+ only.
- PyTorch still uses the old CXX11_ABI in Linux ([issue](https://github.com/pytorch/pytorch/issues/51039)), while TF switched to the new CXX11_ABI since 2.9.
- We need to pick one CXX11_ABI for Open3D - we have been using the old CXX11_ABI till now and we should continue that till PyTorch also supports the new ABI. Unfortunately, this means **temporarily** dropping support for TensorFlow.

As a result, please make these additional changes in this PR for proper Python 3.11 support:
- Update PyTorch to version 2.0.1 that supports Python 3.11
- Comment out tensorflow dependencies from requirements files. Update the CI to not install / build with tensorflow.

We can also drop support for Python 3.7 in the same PR. Python 3.7 is now EOL.

Also, we need to keep the companion Open3D-ML repo in sync - we will need a companion PR for that repo. Let me know if you want some help in preparing a PR for that.

**Comment by OlivierLDff** [comment]
Ok thanks for the guidance. I'm currently away from any computer for a week, but I will continue this PR next week! 
It doesn't seems urgent to update ATM. But if someone wants/need to finalize this this week do not hesitate to superseed this PR.
Have a nice, I will com back with more questions if required when I will get back to it.

To drop python 3.7 is there more than the file I already touched?

**Comment by OlivierLDff** [comment]
Coming back to this PR I now realize it might be harder than what I was expecting, since I'm not familiar with the codebase.

I guess pytorch version has to be updated there:
https://github.com/isl-org/Open3D/blob/10128192e6c444e3b37f28077489db555265418a/util/ci_utils.sh#L45-L50

But then should cuda version be updated too? 
https://github.com/isl-org/Open3D/blob/10128192e6c444e3b37f28077489db555265418a/util/ci_utils.sh#L30-L33

11.7 or 11.8 ?

For tensorflow, should it just be commented here: https://github.com/isl-org/Open3D/blob/10128192e6c444e3b37f28077489db555265418a/.github/workflows/ubuntu.yml#L38

**Comment by ssheorey** [comment]
> Coming back to this PR I now realize it might be harder than what I was expecting, since I'm not familiar with the codebase.

No worries, we'll help as much as required. Thanks for working on this task!

> 
> I guess pytorch version has to be updated there:
> 
> https://github.com/isl-org/Open3D/blob/10128192e6c444e3b37f28077489db555265418a/util/ci_utils.sh#L45-L50

Yes. 

> 
> But then should cuda version be updated too?
> 
> https://github.com/isl-org/Open3D/blob/10128192e6c444e3b37f28077489db555265418a/util/ci_utils.sh#L30-L33
> 
> 11.7 or 11.8 ?

Update CUDA to the oldest supported by our target PyTorch version. For 2.0, this is 11.7. Update this and the corresponding cuDNN version in all dockerfiles in the docker folder.

> 
> For tensorflow, should it just be commented here:
> 
> https://github.com/isl-org/Open3D/blob/10128192e6c444e3b37f28077489db555265418a/.github/workflows/ubuntu.yml#L38

This needs to be changed in a few different places (Linux CI is all in docker):
- `docker/Dockerfile.wheel` is used to build the Open3D wheel. Set this to OFF here:
https://github.com/isl-org/Open3D/blob/10128192e6c444e3b37f28077489db555265418a/docker/Dockerfile.wheel#L128
- Disable TF for various CI configurations. These are all run in docker controlled by the file: `docker/docker_build.sh` Turn all of them OFF there and a comment such as `OFF due to cxx11_abi` to each one.
- Finally, in ubuntu.yml, the BUILD_TENSORFLOW_OPS and BUILD_PYTORCH_OPS settings are unused (leftovers from earlier changes). Go ahead and delete them.

We provide both cxx11_abi and pre cxx11_abi C++ binary builds for Open3D, so it is possible to support TF through C++. However, for simplicity, lets disable it completely in Linux.

For macOS, the ABI is not a problem. Lets upgrade Tensorflow to the latest there (2.12). This ensures that our TF code continues to be maintained. This will also need changes to `util/ci_utils.sh` (near where you update the PyTorch version).

**Comment by OlivierLDff** [comment]
Would it be possible to approve workflow run so I can see what is working/failing?

**Comment by OlivierLDff** [comment]
Forget what I said, it seems everything is working when I PR against my own repo

**Comment by OlivierLDff** [comment]
Ok so I updated a bunch of stuff, they are kept in different commit for easier review/understanding of what I did.
I'm running into multiple issues and I would gladly receive some insight before investing some times.

#  MacOS

## tensorflow framework

So it seems tensorflow framework is no longer available, but I'm not familiar with that library. I just commented out things in the CMakeLists to ignore that for now. I guess this is the kind of issue that will blow up at linking time, that I haven't reached yet.

https://github.com/isl-org/Open3D/pull/6288/commits/e55988bd3f704c6ebde57655346387ea31ea2d33

Do you have any insight if the `tensorflow_framework` disappeared? Couldn't find anything, but didn't look for long.

## Macos min version

It seems that min macos version is 10.15, but I'm running into issues with tensorflow 
- that don't include the right header (for example `#include <optional>` and stuff. 
- libusb was compiled with min version 12.x.

You can checks logs here: https://github.com/OlivierLDff/Open3D/actions/runs/5889809346/job/15973684524?pr=1

I guess by updating min macos version to 12.x, things will go away. Is it something you wish to do?

https://github.com/isl-org/Open3D/blob/c7718fd626d2f446bbbf40fd552ffd424e66d7a0/3rdparty/vtk/CMakeLists.txt#L33-L35

# Ubuntu

## Tensorflow

I have this really strange error:

```
Downloading tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
#24 35.23     ERROR: Command errored out with exit status 1:
#24 35.23      command: /root/miniconda3/envs/open3d/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dp_5t5al/tensorflow-gpu_22a7e4fc178b45c3a700cbb994608eb0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dp_5t5al/tensorflow-gpu_22a7e4fc178b45c3a700cbb994608eb0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rhpu13wg
#24 35.23          cwd: /tmp/pip-install-dp_5t5al/tensorflow-gpu_22a7e4fc178b45c3a700cbb994608eb0/
#24 35.23     Complete output (38 lines):
#24 35.23     Traceback (most recent call last):
#24 35.23       File "/root/miniconda3/envs/open3d/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
#24 35.23         parsed = parse_requirement(requirement_string)
#24 35.23       File "/root/miniconda3/envs/open3d/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
#24 35.23         return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
#24 35.23       File "/root/miniconda3/envs/open3d/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
#24 35.23         url, specifier, marker = _parse_requirement_details(tokenizer)
#24 35.23       File "/root/miniconda3/envs/open3d/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
#24 35.23         marker = _parse_requirement_marker(
#24 35.23       File "/root/miniconda3/envs/open3d/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
#24 35.23         tokenizer.raise_syntax_error(
#24 35.23       File "/root/miniconda3/envs/open3d/lib/python3.10/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
#24 35.23         raise ParserSyntaxError(
#24 35.23     setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
#24 35.23         python_version>"3.7"
```

I'm not sure where is it coming from or how to track that. This seems to come from tensorflow which is anyway not in used. Have you ever heard of this problem?

## Headless docs (ubuntu)

I'm running in a missing symbol, but this seems to be because I'm using the wrong repo for open3d-ML

```
Traceback (most recent call last):
  File "generate_tf_ops_wrapper.py", line 110, in <module>
    sys.exit(main())
  File "generate_tf_ops_wrapper.py", line 61, in main
    oplib = tf.load_op_library(args.lib)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/runner/work/Open3D/Open3D/build/lib/Release/cpu/open3d_tf_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```


https://github.com/OlivierLDff/Open3D/actions/runs/5889809363/job/15973675060?pr=1

**Comment by igozali** [comment]
Looks like build is failing due to this line? https://github.com/isl-org/Open3D/actions/runs/6399541003/job/17371755134?pr=6288#step:4:13726
```
#29 2234.8 make: *** No rule to make target 'open3d_tf_ops'.  Stop.
```

**Comment by ssheorey** [comment]
> Looks like build is failing due to this line? https://github.com/isl-org/Open3D/actions/runs/6399541003/job/17371755134?pr=6288#step:4:13726
> 
> ```
> #29 2234.8 make: *** No rule to make target 'open3d_tf_ops'.  Stop.
> ```
> 
> Probably need to guard these `make` targets behind the env var
> 
> https://github.com/isl-org/Open3D/blob/c61fb71795e7c86e6639a7f30d5c3f6d46bc3bbd/util/ci_utils.sh#L198

Thanks @igozali you have sharp eyes...

**Comment by johnthagen** [comment]
@ssheorey In case it helps, I noticed that Pytorch recently uploaded `cpu.cxx11.abi` wheels to their custom wheel repo:

- https://download.pytorch.org/whl/torch/

For example:

- https://download.pytorch.org/whl/cpu-cxx11-abi/torch-2.1.0%2Bcpu.cxx11.abi-cp311-cp311-linux_x86_64.whl#sha256=0aafe9ff268e209831d38acd3e0b39a95ae76ff45a88ec0e48d7019cf476dc21

**Comment by ssheorey** [comment]
> @ssheorey In case it helps, I noticed that Pytorch recently uploaded `cpu.cxx11.abi` wheels to their custom wheel repo:
> 
>     * https://download.pytorch.org/whl/torch/
> 
> 
> For example:
> 
>     * https://download.pytorch.org/whl/cpu-cxx11-abi/torch-2.1.0%2Bcpu.cxx11.abi-cp311-cp311-linux_x86_64.whl#sha256=0aafe9ff268e209831d38acd3e0b39a95ae76ff45a88ec0e48d7019cf476dc21

Thanks, that is useful. Hope they finish the migration to the new cxx11_abi quickly. To keep a handle on complexity, we'll go with the old cxx11_abi for now and without tf ops on Linux. We'll switch completely to the new cxx11_abi with both torch and tf in a future PR.

I'll add instructions for users to build an Open3D wheel with tf ops and the new cxx11_abi in the meantime.

**Review by ssheorey — APPROVED** [review]

**Comment by johnthagen** [comment]
@ssheorey I was curious if the team was planning a 0.18 release to support Python 3.11? We are excited to try it out. ❤️

**Comment by ssheorey** [comment]
Yes, we will have a 0.18 release soon. :-)

**Comment by thomasegriffith** [comment]
> Yes, we will have a 0.18 release soon. :-)

Really looking forward to this!  Do you have a rough idea on the timeline?

**Comment by thomasegriffith** [comment]
@ssheorey any idea when the 0.18 release will happen?  TIA!

**Comment by sharon-br** [comment]
@ssheorey Any updates on the 0.18 release?

**Comment by johnthagen** [comment]
♫ All I want for Christmas is a new Open3D ♬

😄 ❤️

**Comment by ssheorey** [comment]
> ♫ All I want for Christmas is a new Open3D ♬
> 
> 😄 ❤️

Working on it... Hope to have a new year present for all...

**Pull request merged**
