### PR TITLE
Write PLY Tensor PointCloud Performance Improvement.

### PR DESCRIPTION
**Pull request by reyanshsolis**
Changes:

- Throw a clear warning about not saving the custom attributes other than of shape (N, 1).
- Speed up by avoiding tensor slicing operations for each row. [More than 12x]. 
- Cleaner code.

Performance Improvements:

| Name \[points\]    | Legacy             | Tensor [Master]     | Tensor [A]   | Tensor [B] |
| -------------------------- | ------------------ | ------------------- | ------------------ | ------------------ |
| bedroom.ply | 3,600ms | 31,500ms | 2,600ms | 3,100ms |
| [16,164,488] | 824.4 MB | 452.6 MB | 436.4 MB | 452.6 MB |
| | | | | |
| apartment.ply | 4,900ms | 42,200ms | 3,500ms | 4,600ms |
| [22,763,360] | 1.2 GB | 637.4 MB | 614.6 MB | 637.4 MB |
| | | | | |
| boardroom.ply | 4,500ms | 37,000ms | 3,100ms |  4,100ms |
| [20,061,457] | 1.0 GB | 561.7 MB | 541.7 MB | 561.7 MB |

#### Update: The test file contains an additional attribute `alpha`, which is why [B] is taking more time and space.

All the files are `.ply` type, with points, normals, and colors of type `float, float, uchar` respectively. The saved files were verified by matching attribute tensors with input (using `AllClose`, and opening it manually in the visualizer).

#### PLY Read Tensor is about 2x slower than PLY Read Legacy because the callback function is generic to allow custom attributes and slightly slower.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3835)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3835)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @reyanshsolis and @ssheorey)

___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 344 at r3](https://reviewable.io/reviews/isl-org/open3d/3835#-Mg8DLcc2InD9sMAkhHq:-Mg8DLcc2InD9sMAkhHr:b7max6h) ([raw file](https://github.com/isl-org/open3d/blob/fbf986d3f42f6ddcfc2db03974e16aea760fcb6e/cpp/open3d/t/io/file_format/FilePLY.cpp#L344)):*
> ```cpp
> 
>     geometry::TensorMap t_map = pointcloud.GetPointAttr();
>     geometry::TensorMap t_map_contiguous(t_map.GetPrimaryKey());
> ```

Add a `TensorMap::Contiguous()`function similar to `Tensor::Contiguous()`.
This way we can use `IsSizeSynchronized()` here.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 392 at r3](https://reviewable.io/reviews/isl-org/open3d/3835#-Mg8FkvN3e2ADs-zVwGj:-Mg8FkvN3e2ADs-zVwGk:b-foalvd) ([raw file](https://github.com/isl-org/open3d/blob/fbf986d3f42f6ddcfc2db03974e16aea760fcb6e/cpp/open3d/t/io/file_format/FilePLY.cpp#L392)):*
> ```cpp
>     ply_add_element(ply_file, "vertex", num_points);
> 
>     std::vector<std::tuple<const core::Dtype, const void *, const int>>
> ```

Tuples do not have semantic meanings. Change it to struct instead.

```cpp
struct AttributePtr {
    AttributePtr(...): xxx_(xxx), ... {
    }
    const core::Dtype dtype_;
    const void* data_ptr_;
    const int group_size_;
};
```
And then use `std::vector<AttributePtr>`.

**Review by ssheorey — COMMENTED** [review]
Can the current ply writer write arbitrary attributes of shape `{N,k}`?
LGTM after addressing Yixing's comments.

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3835#-:-MgC50wJ-7b1plfbP2oj:b-2m73ez)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 370 at r3](https://reviewable.io/reviews/isl-org/open3d/3835#-MgC2Ik03MQL_lEejFnb:-MgC2Ik12WkGQfgKo-Il:b-hafg2i) ([raw file](https://github.com/isl-org/open3d/blob/fbf986d3f42f6ddcfc2db03974e16aea760fcb6e/cpp/open3d/t/io/file_format/FilePLY.cpp#L370)):*
> ```cpp
>                     "Write PLY failed. PointCloud contains {} attribute which "
>                     "is not supported by PLY IO. Only points, normals, colors "
>                     "and attributes with shape (N, 1) are supported, where N "
> ```

nit: N-> `num_points` to shorten message.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 462 at r3](https://reviewable.io/reviews/isl-org/open3d/3835#-MgC5baY9F_VHPllpF6V:-MgC5baY9F_VHPllpF6W:baegmet) ([raw file](https://github.com/isl-org/open3d/blob/fbf986d3f42f6ddcfc2db03974e16aea760fcb6e/cpp/open3d/t/io/file_format/FilePLY.cpp#L462)):*
> ```cpp
>                 const int idx_offset = std::get<2>(it) * i;
>                 for (int j = 0; j < std::get<2>(it); ++j) {
>                     ply_write(ply_file, data_ptr[idx_offset + j]);
> ```

nit: Increment `idx_offset` in the loop directly (no j needed) to avoid a bit of computation.

**Comment by reyanshsolis** [comment]
> Can the current ply writer write arbitrary attributes of shape `{N,k}`?

It is possible, but we need to define some contract with the naming, eg.
`normals` are saved as `nx, ny, nz` (3 different attributes of length `{N, 1}`), and when we read the same, we `concatenate` them to use as a single `normals` attribute. So, if we have `radom_attr` of shape `{N, 4}`, we may save it as `radom_attr_0`, `radom_attr_1`, `radom_attr_2`, `radom_attr_3`, and while reading search for similar patterns to concatenate. 

However, since other applications might not support this custom contract, it might not be of much use, and will also complicate things a bit.

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3835)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 85 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgFEtH84Kl6Y7_ASCMV:-MgFEtH84Kl6Y7_ASCMW:b-o8f0p7) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L85)):*
> ```cpp
> 
> TensorMap TensorMap::Contiguous() const {
>     TensorMap tensor_map_contiguous(this->GetPrimaryKey());
> ```

We may not need to check for `TensorMap::IsContiguous()` here, as memory-copy / re-using is handled by `Tensor::Contiguous()`for each tensor individually. 
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 344 at r3](https://reviewable.io/reviews/isl-org/open3d/3835#-Mg8DLcc2InD9sMAkhHq:-MgFDljkERTCGo3EJQHg:bj99of2) ([raw file](https://github.com/isl-org/open3d/blob/fbf986d3f42f6ddcfc2db03974e16aea760fcb6e/cpp/open3d/t/io/file_format/FilePLY.cpp#L344)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Add a `TensorMap::Contiguous()`function similar to `Tensor::Contiguous()`.
This way we can use `IsSizeSynchronized()` here.
</blockquote></details>

Adding `TensorMap::Contiguous()` cleaned up the code. 
However, as we still need to check for the shape of `custom_attribute`, we need to go through this loop anyways. Also, for now, only `{N, 1}` shaped custom attribute is allowed for consistency. 
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 370 at r3](https://reviewable.io/reviews/isl-org/open3d/3835#-MgC2Ik03MQL_lEejFnb:-MgFEYn66Kb0nsa6tmnR:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fbf986d3f42f6ddcfc2db03974e16aea760fcb6e/cpp/open3d/t/io/file_format/FilePLY.cpp#L370)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

nit: N-> `num_points` to shorten message.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 392 at r3](https://reviewable.io/reviews/isl-org/open3d/3835#-Mg8FkvN3e2ADs-zVwGj:-MgFEapNCq4NZzNsV1dm:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fbf986d3f42f6ddcfc2db03974e16aea760fcb6e/cpp/open3d/t/io/file_format/FilePLY.cpp#L392)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Tuples do not have semantic meanings. Change it to struct instead.

```cpp
struct AttributePtr {
    AttributePtr(...): xxx_(xxx), ... {
    }
    const core::Dtype dtype_;
    const void* data_ptr_;
    const int group_size_;
};
```
And then use `std::vector<AttributePtr>`.

</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 462 at r3](https://reviewable.io/reviews/isl-org/open3d/3835#-MgC5baY9F_VHPllpF6V:-MgFEcN39uf5d9bxAH8m:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fbf986d3f42f6ddcfc2db03974e16aea760fcb6e/cpp/open3d/t/io/file_format/FilePLY.cpp#L462)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

nit: Increment `idx_offset` in the loop directly (no j needed) to avoid a bit of computation.
</blockquote></details>

Done.

**Review by ssheorey — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3835)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ssheorey and @yxlao)

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3835)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/t/geometry/TensorMap.h, line 125 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ3Cvy40YSeyt19Ixb:-MgJ3Cvy40YSeyt19Ixc:b-bwdjcg) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.h#L125)):*
> ```objc
>     /// Returns True if the underlying memory buffers of all the Tensors in the
>     /// TensorMap is contiguous.
>     inline bool IsContiguous() const;
> ```

remove inline
___
*[cpp/open3d/t/geometry/TensorMap.h, line 127 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ5vuA6qUNMF2EX8eW:-MgJ5vuBAER2oeIMvrR_:b-ibsegk) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.h#L127)):*
> ```objc
>     inline bool IsContiguous() const;
> 
>     /// Returns a contiguous TensorMap containing the same data in the same
> ```

Returns a new contiguous TensorMap
___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 75 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ3NRP4W_-nno2jJLG:-MgJ3NRP4W_-nno2jJLH:b-bwdjcg) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L75)):*
> ```cpp
> }
> 
> inline bool TensorMap::IsContiguous() const {
> ```

remove inline
___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 76 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6AQG-ATpwIVxI78I:-MgJ6AQG-ATpwIVxI78J:b-e1swjv) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L76)):*
> ```cpp
> 
> inline bool TensorMap::IsContiguous() const {
>     for (auto& kv : *this) {
> ```

const auto&
___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 85 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ61FRDcOMyKmYbl6O:-MgJ61FRDcOMyKmYbl6P:b2s9jc8) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L85)):*
> ```cpp
> 
> TensorMap TensorMap::Contiguous() const {
>     TensorMap tensor_map_contiguous(this->GetPrimaryKey());
> ```

remove this->n
___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 86 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6Bnb3SVB6ltdUTfx:-MgJ6Bnb3SVB6ltdUTfy:b-e1swjv) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L86)):*
> ```cpp
> TensorMap TensorMap::Contiguous() const {
>     TensorMap tensor_map_contiguous(this->GetPrimaryKey());
>     for (auto& kv : *this) {
> ```

const auto&
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 29 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6DXLD5UvAM17z-6v:-MgJ6DXLD5UvAM17z-6w:b-9dldn3) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/io/file_format/FilePLY.cpp#L29)):*
> ```cpp
> #include <rply.h>
> 
> #include <tuple>
> ```

remove tuple
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 394 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6kct2EL97xfT5hy8:-MgJ6kcu2LthIeWshmkb:bia0842) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/io/file_format/FilePLY.cpp#L394)):*
> ```cpp
>     ply_add_element(ply_file, "vertex", num_points);
> 
>     std::vector<AttributePtr> attribute_ptr;
> ```

nit: `attribute_ptrs`
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 395 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6oPH2yCZNVZ_zqQP:-MgJ6jF1BmXpi9FM3IrI:bkpvvt3) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/io/file_format/FilePLY.cpp#L395)):*
> ```cpp
> 
>     std::vector<AttributePtr> attribute_ptr;
>     attribute_ptr.push_back(AttributePtr(t_map["points"].GetDtype(),
> ```

nit: `attribute_ptr.emplace_back(t_map["points"].GetDtype(), xxx, xxx);`, same for the rest.

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3835)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/TensorMap.h, line 125 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ3Cvy40YSeyt19Ixb:-MgK0F0nE_TcHmj-aTds:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.h#L125)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove inline
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TensorMap.h, line 127 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ5vuA6qUNMF2EX8eW:-MgK0FrA1G6Xp16A-ieQ:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.h#L127)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Returns a new contiguous TensorMap
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 75 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ3NRP4W_-nno2jJLG:-MgK0GhR2c0t8s8IX20s:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L75)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove inline
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 76 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6AQG-ATpwIVxI78I:-MgK0HZ58Ttec1aYuVAL:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L76)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

const auto&
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 85 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ61FRDcOMyKmYbl6O:-MgK0JJ0Et_SWyug1Kkx:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L85)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove this->n
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TensorMap.cpp, line 86 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6Bnb3SVB6ltdUTfx:-MgK0JsHCDhsowIpkJ-k:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/geometry/TensorMap.cpp#L86)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

const auto&
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 29 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6DXLD5UvAM17z-6v:-MgK0KoG32efCWmP4zNL:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/io/file_format/FilePLY.cpp#L29)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove tuple
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/file_format/FilePLY.cpp, line 394 at r4](https://reviewable.io/reviews/isl-org/open3d/3835#-MgJ6kct2EL97xfT5hy8:-MgK0Q1zBGwYMxProPxG:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a623759d3165abb294ac367a97ef48a7a7da681f/cpp/open3d/t/io/file_format/FilePLY.cpp#L394)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: `attribute_ptrs`
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]

**Pull request merged**
