### PR TITLE
Tensorboard plugin

### PR DESCRIPTION
**Pull request by ssheorey**
Initial Open3D for TensorBoard plugin. Save intermediate 3D data (point clouds, meshes, line sets) during an iterative optimization procedure (e.g.: 3D semantic segmentation, registration,...) and visualize data through TensorBoard.

### Features:
- Summary writing: Save 3D data to msgpack files on disk and write an index in TensorBoard event files. Async non-blocking writer. Point cloud, mesh and line sets supported.
- De-duplication of written 3D summaries: e.g. If point cloud labels or colors keep changing with iteration, but normals are the same, you can ask Open3D to use normals from step=0 for all iterations. ~~However, primary keys (`*_positions`, `*_indices` cannot be de-duplicated as of now due to validation checks in serialization.)~~ Supported through PR #3963 
- Cached reading of 3D data.
- Display 3D data. Multiple geometry elements to be displayed can be selected with `tags`. The user can scroll through time with a slider for `step`. Geometry element can be written in batches and a specific `batch_idx` can be chosen for display. Finally, multiple experiment `run`s can be displayed in different windows for comparison.
- Displays in multiple windows can show the same iteration step or batch index.
- Tested with large meshes: >30M points and >60M triangles.
- [x] Deduplication for primary keys (`*_positions`, `*_indices`).
- [x] Test with PyTorch and remove TensorFlow dependency.
- [x] Switch http handling from civetweb to TensorBoard. (civetweb needs extra port and browser CORS permissions may prevent secure remote access). Currently this causes a deadlock. This blocks use on Chrome. -> **Fixed**
- [x] Add unit tests for self functions and TensorBoard / TF / PyTorch APIs. TF 2.6.0 has a breaking change for a private function from 2.5.0 -> **Fixed** Ask for explicit `logdir` in TF, since there is no public API and the private API was removed in 2.6.0.
- [x] Validation of msgpack data with CRC-32C
- [x] Jupyter support -> Works without any customization.

### Notes for reviewers: 
- TensorBoard plugin discovery doesn't play nice with our method of including the 3DML repo, so keeping the code in the main repo. for now.
- ~~LineSet needs RPC/mspgpack support from PR #3821.~~ Merged.
- ~~Ready for review now, but set as draft till PR  #3821 is merged.~~ Merged.

 ### TODO (future PRs):
- [ ] Support for materials [Depends on PR #3858 and PR #3985]
- [ ] Allow syncing camera viewpoints for displayed runs.
- [ ] ML3D visualizer interface (labels, features, colormaps)
- [ ] Tutorials + examples.
- [ ] Benchmark read and write performance of msgpack vs Numpy and switch to Numpy if faster.
- [ ] ~~Compression~~ -> `gzip` makes writing and reading slower instead of faster. `lz4` or `zstd` may help, but will add dependencies.

Depends on #3821 [RPC refactorization for serialization] -> Merged.

Screenshot 2021-08-17 at 19-39-54 TensorBoard

Screenshot from 2021-09-08 13-47-35

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3956)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 37 files at r5, 1 of 21 files at r8, 2 of 20 files at r9, 43 of 43 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3956)* status: all files reviewed, 12 unresolved discussions (waiting on @benjaminum, @reyanshsolis, @sanskar107, and @ssheorey)

___
*[cpp/open3d/visualization/webrtc_server/PeerConnectionManager.h, line 290 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-Mih346YEVlpYY-8cGui:-Mih346YEVlpYY-8cGuj:b-jewwsd) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/cpp/open3d/visualization/webrtc_server/PeerConnectionManager.h#L290)):*
> ```objc
>         };
> 
>         bool DataChannelsReady() {
> ```

A data channel is specific to a `peerid`, as we support multiple clients (each have a `peerid`) connecting to the same server. 

In
https://github.com/isl-org/Open3D/blob/4b1a5e0f7527aa3db214d1d2dc117d6510375f68/cpp/open3d/visualization/webrtc_server/PeerConnectionManager.h#L233-L239

we know when the client data channel is ready. With this information, we could maintain a state map in `PeerConnectionManager` (`DataChannelObserver` have access to `PeerConnectionManager*`) to store the status of the data channel specific to a `peerid`.
___
*[cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp, line 163 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-Mih4NMLDm5s5SBt67zs:-Mih4NMLDm5s5SBt67zt:bazqciq) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp#L163)):*
> ```cpp
>                 const std::string window_uid =
>                         value.get("window_uid", "").asString();
>                 const auto oswin = GetOSWindowByUID(window_uid);
> ```

i would use the full name `os_window`
___
*[cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp, line 409 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihFI3Y--A__ae8_OOi:-MihFI3Y--A__ae8_OOj:b4fj246) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp#L409)):*
> ```cpp
>     static const int s_max_initial_frames = 5;
>     static const int s_sleep_between_frames_ms = 100;
>     const auto oswin = GetOSWindowByUID(window_uid);
> ```

same, `os_window`
___
*[cpp/open3d/visualization/webrtc_server/html/webrtcstreamer.js, line 47 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihFV6c5owYDFoUs27t:-MihFV6c5owYDFoUs27u:biehqts) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/cpp/open3d/visualization/webrtc_server/html/webrtcstreamer.js#L47)):*
> ```JavaScript
> 
> let WebRtcStreamer = (function () {
>   // Immediately-executing anonymous functions to enforce variable scope.
> ```

nit: in this file, use 2-space indentation in this file. Also fix the indentation of comments.
___
*[examples/python/visualization/tensorboard_plugin/demo_pytorch.py, line 26 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihKr9PCtQaMx7pmWps:-MihKr9PCtQaMx7pmWpt:b-2jddoy) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/examples/python/visualization/tensorboard_plugin/demo_pytorch.py#L26)):*
> ```Python
> # IN THE SOFTWARE.
> # ----------------------------------------------------------------------------
> # ----------------------------------------------------------------------------
> ```

nit: remove extra line of license, also for the rest of this PR
___
*[python/open3d/visualization/_async_event_loop.py, line 110 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihLYg04_oSJpQFQEtF:-MihLYg134dxMNNNkjch:b-8osr0l) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/_async_event_loop.py#L110)):*
> ```Python
> # There are different ways to achieve this, here we use the module as a holder
> # for singleton variables, see: https://stackoverflow.com/a/31887/1255535.
> _async_event_loop = _AsyncEventLoop()
> ```

since this is imported, may be rename it to `async_event_loop`
___
*[python/open3d/visualization/tensorboard_plugin/plugin.py, line 37 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihLkrh8ULZtwwGE5lI:-MihLkrh8ULZtwwGE5lJ:be8p75s) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/plugin.py#L37)):*
> ```Python
> from tensorboard.backend.event_processing.plugin_event_multiplexer import EventMultiplexer
> from tensorboard.backend.event_processing.plugin_asset_util import PluginDirectory
> import werkzeug
> ```

Will this introduce an extra python dependency? Or is it already handled?
___
*[python/open3d/visualization/tensorboard_plugin/plugin.py, line 56 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihLujkCS3oI1hEe-d8:-MihLujkCS3oI1hEe-d9:bnxldhv) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/plugin.py#L56)):*
> ```Python
> # Set window system before the GUI event loop
> webrtc_server.enable_webrtc()
> from open3d.visualization._async_event_loop import _async_event_loop
> ```

We could `webrtc_server.enable_webrtc()` whenever the async event loop is imported, that is put `webrtc_server.enable_webrtc()` inside async_event_loop file. 
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 200 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihNnPZCyqVD8e1vAsy:-MihNnPZCyqVD8e1vAsz:bml04jl) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/summary.py#L200)):*
> ```Python
>     if color_data.dtype == o3d.core.uint8:
>         return color_data
>     if color_data.dtype == o3d.core.uint16:
> ```

Do we have a use case of supporting `uint16` color type? Othewise, we can just throw exception if the type is not uint8, float32, or float64.

There is a discussion here where the division factor is 256(=65536/256) or 257(=65535/255). Do we have some reference to divide this by 255?
https://answers.opencv.org/question/207313/conversion-16bit-image-to-8-bit-image/
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 210 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihPq70-OOYESKjuoXX:-MihPq71DJUi2cwHYqsV:b-a9wauq) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/summary.py#L210)):*
> ```Python
>     on failure.
>     """
>     try:
> ```

tensor.item()` gets the scalar value if `tensor.num_elements()==1`. 

```python
def _to_integer(tensor):
    try:
        return int(tensor.item())
    except:
        ... # item() failes since tensor.num_elements()!=1
```

___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 224 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihQVA-A69YC0PajnTb:-MihQVA-A69YC0PajnTc:b-52r1mi) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/summary.py#L224)):*
> ```Python
>     """
>     # Check if property is reference to prior step
>     step_ref = _to_integer(tensor)
> ```

we can convert `_to_o3d` at the beginning
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 238 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihRG4f6UjvYk38Dhby:-MihRG4g8ec682aQyb_6:b35ni89) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/summary.py#L238)):*
> ```Python
>         save_tensor.reshape((1,) + tuple(save_tensor.shape))
>     elif tensor.ndim == 3:
>         save_tensor = _to_o3d(tensor[:max_outputs, ...])
> ```

`tensor[:max_outputs, ...]` is equivalent to `tensor[:max_outputs]`, is it true?
If true, we can already do this to open3d tensor.

`ellipsis` has been added to my to-do list for the future.

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3956)* status: 34 of 51 files reviewed, 10 unresolved discussions (waiting on @benjaminum, @reyanshsolis, @sanskar107, @ssheorey, and @yxlao)

___
*[cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp, line 163 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-Mih4NMLDm5s5SBt67zs:-MitPOwx5SZNvZ5-pq-Y:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp#L163)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i would use the full name `os_window`
</blockquote></details>

Done.
___
*[cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp, line 409 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihFI3Y--A__ae8_OOi:-MitPQGD9GwS4697nHNC:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/cpp/open3d/visualization/webrtc_server/WebRTCWindowSystem.cpp#L409)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, `os_window`
</blockquote></details>

Done.
___
*[python/open3d/visualization/tensorboard_plugin/plugin.py, line 37 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihLkrh8ULZtwwGE5lI:-MitRC8MCU4-em28k8Gs:b-emwbzk) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/plugin.py#L37)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Will this introduce an extra python dependency? Or is it already handled?
</blockquote></details>

This module is meant to be imported only by TensorBoard. It should not be imported / used  directly.
___
*[python/open3d/visualization/tensorboard_plugin/plugin.py, line 56 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihLujkCS3oI1hEe-d8:-MitSsZD71IPI13w-yN7:b-h2scgf) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/plugin.py#L56)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We could `webrtc_server.enable_webrtc()` whenever the async event loop is imported, that is put `webrtc_server.enable_webrtc()` inside async_event_loop file. 
</blockquote></details>

Yes. But I think the async event loop would be useful even for local visualization, e.g. if a user wants to add quick 3D visualization to their existing app that already does a lot of things on the main thread.

One problem with the async event loop is that it uses up one CPU code completely all the time due to the Python loop. We need a way for the loop to sleep and wake up on events when the user does something.
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 200 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihNnPZCyqVD8e1vAsy:-MitVfeJEn7CIve1HW_G:bge9ld3) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/summary.py#L200)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Do we have a use case of supporting `uint16` color type? Othewise, we can just throw exception if the type is not uint8, float32, or float64.

There is a discussion here where the division factor is 256(=65536/256) or 257(=65535/255). Do we have some reference to divide this by 255?
https://answers.opencv.org/question/207313/conversion-16bit-image-to-8-bit-image/
</blockquote></details>

This is the use case with intensity data (XYZI)  like lidar reflections. There isn't explicit support for 1 channel color, but a user can just triple the data to make things work.

Good catch. Replaced it with floor division by 256. In C++ it would be integer division:
```
uint16_max = (1<<16)-1
uint16_max // 256 = 255
```

Also added clipping for float values outside [0,1].
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 210 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihPq70-OOYESKjuoXX:-MitXkBK5YH7oO2CtumM:bf0a7dj) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/summary.py#L210)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

tensor.item()` gets the scalar value if `tensor.num_elements()==1`. 

```python
def _to_integer(tensor):
    try:
        return int(tensor.item())
    except:
        ... # item() failes since tensor.num_elements()!=1
</blockquote></details>

The tensor may be a scalar Python integer (reference to earlier step). Also TF doesn't have `tensor.item()`. Simplified the conversion by checking `ndim` if present.
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 224 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihQVA-A69YC0PajnTb:-MitfSNIEogH3JmYmQCS:b-8onplu) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/summary.py#L224)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

we can convert `_to_o3d` at the beginning
</blockquote></details>

Do we have a data copy in the Numpy case? I converted to `_to_o3d` at the end to only copy the `[:max_outputs]` slice.
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 238 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihRG4f6UjvYk38Dhby:-Mitblx0Dp0VaS1SkuXw:bdzq7lx) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/tensorboard_plugin/summary.py#L238)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`tensor[:max_outputs, ...]` is equivalent to `tensor[:max_outputs]`, is it true?
If true, we can already do this to open3d tensor.

`ellipsis` has been added to my to-do list for the future.
</blockquote></details>

Yes thanks. replaced with `tensor[:max_outputs]`
___
*[python/open3d/visualization/_async_event_loop.py, line 110 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-MihLYg04_oSJpQFQEtF:-MitR8j9Eig603PVXhSF:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/python/open3d/visualization/_async_event_loop.py#L110)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

since this is imported, may be rename it to `async_event_loop`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3956)* status: 33 of 52 files reviewed, 10 unresolved discussions (waiting on @benjaminum, @reyanshsolis, @sanskar107, and @yxlao)

___
*[cpp/open3d/visualization/webrtc_server/PeerConnectionManager.h, line 290 at r10](https://reviewable.io/reviews/isl-org/open3d/3956#-Mih346YEVlpYY-8cGui:-Mj0DT7CBaNO2e6y8C98:bb6un1j) ([raw file](https://github.com/isl-org/open3d/blob/89f6fb0a0b20b5d84d0553ebfcf855c5042f24cc/cpp/open3d/visualization/webrtc_server/PeerConnectionManager.h#L290)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

A data channel is specific to a `peerid`, as we support multiple clients (each have a `peerid`) connecting to the same server. 

In
https://github.com/isl-org/Open3D/blob/4b1a5e0f7527aa3db214d1d2dc117d6510375f68/cpp/open3d/visualization/webrtc_server/PeerConnectionManager.h#L233-L239

we know when the client data channel is ready. With this information, we could maintain a state map in `PeerConnectionManager` (`DataChannelObserver` have access to `PeerConnectionManager*`) to store the status of the data channel specific to a `peerid`.
</blockquote></details>

Done

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3956)* status: 31 of 60 files reviewed, 12 unresolved discussions (waiting on @benjaminum, @reyanshsolis, @sanskar107, @ssheorey, and @yxlao)

___
*[examples/python/visualization/tensorboard_plugin/demo_pytorch.py, line 1 at r14](https://reviewable.io/reviews/isl-org/open3d/3956#-MjVsaPM-N2kcxyTh-sB:-MjVsaPM-N2kcxyTh-sC:b-7cyxdk) ([raw file](https://github.com/isl-org/open3d/blob/1907270189776a682629510773000daf953c1297/examples/python/visualization/tensorboard_plugin/demo_pytorch.py#L1)):*
> ```Python
> # ----------------------------------------------------------------------------
> ```

Nit: could we move `examples/python/visualization/tensorboard_plugin/demo_pytorch.py` to
`examples/python/visualization/tensoboard_pytorch.py`

Similarly for the TensorFlow one.
___
*[examples/python/visualization/tensorboard_plugin/demo_pytorch.py, line 34 at r14](https://reviewable.io/reviews/isl-org/open3d/3956#-MjVt4Ww3aETxBK4q6Ai:-MjVt4Ww3aETxBK4q6Aj:b3yu0x1) ([raw file](https://github.com/isl-org/open3d/blob/1907270189776a682629510773000daf953c1297/examples/python/visualization/tensorboard_plugin/demo_pytorch.py#L34)):*
> ```Python
> from torch.utils.tensorboard import SummaryWriter
> ```

In `demo_tensorflow.py`, we have
```python
BASE_LOGDIR = "demo_logs/tf/"
```

Shall we be consistent here by writing to `demo_logs/pytorch/`?

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3956)* status: 31 of 60 files reviewed, 11 unresolved discussions (waiting on @benjaminum, @reyanshsolis, @sanskar107, and @yxlao)

___
*[examples/python/visualization/tensorboard_plugin/demo_pytorch.py, line 1 at r14](https://reviewable.io/reviews/isl-org/open3d/3956#-MjVsaPM-N2kcxyTh-sB:-Mj_Tlwl3OnvmeAd-svE:bb6un1j) ([raw file](https://github.com/isl-org/open3d/blob/1907270189776a682629510773000daf953c1297/examples/python/visualization/tensorboard_plugin/demo_pytorch.py#L1)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Nit: could we move `examples/python/visualization/tensorboard_plugin/demo_pytorch.py` to
`examples/python/visualization/tensoboard_pytorch.py`

Similarly for the TensorFlow one.
</blockquote></details>

Done
___
*[examples/python/visualization/tensorboard_plugin/demo_pytorch.py, line 34 at r14](https://reviewable.io/reviews/isl-org/open3d/3956#-MjVt4Ww3aETxBK4q6Ai:-Mj_VN8U0lIB9bKxKaI0:b-x1qtox) ([raw file](https://github.com/isl-org/open3d/blob/1907270189776a682629510773000daf953c1297/examples/python/visualization/tensorboard_plugin/demo_pytorch.py#L34)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

In `demo_tensorflow.py`, we have
```python
BASE_LOGDIR = "demo_logs/tf/"
```

Shall we be consistent here by writing to `demo_logs/pytorch/`?
</blockquote></details>

Done. Also switched to `os.path.join`

**Comment by benjaminum** [comment]
Hi @ssheorey ,

I noticed some minor bugs/inconveniences using the plugin:
- There is an unwanted camera reset when changing step, options, or tags
- The last tag stays visible even if all tags are unchecked

**Comment by ssheorey** [comment]
@benjaminum Updated behavior:
> 
>     * There is an unwanted camera reset when changing step, options, or tags

The camera is now reset only when one tag is added to an empty scene, i.e. on first load and if all tags are removed and any tag is added.

> 
>     * The last tag stays visible even if all tags are unchecked

Fixed. The scene is empty if all tags are removed.

**Review by yxlao — APPROVED** [review]
> Reviewed 2 of 8 files at r11, 3 of 13 files at r12, 3 of 9 files at r13, 11 of 14 files at r14, 7 of 7 files at r15, 1 of 2 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3956)* status: 60 of 61 files reviewed, 5 unresolved discussions (waiting on @benjaminum, @reyanshsolis, @sanskar107, @ssheorey, and @yxlao)

___
*[docs/make_docs.py, line 225 at r17](https://reviewable.io/reviews/isl-org/open3d/3956#-Mk7Pl6xDOEdwq1hq-wC:-Mk7Pl6xDOEdwq1hq-wD:brfzjik) ([raw file](https://github.com/isl-org/open3d/blob/e6a1324843c7c0addd5326ae8760eaa71deff0f2/docs/make_docs.py#L225)):*
> ```Python
>             obj[0]
>             for obj in inspect.getmembers(module)
>             if inspect.isclass(obj[1]) and not obj[0][0] == '_'
> ```

nit: more "pythonic" way: `and not obj[0].startswith('_')`

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3956)* status: 60 of 61 files reviewed, 5 unresolved discussions (waiting on @benjaminum, @reyanshsolis, @sanskar107, and @yxlao)

___
*[docs/make_docs.py, line 225 at r17](https://reviewable.io/reviews/isl-org/open3d/3956#-Mk7Pl6xDOEdwq1hq-wC:-MkIISHdCY7JOKCGp6qf:b-a2ujfl) ([raw file](https://github.com/isl-org/open3d/blob/e6a1324843c7c0addd5326ae8760eaa71deff0f2/docs/make_docs.py#L225)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: more "pythonic" way: `and not obj[0].startswith('_')`
</blockquote></details>

Changed.

**Pull request merged**
