### PR TITLE
Fix rendering of Python versions table in docs

### PR DESCRIPTION
**Pull request by johnthagen**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

The[ Getting Started](http://www.open3d.org/docs/release/getting_started.html) page currently has a list (supported Python versions) that is not rendered properly.

Screenshot 2023-05-21 125525

## Checklist:

-   [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6162)

### CODE REVIEW

**Comment by johnthagen** [comment]
> Thanks for submitting this pull request! The maintainers of this repository would appreciate if you could update the CHANGELOG.md based on your changes.

I presume this change does not need a changelog entry, but if it does, please let me know.

**Review by reyanshsolis — APPROVED** [review]
LGTM. Don't worry about CHANGELOGS.

**Comment by reyanshsolis** [comment]
@ssheorey I am not able to re-trigger test. Can you please try from your end ?

**Comment by ssheorey** [comment]
> @ssheorey I am not able to re-trigger test. Can you please try from your end ?

You can re-trigger test by either of:
- adding a new commit (e.g. merging master locally and pushing the update).
- closing and re-opening the PR.

**Pull request merged**
