### PR TITLE
Throw proper error for invalid CUDA device id.

### PR DESCRIPTION
**Pull request by reyanshsolis**
- Throw error for invalid CUDA device id from `MemoryManager`. 

Issue to be resolved:
- Unit Test `TEST_P` is unable to catch errors thrown by `CUDA Runtime`. However, under `TEST` it is working fine when devices are initialized manually.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3890)

### CODE REVIEW

**Comment by yxlao** [comment]
As discussed, we can move the checker function to `CUDAUtils` and call the checker function right before the error happening.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3890)* status: all files reviewed, 3 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/core/CUDAUtils.h, line 260 at r3](https://reviewable.io/reviews/isl-org/open3d/3890#-MgjXk8_CzWtSsO72uJS:-MgjXk8_CzWtSsO72uJT:bn9tcfn) ([raw file](https://github.com/isl-org/open3d/blob/d5d8ea0a798d57439bec3bfef9d0d6abfc12da08/cpp/open3d/core/CUDAUtils.h#L260)):*
> ```objc
> /// device-ID must be between 0 to device count - 1.
> /// \param device_id The cuda device id to be checked.
> void AssertCUDADeviceIDIsAvailable(const int& device_id);
> ```

- `AssertCUDADeviceIDIsAvailable` -> `AssertCUDADeviceAvailable`
- `const int &` -> `int`
___
*[cpp/open3d/core/CUDAUtils.cpp, line 93 at r3](https://reviewable.io/reviews/isl-org/open3d/3890#-MgjXwvC-yHIH8T7E72-:-MgjXwvC-yHIH8T7E720:bo2jq8w) ([raw file](https://github.com/isl-org/open3d/blob/d5d8ea0a798d57439bec3bfef9d0d6abfc12da08/cpp/open3d/core/CUDAUtils.cpp#L93)):*
> ```cpp
> void AssertCUDADeviceIDIsAvailable(const int& device_id) {
> #ifdef BUILD_CUDA_MODULE
>     if (core::cuda::DeviceCount()) {
> ```

Remove `core::cuda::`, same for the rest.

We can simplify the logics as following:
```cpp
if (DeviceCount() == 0) {
    utility::LogError("...");
} else if (DeviceCount() == 1 && device_id != 0) {

} else if (device_id < 0 || device_id >= DeviceCount()) {

}
```

Benefits:
- No tested `if`. Previously there are 3-level nested `if`.
- Logically makes more sense for `DeviceCount()`: `== 0`, `==1`, `>1`.
- Be more explicit, avoid using int in `if()` condition when possible. 
___
*[cpp/open3d/core/CUDAUtils.cpp, line 116 at r3](https://reviewable.io/reviews/isl-org/open3d/3890#-Mgj_Wj85P6qwoWUqRBF:-Mgj_Wj85P6qwoWUqRBG:bbktr33) ([raw file](https://github.com/isl-org/open3d/blob/d5d8ea0a798d57439bec3bfef9d0d6abfc12da08/cpp/open3d/core/CUDAUtils.cpp#L116)):*
> ```cpp
> #else
>     utility::LogError(
>             "BUILD_WITH_CUDA=OFF. Please build with CUDA to use CUDA device.");
> ```

build with `-DBUILD...` (specify the full cmake flag)

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3890)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/CUDAUtils.h, line 260 at r3](https://reviewable.io/reviews/isl-org/open3d/3890#-MgjXk8_CzWtSsO72uJS:-MgjgyrbCR1w2uhLjOFy:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d5d8ea0a798d57439bec3bfef9d0d6abfc12da08/cpp/open3d/core/CUDAUtils.h#L260)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

- `AssertCUDADeviceIDIsAvailable` -> `AssertCUDADeviceAvailable`
- `const int &` -> `int`
</blockquote></details>

Done.
___
*[cpp/open3d/core/CUDAUtils.cpp, line 93 at r3](https://reviewable.io/reviews/isl-org/open3d/3890#-MgjXwvC-yHIH8T7E72-:-Mgjh34F8P-eNk-JIUWu:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d5d8ea0a798d57439bec3bfef9d0d6abfc12da08/cpp/open3d/core/CUDAUtils.cpp#L93)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Remove `core::cuda::`, same for the rest.

We can simplify the logics as following:
```cpp
if (DeviceCount() == 0) {
    utility::LogError("...");
} else if (DeviceCount() == 1 && device_id != 0) {

} else if (device_id < 0 || device_id >= DeviceCount()) {

}
```

Benefits:
- No tested `if`. Previously there are 3-level nested `if`.
- Logically makes more sense for `DeviceCount()`: `== 0`, `==1`, `>1`.
- Be more explicit, avoid using int in `if()` condition when possible. 
</blockquote></details>

Done.
___
*[cpp/open3d/core/CUDAUtils.cpp, line 116 at r3](https://reviewable.io/reviews/isl-org/open3d/3890#-Mgj_Wj85P6qwoWUqRBF:-Mgjh7pd4mVlwBGlRwTj:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d5d8ea0a798d57439bec3bfef9d0d6abfc12da08/cpp/open3d/core/CUDAUtils.cpp#L116)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

build with `-DBUILD...` (specify the full cmake flag)
</blockquote></details>

Done.

**Review by yxlao — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3890)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/core/CUDAUtils.cpp, line 95 at r4](https://reviewable.io/reviews/isl-org/open3d/3890#-Mgjhr5VA4A9yvE9wcVV:-Mgjhr5VA4A9yvE9wcVW:b391bzh) ([raw file](https://github.com/isl-org/open3d/blob/a1ee0c0ce5479a31a869b0ec45b24c79cdf9e692/cpp/open3d/core/CUDAUtils.cpp#L95)):*
> ```cpp
>     if (cuda::DeviceCount() == 0) {
>         utility::LogError(
>                 "Invalid device 'CUDA:{}'. BUILD_WITH_CUDA=ON, but no CUDA "
> ```

Please update `BUILD_WITH_CUDA` in the PR, it's the wrong flag. Check the root cmake file to be sure.
I would also suggest adding `-D` to the front, that is `-DBUILD...`

**Review by yxlao — APPROVED** [review]

**Pull request merged**
