### PR TITLE
Fix the triggering in PickPointsInteractor when there are linesets pr…

### PR DESCRIPTION
**Pull request by EwingKang**
Adds handling of LineSet that is similar to Mesh and PointCloud in SetPickableGeometry()

## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

This change fixes https://github.com/isl-org/Open3D/issues/6498

## Checklist:

-   [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code. **(On U22.04, clang_format 10 is not available, the default install script didn't worked, I eyeballed the format instead)**
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

GUI no-longer crashes when there's lineset object in the scene when switching to `Actions -> show settings -> Mouse control (drop down) -> Selection (tab).`

### CODE REVIEW

**Comment by godwincharan** [comment]
I could help review this PR

**Comment by EwingKang** [comment]
Seems like Codacy caught an error (thanks!)
I fixed it. But not sure if I should just rebase (squash) the to make the commit tree cleaner.
Also, automated style check reported an error, but it only says "Style error found in the following files:... Error: Process completed with exit code 1.". I'm also not sure where to check the error report.

**Review by godwincharan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6499)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @EwingKang)

___
*[`cpp/open3d/visualization/gui/PickPointsInteractor.cpp` line 166 at r1](https://reviewable.io/reviews/isl-org/Open3D/6499#-NjxixZU7UJaxUTdABmV:-NjxixZU7UJaxUTdABmW:bbt9nwm) ([raw file](https://github.com/isl-org/Open3D/blob/837a76f6ffd2f3b223b585c47e3fe6f3625c0380/cpp/open3d/visualization/gui/PickPointsInteractor.cpp#L166)):*
> ```cpp
>         auto tmesh =
>                 dynamic_cast<const t::geometry::TriangleMesh *>(pg.tgeometry);
>         auto lineset = dynamic_cast<const geometry::LineSet *>(pg.geometry);
> ```

Can we implement polymorphism here rather than dynamically casting and checking for nullptr?

**Comment by EwingKang** [comment]
Hi @godwincharan ,
I think it would be possible. However the structure `PickableGeometry` defined in [SceneWidget.h#L131](https://github.com/isl-org/Open3D/blob/master/cpp/open3d/visualization/gui/SceneWidget.h#L131) is not a templated class by itself. It actually stores two raw pointers to objects:
```c++
        const geometry::Geometry3D* geometry = nullptr;
        const t::geometry::Geometry* tgeometry = nullptr;
```
So one would have to check which one is the valid pointer essentially. 
Speaking about polymorphism, my first idea of the solution is to make `PickableGeometry` templated by itself, and implement specializations for different objects.

Another way to implement this is to add some sort of base function that returns interest points in their parent class. 
For the newer `open3d::t::geometry::` namespace, [There are 5 chlidrens in `DrawableGeometry`](http://www.open3d.org/docs/release/cpp_api/classopen3d_1_1t_1_1geometry_1_1_drawable_geometry.html#a72987c98386c0a92919cdd2c945af2a2). I think this is doable.
For the old `open3d::geometry::XXXXX` object, [there are many chlidren](http://www.open3d.org/docs/release/cpp_api/classopen3d_1_1geometry_1_1_geometry3_d.html) that all inherits `open3d::geometry`. I don't think it's a good idea to enforce the base function.

The third way is to make pickable objects inherit a new base class. This would require some careful design directly from the owner/maintainers IMHO.

My original intent is to quickly fix this crashing issue for me, so I simply follow what it has been done there. But I would love to implement a more complete solution (at least for the newer `open3d::t::` namespace as described in solution 2). What does everyone think about this issue? I would be happy to have some inputs from you.

**Review by ssheorey — APPROVED** [review]
Thanks @EwingKang for the fix!

PS: Here's the last part of the output of `make apply-style` for me:
```
...
Please correct license header *manually* in the following files (see util/check_style.py for the standard header):
/home/ssheorey/Documents/Open3D/Code/Open3D/examples/cpp/TImage.cpp
make[3]: *** [CMakeFiles/apply-style.dir/build.make:71: CMakeFiles/apply-style] Error 1
make[2]: *** [CMakeFiles/Makefile2:2053: CMakeFiles/apply-style.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2060: CMakeFiles/apply-style.dir/rule] Error 2
make: *** [Makefile:709: apply-style] Error 2
```
I was able to fix it by updating the license header text. Is this the issue you ran into?

**Comment by ssheorey** [comment]
@godwincharan agree with your assessment that polymorphism may help to simplify this code. However, the refactoring will take some careful planning and effort as @EwingKang has noted. Please reach out to me if you would like to help.

**Comment by EwingKang** [comment]
@ssheorey Thanks for merging the code. 
I'm actively using Open3D in my project so I'm definitely going to have some feedbacks. It is probably within the reach for me to contribute the polymorphism part, but I think I'll first take some time to get familiar with the code base and design philosophy.

About the style checker, I just re-ran the checker with `python3 util/check_style.py --apply` and it did worked. But I've done a lot to my system so practically everything is changed. I'll try it again in a few weeks when I'm going to get a new PC, to see which step is missing.
Cheers.

**Comment by EwingKang** [comment]
> 
> About the style checker, I just re-ran the checker with `python3 util/check_style.py --apply` and it did worked. But I've done a lot to my system so practically everything is changed. I'll try it again in a few weeks when I'm going to get a new PC, to see which step is missing. Cheers.

So I've test it again with a fresh Ubuntu 22.04 install. It turns out that the when installing the style checker dependencies [following the instructions](https://www.open3d.org/docs/release/contribute/styleguide.html#style-guide), the install defaults to `~/.local/bin`. It also gave warning like this:
```bash
...
  WARNING: The scripts clang-format, clang-format-diff.py and git-clang-format are installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: nbformat
    Found existing installation: nbformat 5.9.2
    Uninstalling nbformat-5.9.2:
      Successfully uninstalled nbformat-5.9.2
  WARNING: The script jupyter-trust is installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed clang-format-10.0.1.1 nbformat-5.7.0
...
```
I just installed it to the system with `sudo` and the `clang-format` style checker `python util/check_style.py` can be executed correctly
```bash
sudo pip3 install clang-format==10.0.1.1
```

**Pull request merged**
