### PR TITLE
Add flatten operation to Tensor

### PR DESCRIPTION
**Pull request by ShreyanshDarshan**
The flatten operation is based on flatten from pytorch, as pytorch and numpy had inconsistent flatten functions.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4305)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4305)* status: all files reviewed, 7 unresolved discussions (waiting on @ShreyanshDarshan)

___
*[cpp/open3d/core/Tensor.h, line 418 at r2](https://reviewable.io/reviews/isl-org/open3d/4305#-Mokbum66rSMD4pual-l:-Mokbum66rSMD4pual-m:b-erlxo0) ([raw file](https://github.com/isl-org/open3d/blob/6ced90e39d13953926465fbf2af4613c309132d2/cpp/open3d/core/Tensor.h#L418)):*
> ```objc
>     /// - aten/src/ATen/native/TensorShape.cpp
>     /// - aten/src/ATen/TensorUtils.cpp
>     Tensor Flatten(int64_t start_dim = 0, int64_t end_dim = -1) const;
> ```

Document arguments, e.g.`/// \param start_dim`, are they inclusive or exclusive? See `Tensor::Slice()`'s documentation.
___
*[cpp/open3d/core/Tensor.cpp, line 663 at r2](https://reviewable.io/reviews/isl-org/open3d/4305#-MojZysV-r46mzeedAL7:-MojZysV-r46mzeedAL8:b-6kc2al) ([raw file](https://github.com/isl-org/open3d/blob/6ced90e39d13953926465fbf2af4613c309132d2/cpp/open3d/core/Tensor.cpp#L663)):*
> ```cpp
>     core::SizeVector shape = GetShape();
>     core::SizeVector dst_shape;
>     if (start_dim < -(int64_t)shape.size() ||
> ```

Always use `{}` for `if`. Same for the rest.
___
*[cpp/open3d/core/Tensor.cpp, line 663 at r2](https://reviewable.io/reviews/isl-org/open3d/4305#-Moj_HUw6YTG-CzGUtCw:-Moj_HUw6YTG-CzGUtCx:bwv25aw) ([raw file](https://github.com/isl-org/open3d/blob/6ced90e39d13953926465fbf2af4613c309132d2/cpp/open3d/core/Tensor.cpp#L663)):*
> ```cpp
>     core::SizeVector shape = GetShape();
>     core::SizeVector dst_shape;
>     if (start_dim < -(int64_t)shape.size() ||
> ```

Use `Tensor::NumDims()` instead of `(int64_t)shape.size()`. You can save this as a variable for code simplicity.
___
*[cpp/open3d/core/Tensor.cpp, line 664 at r2](https://reviewable.io/reviews/isl-org/open3d/4305#-Moj_LmI5RRNAa_sti5t:-Moj_LmI5RRNAa_sti5u:b-pwu6cj) ([raw file](https://github.com/isl-org/open3d/blob/6ced90e39d13953926465fbf2af4613c309132d2/cpp/open3d/core/Tensor.cpp#L664)):*
> ```cpp
>     core::SizeVector dst_shape;
>     if (start_dim < -(int64_t)shape.size() ||
>         start_dim >= (int64_t)shape.size())
> ```

Use `ShapeUtil::WrapDim()` to convert negative dim.
___
*[cpp/pybind/core/tensor.cpp, line 707 at r2](https://reviewable.io/reviews/isl-org/open3d/4305#-Mokc5nk6-pR9QjWpBBC:-Mokc5nk6-pR9QjWpBBD:b-vgxmtj) ([raw file](https://github.com/isl-org/open3d/blob/6ced90e39d13953926465fbf2af4613c309132d2/cpp/pybind/core/tensor.cpp#L707)):*
> ```cpp
> - aten/src/ATen/native/TensorShape.cpp
> - aten/src/ATen/TensorUtils.cpp)",
>             "start_dim"_a = 0, "end_dim"_a = -1);
> ```

Document arguments, are they inclusive or exclusive? Use the `docstring::ClassMethodDocInject` to specify the docs.
___
*[cpp/tests/core/Tensor.cpp, line 414 at r2](https://reviewable.io/reviews/isl-org/open3d/4305#-Mokb0_T9FWI9hCws6yv:-Mokb0_T9FWI9hCws6yw:b3k8g83) ([raw file](https://github.com/isl-org/open3d/blob/6ced90e39d13953926465fbf2af4613c309132d2/cpp/tests/core/Tensor.cpp#L414)):*
> ```cpp
> }
> 
> TEST_P(TensorPermuteDevices, Flatten) {
> ```

Add more comprehensive tests. You should test the shape of the resulting tensor, and also test exception cases.

* 0-d Tensor. 
    - `Flatten()` # It shall turn from 0-d to 1-d
    - Test combination of positive, negative, and 0 as arguments for `Flatten()`. Some of them may be out-of-range, and in those cases, test that an exception is thrown. 
* 1-D Tensor.
     - Test combination of positive, negative, and 0 as arguments for `Flatten()`
* 2-D Tensor
     - Test combination of positive, negative, and 0 as arguments for `Flatten()`. E.g. if you only flatten the 0-th dimension, the result shall remain completely the same.
* 3-D Tensor
     - Test combination of positive, negative, and 0 as arguments for `Flatten()`. E.g. if you only flatten the 0-th dimension, the result shall remain completely the same.
___
*[python/test/core/test_core.py, line 248 at r2](https://reviewable.io/reviews/isl-org/open3d/4305#-MokdV8p5M8AGLhJ75Mu:-MokdV8p5M8AGLhJ75Mv:b11bd21) ([raw file](https://github.com/isl-org/open3d/blob/6ced90e39d13953926465fbf2af4613c309132d2/python/test/core/test_core.py#L248)):*
> ```Python
> @pytest.mark.parametrize("device", list_devices())
> def test_flatten(device):
>     src_t = o3c.Tensor([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
> ```

Same comments as the C++ test.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4305)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @ShreyanshDarshan and @yxlao)

___
*[python/test/core/test_core.py, line 278 at r4](https://reviewable.io/reviews/isl-org/open3d/4305#-MpA9KXs54qJ6_Paezab:-MpA9KXt05sM1DwUpQOx:b-g0ed73) ([raw file](https://github.com/isl-org/open3d/blob/c52b1cb57cffbfe079d7eb9d2beec8c9dd708ad2/python/test/core/test_core.py#L278)):*
> ```Python
>     assert ((dst_t == src_t.flatten(-1)).all())
> 
>     assert ((dst_t == src_t.flatten(0, 0)).all())
> ```

Use: `dst_t.IsAllEqual(src_t)`
___
*[python/test/core/test_core.py, line 299 at r5](https://reviewable.io/reviews/isl-org/open3d/4305#-MpFza_k0DYRK3YWw0-7:-MpFza_l2QL949ZGDPz4:b-alt9uq) ([raw file](https://github.com/isl-org/open3d/blob/0f69b2406afedf0c2f3074b693fe7c7dd96c0858/python/test/core/test_core.py#L299)):*
> ```Python
>                                  dtype=o3c.Dtype.Int64).to(device)
> 
>     assert (dst_t_flat.allclose(src_t.flatten()))
> ```

Use `assert` without `()`. This is to avoid the confusion of:

```python
assert False # exception 
assert (False) # exception
assert (False,) # no exception, since the tuple is not empty
```

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4305)* status: all files reviewed, 7 unresolved discussions (waiting on @ShreyanshDarshan)

___
*[cpp/open3d/core/Tensor.h, line 419 at r6](https://reviewable.io/reviews/isl-org/open3d/4305#-MpIdtL4-crdDx0bL8IQ:-MpIdtL55o9AHCOD_8wx:bsugr3c) ([raw file](https://github.com/isl-org/open3d/blob/0458f64f69acffef8cd5a8b7e48a8734e6ae1e58/cpp/open3d/core/Tensor.h#L419)):*
> ```objc
>     /// - aten/src/ATen/TensorUtils.cpp
>     ///
>     /// \param start_dim The first dimension to flatten (exclusive).
> ```

Do you mean inclusive?
E.g. for a 3D tensor, if `start_dim == 0`, `end_dim == 2`, that means we flatten all dimensions. Here the `0` and `2` is "included".
___
*[cpp/open3d/core/Tensor.h, line 421 at r6](https://reviewable.io/reviews/isl-org/open3d/4305#-MpIeH5L0sMGXuPDjWiF:-MpIeH5MDYofVDksrgEr:b-pll0wv) ([raw file](https://github.com/isl-org/open3d/blob/0458f64f69acffef8cd5a8b7e48a8734e6ae1e58/cpp/open3d/core/Tensor.h#L421)):*
> ```objc
>     /// \param start_dim The first dimension to flatten (exclusive).
>     /// \param end_dim The last dimension to flatten, starting from \p start_dim
>     /// (exclusive).
> ```

Same comment, shall be "inclusive".
___
*[cpp/open3d/core/Tensor.cpp, line 664 at r6](https://reviewable.io/reviews/isl-org/open3d/4305#-MpJ0IHA9BxCf5KgiLlB:-MpJ0IHA9BxCf5KgiLlC:b84lrct) ([raw file](https://github.com/isl-org/open3d/blob/0458f64f69acffef8cd5a8b7e48a8734e6ae1e58/cpp/open3d/core/Tensor.cpp#L664)):*
> ```cpp
>     core::SizeVector dst_shape;
>     int64_t num_dims = NumDims();
>     if (num_dims == 0) {
> ```

- We can treat 0-dim as 1-dim, to unify everything to one case. I would also move this to the very top of this function.
- Let's also add a comment why 0-dim can accept dimension indexing at all. In most cases, we cannot index a 0-dim tensor.
```cpp
    int64_t num_dims = NumDims();
    if (num_dims == 0) {
        // Flattening a 0-d tensor is equivalent to flattening the tensor
        // reshaped to 1-d. Technically, we cannot have a start_dim or end_dim,
        // since a 0-d tensor cannot be indexed, e.g. np.array(100)[0] is not
        // valid. But start_dim = 0 and end_dim = -1 are the default parameter
        // values so we make an exception case for 0-d. We reshape it to 1-d for
        // boundary checks of start_dim and end_dim.
        return Reshape({1}).Flatten(start_dim, end_dim);
    }
```
___
*[cpp/open3d/core/Tensor.cpp, line 672 at r6](https://reviewable.io/reviews/isl-org/open3d/4305#-MpJ0jE99iBx9nZa91S6:-MpJ0jE99iBx9nZa91S7:bg11myo) ([raw file](https://github.com/isl-org/open3d/blob/0458f64f69acffef8cd5a8b7e48a8734e6ae1e58/cpp/open3d/core/Tensor.cpp#L672)):*
> ```cpp
>     start_dim = shape_util::WrapDim(start_dim, num_dims, false);
>     end_dim = shape_util::WrapDim(end_dim, num_dims, false);
>     if (end_dim < start_dim) {
> ```

- here, I would also print the dimensions such that the message is clear.
- `LogError` already prints the function name, so there's no need to mention it again.

Something like this:
```cpp
    if (start_dim > end_dim) {
        utility::LogError(
                "start_dim {} must be smaller or equal to end_dim {}.",
                start_dim, end_dim);
    }
```
___
*[cpp/open3d/core/Tensor.cpp, line 677 at r6](https://reviewable.io/reviews/isl-org/open3d/4305#-MpJ1r1S6kcsOq8S0IRp:-MpJ1r1S6kcsOq8S0IRq:b-mf7l8x) ([raw file](https://github.com/isl-org/open3d/blob/0458f64f69acffef8cd5a8b7e48a8734e6ae1e58/cpp/open3d/core/Tensor.cpp#L677)):*
> ```cpp
>                 "end_dim");
>     }
>     // Multiply the flattened dimensions together
> ```

nit: add `.` after comment. Also apply this to the rest of this PR. We follow https://google.github.io/styleguide/cppguide.html#Comments in general, and the comments there have `.`.
___
*[cpp/pybind/core/tensor.cpp, line 710 at r6](https://reviewable.io/reviews/isl-org/open3d/4305#-MpJ2aGZ9vZA2ZQth4nG:-MpJ2aGZ9vZA2ZQth4nH:bg8jale) ([raw file](https://github.com/isl-org/open3d/blob/0458f64f69acffef8cd5a8b7e48a8734e6ae1e58/cpp/pybind/core/tensor.cpp#L710)):*
> ```cpp
>     docstring::ClassMethodDocInject(
>             m, "Tensor", "flatten",
>             {{"start_dim", "The first dimension to flatten (exclusive)"},
> ```

inclusive. 
Add `.`
___
*[cpp/pybind/core/tensor.cpp, line 713 at r6](https://reviewable.io/reviews/isl-org/open3d/4305#-MpJ2cCe9llX5JmWtWUj:-MpJ2cCe9llX5JmWtWUk:bg8jale) ([raw file](https://github.com/isl-org/open3d/blob/0458f64f69acffef8cd5a8b7e48a8734e6ae1e58/cpp/pybind/core/tensor.cpp#L713)):*
> ```cpp
>              {"end_dim",
>               "The last dimension to flatten, starting from start_dim "
>               "(exclusive)"}});
> ```

inclusive. 
Add `.`

**Comment by ShreyanshDarshan** [comment]
> Do you mean inclusive?
> E.g. for a 3D tensor, if `start_dim == 0`, `end_dim == 2`, that means we flatten all dimensions. Here the `0` and `2` is "included".

I followed the definition of inclusive in the comments of ShapeUtil::WrapDim. Does this need to be changed?
```cpp
/// \brief Wrap around negative \p dim.
///
/// E.g. If max_dim == 5, dim -1 will be converted to 4.
///
/// \param dim Dimension index
/// \param max_dim Maximum dimension index
/// \param inclusive Set to true to allow dim == max_dim. E.g. for slice
///        T[start:end], we allow end == max_dim.
int64_t WrapDim(int64_t dim, int64_t max_dim, bool inclusive = false);
```

**Review by yxlao — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4305)* status: all files reviewed, 2 unresolved discussions (waiting on @ShreyanshDarshan)

**Pull request merged**
