### PR TITLE
Parallelize FastGlobalRegistration

### PR DESCRIPTION
**Pull request by gsakkis**
Parallelize with OpenMP the initial matching of `FastGlobalRegistration`, plus minor refactoring.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3849)

### CODE REVIEW

**Comment by theNded** [comment]
Thanks for the contribution! Prior to the review, could you please provide some stats? I would like to check 3 items:
1) the returned transformations are unchanged fixing the seed;
2) the speed is on par or faster **without** `omp parallel for` -- the introduced `std::map` might slow down the process compared to `std::vector`;
3) the speed gain from **omp parallel for**.
Thanks!

**Comment by gsakkis** [comment]
> Thanks for the contribution! Prior to the review, could you please provide some stats? I would like to check 3 items:

<details>
<summary>Sample script to address the request:</summary>

```py
import sys
import time

import open3d as o3d


o3d_registration = o3d.pipelines.registration
KDTreeSearchParamHybrid = o3d.geometry.KDTreeSearchParamHybrid


def read_point_cloud(uri, voxel_size):
    pcd = o3d.io.read_point_cloud(uri)
    pcd = pcd.voxel_down_sample(voxel_size)
    pcd.estimate_normals(KDTreeSearchParamHybrid(radius=voxel_size * 2, max_nn=30))
    fpfh = o3d_registration.compute_fpfh_feature(
        pcd, KDTreeSearchParamHybrid(radius=voxel_size * 5, max_nn=100)
    )
    return pcd, fpfh


def main(source_uri, target_uri, voxel_size, seed=None):
    source, source_feature = read_point_cloud(source_uri, voxel_size)
    target, target_feature = read_point_cloud(target_uri, voxel_size)
    start = time.time()
    reg_result = o3d_registration.registration_fast_based_on_feature_matching(
        source,
        target,
        source_feature,
        target_feature,
        option=o3d_registration.FastGlobalRegistrationOption(
            maximum_correspondence_distance=voxel_size * 0.5, seed=seed
        ),
    )
    print("Global registration took %.3f sec.\n" % (time.time() - start))
    print(reg_result)
    print(reg_result.transformation)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], voxel_size=float(sys.argv[3]), seed=42)
```
</details>  

<details>  
<summary>Sample run on this branch (c507370eb):</summary>

```
$ python test_fast_registration.py examples/test_data/ICP/cloud_bin_0.pcd examples/test_data/ICP/cloud_bin_1.pcd 0.01
Global registration took 2.474 sec.

RegistrationResult with fitness=9.039998e-02, inlier_rmse=3.813651e-03, and correspondence_set size of 8620
Access transformation to get result.
[[ 0.85118264  0.00562547 -0.52483947  0.63863835]
 [-0.13728709  0.96751686 -0.21228138  0.76214521]
 [ 0.50659685  0.2527439   0.82430586 -1.42676343]
 [-0.          0.         -0.          1.        ]]
```
</details>  

<details>  
<summary>Sample run on master (76c2baf9d):</summary>

```
$ python test_fast_registration.py examples/test_data/ICP/cloud_bin_0.pcd examples/test_data/ICP/cloud_bin_1.pcd 0.01
Global registration took 10.328 sec.

RegistrationResult with fitness=9.039998e-02, inlier_rmse=3.813651e-03, and correspondence_set size of 8620
Access transformation to get result.
[[ 0.85118264  0.00562547 -0.52483947  0.63863835]
 [-0.13728709  0.96751686 -0.21228138  0.76214521]
 [ 0.50659685  0.2527439   0.82430586 -1.42676343]
 [-0.          0.         -0.          1.        ]]
```
</details>  

<details>  
<summary>Sample run on this branch (c507370eb) after removing the <code>omp parallel for</code>:</summary>

```
$ python test_fast_registration.py examples/test_data/ICP/cloud_bin_0.pcd examples/test_data/ICP/cloud_bin_1.pcd 0.01
Global registration took 10.432 sec.

RegistrationResult with fitness=9.039998e-02, inlier_rmse=3.813651e-03, and correspondence_set size of 8620
Access transformation to get result.
[[ 0.85118264  0.00562547 -0.52483947  0.63863835]
 [-0.13728709  0.96751686 -0.21228138  0.76214521]
 [ 0.50659685  0.2527439   0.82430586 -1.42676343]
 [-0.          0.         -0.          1.        ]]
```
</details>  

The `std::map` vs `std::vector` perf difference is up to ~1% in my tests.

**Review by theNded — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3849)* status: all files reviewed, 5 unresolved discussions (waiting on @gsakkis, @ssheorey, and @yxlao)

___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/3849#-MgBYDJDCkiVC34INth9:-MgBYDJDCkiVC34INthA:butublx) ([raw file](https://github.com/isl-org/open3d/blob/c507370eb16520f637a783c7a449e757e73a624a/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L43)):*
> ```cpp
> 
> static std::vector<std::pair<int, int>> InitialMatching(
>         const Feature& big_features, const Feature& small_features) {
> ```

I would recommend using `src_features` and `dst_features`. Then add comments and a length check to ensure `src_features.size() > dst_features.size()`.
___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 61 at r3](https://reviewable.io/reviews/isl-org/open3d/3849#-MgHjUsh2Cvwq2sjXlK9:-MgHjUsh2Cvwq2sjXlKA:b-rxz0ks) ([raw file](https://github.com/isl-org/open3d/blob/625bbb20e6a81866322e7afa98a09a9d85d605ce/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L61)):*
> ```cpp
>             // corres_ij[i] until the following small_feature_tree.SearchKNN()
>             // call completes
>             corres_ij[i] = -1;
> ```

Recomputation may not be fully avoided. For instance, thread 1 and 2 can reach the if clause and fail simultaneously, and proceed with the search together. The result would be fine since both threads will converge to the same writing.
___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 79 at r3](https://reviewable.io/reviews/isl-org/open3d/3849#-MgHkBez-he7hzRdpy0N:-MgHkBf-3OWdvyWIvHkR:b-1ou57t) ([raw file](https://github.com/isl-org/open3d/blob/625bbb20e6a81866322e7afa98a09a9d85d605ce/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L79)):*
> ```cpp
> 
> static std::vector<std::pair<int, int>> AdvancedMatching(
>         const geometry::PointCloud& big_point_cloud,
> ```

Same, rename to src and dst and add a length check.
___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 310 at r3](https://reviewable.io/reviews/isl-org/open3d/3849#-MgHkqZ46VQVcTxeaiQg:-MgHkqZ46VQVcTxeaiQh:bbewtv6) ([raw file](https://github.com/isl-org/open3d/blob/625bbb20e6a81866322e7afa98a09a9d85d605ce/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L310)):*
> ```cpp
>     std::vector<Eigen::Vector3d> pcd_mean_vec;
>     std::tie(pcd_mean_vec, scale_global, scale_start) =
>             NormalizePointCloud(point_cloud_vec, option);
> ```

For consistency, it could be better to fully eliminate `point_cloud_vec` by refactoring NormalizePointCloud. We can do this in a future PR.
___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 326 at r3](https://reviewable.io/reviews/isl-org/open3d/3849#-MgHlW1m-8VEh-fnGUpd:-MgHlW1m-8VEh-fnGUpe:b-6qgh6s) ([raw file](https://github.com/isl-org/open3d/blob/625bbb20e6a81866322e7afa98a09a9d85d605ce/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L326)):*
> ```cpp
> 
>     Eigen::Matrix4d transformation;
>     transformation = OptimizePairwiseRegistration(point_cloud_vec, corres,
> ```

Same. For consistency, it could be better to fully eliminate `point_cloud_vec` by refactoring `OptimizePairwiseRegistration`. We can do this in a future PR.

**Review by gsakkis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3849)* status: all files reviewed, 5 unresolved discussions (waiting on @gsakkis, @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/3849#-MgBYDJDCkiVC34INth9:-MgKacLe8Yqw5dsN8uth:bebrt1w) ([raw file](https://github.com/isl-org/open3d/blob/c507370eb16520f637a783c7a449e757e73a624a/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L43)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

I would recommend using `src_features` and `dst_features`. Then add comments and a length check to ensure `src_features.size() > dst_features.size()`.
</blockquote></details>

Will do
___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 61 at r3](https://reviewable.io/reviews/isl-org/open3d/3849#-MgHjUsh2Cvwq2sjXlK9:-MgKaFgBDWXz0s8BUo0m:b-a44t1v) ([raw file](https://github.com/isl-org/open3d/blob/625bbb20e6a81866322e7afa98a09a9d85d605ce/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L61)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Recomputation may not be fully avoided. For instance, thread 1 and 2 can reach the if clause and fail simultaneously, and proceed with the search together. The result would be fine since both threads will converge to the same writing.
</blockquote></details>

Indeed there is a small race condition but as you mentioned it's ok in this case.
___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 79 at r3](https://reviewable.io/reviews/isl-org/open3d/3849#-MgHkBez-he7hzRdpy0N:-MgKalFO1p6Mnh9mrwtC:bebrt1w) ([raw file](https://github.com/isl-org/open3d/blob/625bbb20e6a81866322e7afa98a09a9d85d605ce/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L79)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Same, rename to src and dst and add a length check.
</blockquote></details>

Will do
___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 310 at r3](https://reviewable.io/reviews/isl-org/open3d/3849#-MgHkqZ46VQVcTxeaiQg:-MgKao2ZBgp6mrv6zO5x:b-97bwhm) ([raw file](https://github.com/isl-org/open3d/blob/625bbb20e6a81866322e7afa98a09a9d85d605ce/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L310)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

For consistency, it could be better to fully eliminate `point_cloud_vec` by refactoring NormalizePointCloud. We can do this in a future PR.
</blockquote></details>

Agreed, will leave it as is for now.
___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 326 at r3](https://reviewable.io/reviews/isl-org/open3d/3849#-MgHlW1m-8VEh-fnGUpd:-MgKas5l7Iakg-LdzxAo:b-97bwhm) ([raw file](https://github.com/isl-org/open3d/blob/625bbb20e6a81866322e7afa98a09a9d85d605ce/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L326)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Same. For consistency, it could be better to fully eliminate `point_cloud_vec` by refactoring `OptimizePairwiseRegistration`. We can do this in a future PR.
</blockquote></details>

Agreed, will leave it as is for now.

**Review by gsakkis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3849)* status: all files reviewed, 5 unresolved discussions (waiting on @gsakkis, @ssheorey, @theNded, and @yxlao)

___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/3849#-MgBYDJDCkiVC34INth9:-MgKcZksBQOY6xWdsGjU:byp03xr) ([raw file](https://github.com/isl-org/open3d/blob/c507370eb16520f637a783c7a449e757e73a624a/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L43)):*
<details><summary><i>Previously, gsakkis (George Sakkis) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Actually the `src_features.size() > dst_features.size()` check is not strictly necessary; it's just an optimization to iterate over the smaller matrix but the result should be the same regardless.

**Review by theNded — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3849)* status: all files reviewed, 4 unresolved discussions (waiting on @gsakkis, @ssheorey, @theNded, and @yxlao)

**Comment by theNded** [comment]
This PR has introduced bugs #4481 and #4522, identified by differentiating commits. Investigating.

**Pull request merged**
