### PR TITLE
Helper functions for checking shape, dtype, device

### PR DESCRIPTION
**Pull request by yxlao**
### Before
```cpp
Tensor::AssertShape()
Tensor::AssertDevice()
Tensor::AssertDtype()
```

### After
The new implementation gives more contexts (file, line, function) when the assertion fails:
```cpp
core::AssertTensorDtype(tensor, core::Float32);
core::AssertTensorDevice(tensor, core::Device("CUDA:0"));
core::AssertTensorShape(tensor, {100, 3});
core::AssertTensorShape(tensor, {utility::nullopt, 3});
```

### Why no more message?
Now `AssertTensor*` doesn't take an optional "message" argument. `AssertTensor*` already gives sufficient context (file, line, function).

The technical issue is that the following "optional argument" macro code works on ubuntu/macos, but it does not work for MSVC. I'll leave it as future work to improve on this. 
```cpp
#define OPEN3D_GET_ARG_4(s1, s2, s3, s4, ...) s4
#define AssertTensorDtype(...)                                                \
    OPEN3D_GET_ARG_4(__VA_ARGS__, _AssertTensorDtype3, _AssertTensorDtype2, ) \
    (__VA_ARGS__)
#define _AssertTensorDtype2(tensor, dtype)                                    \
    tensor_check::_AssertTensorDtype(__FILE__, __LINE__, (const char*)__FN__, \
                                     tensor, dtype)
#define _AssertTensorDtype3(tensor, dtype, message)                           \
    tensor_check::_AssertTensorDtype(__FILE__, __LINE__, (const char*)__FN__, \
                                     tensor, dtype, message)
```

### Scope
This PR only adds the new helper functions. It does not replace the actual invocations (will be done in a separate PR). 

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3953)

### CODE REVIEW

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3953)* status: all files reviewed, 9 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/Macro.h, line 60 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYiBlc5HUQrCBmLhAC:-MhYiBlc5HUQrCBmLhAD:b2rni49) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/Macro.h#L60)):*
> ```objc
> // Ref: https://stackoverflow.com/a/4384825
> #ifdef _WIN32
> #define __FN__ __FUNCSIG__
> ```

`__FN__` is a quite short name. Furthermore it uses double underscores which is reserved by the C++ standard and should not be used. What about calling the macro`OPEN3D_FUNCTION` or`OPEN3D_FUNC`?
___
*[cpp/open3d/core/TensorCheck.h, line 29 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYm0zY6xNj1aeofowg:-MhYm0zY6xNj1aeofowh:be1687a) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L29)):*
> ```objc
> #pragma once
> 
> #include <string>
> ```

I think we can move this to the `.cpp` file.
___
*[cpp/open3d/core/TensorCheck.h, line 32 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYmW0zCQmfDPHFl6hK:-MhYmW0zCQmfDPHFl6hL:b-vcar6k) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L32)):*
> ```objc
> 
> #include "open3d/Macro.h"
> #include "open3d/core/Device.h"
> ```

Could be replaced by forward declarations. Keep it as is if this better fits the current style in Open3D.
___
*[cpp/open3d/core/TensorCheck.h, line 42 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYjp0HDnrWkTTT0lOs:-MhYjp0HDnrWkTTT0lOt:b-pl5dtu) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L42)):*
> ```objc
> /// Example: check that the tensor has dtype Float32
> /// core::AssertTensorDtype(tensor, core::Float32);
> #define AssertTensorDtype(tensor, dtype)                                      \
> ```

It is probably highly unlikely, but what if I pass `core::Dtype(core::Dtype::DtypeCode::Float,  4, "Float32")` instead of `core::Float32`? Should we technically forbid using such custom `Dtype` instances in general? Or should we allow them by using `...` and `__VA_ARGS__` instead of `device` in the macro (since there might be commas in the expression)?
___
*[cpp/open3d/core/TensorCheck.h, line 52 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYkrTsB3EAdAD-B_hi:-MhYkrTsB3EAdAD-B_hj:b-nqskbz) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L52)):*
> ```objc
> /// Example: check that the tensor has device CUDA:0
> /// core::AssertTensorDevice(tensor, core::Device("CUDA:0"));
> #define AssertTensorDevice(tensor, device)                                     \
> ```

Same question here, but this time more likely to happen.
___
*[cpp/open3d/core/TensorCheck.h, line 75 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYlI8H6XhGn0MwR82J:-MhYlI8H6XhGn0MwR82K:b-jiq48b) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L75)):*
> ```objc
> namespace tensor_check {
> 
> void _AssertTensorDtype(const char* file,
> ```

Just a hint: Names with leading underscores are technically reserved by the C++ standard. We also have this in other places, so this could be addressed separately.
___
*[cpp/open3d/core/TensorCheck.cpp, line 47 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYmrgd6R2ytAYKBC6k:-MhYmrgd6R2ytAYKBC6l:bj83mi9) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.cpp#L47)):*
> ```cpp
>     }
>     std::string error_message =
>             fmt::format("Tensor has dtype {}, but is expected to be {}.",
> ```

`to be` -> `to have`
___
*[cpp/open3d/core/TensorCheck.cpp, line 61 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYmwyV3v_Aw1g96bH5:-MhYmwyV3v_Aw1g96bH6:brhumzt) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.cpp#L61)):*
> ```cpp
>     }
>     std::string error_message =
>             fmt::format("Tensor has device {}, but is expected to be {}.",
> ```

Same here.
___
*[cpp/open3d/core/TensorCheck.cpp, line 86 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYmyZr8bESp2uXy5l5:-MhYmyZr8bESp2uXy5l6:brhumzt) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.cpp#L86)):*
> ```cpp
>         }
>         std::string error_message = fmt::format(
>                 "Tensor has shape {}, but is expected to be {}.",
> ```

Same here.

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3953)* status: 8 of 16 files reviewed, 9 unresolved discussions (waiting on @stotko)

___
*[cpp/open3d/Macro.h, line 60 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYiBlc5HUQrCBmLhAC:-MhZJoRa5nkgLbTsw1VS:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/Macro.h#L60)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`__FN__` is a quite short name. Furthermore it uses double underscores which is reserved by the C++ standard and should not be used. What about calling the macro`OPEN3D_FUNCTION` or`OPEN3D_FUNC`?
</blockquote></details>

Done.
___
*[cpp/open3d/core/TensorCheck.h, line 29 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYm0zY6xNj1aeofowg:-MhZJpCS2-Rf8jv5Oiq5:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L29)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

I think we can move this to the `.cpp` file.
</blockquote></details>

Done.
___
*[cpp/open3d/core/TensorCheck.h, line 32 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYmW0zCQmfDPHFl6hK:-MhZJp_i5TGUu2qCKbul:b-5ymdmc) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L32)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Could be replaced by forward declarations. Keep it as is if this better fits the current style in Open3D.
</blockquote></details>

Yes. We typically just include headers, following https://google.github.io/styleguide/cppguide.html#Forward_Declarations 
___
*[cpp/open3d/core/TensorCheck.h, line 42 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYjp0HDnrWkTTT0lOs:-MhasbdR0a3AwG1TKodi:b-kmsfg9) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L42)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

It is probably highly unlikely, but what if I pass `core::Dtype(core::Dtype::DtypeCode::Float,  4, "Float32")` instead of `core::Float32`? Should we technically forbid using such custom `Dtype` instances in general? Or should we allow them by using `...` and `__VA_ARGS__` instead of `device` in the macro (since there might be commas in the expression)?
</blockquote></details>

That should already work in this case: since the `,` is inside `()`, the whole `core::Dtype(core::Dtype::DtypeCode::Float, 4, "Float32")` will be considered as one argument in the macro. 

Changes:
- Added unit tests for the case mentioned.
- Marked constructors (for one or more arguments) for `Dtype` and `Device` explicit. This does not affect the `TensorCheck` macros but it shall prevent some accidental conversions. 
___
*[cpp/open3d/core/TensorCheck.h, line 52 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYkrTsB3EAdAD-B_hi:-MhavGFE2y9abCgY8m0x:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L52)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Same question here, but this time more likely to happen.
</blockquote></details>

Done.
___
*[cpp/open3d/core/TensorCheck.h, line 75 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYlI8H6XhGn0MwR82J:-MhavZAa55MhdwJaxYPw:bf6wi) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L75)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Just a hint: Names with leading underscores are technically reserved by the C++ standard. We also have this in other places, so this could be addressed separately.
</blockquote></details>

Done. Renamed `_x` to `x_`. (We cannot use `x` since `x` is the name of the macro.)
Also updated `Logging.h`.
___
*[cpp/open3d/core/TensorCheck.cpp, line 47 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYmrgd6R2ytAYKBC6k:-Mhaw25w6BC4o8Jt-zaP:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.cpp#L47)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`to be` -> `to have`
</blockquote></details>

Done.
___
*[cpp/open3d/core/TensorCheck.cpp, line 61 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYmwyV3v_Aw1g96bH5:-Mhaw2mX8p85DzlBUqO8:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.cpp#L61)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[cpp/open3d/core/TensorCheck.cpp, line 86 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYmyZr8bESp2uXy5l5:-Mhaw3OF7N8v9G49K6mT:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.cpp#L86)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Review by stotko — COMMENTED** [review]
> Reviewed 5 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3953)* status: all files reviewed, 2 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/TensorCheck.h, line 42 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYjp0HDnrWkTTT0lOs:-MhmvuLg2sY2qup_-PPi:bx4e8oi) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L42)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

That should already work in this case: since the `,` is inside `()`, the whole `core::Dtype(core::Dtype::DtypeCode::Float, 4, "Float32")` will be considered as one argument in the macro. 

Changes:
- Added unit tests for the case mentioned.
- Marked constructors (for one or more arguments) for `Dtype` and `Device` explicit. This does not affect the `TensorCheck` macros but it shall prevent some accidental conversions. 
</blockquote></details>

Thanks. The example I mentioned should be fine, but what about the C++11 version of it that makes use of braces: `core::Dtype{core::Dtype::DtypeCode::Float, 4, "Float32"}`?
___
*[cpp/tests/core/TensorCheck.cpp, line 59 at r3](https://reviewable.io/reviews/isl-org/open3d/3953#-MhmwRYPAk5K3UtRd5cd:-MhmwRYPAk5K3UtRd5ce:b-7u5f5l) ([raw file](https://github.com/isl-org/open3d/blob/09117fbc680df894965961bf4fc667ab9b56400f/cpp/tests/core/TensorCheck.cpp#L59)):*
> ```cpp
>     }
> 
>     // More tests for macro exstension.
> ```

`macro exstension` -> `macro expansion`

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3953)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @stotko)

___
*[cpp/open3d/core/TensorCheck.h, line 42 at r1](https://reviewable.io/reviews/isl-org/open3d/3953#-MhYjp0HDnrWkTTT0lOs:-MiAtF6a1whszE18f29D:b-xv98fe) ([raw file](https://github.com/isl-org/open3d/blob/f3986c5ccf326dae69d557641541daef5724e2e4/cpp/open3d/core/TensorCheck.h#L42)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Thanks. The example I mentioned should be fine, but what about the C++11 version of it that makes use of braces: `core::Dtype{core::Dtype::DtypeCode::Float, 4, "Float32"}`?
</blockquote></details>

You're right. Switched to `__VA_ARGS__` for all checks.
___
*[cpp/tests/core/TensorCheck.cpp, line 59 at r3](https://reviewable.io/reviews/isl-org/open3d/3953#-MhmwRYPAk5K3UtRd5cd:-MiAtLfH6pGeewRYojdI:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/09117fbc680df894965961bf4fc667ab9b56400f/cpp/tests/core/TensorCheck.cpp#L59)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`macro exstension` -> `macro expansion`
</blockquote></details>

Done.

**Review by stotko — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3953)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yxlao)

**Pull request merged**
