### PR TITLE
refactor unit test for FixedRadiusIndex

### PR DESCRIPTION
**Pull request by junha-l**
- Refactor unit test for FixedRadiusIndex
- Resolve unit test failure on CUDA 11.0 #3856

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895)

### CODE REVIEW

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @junha-l)

___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 134 at r1](https://reviewable.io/reviews/isl-org/open3d/3895#-Mgl9mvM2Wz7t-VzwiPA:-Mgl9mvM2Wz7t-VzwiPB:b-8sh4lu) ([raw file](https://github.com/isl-org/open3d/blob/87d5f1efd83e24bfe48551d91ed9f8c41a175924/cpp/tests/core/FixedRadiusIndex.cpp#L134)):*
> ```cpp
>         std::sort(indices_vector.begin() + gt_neighbors_row_splits[i],
>                   indices_vector.begin() + gt_neighbors_row_splits[i + 1]);
>         std::sort(distances_vector.begin() + gt_neighbors_row_splits[i],
> ```

The association of indices with distances is lost if both vectors are sorted separately.
We need to keep the association to know if the implementation is correct.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @benjaminum)

___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 134 at r1](https://reviewable.io/reviews/isl-org/open3d/3895#-Mgl9mvM2Wz7t-VzwiPA:-MglM34UABHlxDBHqekP:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/87d5f1efd83e24bfe48551d91ed9f8c41a175924/cpp/tests/core/FixedRadiusIndex.cpp#L134)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

The association of indices with distances is lost if both vectors are sorted separately.
We need to keep the association to know if the implementation is correct.
</blockquote></details>

Done.

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @junha-l)

___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 134 at r1](https://reviewable.io/reviews/isl-org/open3d/3895#-Mgl9mvM2Wz7t-VzwiPA:-MglQSDBDJmcAUgtlqTp:btxq2k8) ([raw file](https://github.com/isl-org/open3d/blob/87d5f1efd83e24bfe48551d91ed9f8c41a175924/cpp/tests/core/FixedRadiusIndex.cpp#L134)):*
<details><summary><i>Previously, junha-l (Junha Lee) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think the `perm_i` should be sorted with respect to the indices because the indices are unique keys.
Are the GT vectors already sorted?
___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 159 at r2](https://reviewable.io/reviews/isl-org/open3d/3895#-MglQx_6AdfQvWUOe4fm:-MglQx_6AdfQvWUOe4fn:bchqjma) ([raw file](https://github.com/isl-org/open3d/blob/942c9b80422584d70d30c7d581637ead2a27a0f6/cpp/tests/core/FixedRadiusIndex.cpp#L159)):*
> ```cpp
>     ExpectEQ(indices_sorted, gt_indices);
>     ExpectEQ(distances_sorted, gt_distances);
>     ExpectEQ(neighbor_row_splits.ToFlatVector<int64_t>(),
> ```

We can move this up before we do the sorting and change it to `AssertEQ`. If the row_splits do not match we cannot finish the other checks.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @benjaminum)

___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 134 at r1](https://reviewable.io/reviews/isl-org/open3d/3895#-Mgl9mvM2Wz7t-VzwiPA:-Mgn9i0P2jlcW7FVARwS:b-es5u1q) ([raw file](https://github.com/isl-org/open3d/blob/87d5f1efd83e24bfe48551d91ed9f8c41a175924/cpp/tests/core/FixedRadiusIndex.cpp#L134)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

I think the `perm_i` should be sorted with respect to the indices because the indices are unique keys.
Are the GT vectors already sorted?
</blockquote></details>

```gt_indices``` and ```gt_distances``` are sorted results, so we sort the predicted unsorted indices and distances here. 

I found that ```std::sort``` use ```quick sort``` internally, which is unstable sort and FixedRadiusIndex use stable ```merge sort``` so there is a probability that the results can be different after sorting. 
I'll update to sort by indices
___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 159 at r2](https://reviewable.io/reviews/isl-org/open3d/3895#-MglQx_6AdfQvWUOe4fm:-Mgn9gvs9m1y6BRo_upd:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/942c9b80422584d70d30c7d581637ead2a27a0f6/cpp/tests/core/FixedRadiusIndex.cpp#L159)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

We can move this up before we do the sorting and change it to `AssertEQ`. If the row_splits do not match we cannot finish the other checks.
</blockquote></details>

Done.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @benjaminum)

___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 134 at r1](https://reviewable.io/reviews/isl-org/open3d/3895#-Mgl9mvM2Wz7t-VzwiPA:-MgnLecu7mckAT-jbRFC:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/87d5f1efd83e24bfe48551d91ed9f8c41a175924/cpp/tests/core/FixedRadiusIndex.cpp#L134)):*
<details><summary><i>Previously, junha-l (Junha Lee) wrote…</i></summary><blockquote>

```gt_indices``` and ```gt_distances``` are sorted results, so we sort the predicted unsorted indices and distances here. 

I found that ```std::sort``` use ```quick sort``` internally, which is unstable sort and FixedRadiusIndex use stable ```merge sort``` so there is a probability that the results can be different after sorting. 
I'll update to sort by indices
</blockquote></details>

Done.

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @benjaminum and @junha-l)

___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 184 at r3](https://reviewable.io/reviews/isl-org/open3d/3895#-MgpGxTcBBNgzlbli-Ig:-MgpGxTcBBNgzlbli-Ih:b-4nhnry) ([raw file](https://github.com/isl-org/open3d/blob/9ead364bd5e2291ca0607d910c26ccaceb0ff616/cpp/tests/core/FixedRadiusIndex.cpp#L184)):*
> ```cpp
> 
>         // Sort gt indices and distances
>         std::vector<size_t> gt_p_i = FindPermutation<int32_t>(
> ```

Why do we sort the gt vectors here? Aren't they already sorted? 
Suggestion:
If you want to keep the sort because it makes it easier to update the unit test in the future, we should rename the vectors `gt_x_sorted` simply to `gt_x` and the `gt_x_unsorted` to `gt_x_sorted`.

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @benjaminum)

___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 184 at r3](https://reviewable.io/reviews/isl-org/open3d/3895#-MgpGxTcBBNgzlbli-Ig:-Mgpu5lf-RdXWdCtHCnW:btqcskm) ([raw file](https://github.com/isl-org/open3d/blob/9ead364bd5e2291ca0607d910c26ccaceb0ff616/cpp/tests/core/FixedRadiusIndex.cpp#L184)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Why do we sort the gt vectors here? Aren't they already sorted? 
Suggestion:
If you want to keep the sort because it makes it easier to update the unit test in the future, we should rename the vectors `gt_x_sorted` simply to `gt_x` and the `gt_x_unsorted` to `gt_x_sorted`.
</blockquote></details>

Yes the naming for the variables are somewhat misleading.

For clarity,  ```gt_x_sorted``` is the ground-truth values to be compared with the results of fixed radius search with search=True flag.
The reason I sort the gt vectors is that we sort the predicted indices and distances by the indices rather than distances.

**Review by benjaminum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3895#-:-MgqDdOK9uVYxbKR9BrQ:bnfp4nl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @benjaminum and @junha-l)

___
*[cpp/tests/core/FixedRadiusIndex.cpp, line 184 at r3](https://reviewable.io/reviews/isl-org/open3d/3895#-MgpGxTcBBNgzlbli-Ig:-MgqCxyC3X4sKaZ0yk-E:btyfoeo) ([raw file](https://github.com/isl-org/open3d/blob/9ead364bd5e2291ca0607d910c26ccaceb0ff616/cpp/tests/core/FixedRadiusIndex.cpp#L184)):*
<details><summary><i>Previously, junha-l (Junha Lee) wrote…</i></summary><blockquote>

Yes the naming for the variables are somewhat misleading.

For clarity,  ```gt_x_sorted``` is the ground-truth values to be compared with the results of fixed radius search with search=True flag.
The reason I sort the gt vectors is that we sort the predicted indices and distances by the indices rather than distances. 

</blockquote></details>

I see. `sorted` referred to the sort option.

**Pull request merged**
