### PR TITLE
Add BUILD_DEBIAN_PACKAGE option for Debian package support

### PR DESCRIPTION
**Pull request by meetgandhi-dev**
Introduced the `BUILD_DEBIAN_PACKAGE` CMake option to enable building a Debian package for the library. When this option is enabled and the host system supports Debian, the library will be packaged accordingly.

Usage:
To enable debian package building:
`cmake -DBUILD_DEBIAN_PACKAGE=ON <other_config_options> ..

To build debian package:
`make package`
or
`cpack`

## Type

-   [ ] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [x] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

This feature simplifies installation by allowing users to generate a Debian package directly through CMake, adhering to standard packaging conventions and enabling seamless integration with package management tools like apt. By streamlining the development workflow, we empower developers to focus on feature enhancement while encouraging community contributions and customisation. Overall, this initiative broadens our library's reach and strengthens its position within the open-source ecosystem, making it more user-friendly and accessible.

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

#### $ cmake -DBUILD_DEBIAN_PACKAGE=ON ..
[configure.log](https://github.com/user-attachments/files/17101394/configure.log)

#### cpack
```
$ cpack
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: Open3D
CPack: - Install project: Open3D []
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /home/meet/Open3D/build/package/open3d_0.18.0_amd64.deb generated.
```

#### Install manifests:
[install_manifest.txt](https://github.com/user-attachments/files/17101431/install_manifest.txt)

### CODE REVIEW

**Comment by ssheorey** [comment]
Hi @meetgandhi-dev This is a really useful PR. Can you add this to the CI, so we can test the resulting deb package?

Screenshot 2024-09-27 at 6 03 06 PM

You can add to the CI here. Essentially, just copy the steps we do for `make package (tar.xz)` (copying out of the docker container and uploading to github later, etc.). Let me know if you need help with this and I can help as well.

**Comment by meetgandhi-dev** [comment]
Hello @ssheorey 
I have made the required changes as per my understanding. Let me know your feedback!

**Comment by ssheorey** [comment]
Hi @meetgandhi-dev can you check the CI? The deb package was not created (The CI runs on Ubuntu 20.04).

https://github.com/isl-org/Open3D/actions/runs/11086074701/job/30938149427?pr=6982#step:4:13576

**Comment by meetgandhi-dev** [comment]
Hello @ssheorey ,
I’ve attempted to resolve the issue. Could you please check again with the latest version?

**Comment by ssheorey** [comment]
HI @meetgandhi-dev thanks for the update. I can now locally build the deb package and install it. One issue with the deb package is `libtbb.so`. Currently, we only package .tar.gz binary archives that are "all inclusive" and are locally installed. deb packages must however work with the OS, i.e. not conflict with other packages in the system. Currently, open3d will install libtbb.so, which conflicts with the system package libtbb. We need to make this change:
- Do not install libtbb for the deb package. It should still be included in the tar.xz package as before.
- Add a dependence for open3d on libtbb12, so that `apt` will install it for us.

**Comment by meetgandhi-dev** [comment]
@ssheorey Thanks for the heads up! When we disable the `tbb` build by setting `-DUSE_SYSTEM_TBB=ON`, it isn't being installed. Should we skip the installation even if `USE_SYSTEM_TBB` is set to `OFF` and `TBB_BUILD` is set to `ON`?

**Comment by meetgandhi-dev** [comment]
@ssheorey any updates?

**Comment by meetgandhi-dev** [comment]
> @ssheorey Thanks for the heads up! When we disable the `tbb` build by setting `-DUSE_SYSTEM_TBB=ON`, it isn't being installed. Should we skip the installation even if `USE_SYSTEM_TBB` is set to `OFF` and `TBB_BUILD` is set to `ON`?

@ssheorey any updates here?

**Comment by ssheorey** [comment]
Yes, we should not install it in any case. Also, add it as a Debian package dependency, so that apt installs it from the Ubuntu repos.

**Comment by meetgandhi-dev** [comment]
@ssheorey 
Thanks for the confirmation! I'm currently working on it. CMake can generate the dependencies on its own, and it's working on my machine, but not inside the Docker container. I'm investigating the issue and will update the PR with the requested changes soon.

**Comment by meetgandhi-dev** [comment]
@ssheorey It looks like this PR was closed while resolving the conflicts. I will reopen it once the issue is fixed.

**Comment by ruffsl** [comment]
@meetgandhi-dev , looks like your force push nullified the diff for the PR. I was curious what your change set here was.
Have any time to resolve your merge conflicts and/or adjust the cmake to link  against the system installed `libtbb12`?

**Comment by meetgandhi-dev** [comment]
Hey @ruffsl 
Lost my previous changes :(
[This commit](https://github.com/isl-org/Open3D/compare/main...meetgandhi-dev:Open3D:feature/build-deb-pkg) includes the logic for generating the Debian packages. I was unable to find a way to explicitly remove `libtbb` from the package. Instead, I'm exploring CMake's component-based packaging to resolve this, so `libtbb` can be packaged as a separate component.

**Comment by meetgandhi-dev** [comment]
@ruffsl / @ssheorey 
Created #7178 to address this. I have a few doubts, so let's continue the discussion there.

**Pull request closed without merging**
