### PR TITLE
Add function to create Mitsuba mesh from an Open3D mesh

### PR DESCRIPTION
**Pull request by errissa**
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5688)

### CODE REVIEW

**Review by benjaminum — COMMENTED** [review]
Added some comments

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5688#-:-NGv_C_f1W93F1t8Zfr-:bkla33v)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @errissa)

___
*[`examples/python/visualization/to_mitsuba.py` line 39 at r1](https://reviewable.io/reviews/isl-org/open3d/5688#-NGvXG9bAyt0JxPd40M5:-NGvXG9bAyt0JxPd40M6:b-gr2pch) ([raw file](https://github.com/isl-org/open3d/blob/f2eedbfc3be6f31e7325b139125a01c3f8581313/examples/python/visualization/to_mitsuba.py#L39)):*
> ```Python
>         "light": {
>             "type": "envmap",
>             "filename": "/home/renes/Downloads/solitude_interior_1k.exr",
> ```

We probably need to add an hdri to the datasets or is there a way we can get one of the backgrounds from the viewer?
___
*[`examples/python/visualization/to_mitsuba.py` line 74 at r1](https://reviewable.io/reviews/isl-org/open3d/5688#-NGvXlEV8mpo81No_wTf:-NGvXlEV8mpo81No_wTg:b8cjcn2) ([raw file](https://github.com/isl-org/open3d/blob/f2eedbfc3be6f31e7325b139125a01c3f8581313/examples/python/visualization/to_mitsuba.py#L74)):*
> ```Python
> # Load mesh using Open3D
> dataset = o3d.data.MonkeyModel()
> # NOTE: Once PR 5632 is merged we can use t IO directly here
> ```

switch to t.io
___
*[`python/open3d/visualization/to_mitsuba.py` line 30 at r1](https://reviewable.io/reviews/isl-org/open3d/5688#-NGvXCG-9q3UqnnCOr7d:-NGvXCG-9q3UqnnCOr7e:brzurrc) ([raw file](https://github.com/isl-org/open3d/blob/f2eedbfc3be6f31e7325b139125a01c3f8581313/python/open3d/visualization/to_mitsuba.py#L30)):*
> ```Python
> 
> 
> def to_mitsuba(name, o3d_mesh, bsdf=None):
> ```

Please add a docstring.

I contemplating about the fn name because there could be more objects that can be converted to Mitsuba,
```
mi_mesh = o3d.visualization.to_mitsuba(o3d_mesh)
mi_bsdf = o3d.visualization.to_mitsuba(o3d.mesh.material)
mi_sensor = o3d.visualization.to_mitsuba(o3d_cam)

# Maybe it makes sense to patch the python classes that can be converted.
mi_mesh = o3d_mesh.to_mitsuba()
mi_bsdf = o3d_mesh.material.to_mitsuba()
mi_sensor = o3d_cam.to_mitsuba()
```

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5688)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @benjaminum)

___
*[`examples/python/visualization/to_mitsuba.py` line 39 at r1](https://reviewable.io/reviews/isl-org/open3d/5688#-NGvXG9bAyt0JxPd40M5:-NH9xOVd8KipeyBUnxuq:bv5k52d) ([raw file](https://github.com/isl-org/open3d/blob/f2eedbfc3be6f31e7325b139125a01c3f8581313/examples/python/visualization/to_mitsuba.py#L39)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

We probably need to add an hdri to the datasets or is there a way we can get one of the backgrounds from the viewer?
</blockquote></details>

Agreed we need a selection of hdris in the dataset, however that will take a separate PR. For now, I updated the example to use a constant emitter and we can switch the example to use an envmap once HDRI dataset is available
___
*[`examples/python/visualization/to_mitsuba.py` line 74 at r1](https://reviewable.io/reviews/isl-org/open3d/5688#-NGvXlEV8mpo81No_wTf:-NH9y0L6CCEkbbgCWMgd:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f2eedbfc3be6f31e7325b139125a01c3f8581313/examples/python/visualization/to_mitsuba.py#L74)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

switch to t.io
</blockquote></details>

Done.

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5688)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @benjaminum)

___
*[`python/open3d/visualization/to_mitsuba.py` line 30 at r1](https://reviewable.io/reviews/isl-org/open3d/5688#-NGvXCG-9q3UqnnCOr7d:-NHA93mg511U38iZm9Yl:b-5h2z9x) ([raw file](https://github.com/isl-org/open3d/blob/f2eedbfc3be6f31e7325b139125a01c3f8581313/python/open3d/visualization/to_mitsuba.py#L30)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Please add a docstring.

I contemplating about the fn name because there could be more objects that can be converted to Mitsuba,
```
mi_mesh = o3d.visualization.to_mitsuba(o3d_mesh)
mi_bsdf = o3d.visualization.to_mitsuba(o3d.mesh.material)
mi_sensor = o3d.visualization.to_mitsuba(o3d_cam)

# Maybe it makes sense to patch the python classes that can be converted.
mi_mesh = o3d_mesh.to_mitsuba()
mi_bsdf = o3d_mesh.material.to_mitsuba()
mi_sensor = o3d_cam.to_mitsuba()
```


</blockquote></details>

Went with second option of making `to_mitsuba` a method of `TriangleMesh`

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5688)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @errissa)

___
*[`python/open3d/visualization/to_mitsuba.py` line 73 at r3](https://reviewable.io/reviews/isl-org/open3d/5688#-NHAOuW3BZoQiaWoyQox:-NHAOuW3BZoQiaWoyQoy:b-4yie5j) ([raw file](https://github.com/isl-org/open3d/blob/48e2e411bddbd04b6b1d7ac3618965fd85690ab9/python/open3d/visualization/to_mitsuba.py#L73)):*
> ```Python
>     user may set `bsdf` to a Mitsuba BSDF in which case the TriangleMesh's
>     material will be ignored and the user supplied BSDF will be assigned to the
>     returned Mitsuba Mesh.
> ```

The description is good! Can format it with the Google docstring style?

```
    short

    long desc
    Args:
       name (str):...
       ...
    Returns:
       ....
```

**Review by benjaminum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5688#-:-NHAqbfH0oBHiU1bTUSt:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @errissa)

___
*[`python/open3d/visualization/to_mitsuba.py` line 73 at r3](https://reviewable.io/reviews/isl-org/open3d/5688#-NHAOuW3BZoQiaWoyQox:-NHAqXMA0xV94LfGU_pM:b-qn5lbb) ([raw file](https://github.com/isl-org/open3d/blob/48e2e411bddbd04b6b1d7ac3618965fd85690ab9/python/open3d/visualization/to_mitsuba.py#L73)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

The description is good! Can format it with the Google docstring style?

```
    short

    long desc
    Args:
       name (str):...
       ...
    Returns:
       ....
```
</blockquote></details>

Perfect!

**Pull request merged**
