### PR TITLE
Embed Resources into Open3D binary

### PR DESCRIPTION
**Pull request by ShreyanshDarshan**
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4873)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4873)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @ShreyanshDarshan and @yxlao)

___
*[cpp/open3d/visualization/gui/CMakeLists.txt, line 7 at r2](https://reviewable.io/reviews/isl-org/open3d/4873#-MxmBULb-DSldMUfSGj_:-MxmBULb-DSldMUfSGja:b-dvs04f) ([raw file](https://github.com/isl-org/open3d/blob/a7fee3901b535993ea80f02d8a39d79d9b78261b/cpp/open3d/visualization/gui/CMakeLists.txt#L7)):*
> ```CMake
>         EmbedResources
>     COMMAND
>         rm -f ${PROJECT_SOURCE_DIR}/cpp/open3d/visualization/gui/Resource.cpp &&
> ```

`rm -f` doesn't work on windows. Use CMake commands. 

e.g.
```cmake
${CMAKE_COMMAND} -E copy_directory <SOURCE_DIR>/Library/lib ${STATIC_MKL_LIB_DIR}
```
___
*[cpp/tools/TestEmbedResources.sh, line 1 at r2](https://reviewable.io/reviews/isl-org/open3d/4873#-MxmC5qP6Sp19jI91rHx:-MxmC5qP6Sp19jI91rHy:b-vbm7ix) ([raw file](https://github.com/isl-org/open3d/blob/a7fee3901b535993ea80f02d8a39d79d9b78261b/cpp/tools/TestEmbedResources.sh#L1)):*
> ```Shell
> ../../build/bin/TestEmbedResources /home/darshan/Intel/Open3D/cpp/tools
> ```

Convert this into CMake custom command (or custom target)

E.g. same as `make pip-package`, `make test-embed`. Add `make test-embed` to CI. 



_Code quote (from cpp/tools/EmbedResources.cpp):_
```cpp
·········
```

**Review by ShreyanshDarshan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4873)* status: 0 of 47 files reviewed, 2 unresolved discussions (waiting on @yxlao)

___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 7 at r2](https://reviewable.io/reviews/isl-org/open3d/4873#-MxmBULb-DSldMUfSGj_:-My8AJMe1vKPEHlCvCxG:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a7fee3901b535993ea80f02d8a39d79d9b78261b/cpp/open3d/visualization/gui/CMakeLists.txt#L7)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`rm -f` doesn't work on windows. Use CMake commands. 

e.g.
```cmake
${CMAKE_COMMAND} -E copy_directory <SOURCE_DIR>/Library/lib ${STATIC_MKL_LIB_DIR}
```
</blockquote></details>

Done.
___
*[`cpp/tools/TestEmbedResources.sh` line 1 at r2](https://reviewable.io/reviews/isl-org/open3d/4873#-MxmC5qP6Sp19jI91rHx:-N1sD3_NAzy5ajxTJJxy:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/a7fee3901b535993ea80f02d8a39d79d9b78261b/cpp/tools/TestEmbedResources.sh#L1)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Convert this into CMake custom command (or custom target)

E.g. same as `make pip-package`, `make test-embed`. Add `make test-embed` to CI. 

</blockquote></details>

Done.

**Review by yxlao — CHANGES_REQUESTED** [review]
Could you provide several lines of command to show how to verify that this PR is working? E.g. the same command will fail on master but works on this branch. 

```
```

> Reviewed 2 of 24 files at r3, 10 of 39 files at r5, 3 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4873#-:-N2p4cbeDiaqXwhSAwMF:b6sbtcn)* status: 15 of 49 files reviewed, 20 unresolved discussions (waiting on @ShreyanshDarshan and @yxlao)

___
*[`.gitignore` line 18 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p4VJTD2Nqe3jWeMKX:-N2p4VJTD2Nqe3jWeMKY:b-gdfeda) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/.gitignore#L18)):*
> ```ignore
> cpp/open3d/visualization/shader/Shader.h
> util/pip_package/setup.py
> cpp/open3d/visualization/gui/CompiledResources/
> ```

We shouldn't need to ignore this. Can we move the generated source and compiled code to `build/`?
___
*[`cmake/Open3DEmbedResources.cmake` line 1 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p4rqy6b2HPIPpz8B1:-N2p4rqy6b2HPIPpz8B2:b-2gxs6h) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L1)):*
> ```CMake
> # open3d_embed_resources(<target>
> ```

Clean up.
___
*[`cmake/Open3DEmbedResources.cmake` line 27 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p4upiEnht57NLCeOl:-N2p4upiEnht57NLCeOm:bwi9z2h) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L27)):*
> ```CMake
>         message(FATAL_ERROR "No resource files specified for compilation.")
>     endif()
> # file(GLOB GUI_MATERIAL_SOURCE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/Materials/*")
> ```

clean up. 
___
*[`cmake/Open3DEmbedResources.cmake` line 53 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p4xYW-Musayk5RKIb:-N2p4xYW-Musayk5RKIc:b-pnqah3) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L53)):*
> ```CMake
> 
>     file(RELATIVE_PATH EMBEDDED_RESOURCE_RELATIVE_PATH "${CMAKE_CURRENT_BINARY_DIR}" "${EMBEDDED_RESOURCE_FULL_PATH}")
>     
> ```

clean up spaces. Notice there are red dots. It's best to configure the editor to trim trailing white spaces automatically. 
___
*[`cmake/Open3DEmbedResources.cmake` line 57 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p54f97CEtRDmuvFPe:-N2p54f97CEtRDmuvFPf:b-w6fqp2) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L57)):*
> ```CMake
>         OUTPUT 
>             ${EMBEDDED_RESOURCE_FULL_PATH}
>         COMMAND 
> ```

Clean up. Notice there is a red dot. It's best to configure the editor to trim trailing white spaces automatically. 
___
*[`cmake/Open3DEmbedResources.cmake` line 92 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8_L_DbfBGQz1mK0H:-N2p8_L_DbfBGQz1mK0I:b-sx4sig) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L92)):*
> ```CMake
>         ${EMBEDDED_RESOURCES}
> )
> ```

clean up lines. 
___
*[`cmake/Open3DEmbedResources.cmake` line 95 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8awx9mY9v3B3GkL6:-N2p8awx9mY9v3B3GkL7:b-g4mfoq) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L95)):*
> ```CMake
> 
> 
> # set(EMBEDDED_RESOURCES ${EMBEDDED_RESOURCES} PARENT_SCOPE)
> ```

clean up comment
___
*[`cpp/open3d/io/ImageIO.h` line 41 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8epd5QuzsM6lecMR:-N2p8epd5QuzsM6lecMS:b-gl7mbk) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/io/ImageIO.h#L41)):*
> ```objc
>         const std::string &filename);
> 
> std::shared_ptr<geometry::Image> CreateImageFromMemoryPNG(
> ```

remove this if not meant to be used by the user.
___
*[`cpp/open3d/io/ImageIO.h` line 66 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8k926r3sAoNNxNoF:-N2p8k926r3sAoNNxNoG:bdlafpn) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/io/ImageIO.h#L66)):*
> ```objc
> 
> bool ReadImageFromPNG(const std::string &filename, geometry::Image &image);
> bool ReadImageFromMemoryPNG(const std::vector<char> &image_bytes,
> ```

move this to a private function, not put in `.h`, if this is not meant to be used by the user
___
*[`cpp/open3d/io/file_format/FilePNG.cpp` line 102 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2pAiIt2aPZVhtOACsk:-N2pAiIt2aPZVhtOACsl:bwr641s) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/io/file_format/FilePNG.cpp#L102)):*
> ```cpp
>     }
> 
>     // Clear colormap flag if necessary to ensure libpng expands the colo
> ```

`colo` typo.
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 5 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9Cas813bf1q6Kw8A:-N2p9Cas813bf1q6Kw8B:b-9y3v0i) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L5)):*
> ```CMake
> file(MAKE_DIRECTORY ${GUI_RESOURCE_DIR})
> file(GLOB GUI_RESOURCE_SOURCE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/Resources/*")
> # file(MAKE_DIRECTORY ${COMPILED_RESOURCE_DIR})
> ```

clean up code comments
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 8 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2pCK1B1BYa_DY-xyiB:-N2pCK1B1BYa_DY-xyiC:b-kxdm0d) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L8)):*
> ```CMake
> # file(COPY ${GUI_RESOURCE_SOURCE_FILES}
> # DESTINATION ${GUI_RESOURCE_DIR})
> ```

clean up extra empty lines
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 12 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8zDK7LvXM1iivBMf:-N2p8zDK7LvXM1iivBMg:b-ivcrx7) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L12)):*
> ```CMake
> include(Open3DAddCompiledMaterials)
> open3d_add_compiled_materials(materials
> OUTPUT_DIRECTORY
> ```

Format with indentation. 
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 42 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9HaGDyBNxOPgW-Lj:-N2p9HaGDyBNxOPgW-Lk:bd5d6lg) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L42)):*
> ```CMake
> # Export GUI_RESOURCE_FILES to parent CMake context (cpp/open3d/)
> set(GUI_RESOURCE_FILES
> ${GUI_RESOURCE_SOURCE_FILES} ${GUI_MATERIAL_COMPILED_FILES})
> ```

indentation
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 57 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9EfS2hAZw7c4AmKg:-N2p9EfS2hAZw7c4AmKh:bh3o6fy) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L57)):*
> ```CMake
> 
> get_target_property(EMBEDDED_RESOURCE_FILES resource-embed EMBEDDED_RESOURCES)
> ```

remove empty line
___
*[`cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp` line 188 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9SpzE1TbcHh_GOkD:-N2p9SpzE1TbcHh_GOkE:bj6bovv) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp#L188)):*
> ```cpp
> }
> 
> filament::Material* LoadMaterialFromFile(std::vector<char> material_data,
> ```

- This is no longer "LoadMaterialFromFile", rename function to `LoadMaterialFromMemory`?
- `const std::vector<char>&`
___
*[`cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp` line 950 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2pACBe8Nhb7EZJ_STE:-N2pACBe8Nhb7EZJ_STF:b-9jiz2b) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp#L950)):*
> ```cpp
>     // FIXME: Move to precompiled resource blobs
> 
>     auto texture_img = io::CreateImageFromMemoryPNG(defaultTexture_png());
> ```

It is best to give a prefix to these functions, e.g. `get_buffer_defaultTexture_png()`.
___
*[`cpp/pybind/make_python_package.cmake` line 132 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9gWWBZIKNK8GFd9J:-N2p9gWWBZIKNK8GFd9K:bo1b7i2) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/pybind/make_python_package.cmake#L132)):*
> ```CMake
> 
> if (BUILD_WEBRTC)
>     file(MAKE_DIRECTORY "${PYTHON_PACKAGE_DST_DIR}/open3d/resources/")
> ```

Please verify that the WebRTC still works. http://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html#python-server 

We might still need to keep the original resources folder for WebRTC. Our WebRTC code is not designed to consume resource files from memory yet.

**Comment by yxlao** [comment]
> Could you provide several lines of command to show how to verify that this PR is working? E.g. the same command will fail on master but works on this branch.

For both C++ and Python.

**Review by ShreyanshDarshan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4873)* status: 6 of 49 files reviewed, 20 unresolved discussions (waiting on @errissa and @yxlao)

___
*[`.gitignore` line 18 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p4VJTD2Nqe3jWeMKX:-N2pmZIe8TcUJCodmxzz:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/.gitignore#L18)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We shouldn't need to ignore this. Can we move the generated source and compiled code to `build/`?
</blockquote></details>

Done.
___
*[`cmake/Open3DEmbedResources.cmake` line 1 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p4rqy6b2HPIPpz8B1:-N2pcvEE8rSA6WFrB-vf:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L1)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Clean up.
</blockquote></details>

Done.
___
*[`cmake/Open3DEmbedResources.cmake` line 27 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p4upiEnht57NLCeOl:-N2pcvoR43AjRUqmROkd:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L27)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

clean up. 
</blockquote></details>

Done.
___
*[`cmake/Open3DEmbedResources.cmake` line 53 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p4xYW-Musayk5RKIb:-N2pcwK23c6Cjkkx1Sp1:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L53)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

clean up spaces. Notice there are red dots. It's best to configure the editor to trim trailing white spaces automatically. 
</blockquote></details>

Done.
___
*[`cmake/Open3DEmbedResources.cmake` line 57 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p54f97CEtRDmuvFPe:-N2pcxXj3lfkiTbZuW9r:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L57)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Clean up. Notice there is a red dot. It's best to configure the editor to trim trailing white spaces automatically. 
</blockquote></details>

Done.
___
*[`cmake/Open3DEmbedResources.cmake` line 92 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8_L_DbfBGQz1mK0H:-N2pdZxvAXrI6J5BSfn5:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L92)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

clean up lines. 
</blockquote></details>

Done.
___
*[`cmake/Open3DEmbedResources.cmake` line 95 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8awx9mY9v3B3GkL6:-N2pd_OBCQYHmGLU2TqP:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cmake/Open3DEmbedResources.cmake#L95)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

clean up comment
</blockquote></details>

Done.
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 5 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9Cas813bf1q6Kw8A:-N2psrKS5MWGVFXpL51A:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L5)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

clean up code comments
</blockquote></details>

Done.
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 8 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2pCK1B1BYa_DY-xyiB:-N2pstP877syyXzzLx3u:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L8)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

clean up extra empty lines
</blockquote></details>

Done.
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 12 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8zDK7LvXM1iivBMf:-N2pgzVn2Y9K4nzmEsE_:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L12)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Format with indentation. 
</blockquote></details>

Done.
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 42 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9HaGDyBNxOPgW-Lj:-N2phSYJ9IGkGiaxP3lq:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L42)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

indentation
</blockquote></details>

Done.
___
*[`cpp/open3d/visualization/gui/CMakeLists.txt` line 57 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9EfS2hAZw7c4AmKg:-N2phSvbDyvVf_q5Uaoj:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/gui/CMakeLists.txt#L57)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.
___
*[`cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp` line 188 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9SpzE1TbcHh_GOkD:-N2pi5Eb-lT9NwLvfyAX:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp#L188)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

- This is no longer "LoadMaterialFromFile", rename function to `LoadMaterialFromMemory`?
- `const std::vector<char>&`

</blockquote></details>

Done.
___
*[`cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp` line 950 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2pACBe8Nhb7EZJ_STE:-N2pmDLi-iwOAUUFgwAZ:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/visualization/rendering/filament/FilamentResourceManager.cpp#L950)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

It is best to give a prefix to these functions, e.g. `get_buffer_defaultTexture_png()`.
</blockquote></details>

Done.
___
*[`cpp/pybind/make_python_package.cmake` line 132 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p9gWWBZIKNK8GFd9J:-N2sL0jvE1Df4IeNDwmG:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/pybind/make_python_package.cmake#L132)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Please verify that the WebRTC still works. http://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html#python-server 

We might still need to keep the original resources folder for WebRTC. Our WebRTC code is not designed to consume resource files from memory yet. 
</blockquote></details>

Done.
___
*[`cpp/open3d/io/ImageIO.h` line 41 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8epd5QuzsM6lecMR:-N2pslIPBAeSgXBqXMUE:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/io/ImageIO.h#L41)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove this if not meant to be used by the user.
</blockquote></details>

Done.
___
*[`cpp/open3d/io/ImageIO.h` line 66 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2p8k926r3sAoNNxNoF:-N2psm7y6dptfsOc3On4:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/io/ImageIO.h#L66)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

move this to a private function, not put in `.h`, if this is not meant to be used by the user
</blockquote></details>

Done.
___
*[`cpp/open3d/io/file_format/FilePNG.cpp` line 102 at r6](https://reviewable.io/reviews/isl-org/open3d/4873#-N2pAiIt2aPZVhtOACsk:-N2pspHh4UofRRnSo0ml:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d527c7cd35e4c571e35d584827eb8096ce035f10/cpp/open3d/io/file_format/FilePNG.cpp#L102)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`colo` typo.
</blockquote></details>

Done.

**Comment by ShreyanshDarshan** [comment]
> Could you provide several lines of command to show how to verify that this PR is working? E.g. the same command will fail on master but works on this branch.

These examples will work from any working directory after this PR:

- Draw
- OfflineSLAM

i.e.

```bash
cd build

./bin/examples/Draw             # Works even though the cwd is not Open3D/build/bin/examples

# or

./bin/examples/OfflineSLAM      # Works even though the cwd is not Open3D/build/bin/examples
```

In other words, open3d::visualization::Draw can be used in any c++ program now without path specification.

C++ examples that may now be updated to use the new visualizer:
- CameraPoseTrajectory
- DepthCapture
- Flann
- GeneralisedICP
- ISSKeypoints
- LineSet
- Octree
- PCDFileFormat
- PointCloud
- RegistrationColoredICP
- RegistrationFGR
- RegistrationRANSAC
- RGBDOdometry
- TIntegrateRGBD
- TOdometryRGBD
- TriangleMesh
- ViewDIstances
- ViewPCDMatch
- VIsualizer
- Voxelization

**Comment by ssheorey** [comment]
Hi @yxlao can you approve or close this PR?

**Comment by ssheorey** [comment]
Closing this PR due to lack of progress. @ShreyanshDarshan @yxlao please reopen when this is ready.

**Pull request closed without merging**
