### PR TITLE
Switched QHull ImGUI and GoogleTest to use FetchContent

### LINKED ISSUE #6644: CMake with Ninja generator delets some 3rdparty source files
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Ubuntu 22.04) with:
```
mkdir cmake-build-debug
cmake -S . -B cmake-build-debug -G Ninja -DCMAKE_BUILD_TYPE=Debug -DGLIBCXX_USE_CXX11_ABI=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_UNIT_TESTS=OFF -DBUILD_GUI=OFF -DWITH_SIMD=ON -DBUILD_WEBRTC=OFF -DUSE_BLAS=OFF -DOPEN3D_USE_ONEAPI_PACKAGES=ON -DUSE_SYSTEM_EIGEN3=ON -DUSE_SYSTEM_CURL=OFF -DBUILD_CURL_FROM_SOURCE=ON -DUSE_SYSTEM_OPENSSL=OFF -DBUILD_ISPC_MODULE=OFF
cmake --build cmake-build-debug --target clean
```

### Error message

```shell
Result from `git status -s`

 D 3rdparty/glew/src/glew.c
 D 3rdparty/liblzf/liblzf/lzf_c.c
 D 3rdparty/liblzf/liblzf/lzf_d.c
 D 3rdparty/rply/rply/rply.c
 D 3rdparty/tinyfiledialogs/include/tinyfiledialogs/tinyfiledialogs.c
```
```


### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Open3D version: 18.0
- System architecture: x86_64
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gnu 11.4.0
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dbs4261**
Changed the CMake scripts for 3rdparty dependencies to not mark files in the Open3D git repo as generated. This is because the `clean` target would delete them and break the build.

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6644
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context
When running the clean target on some generators, source files not fetched by `ExternalProject` would be deleted. This would prevent rebuilding without using git to reset those files. See issue #6644 for details. 

## Checklist:

-  [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

Switched GoogleTest and QHull dependencies to use `FetchContent` instead of `ExternalProject`. Removed `GENERATED` property from source files passed to `open3d_build_3rdparty_library`.

### CODE REVIEW

**Comment by ssheorey** [comment]
Hi @dbs4261 please check the CI errors. Removing GENERATED property causes CMake to fail with some file not found errors for 3rd party C++ sources.

**Comment by dbs4261** [comment]
@ssheorey How can I run the CI pipeline locally to verify my fix?

**Comment by ssheorey** [comment]
This PR doesn't depend on the platform. It should be sufficient if Open3D builds for you on your machine. Try building the library (make libopen3d), python package (make pip-package) and the tests (make tests) and running the tests on your machine.

Make sure the build succeeds from an empty build folder.

**Comment by dbs4261** [comment]
Hmmm, Looks like the ubuntu-wheel build is failing because c-cache is out of space? Not sure what to do about that.

**Review by ssheorey — APPROVED** [review]
Thanks @dbs4261 for simplifying the build process!

**Comment by ssheorey** [comment]
> Hmmm, Looks like the ubuntu-wheel build is failing because c-cache is out of space? Not sure what to do about that.

Fixing that in a separate PR. You can ignore that for this PR.

**Pull request merged**
