### PR TITLE
Add Command Line Interface for Open3D

### PR DESCRIPTION
**Pull request by ShreyanshDarshan**
# Supported Features
## Help
```sh
open3d
# or
open3d -h
# or
open3d --help
```
```
*******************************************************
**                       Open3D                      **
**      A Modern Library for 3D Data Processing      **
*******************************************************

Docs:     http://www.open3d.org/docs/release/
GitHub:   https://github.com/isl-org/Open3D
Discord:  https://discord.com/invite/D35BGvn

usage: 
    open3d <command> <additional_arguments ...>

commands:
  draw           Visualize a mesh or pointcloud from a file 
                 usage       :  open3d draw <filename> 
                 for example :  open3d draw

  example        Run an example by category/name (or category/name.py) 
                 usage       :  open3d example <category>/<name> <example_args ...> 
                 for example :  open3d example geometry/mesh_deformation

Open3D CLI

positional arguments:
  command        command from the above list to run

optional arguments:
  -V, --version  Show program's version number and exit
                 usage : open3d --verison
                  
  -h, --help     Show this help message and exit
                 usage : open3d --help
```

## Version
```sh
open3d -V
# or
open3d --version
```
```
*******************************************************
**                       Open3D                      **
**      A Modern Library for 3D Data Processing      **
*******************************************************

Docs:     http://www.open3d.org/docs/release/
GitHub:   https://github.com/isl-org/Open3D
Discord:  https://discord.com/invite/D35BGvn

Open3D 0.13.0+f7676063f
```
(branch was created in previous release)

### Help
```sh
open3d example
# or
open3d example -h
```
```
*******************************************************
**                       Open3D                      **
**      A Modern Library for 3D Data Processing      **
*******************************************************

Docs:     http://www.open3d.org/docs/release/
GitHub:   https://github.com/isl-org/Open3D
Discord:  https://discord.com/invite/D35BGvn

usage:       open3d example <category>/<name> <example_args ...> 
for example: open3d example geometry/mesh_deformation

categories:
  benchmark
  core
  geometry
  gui
  misc
  pipelines
  reconstruction_system
  t_pipelines
  t_reconstruction_system
  utility
  visualization

To view the example in each category run:
  open3d example --list <category>
 

Run an example by category/name (or category/name.py) 

positional arguments:
  name               Category/name of an example (supports .py extension too)
  example_args       Arguments for the example to be run

optional arguments:
  -l, --list         List all categories or examples available
                     usage       :  open3d example --list 
                                    open3d example --list <category>
                     for example :  open3d example --list geometry
                      
  -s, --show         Show example source code instead of running it
                     usage       :  open3d example --show <category>/<example_name>
                     for example :  open3d example --show geometry/mesh_deformation
                      
  -p, --show_pretty  Like --show, but show in a rich format with line numbers
                     usage       :  open3d example --show_pretty <category>/<example_name>
                     for example :  open3d example --show_pretty geometry/mesh_deformation
                      
  -h, --help         Show this help message and exit
                     usage       :  open3d example --help
```
### List examples
```sh
open3d example --list
# or
open3d example -l
```
```
*******************************************************
**                       Open3D                      **
**      A Modern Library for 3D Data Processing      **
*******************************************************

Docs:     http://www.open3d.org/docs/release/
GitHub:   https://github.com/isl-org/Open3D
Discord:  https://discord.com/invite/D35BGvn

categories: 
  benchmark
  core
  geometry
  gui
  misc
  pipelines
  reconstruction_system
  t_pipelines
  t_reconstruction_system
  utility
  visualization

To view the example in each category run:
  open3d example --list <category>

```
and
```sh
open3d example --list gui
# or
open3d example -l gui
# or
open3d example gui
```
```
*******************************************************
**                       Open3D                      **
**      A Modern Library for 3D Data Processing      **
*******************************************************

Docs:     http://www.open3d.org/docs/release/
GitHub:   https://github.com/isl-org/Open3D
Discord:  https://discord.com/invite/D35BGvn

examples in gui: 
  add-geometry
  all-widgets
  demo_scene
  draw
  draw_webrtc
  line-width
  mouse-and-point-coord
  multiple-windows
  non-english
  online-processing
  render-to-image
  tensorboard_pytorch
  tensorboard_tensorflow
  text3d
  textured-mesh
  textured-model
  video
  vis-gui

To view all categories run:
  open3d example --list
```
### Run examples
```sh
open3d example gui/video
# or
open3d example gui/video.py
```
Example need not be directly in the category folder. gui/video would still work even if the directory structure is gui/somedir/video.py

### Show example code
```sh
open3d example --show gui/video
# or
open3d example -s gui/video
```

### Show example code in rich format
```sh
open3d example --show_pretty gui/video
# or
open3d example -p gui/video
```

### Help
```sh
open3d draw -h
```
```
*******************************************************
**                       Open3D                      **
**      A Modern Library for 3D Data Processing      **
*******************************************************

Docs:     http://www.open3d.org/docs/release/
GitHub:   https://github.com/isl-org/Open3D
Discord:  https://discord.com/invite/D35BGvn

usage: open3d draw <filename> 

Visualize a mesh or pointcloud from a file 

positional arguments:
  filename    Name of the mesh or point cloud file

optional arguments:
  -h, --help  Show this help message and exit
              usage       :  open3d draw --help
```
### Visualize mesh / pointcloud files
```sh
open3d draw
# or
open3d draw filename.ext
```
This command will work after merging #4586 

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4594)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4594)* status: all files reviewed, 20 unresolved discussions (waiting on @ShreyanshDarshan)

___
*[cpp/pybind/make_python_package.cmake, line 135 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtpfmFG8yWnsWk4_Pi8:-MtpfmFG8yWnsWk4_Pi9:bvemjts) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/cpp/pybind/make_python_package.cmake#L135)):*
> ```CMake
> endif()
> 
> # Add all examples to installation directory.
> ```

Add
```
TODO: after downloader is implemented, refactor test data dir
```
___
*[python/tools/cli.py, line 28 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtpfZWo3K4EmwVbwX0L:-MtpfZWo3K4EmwVbwX0M:bo3l3wl) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L28)):*
> ```Python
> 
> import argparse
> import argcomplete
> ```

Go through the imports and remove the ones that are not used. There shall also be linters or vscode plugins to do this automatically. 

Also, add to `python/requirements.txt` if we need a new requirement. Otherwise, we'll be getting:
```
(open3d) ➜  ~/repo/Open3D/build (darshan/cli) open3d         
Traceback (most recent call last):
  File "/home/yixing/miniconda3/envs/open3d/bin/open3d", line 5, in <module>
    from open3d.tools.cli import main
  File "/home/yixing/miniconda3/envs/open3d/lib/python3.8/site-packages/open3d/tools/cli.py", line 28, in <module>
    import argcomplete
ModuleNotFoundError: No module named 'argcomplete'
```
___
*[python/tools/cli.py, line 57 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtpfboIEYF9bpCTmllE:-MtpfboIEYF9bpCTmllF:btnecak) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L57)):*
> ```Python
> 
> 
> def registerableCLI(cls):
> ```

`snake_case` for function name.
___
*[python/tools/cli.py, line 93 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-Mtv7YZ8CBWOHNqx7_5z:-Mtv7YZ8CBWOHNqx7_6-:b-c3y616) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L93)):*
> ```Python
> 
>     def __init__(self):
>         self.banner = f"\n{'*' * 55}"
> ```

I think strings can be directly concatenated with

```python
my_str = f"abcdefg {xxx}"
         f"abcdefg"
```

Can we try that?
___
*[python/tools/cli.py, line 98 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtpfggLA_UnV8mBmNO9:-MtpfggLA_UnV8mBmNOA:b-dpmu9z) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L98)):*
> ```Python
>         print(self.banner)
> 
>         print(self._get_friend_links())
> ```

This can also be a part of the banner. 
___
*[python/tools/cli.py, line 103 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-Mtv7nh3623_HbkdH3Es:-Mtt6v_9BlzWaKHLZeK1:b-ckimvx) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L103)):*
> ```Python
>         for command in sorted(self.registered_commands):
>             try:
>                 self.command_helper[command] = CommandHelp(
> ```

Are we copying some code from external resources? This seems to be fragile and over-engineered. 

We get the `__doc__` member of a function and split the docstring with `|`. If the docstring is accidentally modified by the developer, it could actually break the logic. Typically comments should not break logic. 

I would construct three properties directly, instead of splitting a longer string. 
___
*[python/tools/cli.py, line 118 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvCQN0APoOQWEZvB9L:-MtvCQN0APoOQWEZvB9M:b-ylhjw9) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L118)):*
> ```Python
>             formatter_class=argparse.RawTextHelpFormatter)
>         parser.add_argument('command',
>                             help="command from the above list to run")
> ```

command -> Command

Do we need `\n` at the end? I haven't seen a lot of `\n` at the end. Perhaps we can remove other `\n`s for other arguments. 
___
*[python/tools/cli.py, line 140 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-Mtv8_4H9nwxCQc18c7D:-Mtv8_4H9nwxCQc18c7E:b-pl8i58) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L140)):*
> ```Python
> 
>     @staticmethod
>     def _get_friend_links():
> ```

if other functions have type hits, this should have as well
___
*[python/tools/cli.py, line 159 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-Mtv8cU203912qrxZqS4:-Mtv8cU203912qrxZqS5:bxesn5d) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L159)):*
> ```Python
> 
>     @staticmethod
>     def _exec_python_file(filename: str,):
> ```

type hint to return `None`? 
also, remove `,`
___
*[python/tools/cli.py, line 167 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-Mtv8rcB1HheczrE8QcG:-Mtv8rcB1HheczrE8QcH:b80tk8m) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L167)):*
> ```Python
>         """Get the path to the examples directory."""
>         tools_path = os.path.dirname(os.path.abspath(__file__))
>         examples_path = os.path.join(os.path.dirname(tools_path), "examples")
> ```

Try avoiding mix-use of `os.path` and `Pathlib`. Implement with `Pathlib` whenever possible. 

Apply this to the rest of the PR. 
___
*[python/tools/cli.py, line 176 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-Mtv9OoqEgviQHIiTlAY:-Mtv9OoqEgviQHIiTlAZ:btdf6jz) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L176)):*
> ```Python
>         examples_dir = Open3DMain._get_examples_dir()
>         all_categories = [x.name for x in examples_dir.iterdir() if x.is_dir()]
>         if "__pycache__" in all_categories:
> ```

Instead of doing negative filtering, I would do positive filtering. E.g. match regex `^[a-z].*$` or something, to make sure that the starting character is lower-case letters only. This is because some OS may generate additional hidden files besides `__pycache__`. We can even hard-code all valid entries. 
___
*[python/tools/cli.py, line 184 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvAU9kC7fEQqEetBQK:-MtvAU9kC7fEQqEetBQL:b-z1o2ds) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L184)):*
> ```Python
>         """Get a set of all available example names."""
>         examples_dir = Open3DMain._get_examples_dir()
>         all_examples = examples_dir.rglob('*.py')
> ```

how do we deal with `reconsturction_system`, `t_reconsturction_system`?
___
*[python/tools/cli.py, line 200 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvBGAx9NpAUWno_q17:-MtvBGAx9NpAUWno_q18:brqur3k) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L200)):*
> ```Python
> 
>     @staticmethod
>     def _get_version() -> str:
> ```

This function can be removed.
___
*[python/tools/cli.py, line 202 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvB3GGA6N5TZB-KJSI:-MtvB3GGA6N5TZB-KJSJ:bvu5vqm) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L202)):*
> ```Python
>     def _get_version() -> str:
>         """Get the current Open3D version."""
>         import open3d
> ```

I think we can import `open3d` first, on top. And if the import is not successful, warn the user and exit.
___
*[python/tools/cli.py, line 209 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvBPZEEQWUn86P6q2F:-MtvBPZEEQWUn86P6q2G:b-vubcpg) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L209)):*
> ```Python
>         if choice.endswith('.py'):
>             # try to find and remove python file extension
>             return choice.split('.')[0]
> ```

What if you have `my.file.name.py`? Will `my.file.name.py` -> `my`?
___
*[python/tools/cli.py, line 252 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvBlEkB_R0DCCupgMJ:-MtvBlEkB_R0DCCupgMK:bftcr7k) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L252)):*
We are mixing the usage of `"` and `'` everywhere. We can change everything to `"` and only use `'` when we need nested quotes. 

We typically follow google styles: https://google.github.io/styleguide/pyguide.html#310-strings

> Be consistent with your choice of string quote character within a file. Pick ' or " and stick with it. It is okay to use the other quote character on a string to avoid the need to backslash-escape quote characters within the string.
___
*[python/tools/cli.py, line 286 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvCIgoCMVVzXuPMnvM:-MtvCIgoCMVVzXuPMnvN:beb41g6) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L286)):*
> ```Python
>                 print("categories: ")
>                 for category in sorted(self._get_example_categories()):
>                     print("  " + str(category))
> ```

use f-string
___
*[python/tools/cli.py, line 323 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvVhtS6Kad3eAA8CU_:-MtvVhtS6Kad3eAA8CUa:b-duxkan) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L323)):*
> ```Python
>                       f"{example}.py").resolve())
>         # path for examples needs to be modified for implicit relative imports
>         sys.path.append(
> ```

can `sys.path.append` take pathlib?
___
*[python/tools/cli.py, line 329 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvVljn4IUVt-BzQqam:-MtvVljn4IUVt-BzQqan:b-7zuofg) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L329)):*
> ```Python
>         if args.show_pretty:
>             try:
>                 import rich.console
> ```

is this built-in package?
___
*[python/tools/cli.py, line 361 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvW2Dl8evU76fs3k-n:-MtvW2Dm54YV3c4G9qqu:b-olueaw) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L361)):*
> ```Python
>         'open3d draw'
> 
>         parser = Open3DArgumentParser(
> ```

Can we also check `argparse.ArgumentParser.add_subparsers()`?

Something like this:

```python
parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers()

draw_parser = subparsers.add_parser("draw", ...)
draw_parser.add_argument("filename", ...)
```

Then, we can migrate this to the registration pattern. Or, maybe we don't even need the registration pattern, since the sub parser is essentially doing the registration for us.

**Comment by yxlao** [comment]
Please merge the pybind branch to fix the conflicts.

**Review by ShreyanshDarshan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4594)* status: 1 of 3 files reviewed, 20 unresolved discussions (waiting on @ShreyanshDarshan and @yxlao)

___
*[cpp/pybind/make_python_package.cmake, line 135 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtpfmFG8yWnsWk4_Pi8:-MuWp2Dt6g_zRAlN_PGr:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/cpp/pybind/make_python_package.cmake#L135)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Add
```
TODO: after downloader is implemented, refactor test data dir
```
</blockquote></details>

Done.
___
*[python/tools/cli.py, line 103 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-Mtv7nh3623_HbkdH3Es:-MuWp9fD70nkQWiePWj7:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L103)):*
<details><summary><i>Previously, ShreyanshDarshan (Shreyansh Darshan) wrote…</i></summary><blockquote>

Sure, I will make the change. 
I borrowed the idea of using docstring of a function for help prompts in the CLI from the CLI of taichi. It made it slightly convenient to add additional commands because it enabled the help, usage and example string to all be contained within the function for the command, yet still be accessible from outside the function.
</blockquote></details>

Done.
___
*[python/tools/cli.py, line 176 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-Mtv9OoqEgviQHIiTlAY:-MuWprQQ3JCVdobQhVgj:b-8ss3v4) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L176)):*
<details><summary><i>Previously, ShreyanshDarshan (Shreyansh Darshan) wrote…</i></summary><blockquote>

Would filtering directories based on the presence of .py files be a viable solution?
</blockquote></details>

Hardcoded all example filenames.
___
*[python/tools/cli.py, line 209 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvBPZEEQWUn86P6q2F:-MuWq2cN4NxQ_BJVXFej:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L209)):*
<details><summary><i>Previously, ShreyanshDarshan (Shreyansh Darshan) wrote…</i></summary><blockquote>

Will fix this. Currently we don't have any examples with multiple `.` in their name.
</blockquote></details>

Done.
___
*[python/tools/cli.py, line 329 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvVljn4IUVt-BzQqam:-MuWq8NU83XWtHgCodDR:b-e1cyvf) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L329)):*
<details><summary><i>Previously, ShreyanshDarshan (Shreyansh Darshan) wrote…</i></summary><blockquote>

No. Added to requirements.
</blockquote></details>

Removed this feature.
___
*[python/tools/cli.py, line 361 at r3](https://reviewable.io/reviews/isl-org/open3d/4594#-MtvW2Dl8evU76fs3k-n:-MuWqBnoEcyH3C4QYo16:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fb1e2fc60b8f25510b9ddcd29ff9ad192b39128b/python/tools/cli.py#L361)):*
<details><summary><i>Previously, ShreyanshDarshan (Shreyansh Darshan) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.

**Comment by ShreyanshDarshan** [comment]
> Please merge the pybind branch to fix the conflicts.

Done.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4594)* status: all files reviewed, 5 unresolved discussions (waiting on @ShreyanshDarshan)

___
*[python/tools/cli.py, line 35 at r6](https://reviewable.io/reviews/isl-org/open3d/4594#-Mu_ez9k7aPL5CSK6C5R:-Mu_ez9k7aPL5CSK6C5S:bvu4fbp) ([raw file](https://github.com/isl-org/open3d/blob/646369160804e8d30f7539b9b506aed8d340869d/python/tools/cli.py#L35)):*
> ```Python
> 
> 
> class Open3DArgumentParser(argparse.ArgumentParser):
> ```

all "private" classes shall start with `_` name
___
*[python/tools/cli.py, line 43 at r6](https://reviewable.io/reviews/isl-org/open3d/4594#-Mu_evjiEwB_EogE35n5:-Mu_evjiEwB_EogE35n6:b-v9roty) ([raw file](https://github.com/isl-org/open3d/blob/646369160804e8d30f7539b9b506aed8d340869d/python/tools/cli.py#L43)):*
> ```Python
> 
> 
> def get_examples_dict():
> ```

all "private" functions shall start with `_` name
___
*[python/tools/cli.py, line 70 at r6](https://reviewable.io/reviews/isl-org/open3d/4594#-Mu_eqz0AvBcBxgVR8Yc:-Mu_eqz0AvBcBxgVR8Yd:bwcf2d9) ([raw file](https://github.com/isl-org/open3d/blob/646369160804e8d30f7539b9b506aed8d340869d/python/tools/cli.py#L70)):*
> ```Python
>             "triangle_mesh_subdivision", "triangle_mesh_transformation",
>             "triangle_mesh_with_numpy", "voxel_grid_carving",
>             "voxel_grid_from_point_cloud", "voxel_grid_from_triangle_mesh"
> ```

add `,` at the end of the list, such that one instance will take one line.
___
*[python/tools/cli.py, line 286 at r6](https://reviewable.io/reviews/isl-org/open3d/4594#-Mu_ehHFB_A4gIDNmfRU:-Mu_ehHFB_A4gIDNmfRV:b-g7yich) ([raw file](https://github.com/isl-org/open3d/blob/646369160804e8d30f7539b9b506aed8d340869d/python/tools/cli.py#L286)):*
> ```Python
>     parser_draw.set_defaults(func=draw)
> 
>     args = main_parser.parse_args()
> ```

Gives the following error when called with no arguments.

```bash
(open3d) ➜  ~/repo/Open3D/build (darshan/cli) open3d
*******************************************************
**                       Open3D                      **
**      A Modern Library for 3D Data Processing      **
*******************************************************

Docs:     http://www.open3d.org/docs/release/
GitHub:   https://github.com/isl-org/Open3D
Discord:  https://discord.com/invite/D35BGvn

Traceback (most recent call last):
  File "/home/yixing/miniconda3/envs/open3d/bin/open3d", line 8, in <module>
    sys.exit(main())
  File "/home/yixing/miniconda3/envs/open3d/lib/python3.8/site-packages/open3d/tools/cli.py", line 287, in main
    args.func(subparsers.choices[args.command], args)
AttributeError: 'Namespace' object has no attribute 'func'
```

Ref: https://stackoverflow.com/a/54161510/1255535

**Review by yxlao — CHANGES_REQUESTED** [review]
We'll need to add a unit test to test that:

- `open3d` with no arguments shall work
- List examples 
- List examples by category
- List code

One location to add this is in `docker/docker_test.sh::cpp_python_linking_uninstall_test()`, under the `Python test` section. 

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4594#-:-Mu_fiiT8beo0gK8zoOe:bb4fxsv)* status: all files reviewed, 5 unresolved discussions (waiting on @ShreyanshDarshan)

**Comment by reyanshsolis** [comment]
Extract unit test is failing (might have changed in merging master), this is the correct unit test:
```cpp
TEST(Extract, ExtractFromZIP) {
    // Directory relative to `data_root`, where files will be temp. downloaded
    // for this test.
    const std::string prefix = "test_extract";
    const std::string extract_dir = data::LocateDataRoot() + "/" + prefix;
    EXPECT_TRUE(utility::filesystem::DeleteDirectory(extract_dir));

    // Download the `test_data_v2_00.zip` test data.
    std::string url =
            "https://github.com/isl-org/open3d_downloads/releases/download/"
            "data-manager/test_data_v2_00.zip";
    std::string md5 = "bc47a5e33d33e717259e3a37fa5eebef";
    std::string file_path = extract_dir + "/test_data_v2_00.zip";
    // This download shall work.
    EXPECT_EQ(utility::DownloadFromURL(url, md5, prefix), file_path);

    // Extract the test zip file.
    EXPECT_NO_THROW(utility::Extract(file_path, extract_dir));
    url = "https://github.com/isl-org/open3d_downloads/releases/download/"
          "data-manager/test_data_v2_00.tar.xz";
    md5 = "7c682c7af4ef9bda1fc854b008ae2bef";
    file_path = extract_dir + "/test_data_v2_00.tar.xz";
    EXPECT_EQ(utility::DownloadFromURL(url, md5, prefix), file_path);

    // Currently only `.zip` files are supported.
    EXPECT_ANY_THROW(utility::Extract(file_path, extract_dir));

    // Clean up.
    EXPECT_TRUE(utility::filesystem::DeleteDirectory(extract_dir));
}
```

**Comment by yxlao** [comment]
- [ ]  I pushed an example of how to show usage example: https://github.com/isl-org/Open3D/pull/4594/commits/adbcb7434e0004d42cfa70695f3f6a6f36438361 . Could you apply it to the sub-commands (e.g. ``--list``, ``--show``) as well?
- [ ]  `open3d example --list` shall list all examples. To save space, we don't need to print examples line-by-line. Mutiple examples in one category can be printed in one line.
- [ ] When listing examples, always pre-fix the category name. This is because the example is always referred with the category name. That is change `triangle_mesh_deformation` to `geometry/triangle_mesh_deformation`. It is okay that the `geometry` keyword is repeated.
- [ ]  Modify 
   ```
   To view the example in each category run:
   open3d example --list category
   ```
   to
   ```
   To view the example in each category run one of the following caommands:
   open3d example --list camera
   open3d example --list geometry
   ...
   ```
   The idea is to provide copiable commands to the user as much as possible.
- [ ] The "debugging" mode seems broken. E.g. 
   ```bash
   cd python/tools
   python cli.py example geometry/kd_tree_search
   # Complains file not found: /home/yixing/repo/Open3D/python/examples/geometry/kd_tree_search.py
   # Actual file path        : /home/yixing/repo/Open3D/examples/python/geometry/kd_tree_search.py
   ```

**Comment by yxlao** [comment]
Additional items:
- [ ] When we run `open3d draw non-existing-file`, the error shall be caught in `cli.py`, not in the visualizer.

**Review by yxlao — CHANGES_REQUESTED** [review]
Added two additional comments above.

**Comment by ShreyanshDarshan** [comment]
> * [ ]  Do we need `app.py` at all? Is it possible to call `o3d.visualization.app.run_viewer(args)` directly from `cli.py`?

`app.py` calls `RunViewer()` which calls 
```cpp
auto &app = gui::Application::GetInstance();
app.Initialize(argc, argv);
```
The `Initialize` function defines `argv[0]` to be the path of the calling code but expects it to be alongside the resources folder.
If we call `RunViewer()` directly from `cli.py` (which is not adjacent to the resources folder), then we can pass in the path of a nonexistent file that is adjacent to the resources folder as a hack to make the code work, but in my opinion that would make the code less clean and a bit confusing.

**Review by yxlao — APPROVED** [review]

**Pull request merged**
