### PR TITLE
Update nanoflann to version 1.5.0

### PR DESCRIPTION
**Pull request by roehling**
## Type

-   [ ] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [x] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

Maintenance of third-party dependencies, in this case nanoflann

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

This PR updates Open3D to build with the latest nanoflann version 1.5.0. Note that Jose did some refactoring, so this PR makes Open3D incompatible with older nanoflann releases.

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6216)

### CODE REVIEW

**Comment by roehling** [comment]
It looks like the unit test is failing for the new Nanoflann. I'll convert this into a Draft pending further investigation.

**Comment by roehling** [comment]
I found and fixed the issue; the PR is ready for review now.

**Comment by ssheorey** [comment]
> Note that Jose did some refactoring, so this PR makes Open3D incompatible with older nanoflann releases.

In that case, can you add a check in find_dependencies.cmake that gives a fatal error if USE_SYSTEM_NANOFLANN but the version is less than 1.5?

**Comment by roehling** [comment]
Good point.

**Review by ssheorey — APPROVED** [review]
Thanks as always @roehling !

**Pull request merged**
