### PR TITLE
Fix some tool's link flags when using system libs

### PR DESCRIPTION
**Pull request by cielavenir**
can reproduce by `-DUSE_SYSTEM_FMT=ON -DUSE_SYSTEM_OPENGL=ON -DUSE_SYSTEM_GLFW=ON -DGLIBCXX_USE_CXX11_ABI=ON`

error without patch:

```
ld: CMakeFiles/GLInfo.dir/GLInfo.cpp.o: undefined reference to symbol '_ZN3fmt2v76detail7vformatB5cxx11ENS0_17basic_string_viewIcEENS0_11format_argsE'
ld: /usr/lib/x86_64-linux-gnu/libfmt.so.7: error adding symbols: DSO missing from command line

ld: CMakeFiles/ConvertPointCloud.dir/ConvertPointCloud.cpp.o: undefined reference to symbol '_ZN3fmt2v76detail7vformatB5cxx11ENS0_17basic_string_viewIcEENS0_11format_argsE'
ld: /usr/lib/x86_64-linux-gnu/libfmt.so.7: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5622)

### CODE REVIEW

**Comment by ssheorey** [comment]
Hi @cielavenir I cannot reproduce your error. `libfmt.a` is already present in the linker argument produced by `cmake`. 
On Ubuntu 20.04 (libfmt v6), here is a summary:
```
cd build
cmake -DUSE_SYSTEM_FMT=ON -DUSE_SYSTEM_OPENGL=ON -DUSE_SYSTEM_GLFW=ON -DGLIBCXX_USE_CXX11_ABI=ON ..
make GLInfo
... no errrors ...
[100%] Built target GLInfo 
cat cpp/tools/CMakeFiles/GLInfo.dir/link.txt 
/usr/bin/c++ -O3 -DNDEBUG -Wl,-z,noexecstack -Wl,-z,relro,-z,now -pie -Wl,--strip-debug -Wl,--exclude-libs,libz.a -Wl,--exclude-libs,libzmq.a -Wl,--exclude-libs,libvtkFiltersGeneral-9.1.a -Wl,--exclude-libs,libvtkFiltersSources-9.1.a -Wl,--exclude-libs,libvtkFiltersModeling-9.1.a -Wl,--exclude-libs,libvtkFiltersCore-9.1.a -Wl,--exclude-libs,libvtkCommonExecutionModel-9.1.a -Wl,--exclude-libs,libvtkCommonDataModel-9.1.a -Wl,--exclude-libs,libvtkCommonTransforms-9.1.a -Wl,--exclude-libs,libvtkCommonMath-9.1.a -Wl,--exclude-libs,libvtkCommonMisc-9.1.a -Wl,--exclude-libs,libvtkCommonSystem-9.1.a -Wl,--exclude-libs,libvtkCommonCore-9.1.a -Wl,--exclude-libs,libvtkkissfft-9.1.a -Wl,--exclude-libs,libvtkpugixml-9.1.a -Wl,--exclude-libs,libvtksys-9.1.a -Wl,--exclude-libs,libUVAtlas.a -Wl,--exclude-libs,libmkl_merged.a -Wl,--exclude-libs,libtbb_static.a -Wl,--exclude-libs,libippiw.a -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libembree3.a -Wl,--exclude-libs,libembree_avx.a -Wl,--exclude-libs,libembree_avx2.a -Wl,--exclude-libs,libsimd.a -Wl,--exclude-libs,liblexers.a -Wl,--exclude-libs,libsys.a -Wl,--exclude-libs,libmath.a -Wl,--exclude-libs,libtasking.a -Wl,--exclude-libs,libwebrtc.a -Wl,--exclude-libs,libwebrtc_extra.a CMakeFiles/GLInfo.dir/GLInfo.cpp.o -o ../../bin/GLInfo  ../../lib/Release/libOpen3D.a -lstdc++fs /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libglfw.so.3.3 /usr/lib/x86_64-linux-gnu/libX11.so ../../assimp/lib/libassimp.a ../../turbojpeg/lib/libturbojpeg.a ../../jsoncpp/lib/libjsoncpp.a ../../lib/Release/libOpen3D_3rdparty_liblzf.a ../../curl/src/ext_curl/lib/libcurl.a ../../libpng/lib/libpng16.a ../../zlib/lib/libz.a ../../lib/Release/libOpen3D_3rdparty_rply.a ../../lib/Release/libOpen3D_3rdparty_tinyfiledialogs.a ../../lib/Release/libOpen3D_3rdparty_qhullcpp.a ../../lib/Release/libOpen3D_3rdparty_qhull_r.a ../../lib/Release/libOpen3D_3rdparty_imgui.a ../../zeromq/lib/libzmq.a ../../vtk/src/ext_vtk/lib/libvtkFiltersGeneral-9.1.a ../../vtk/src/ext_vtk/lib/libvtkFiltersSources-9.1.a ../../vtk/src/ext_vtk/lib/libvtkFiltersModeling-9.1.a ../../vtk/src/ext_vtk/lib/libvtkFiltersCore-9.1.a ../../vtk/src/ext_vtk/lib/libvtkCommonExecutionModel-9.1.a ../../vtk/src/ext_vtk/lib/libvtkCommonDataModel-9.1.a ../../vtk/src/ext_vtk/lib/libvtkCommonTransforms-9.1.a ../../vtk/src/ext_vtk/lib/libvtkCommonMath-9.1.a ../../vtk/src/ext_vtk/lib/libvtkCommonMisc-9.1.a ../../vtk/src/ext_vtk/lib/libvtkCommonSystem-9.1.a ../../vtk/src/ext_vtk/lib/libvtkCommonCore-9.1.a ../../vtk/src/ext_vtk/lib/libvtkkissfft-9.1.a ../../vtk/src/ext_vtk/lib/libvtkpugixml-9.1.a ../../vtk/src/ext_vtk/lib/libvtksys-9.1.a ../../uvatlas/lib/libUVAtlas.a ../../mkl_install/lib/libtbbmalloc_static.a ../../mkl_install/lib/libmkl_merged.a ../../mkl_install/lib/libtbb_static.a ../../embree/lib/libembree3.a ../../embree/lib/libembree_avx.a ../../embree/lib/libembree_avx2.a ../../embree/lib/libsimd.a ../../embree/lib/liblexers.a ../../embree/lib/libsys.a ../../embree/lib/libmath.a ../../embree/lib/libtasking.a ../../webrtc/src/ext_webrtc/lib/libwebrtc.a ../../webrtc/src/ext_webrtc/lib/libwebrtc_extra.a ../../civetweb/lib/libcivetweb.a ../../civetweb/lib/libcivetweb-cpp.a /usr/lib/gcc/x86_64-linux-gnu/11/libgomp.so /usr/lib/x86_64-linux-gnu/libpthread.a ../../ippicv/lib/libippiw.a ../../ippicv/lib/libippicv.a ../../lib/Release/libOpen3D_3rdparty_glew.a -lstdc++fs ../../filament/src/ext_filament/lib//libfilameshio.a ../../filament/src/ext_filament/lib//libfilament.a ../../filament/src/ext_filament/lib//libfilamat_lite.a ../../filament/src/ext_filament/lib//libfilaflat.a ../../filament/src/ext_filament/lib//libfilabridge.a ../../filament/src/ext_filament/lib//libgeometry.a ../../filament/src/ext_filament/lib//libbackend.a ../../filament/src/ext_filament/lib//libbluegl.a ../../filament/src/ext_filament/lib//libbluevk.a ../../filament/src/ext_filament/lib//libibl.a ../../filament/src/ext_filament/lib//libimage.a ../../filament/src/ext_filament/lib//libmeshoptimizer.a ../../filament/src/ext_filament/lib//libsmol-v.a ../../filament/src/ext_filament/lib//libutils.a ../../filament/src/ext_filament/lib//libvkshaders.a -ldl -lstdc++ /usr/lib/x86_64-linux-gnu/libc++.so /usr/lib/x86_64-linux-gnu/libc++abi.so /usr/lib/x86_64-linux-gnu/libfmt.a 
```
Similarly for `ConvertPointCloud`.

**Comment by ssheorey** [comment]
Closing for now. Please re-open if you are able to reproduce in a clean environment.

**Comment by cielavenir** [comment]
@ssheorey would you mind telling me the right direction on Debian11? Note that it ships libfmt7.

**Comment by ssheorey** [comment]
On master, what is the link command for GLInfo? The link command that I get already contains `libfmt.a`. See my comment above.

**Comment by cielavenir** [comment]
@ssheorey I reproduced using docker:

docker run -it --rm ubuntu:20.04 bash

```
apt update
apt install -y wget gpg git g++ libfmt-dev libopengl-dev libglu1-mesa-dev python3-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - > /usr/share/keyrings/kitware-archive-keyring.gpg
echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' > /etc/apt/sources.list.d/kitware.list
apt-get update
apt install -y cmake

git clone https://github.com/isl-org/Open3D.git
mkdir Open3D/build
(cd Open3D/build; cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_MODULE=ON -DBUILD_SHARED_LIBS=ON -DBUILD_GUI=OFF -DBUILD_WEBRTC=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_CXX_STANDARD=17 -DUSE_SYSTEM_FMT=ON -DUSE_SYSTEM_OPENGL=ON)
(cd Open3D/build; make -j4)
```

So actually -DBUILD_SHARED_LIBS=ON is causing the issue.

**Comment by cielavenir** [comment]
This was correctly built

docker run -it --rm ubuntu:20.04 bash

```sh
apt update
apt install -y wget gpg git g++ libfmt-dev libopengl-dev libglu1-mesa-dev python3-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - > /usr/share/keyrings/kitware-archive-keyring.gpg
echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' > /etc/apt/sources.list.d/kitware.list
apt-get update
apt install -y cmake

git clone https://github.com/isl-org/Open3D.git
git -C Open3D checkout v0.15.1
mkdir Open3D/build
(cd Open3D/build; cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_MODULE=ON -DBUILD_SHARED_LIBS=ON -DBUILD_GUI=OFF -DBUILD_WEBRTC=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_CXX_STANDARD=17 -DUSE_SYSTEM_FMT=ON -DUSE_SYSTEM_OPENGL=ON)
(cd Open3D/build; make -j4)
```

**Comment by cielavenir** [comment]
According to https://packages.debian.org/en/source/fmtlib and https://packages.ubuntu.com/en/source/fmtlib , Ubuntu20 or Debian10 have libfmt.a whereas Ubuntu22 or Debian11 have libfmt.so. It seems .so has issues.

**Comment by cielavenir** [comment]
@ssheorey OK, reproduced this way!

docker run -it --rm ubuntu:20.04 bash

```sh
apt update
apt install -y wget gpg git g++ libopengl-dev libglu1-mesa-dev python3-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - > /usr/share/keyrings/kitware-archive-keyring.gpg
echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' > /etc/apt/sources.list.d/kitware.list
apt-get update
apt install -y cmake

git clone https://github.com/fmtlib/fmt.git
git -C fmt checkout 6.2.1
mkdir fmt/build
(cd fmt/build; cmake .. -DBUILD_SHARED_LIBS=ON)
(cd fmt/build; make -j4)
(cd fmt/build; make install)

git clone https://github.com/isl-org/Open3D.git
git -C Open3D checkout v0.15.1
mkdir Open3D/build
(cd Open3D/build; cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_MODULE=ON -DBUILD_SHARED_LIBS=ON -DBUILD_GUI=OFF -DBUILD_WEBRTC=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_CXX_STANDARD=17 -DUSE_SYSTEM_FMT=ON -DUSE_SYSTEM_OPENGL=ON)
(cd Open3D/build; make -j4)
```

**Comment by cielavenir** [comment]
and applying this fixes the issue

```sh
(cd Open3D; patch -p1 <<EOM)
diff --git a/cpp/tools/CMakeLists.txt b/cpp/tools/CMakeLists.txt
index 9d5f681a9d8..cfc98a35edd 100644
--- a/cpp/tools/CMakeLists.txt
+++ b/cpp/tools/CMakeLists.txt
@@ -11,8 +11,8 @@ macro(open3d_add_tool TOOL_NAME)
     open3d_set_global_properties(${TOOL_NAME})
 endmacro()
 
-open3d_add_tool(ConvertPointCloud)
-open3d_add_tool(GLInfo                  Open3D::3rdparty_opengl Open3D::3rdparty_glfw)
+open3d_add_tool(ConvertPointCloud       Open3D::3rdparty_fmt)
+open3d_add_tool(GLInfo                  Open3D::3rdparty_opengl Open3D::3rdparty_glfw Open3D::3rdparty_fmt)
 open3d_add_tool(ManuallyCropGeometry)
 open3d_add_tool(MergeMesh)
 open3d_add_tool(ViewGeometry)
diff --git a/cpp/tools/ManuallyAlignPointCloud/CMakeLists.txt b/cpp/tools/ManuallyAlignPointCloud/CMakeLists.txt
index 99da7e93fc4..06d61035dbd 100644
--- a/cpp/tools/ManuallyAlignPointCloud/CMakeLists.txt
+++ b/cpp/tools/ManuallyAlignPointCloud/CMakeLists.txt
@@ -9,6 +9,7 @@ target_link_libraries(ManuallyAlignPointCloud PRIVATE
     Open3D::Open3D
     Open3D::3rdparty_jsoncpp
     Open3D::3rdparty_tinyfiledialogs
+    Open3D::3rdparty_fmt
 )
 
 set_target_properties(ManuallyAlignPointCloud PROPERTIES FOLDER "Tools")
EOM
```

**Comment by cielavenir** [comment]
my patch is ok for v0.15.1, but on v0.16.1 I have this

```
/usr/bin/ld: ../../lib/Release/libOpen3D.so: undefined reference to `std::string fmt::v6::internal::grouping_impl<char>(fmt::v6::internal::locale_ref)'
```

**Pull request closed without merging**
