### PR TITLE
Fix mesh naming in mesh docs

### PR DESCRIPTION
**Pull request by pmokeev**
Changed:
- `mesh_in` -> `mesh` on [Mesh page](http://www.open3d.org/docs/release/tutorial/geometry/mesh.html#Vertex-clustering)

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4942)

### CODE REVIEW

**Comment by yxlao** [comment]
Looks like the name `mesh_in` corresponds to the name `mesh_out`. Probably we should keep the original name. Any other reasons to update the name besides cosmetics @pmokeev ?

**Comment by pmokeev** [comment]
> Any other reasons to update the name besides cosmetics?

In this example, a mesh is created with the name `mesh` (a few lines above, I did not change them), and then the name `mesh_in` is used. Therefore, this example cannot be reproduced.
I can replace the named BunnyMesh initialization with `mesh_in` if you think that looks better.

**Comment by reyanshsolis** [comment]
> > Any other reasons to update the name besides cosmetics?
> 
> In this example, a mesh is created with the name `mesh` (a few lines above, I did not change them), and then the name `mesh_in` is used. Therefore, this example cannot be reproduced. I can replace the named BunnyMesh initialization with `mesh_in` if you think that looks better.

Hi @pmokeev, Yes I think that will look better (init. with `mesh_in`). Thanks for your valuable contribution.

**Comment by pmokeev** [comment]
> Hi @pmokeev, Yes I think that will look better (init. with `mesh_in`). Thanks for your valuable contribution.
It's done :)

**Review by reyanshsolis — APPROVED** [review]

**Pull request merged**
