### PR TITLE
Tensorboard plugin UI + ML3D visualizer

### PR DESCRIPTION
**Pull request by ssheorey**
Accompanying 3DML PR https://github.com/isl-org/Open3D-ML/pull/405

To test locally with a small test summary, unzip `examples/test_data/test_tensorboard_plugin.zip` and run
```
tensorboard --logdir examples/test_data/test_tensorboard_plugin
```
[Increase point size for the point cloud to see the point colors easily, since the point cloud is very small].

### TensorBoard UI:
- [x] Synchronized view in multiple run widgets
- [x] Show / hide axes, ground plane, GUI settings panel.
- [x] TB look and feel (fonts + colors)
- [x] Widget zoom - small view for comparisons and full view for details.
- [x] Loading animation (large geometry may take a few seconds to load).

### ML3D visualizer:
- [x] Bounding boxes serialization, with labels and confidences. Label names are serialized separately for display.
- [x] Point clouds: Custom properties with RGB shader (first 3 dims as RGB), Any property / dimension can be used to assign colors with a color gradient. Color map is customizable.
- [x] Label UI allows hiding / showing chosen classes for both BBs and points.

### TODO:
- [x] Auto-update (remove update button).
- [x] Add / remove more colors in UI.
- [x] Disable custom line / triangle properties.
- [x] Disable property view if labels or custom vertex properties absent.
- [x] post_redraw doesn't work with rendering updates. Works with add/remove geometry. Click on scene is needed to trigger redraw.
- [x] Visual accents for runs, to match run widget with run name (as in TB UI) when there are multiple runs.
- [x] Start GUI only if Open3D data is present. This avoids TB crash if Open3D is installed and GPU is not present / EGL is not supported.
- [x] Add example and unit test

Screenshot 2021-10-09 at 21-29-21 TensorBoard
Screenshot 2021-10-09 at 21-28-13 TensorBoard
Screenshot 2021-10-09 at 21-27-49 TensorBoard
Screenshot 2021-10-09 at 21-27-40 TensorBoard
Screenshot 2021-10-09 at 21-27-13 TensorBoard
Screenshot 2021-10-09 at 21-26-03 TensorBoard

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4152)

### CODE REVIEW

**Review by benjaminum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4152)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @germanros1987, @sanskar107, @ssheorey, and @yxlao)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 141 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnB6FJD0GM9V06Gr5Ig:-MnB6FJD0GM9V06Gr5Ih:bpk0dq1) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L141)):*
> ```objc
>     void RemoveGeometry(const std::string& name);
> 
>     void UpdateGeometry(const std::string& name,
> ```

Please add docstring
___
*[python/open3d/visualization/tensorboard_plugin/plugin.py, line 46 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnB6rRY9-zIXMJvw5Ny:-MnB6rRY9-zIXMJvw5Nz:bary7zn) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/python/open3d/visualization/tensorboard_plugin/plugin.py#L46)):*
> ```Python
> from open3d.visualization import webrtc_server
> # Set window system before the GUI event loop
> o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)
> ```

# TODO remove for release?
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 489 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnBVpUN-VNVB4ax0Qbc:-MnBVpUN-VNVB4ax0Qbd:b2q40wh) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/python/open3d/visualization/tensorboard_plugin/summary.py#L489)):*
> ```Python
>            description=None):
>     """Write 3D geometry data as summary.
> ```

Would it make sense to put here a minimal code example?
___
*[python/test/visualization/test_tensorboard_plugin.py, line 191 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnCfXk14B5119QtlRQC:-MnCfXk14B5119QtlRQD:bmebb87) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/python/test/visualization/test_tensorboard_plugin.py#L191)):*
> ```Python
>                                label_to_names=label_to_names)
> 
>     sleep(0.25)  # msgpack writing disk flush time
> ```

There is `tf.summary.flush`. Would that help?

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4152)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @benjaminum, @errissa, @germanros1987, @sanskar107, and @yxlao)

___
*[python/open3d/visualization/tensorboard_plugin/plugin.py, line 46 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnB6rRY9-zIXMJvw5Ny:-MnE2CY10JWk7CutPiI4:b-e8hdns) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/python/open3d/visualization/tensorboard_plugin/plugin.py#L46)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

# TODO remove for release?
</blockquote></details>

Yes. I'll remove the Debug verbosity level before merging to master.
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 489 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnBVpUN-VNVB4ax0Qbc:-MnE2QiOBNOsKgmHahNU:b87iq69) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/python/open3d/visualization/tensorboard_plugin/summary.py#L489)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Would it make sense to put here a minimal code example?
</blockquote></details>

Yes. A basic example (writes a colored box to summary) for both PyTorch and TF is there since an earlier PR.  Do you want to add to it?
___
*[python/test/visualization/test_tensorboard_plugin.py, line 191 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnCfXk14B5119QtlRQC:-MnE3pnTEsJfmLIVkWyk:b-op8ko4) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/python/test/visualization/test_tensorboard_plugin.py#L191)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

There is `tf.summary.flush`. Would that help?
</blockquote></details>

That flushes the event file. But Python or the OS buffers the .msgpack files and they are not guaranteed to be written to disk before Python exits. [Empirically, they don't get written out if they are only a few hundred bytes, as in these tests].
___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 141 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnB6FJD0GM9V06Gr5Ig:-MnE4llT1cKAGSi5CR9M:b-in0ilc) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L141)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Please add docstring
</blockquote></details>

This is actually @errissa 's code that he accidentally committed here. @errissa when you get some time, can you add docstrings to this file?

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4152)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @errissa, @germanros1987, @sanskar107, @ssheorey, and @yxlao)

___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 489 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnBVpUN-VNVB4ax0Qbc:-MnSK6mC-SyqPgU55v77:bxmp25q) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/python/open3d/visualization/tensorboard_plugin/summary.py#L489)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Yes. A basic example (writes a colored box to summary) for both PyTorch and TF is there since an earlier PR.  Do you want to add to it?
</blockquote></details>

Yes, it would be nice to have an example that can be just copypasted.
___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 141 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnB6FJD0GM9V06Gr5Ig:-MnSRWjDCedURkJuUS1D:b-hlyat6) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L141)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

This is actually @errissa 's code that he accidentally committed here. @errissa when you get some time, can you add docstrings to this file?
</blockquote></details>

Docstring please

**Review by errissa — CHANGES_REQUESTED** [review]
> Reviewed 2 of 17 files at r1, 8 of 12 files at r2, 1 of 7 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4152)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @benjaminum, @errissa, @germanros1987, @sanskar107, @ssheorey, and @yxlao)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 141 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnB6FJD0GM9V06Gr5Ig:-Mnd3WlICWq8weoJ-lRL:b-896fjx) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L141)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Docstring please
</blockquote></details>

Done
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 406 at r5](https://reviewable.io/reviews/isl-org/open3d/4152#-Mnd4FL-6LokzxmtVnFI:-Mnd4FL-6LokzxmtVnFJ:b-mewp6c) ([raw file](https://github.com/isl-org/open3d/blob/aec5ab4da81979665b0b9a339da701b28cbee78e/python/open3d/visualization/tensorboard_plugin/summary.py#L406)):*
> ```Python
>     max_outputs = int(max_outputs)
>     if 'triangle_texture_uvs' in data and 'vertex_texture_uvs' in data:
>         raise ValueError("Please provide only one of triangle_texture_uvs "
> ```

Do you want to raise an error here or just output a warning? The visualizer will prefer the per-vertex texture uvs if both are present but having both present doesn't cause any problems.

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4152)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @benjaminum, @errissa, @germanros1987, @sanskar107, and @yxlao)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 141 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnB6FJD0GM9V06Gr5Ig:-MnijcO01Na15nkWYIOa:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L141)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 489 at r1](https://reviewable.io/reviews/isl-org/open3d/4152#-MnBVpUN-VNVB4ax0Qbc:-MniiqHXDgrT3fO82pAG:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/09d77c36def5bfc87cd39a1f8a81f4a9d58e8a02/python/open3d/visualization/tensorboard_plugin/summary.py#L489)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Yes, it would be nice to have an example that can be just copypasted.
</blockquote></details>

Done.
___
*[python/open3d/visualization/tensorboard_plugin/summary.py, line 406 at r5](https://reviewable.io/reviews/isl-org/open3d/4152#-Mnd4FL-6LokzxmtVnFI:-Mniis5_5rE5PCWiNI7e:b8ftm81) ([raw file](https://github.com/isl-org/open3d/blob/aec5ab4da81979665b0b9a339da701b28cbee78e/python/open3d/visualization/tensorboard_plugin/summary.py#L406)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

Do you want to raise an error here or just output a warning? The visualizer will prefer the per-vertex texture uvs if both are present but having both present doesn't cause any problems.
</blockquote></details>

I think raise an error to reduce user confusion and size of the serialized data. If we allow both, the user will need to check documentation to figure out which one will be actually used. Also, the triangle uvs will waste disk space / read / write time.

**Review by errissa — APPROVED** [review]
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4152)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @benjaminum, @germanros1987, @sanskar107, and @yxlao)

**Review by yxlao — APPROVED** [review]
> Reviewed 2 of 17 files at r1, 6 of 12 files at r2, 5 of 7 files at r3, 1 of 5 files at r4, 4 of 5 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4152)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @benjaminum, @germanros1987, @sanskar107, and @ssheorey)

___
*[cpp/open3d/visualization/visualizer/O3DVisualizer.h, line 126 at r9](https://reviewable.io/reviews/isl-org/open3d/4152#-MnszITa64mCJMWWO4hr:-MnszITb89FegQNOP2sP:bgvqedh) ([raw file](https://github.com/isl-org/open3d/blob/728081cb0cae951293f2400550c3e76430850bb1/cpp/open3d/visualization/visualizer/O3DVisualizer.h#L126)):*
> ```objc
>                      bool is_visible = true);
> 
>     /// Adds a t geometry to the Visualizer, only DrawableGeometries are
> ```

nit: t-geometry
___
*[python/open3d/visualization/tensorboard_plugin/util.py, line 400 at r9](https://reviewable.io/reviews/isl-org/open3d/4152#-Mnt-GVDEOXrc1Rw6i_r:-Mnt-GVDEOXrc1Rw6i_s:bdtb37p) ([raw file](https://github.com/isl-org/open3d/blob/728081cb0cae951293f2400550c3e76430850bb1/python/open3d/visualization/tensorboard_plugin/util.py#L400)):*
> ```Python
> 
> 
> def _u8_float(color):
> ```

nit: `_u8_to_float`
___
*[python/open3d/visualization/tensorboard_plugin/util.py, line 405 at r9](https://reviewable.io/reviews/isl-org/open3d/4152#-Mnt-DBF07uGOGwLrC-T:-Mnt-DBF07uGOGwLrC-U:b3xxupg) ([raw file](https://github.com/isl-org/open3d/blob/728081cb0cae951293f2400550c3e76430850bb1/python/open3d/visualization/tensorboard_plugin/util.py#L405)):*
> ```Python
> 
> def _float_u8(color):
>     return tuple(int(255 * c + 0.5) for c in color)
> ```

nit: `_float_to_u8`
do we need to add 0.5?

**Pull request merged**
