### PR TITLE
Python 3.10

### LINKED ISSUE #4535: Python 3.10 wheel
Hi! As suggested [here](https://github.com/isl-org/Open3D/issues/3983#issuecomment-985825097), I'm opening this issue to track the Python 3.10 wheel availability.

References to dependencies progress regarding Python 3.10 support:
- Tensorflow: https://github.com/tensorflow/tensorflow/issues/52324 ([tf2.8-rc0](https://github.com/tensorflow/tensorflow/releases/tag/v2.8.0-rc0) supports Python 3.10 except on Windows)
- Pytorch: https://github.com/pytorch/pytorch/issues/66424

### PR DESCRIPTION
**Pull request by ssheorey**
- Drop support for EOL Python 3.6 (no PyTorch, TF wheels available)
- PyTorch 1.12 (custom wheels not needed for version >=1.9. See https://github.com/pytorch/pytorch/issues/52663#issuecomment-965600076)
- Tensorflow 2.8.2
- CUDA 11.6 (CUDA 11.3 nvcc causes compile error in tf_ops)
- [Also updated Nvidia drivers on Google cloud GPU VM base image to support CUDA<=11.7]
- CUDNN 8.4
- scipy 1.7.3

Closes https://github.com/isl-org/Open3D/issues/3324
Closes #4535 

TODO: Switch Python version in CI to 3.7 from 3.10 (current) before merging.
Companion Open3D-ML PR https://github.com/isl-org/Open3D-ML/pull/554

Tensorflow 2.9+ switched to _GLIBCXX_USE_CXX11_ABI=1
PyTorch *plans* to from 1.13 (next release).

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5320)

### CODE REVIEW

**Review by benjaminum — COMMENTED** [review]
@ssheorey Did you have time to run the minimal example in #3324 ?

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5320#-:-N7zQaQt-8-elR6O8hqC:b-cvtc4n)* status: 0 of 26 files reviewed, all discussions resolved (waiting on @sanskar107 and @yxlao)

**Review by yxlao — APPROVED** [review]
> Reviewed 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5320)* status: all files reviewed, 3 unresolved discussions (waiting on @sanskar107 and @ssheorey)

___
*[`docker/docker_build.sh` line 85 at r2](https://reviewable.io/reviews/isl-org/open3d/5320#-N81J2OV1997zGmCZzBT:-N81J2OV1997zGmCZzBU:b2ivxup) ([raw file](https://github.com/isl-org/open3d/blob/5e32daab9e55047d8692ed467b8728c4b82dd3f1/docker/docker_build.sh#L85)):*
> ```Shell
> 
> print_usage_and_exit_docker_build() {
> 	echo "$__usage_docker_build"
> ```

Seems like 4-space indentations are replaced with tabs. Shall we keep the 4-space indentation?
___
*[`docker/docker_test.sh` line 61 at r2](https://reviewable.io/reviews/isl-org/open3d/5320#-N81JEVM4wFGQnk4vn7T:-N81JEVM4wFGQnk4vn7U:b-g9opt8) ([raw file](https://github.com/isl-org/open3d/blob/5e32daab9e55047d8692ed467b8728c4b82dd3f1/docker/docker_test.sh#L61)):*
> ```Shell
> 
> print_usage_and_exit_docker_test() {
> 	echo "$__usage_docker_test"
> ```

Same, shall we keep the 4-space indentation?
___
*[`util/ci_utils.sh` line 10 at r2](https://reviewable.io/reviews/isl-org/open3d/5320#-N81JNsj2H5KI5GFBdNP:-N81JNsj2H5KI5GFBdNQ:b-g9opt8) ([raw file](https://github.com/isl-org/open3d/blob/5e32daab9e55047d8692ed467b8728c4b82dd3f1/util/ci_utils.sh#L10)):*
> ```Shell
> DEVELOPER_BUILD="${DEVELOPER_BUILD:-ON}"
> if [[ "$DEVELOPER_BUILD" != "OFF" ]]; then # Validate input coming from GHA input field
> 	DEVELOPER_BUILD="ON"
> ```

Same, shall we keep the 4-space indentation?

**Review by ssheorey — COMMENTED** [review]
Yes, tested with PyTorch 1.9 (CUDA 11.1)  and PyTorch 1.12 (CUDA 11.6). Both work correctly. Test output in #3324  

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5320#-:-N821Ao57UauYDBSPxVa:bz2o0nf)* status: 21 of 27 files reviewed, 3 unresolved discussions (waiting on @sanskar107 and @yxlao)

___
*[`docker/docker_build.sh` line 85 at r2](https://reviewable.io/reviews/isl-org/open3d/5320#-N81J2OV1997zGmCZzBT:-N821Rt31yPxkREXB3NN:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/5e32daab9e55047d8692ed467b8728c4b82dd3f1/docker/docker_build.sh#L85)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Seems like 4-space indentations are replaced with tabs. Shall we keep the 4-space indentation?
</blockquote></details>

Done.
___
*[`docker/docker_test.sh` line 61 at r2](https://reviewable.io/reviews/isl-org/open3d/5320#-N81JEVM4wFGQnk4vn7T:-N821SWbDuAPzWPtL2K1:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/5e32daab9e55047d8692ed467b8728c4b82dd3f1/docker/docker_test.sh#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, shall we keep the 4-space indentation?
</blockquote></details>

Done.
___
*[`util/ci_utils.sh` line 10 at r2](https://reviewable.io/reviews/isl-org/open3d/5320#-N81JNsj2H5KI5GFBdNP:-N821Th16a9L4Cp3M4Up:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/5e32daab9e55047d8692ed467b8728c4b82dd3f1/util/ci_utils.sh#L10)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Same, shall we keep the 4-space indentation?
</blockquote></details>

Done.

**Review by benjaminum — APPROVED** [review]
Perfect!

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5320#-:-N82dsTt-SJyJTUjs67c:b-qn5lbb)* status: 21 of 27 files reviewed, 3 unresolved discussions (waiting on @sanskar107 and @yxlao)

**Pull request merged**
