### PR TITLE
Updated Issues Template

### PR DESCRIPTION
**Pull request by reyanshsolis**
One may check the changes on: https://github.com/reyanshsolis/rey_experimental/issues/new/choose

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4459)

### CODE REVIEW

**Comment by ssheorey** [comment]
Hi @reyanshsolis are you also planning to add a PR template?

**Comment by reyanshsolis** [comment]
> Hi @reyanshsolis are you also planning to add a PR template?

I tried adding one, it is currently not working. Investigating further.

**Comment by ssheorey** [comment]
Hi @reyanshsolis could you also create an analogous PR (issue templates) for the Open3D-ML repo?

**Comment by reyanshsolis** [comment]
> Hi @reyanshsolis could you also create an analogous PR (issue templates) for the Open3D-ML repo?

Sure, once changes in this repo are finalized, I will also make the same for `Open3D-ML` repo. Thanks for the suggestion.

**Comment by yxlao** [comment]
I have pushed some changes to the issues template. LGTM for merging.

**Pull request merged**
