### PR TITLE
MiniVec's constructor shall not call Device's constructor/destructor

### PR DESCRIPTION
**Pull request by yxlao**
## Issue

When I add `Device:::description_`:

```diff
diff --git a/cpp/open3d/core/Device.h b/cpp/open3d/core/Device.h
index d3d400de1..b0d6225f5 100644
--- a/cpp/open3d/core/Device.h
+++ b/cpp/open3d/core/Device.h
@@ -130,6 +130,7 @@ protected:
 protected:
     DeviceType device_type_ = DeviceType::CPU;
     int device_id_ = 0;
+    std::string description_;
 };
```

It results in this cryptic error:

```
[ 96%] Building CUDA object cpp/open3d/t/geometry/kernel/CMakeFiles/tgeometry_kernel.dir/VoxelBlockGridCUDA.cu.o
/home/yixing/repo/Open3D/cpp/open3d/utility/MiniVec.h(49): error: calling a __host__ function("std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(const ::std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)") from a __host__ __device__ function("open3d::core::Device::Device") is not allowed

/home/yixing/repo/Open3D/cpp/open3d/utility/MiniVec.h(49): error: calling a __host__ function("std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()") from a __host__ __device__ function("open3d::core::Device::~Device") is not allowed

2 errors detected in the compilation of "/home/yixing/repo/Open3D/cpp/open3d/t/geometry/kernel/VoxelBlockGridCUDA.cu".
make[3]: *** [cpp/open3d/t/geometry/kernel/CMakeFiles/tgeometry_kernel.dir/build.make:244: cpp/open3d/t/geometry/kernel/CMakeFiles/tgeometry_kernel.dir/VoxelBlockGridCUDA.cu.o] Error 1
```

Somehow, `MiniVec` calls the `Device::~Device()` in a `__host__ __device__` function, where it calls the `~basic_string()', which is not allowed.

More hints:
```
Key=open3d::utility::MiniVec<open3d::t::geometry::kernel::voxel_grid::index_t, 3>, 
Hash=open3d::utility::MiniVecHash<open3d::t::geometry::kernel::voxel_grid::index_t, 3>,
Eq=open3d::utility::MiniVecEq<open3d::t::geometry::kernel::voxel_grid::index_t, 3>
```

## Reason

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5192)

### CODE REVIEW

**Comment by ssheorey** [comment]
@yxlao with update PR and merge.

**Comment by yxlao** [comment]
I think the reason is identified: `StdAllocator` shall not own a `Device` object. 

```cpp
// VoxelBlockGridImpl.h
Key key(x_b, y_b, z_b);
index_t block_buf_idx = cache.Check(x_b, y_b, z_b);
if (block_buf_idx < 0) {
    auto iter = hashmap_impl.find(key);
    if (iter == hashmap_impl.end()) return -1;
    block_buf_idx = iter->second;
    cache.Update(x_b, y_b, z_b, block_buf_idx);
}
```
->

```cpp
InternalStdGPUHashBackend<Key, Hash, Eq> GetImpl() const { return impl_; }
```

->

```cpp
impl_ = InternalStdGPUHashBackend<Key, Hash, Eq>::createDeviceObject(
                this->capacity_,
                InternalStdGPUHashBackendAllocator<Key>(this->device_));
```

Since stdgpu has a hold of the `Device` object, every time it tries to allocate/free, a `Device` object will be constructed and destructed. This causes the issue. The solution is to avoid stdgpu getting a hold of the `Device` object.

https://github.com/isl-org/Open3D/pull/5192/commits/b651f3c5206fbc16334a8f3d916faa481dcac21b fixes the issue, but it is still ugly.

**Comment by yxlao** [comment]
This issue will be ready for review if the CI passes.

**Review by theNded — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ssheorey)

**Pull request merged**
