### PR TITLE
Rename pipelines and add new reconstruction system basic config

### PR DESCRIPTION
**Pull request by theNded**
- Rename `VoxleHashing` -> `DenseSLAM`, `voxelhashing` namespace -> `slam`
- Provide pybind for dense SLAM
- Provide python SLAM example (no gui) and corresponding upgraded configuration pipeline for further refactorization.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3892)

### CODE REVIEW

**Review by reyanshsolis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3892)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/pybind/t/pipelines/slam/slam.cpp, line 37 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh0470373MIEFEtUyAS:-Mh0470373MIEFEtUyAT:b69cs5f) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/cpp/pybind/t/pipelines/slam/slam.cpp#L37)):*
> ```cpp
> 
> void pybind_slam_model(py::module &m) {
>     // TODO: doc
> ```

may we add some basic doc? 

As there are many common arguments we may add 
`static const std::unordered_map<std::string, std::string>  map_shared_argument_docstrings`, 
and use  `docstring::FunctionDocInject(m, "function_name", map_shared_argument_docstrings);`
                                 
also some basic brief about the params such as `block_count`, `block_resolution`. 
___
*[cpp/pybind/t/pipelines/slam/slam.cpp, line 82 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh04P0a-qdpxBK3reUA:-Mh04P0a-qdpxBK3reUB:b9lq4zh) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/cpp/pybind/t/pipelines/slam/slam.cpp#L82)):*
> ```cpp
> 
>     model.def_readwrite("voxel_grid", &Model::voxel_grid_);
>     model.def_readwrite("T_frame_to_world", &Model::T_frame_to_world_);
> ```

suggestion (not sure):
can we use `transform_frame_to_world` or just `global_transform` instead of this ? 

generally when we use only `transform` we refer to `frame_to_world`, so just using `transform` and adding docstrings might also work, but it's better to be explicit. 
___
*[cpp/pybind/t/pipelines/slam/slam.cpp, line 87 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh04Rp-7-ncUAqoQwc_:-Mh04Rp-7-ncUAqoQwca:b15wgs6) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/cpp/pybind/t/pipelines/slam/slam.cpp#L87)):*
> ```cpp
> 
> void pybind_slam_frame(py::module &m) {
>     // TODO: doc
> ```

some basic brief maybe?
___
*[examples/cpp/DenseSLAMGUI.cpp, line 265 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh04hti8AR1tCLd0Zjc:-Mh04hti8AR1tCLd0Zjd:bhvcmbx) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/cpp/DenseSLAMGUI.cpp#L265)):*
> ```cpp
>                                     camera::PinholeCameraTrajectory>();
>                             float voxel_size = prop_values_.voxel_size;
>                             this->model_ =
> ```

I think an example is a good reference start point for many of the users, so if possible may you please share your insights about the parameter settings, for example: why are we taking `sdf_trunc` as `voxel_size * 6`, it that generally a good guess?

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 16 of 20 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3892)* status: 17 of 20 files reviewed, 13 unresolved discussions (waiting on @theNded)

___
*[examples/python/new_reconstruction_system/config.py, line 7 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3zkgK09Zw6jnelZhj:-Mh3zkgK09Zw6jnelZhk:b-hllb2o) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/config.py#L7)):*
> ```Python
> 
> 
> def add_arguments(parser):
> ```

See comments in the main function. We can refactor this into a class.
___
*[examples/python/new_reconstruction_system/config.py, line 110 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3x0f487xKwjtt9KQE:-Mh3x0f52majTpUCEUm-:b3t3mr3) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/config.py#L110)):*
> ```Python
> 
> def get_config(args):
>     d = edict(vars(args))
> ```

Can we right to `args` directly, e.g. `args.new_key=new_value`? If we can do that, we can avoid `edict`.
___
*[examples/python/new_reconstruction_system/config.py, line 138 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3tvGR9MRTtlYEnIUs:-Mh3tvGR9MRTtlYEnIUt:bwqcjyb) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/config.py#L138)):*
> ```Python
> 
> if __name__ == '__main__':
>     # Priority: command line > loaded yaml > default config
> ```

`# Priority: command line > custom config file > default config file`

"loaded yaml" doesn't tell say it's the default or custom one, it also doesn't tell it should be specified by `--config`.
___
*[examples/python/new_reconstruction_system/default_config.yml, line 27 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3asQh6S96V43UXtyV:-Mh3asQh6S96V43UXtyW:b-4tzenx) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/default_config.yml#L27)):*
> ```YAML
> block_count: 40000
> surface_weight_thr: 3.0
> ```

nit: empty line remove
___
*[examples/python/new_reconstruction_system/default_intrinsics.json, line 2 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3aolK4atzYkeYmYSy:-Mh3aolK4atzYkeYmYSz:b-80thne) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/default_intrinsics.json#L2)):*
> ```JSON
> {
> 	"width" : 640,
> ```

nit: tab to space
___
*[examples/python/new_reconstruction_system/dense_slam.py, line 5 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3bLSq0jW9i3hqgA-q:-Mh3bLSq0jW9i3hqgA-r:b-ttxchq) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/dense_slam.py#L5)):*
> ```Python
> # See license file or visit www.open3d.org for details
> 
> # examples/python/reconstruction_system/integrate_scene.py
> ```

update name (or, i think we can just remove this)
___
*[examples/python/new_reconstruction_system/dense_slam.py, line 18 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3tKXDEZAJ4to7Yv7n:-Mh3tKXE5_kfxkbUW-5J:b-cb0qo9) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/dense_slam.py#L18)):*
> ```Python
> 
> 
> def slam(depth_file_names, color_file_names, intrinsic, config, mode='scene'):
> ```

`mode` not used?
___
*[examples/python/new_reconstruction_system/dense_slam.py, line 64 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3u_gEDRfR3DAMZ3xY:-Mh3u_gEDRfR3DAMZ3xZ:b-4aaay3) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/dense_slam.py#L64)):*
> ```Python
> 
> if __name__ == '__main__':
>     parser = configargparse.ArgParser(default_config_files=[
> ```

The logic here seems to be convoluted. For example, the user needs to know:
1. the class (`ArgParser`), 
2. some separate standalone functions (`add_arguments`, `get_config`), and
3. how to call them in particular order. 

Can we simplify this by creating our one wrapper class, and the user only has to deal with this wrapper class? The `config.py` is specific to the reconstruction system, so perhaps we can make a config class just for the reconstruction system. Here's one possible design that only needs 3 lines of code for the main function:

```python
# ReconstructionArgParser comes with all reconstruction args
# That is, it does add_arguments() internally.
# Since add_arguments() was already hidden from the main function,
# it may be better to put that inside a class.
parser = ReconstructionArgParser(default_config_file)  

# We also allow user to specify custom args
# add() will be forwarded to configargparse.ArgParser.add()
# e.g. forward it by: 
# def add(*args, **kwargs):
#     self.arg_parser.add(*args, **kwargs)
parser.add("--config", is_config_file=True, help="xxx")
parser.add("--some_other_config", type=int, default=xxx, xxx=xxx)

# Like how we use the traditional arg parse class.
# The logics in `get_config()` can be executed here internally
args = parser.parse_args()
```
___
*[cpp/open3d/t/pipelines/slam/Model.cpp, line 82 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3a5LX0whVC24edMRF:-Mh3a5LY2zV01fHsPsso:b-60rkgm) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/cpp/open3d/t/pipelines/slam/Model.cpp#L82)):*
> ```cpp
>                 "color", core::Tensor({raycast_frame.GetHeight(),
>                                        raycast_frame.GetWidth(), 3},
>                                       core::Dtype::Float32, core::Device()));
> ```

`core::Float32` is the new shortcut

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3892)* status: 13 of 20 files reviewed, 10 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/pybind/t/pipelines/slam/slam.cpp, line 37 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh0470373MIEFEtUyAS:-Mh5VFKu16vC7BASIqmI:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/cpp/pybind/t/pipelines/slam/slam.cpp#L37)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

may we add some basic doc? 

As there are many common arguments we may add 
`static const std::unordered_map<std::string, std::string>  map_shared_argument_docstrings`, 
and use  `docstring::FunctionDocInject(m, "function_name", map_shared_argument_docstrings);`
                                 
also some basic brief about the params such as `block_count`, `block_resolution`. 
</blockquote></details>

Done.
___
*[cpp/pybind/t/pipelines/slam/slam.cpp, line 87 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh04Rp-7-ncUAqoQwc_:-Mh5ItXiDm0JyNvQFBsF:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/cpp/pybind/t/pipelines/slam/slam.cpp#L87)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

some basic brief maybe?
</blockquote></details>

Done.
___
*[examples/python/new_reconstruction_system/config.py, line 7 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3zkgK09Zw6jnelZhj:-Mh5aGQWBr9J7Nhn2kaW:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/config.py#L7)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

See comments in the main function. We can refactor this into a class.
</blockquote></details>

Done.
___
*[examples/python/new_reconstruction_system/config.py, line 110 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3x0f487xKwjtt9KQE:-Mh5aFcj85la2DONmlyV:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/config.py#L110)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Can we right to `args` directly, e.g. `args.new_key=new_value`? If we can do that, we can avoid `edict`.
</blockquote></details>

Done.
___
*[examples/python/new_reconstruction_system/config.py, line 138 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3tvGR9MRTtlYEnIUs:-Mh5__W8A7QEQ2yMx54l:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/config.py#L138)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`# Priority: command line > custom config file > default config file`

"loaded yaml" doesn't tell say it's the default or custom one, it also doesn't tell it should be specified by `--config`.
</blockquote></details>

Done.
___
*[examples/python/new_reconstruction_system/default_intrinsics.json, line 2 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3aolK4atzYkeYmYSy:-Mh5W3sR-77K9hIpmLZ4:b-3qjjwl) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/default_intrinsics.json#L2)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: tab to space
</blockquote></details>

This is taken from test_data.
___
*[examples/python/new_reconstruction_system/dense_slam.py, line 5 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3bLSq0jW9i3hqgA-q:-Mh5VwLXAiolU9hKgzt1:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/dense_slam.py#L5)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

update name (or, i think we can just remove this)
</blockquote></details>

Done.
___
*[examples/python/new_reconstruction_system/dense_slam.py, line 18 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3tKXDEZAJ4to7Yv7n:-Mh5XAL_124bcwqOTNs4:b-ptj3hf) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/dense_slam.py#L18)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`mode` not used?
</blockquote></details>

Reserved for make_fragments. Removed for now.
___
*[examples/python/new_reconstruction_system/dense_slam.py, line 64 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3u_gEDRfR3DAMZ3xY:-Mh5_VPH1--zb7uB5ePp:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/examples/python/new_reconstruction_system/dense_slam.py#L64)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

The logic here seems to be convoluted. For example, the user needs to know:
1. the class (`ArgParser`), 
2. some separate standalone functions (`add_arguments`, `get_config`), and
3. how to call them in particular order. 

Can we simplify this by creating our one wrapper class, and the user only has to deal with this wrapper class? The `config.py` is specific to the reconstruction system, so perhaps we can make a config class just for the reconstruction system. Here's one possible design that only needs 3 lines of code for the main function:

```python
# ReconstructionArgParser comes with all reconstruction args
# That is, it does add_arguments() internally.
# Since add_arguments() was already hidden from the main function,
# it may be better to put that inside a class.
parser = ReconstructionArgParser(default_config_file)  

# We also allow user to specify custom args
# add() will be forwarded to configargparse.ArgParser.add()
# e.g. forward it by: 
# def add(*args, **kwargs):
#     self.arg_parser.add(*args, **kwargs)
parser.add("--config", is_config_file=True, help="xxx")
parser.add("--some_other_config", type=int, default=xxx, xxx=xxx)

# Like how we use the traditional arg parse class.
# The logics in `get_config()` can be executed here internally
args = parser.parse_args()
```
</blockquote></details>

Done.
___
*[cpp/open3d/t/pipelines/slam/Model.cpp, line 82 at r2](https://reviewable.io/reviews/isl-org/open3d/3892#-Mh3a5LX0whVC24edMRF:-Mh5BuDj4yzOwOeUTtPa:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/bd671286cd2819e360314449576055e4c386faed/cpp/open3d/t/pipelines/slam/Model.cpp#L82)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`core::Float32` is the new shortcut
</blockquote></details>

Done.

**Review by yxlao — APPROVED** [review]
> Reviewed 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3892)* status: 16 of 20 files reviewed, 7 unresolved discussions (waiting on @reyanshsolis and @yxlao)

**Review by reyanshsolis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3892)* status: 16 of 20 files reviewed, 5 unresolved discussions (waiting on @yxlao)

**Comment by guyuezuntinggithub** [comment]
@yxlao The DenseSLAM.cpp set device "CPU:0" , can I set It to GPU by changing the string to "GPU:0"?

**Pull request merged**
