### PR TITLE
robust plane detection

### PR DESCRIPTION
**Pull request by plusk01**
This adds a plane / planar patch detection algorithm. It is an implementation of

> AMC Araújo and MM Oliveira, “A robust statistics approach for plane detection in unorganized point clouds,” Pattern Recognition, 2020. ([**info**](https://www.inf.ufrgs.br/~oliveira/pubs_files/RE/RE.html))

It is a reimplementation of [my fork](https://github.com/plusk01/pointcloud-plane-segmentation) of the [author's original code](https://github.com/abnerrjo/PlaneDetection). The algorithm is accessible as

```c++
std::vector<std::shared_ptr<PlanarPatch>> PointCloud::DetectPlanarPatches(
            double normal_similarity = 0.5,
            double coplanarity = 0.25,
            double outlier_ratio = 0.75,
            double min_plane_edge_length = 0.0,
            size_t min_num_points = 0,
            const geometry::KDTreeSearchParam &search_param =
                    geometry::KDTreeSearchParamKNN()) const;
```
I have also added a `geometry::PlanarPatch` to allow visualization of detected planes / patches. Python bindings added / updated.

image
image

@abnerrjo may be interested in reviewing

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/2868)

### CODE REVIEW

**Comment by plusk01** [comment]
thanks for the review @theNded - re `TriangleMeshFactor.cpp`: currently `PlanarPatch` subclasses `Geometry3D` directly, allowing `PlanarPatch` objects to be visualized by specialized renderers, shaders, etc. I believe subclassing `PlanarPatch` in this way is useful and makes the API more intuitive. On the other hand, code reuse is nice - especially for visualization. It seems a path forward is to have `PlanarPatch` subclass `MeshBase`? Is this what you had in mind or something else?

**Comment by martinakos** [comment]
Thanks for the contribution. I've tested your PR locally and it works well. Just one request. 
I can visualize the PlanarPatches with the open3d::visualization::Visualizer / open3d.visualization.draw_geometries() but I can't with the  open3d::visualization::visualizer::O3DVisualizer / open3d.visualization.draw(). I would like to use the second as it supports materials. I'm particularly interested in transparency. So that you can inspect the PlanarPatches and the underlying point clouds easily.

**Comment by plusk01** [comment]
I've removed the `geometry::PlanarPatch` type and its associated geometry-specific rendering functionality. Now, the `PointCloud::DetectPlanarPatches` function returns a `std::vector<Eigen::Matrix<double,12, 1>>` -- a list of planar patch parameters. These parameters can be used with the newly implemented `TriangleMesh::CreatePlanarPatch` factory function. @theNded was this what you were thinking?

**Comment by plusk01** [comment]
@martinakos  -- try the code now. I'm leveraging the standard `TriangleMesh` functionality to create the planar patch visualization, so it should support your desired functionality

**Comment by plusk01** [comment]
using `OrientedBoundingBox` to represent planar patches

**Comment by benjaminum** [comment]
@theNded have the changes to the visualization you requested been addressed?

**Review by theNded — APPROVED** [review]
> Reviewed 20 of 31 files at r2, 1 of 10 files at r3, 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/2868)* status: 22 of 31 files reviewed, 5 unresolved discussions (waiting on @benjaminum and @plusk01)

**Comment by wyfSunflower** [comment]
failed to pass a filename with type of std::string  to io::ReadPointCloud. code is:
`    const string filename = "D:\\BaiduNetdiskDownload\\open3d_downloads\\ICP\\Civil.pcd";//必须指定类型，auto会给你搞成char* "D:\\BaiduNetdiskDownload\\open3d_downloads\\ICP\\Civil.pcd"   "D:\\Qt\\bunny\\bunny\\reconstruction\\bun_zipper.ply"
    auto demo_data = data::DemoCropPointCloud();
    auto cloud_ptr = std::make_shared<geometry::PointCloud>();
    bool result = io::ReadPointCloud(filename, *cloud_ptr);
    cout << "result = " << result << ", fn = " << filename << endl;
    if (result) {// demo_data.GetPointCloudPath()  argv[1]   file_name  , { "ply", false, false, false }
        utility::LogInfo("Successfully read {}\n", filename);// argv[1]
        cout << __LINE__ << " I'm here\n" << filename << endl;
    }
    else {
        utility::LogWarning("Failed to read {}\n\n", filename);// argv[1]
        cout << __LINE__ << " I'm here\n"<<filename<<endl;
        //return 1;
    }`
 - ## it throw such error with filename is empty:
[Open3D WARNING] [DrawGeometries] Failed adding geometry.
[Open3D WARNING] [DrawGeometries] Possibly due to bad geometry or wrong geometry type.
[Open3D INFO] Open3D 0.17.0
[Open3D INFO]
[Open3D INFO]
[Open3D INFO]
[Open3D INFO]
[Open3D INFO]
[Open3D INFO]
25 no input
[Open3D WARNING] Read geometry::PointCloud failed: unknown file extension for  (format: ).
result = 0, fn = D:\BaiduNetdiskDownload\open3d_downloads\ICP\Civil.pcd
[Open3D WARNING]
43 I'm here
D:\BaiduNetdiskDownload\open3d_downloads\ICP\Civil.pcd

 - ## file is exist
D:\Qt\open3d_demo\build\Debug>dir d:\BaiduNetdiskDownload\open3d_downloads\ICP\
 驱动器 D 中的卷是 系统
 卷的序列号是 D985-D152

 d:\BaiduNetdiskDownload\open3d_downloads\ICP 的目录

2023/06/03  16:18    <DIR>          .
2023/06/03  16:18    <DIR>          ..
2023/06/03  16:18        22,037,056 Civil.pcd
               1 个文件     22,037,056 字节
               2 个目录 904,786,071,552 可用字节

**Comment by wyfSunflower** [comment]
I used the binary package archive which link is [https://storage.googleapis.com/open3d-releases-master/devel/open3d-devel-windows-amd64-0.17.0+e892d5b-dbg.zip](url)

**Comment by plusk01** [comment]
hi @wyfSunflower it seems like your issue is with the file and has nothing to do with this pull request - please create a new issue or ask a question on the forum or discord as per https://github.com/isl-org/Open3D#communication-channels.

You should check your code with a file that is known to work and also inspect your file in another program to make sure the data is valid.

**Comment by wyfSunflower** [comment]
ok, but I run success when on ubuntu 2022 python 3.10 version with the same file

**Pull request merged**
