### PR TITLE
Refactor RPC serialization

### PR DESCRIPTION
**Pull request by benjaminum**
Changes in this PR
-added more fine grained functions for message generation and conversion
-pass msgpack object handle instead of object to processing functions
-add function for extracting geometry from a SetMeshData message buffer
-hide hidden classes in io.rpc in the documentation
-split receiving and processing messages into two separate classes
-set linger time for sockets to 0

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3821)

### CODE REVIEW

**Comment by benjaminum** [comment]
Example for creating a triangle mesh via the rpc serialization
```python
import open3d as o3d
import numpy as np

verts = np.random.rand(100,3).astype(np.float32)
tris = np.random.randint(0,100, size=[100,3]).astype(np.int32)

bc = o3d.io.rpc.BufferConnection()
o3d.io.rpc.set_mesh_data(verts, faces=tris, path='test/path', time=123, connection=bc)

ans = o3d.io.rpc.get_data_from_set_mesh_data_buffer(bc.get_buffer())

print(ans)
```

**Review by ssheorey — CHANGES_REQUESTED** [review]
Some overall comments:
- Can you add C++ unit tests for the new functionality?
Perhaps in future PRs:
- Being able to skip storing the primary keys (*_positions and *_indices) would be useful for de-deduplication. There are several places where the primary key presence and shape are checked, so this may be tricky. Perhaps (de)serializing a `TensoMap` is a better option in that case, instead of a specific Geometry type.

> Reviewed 2 of 10 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3821#-:-MhPkQ0-2D00-CgsiU6u:bae9axc)* status: all files reviewed, 15 unresolved discussions (waiting on @benjaminum)

___
*[cpp/open3d/io/rpc/MessageProcessorBase.cpp, line 61 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQR-vU8Fbm1TpFqf8n:-MhQR-vU8Fbm1TpFqf8o:bqmyn6z) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageProcessorBase.cpp#L61)):*
> ```cpp
>         const messages::Request& req,
>         const messages::SetMeshData& msg,
>         const msgpack::object_handle& obj) {
> ```

Are all the function bodies the same? Can we use a template here then?
___
*[cpp/open3d/io/rpc/Messages.h, line 120 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQHHfo5ceL8oqgtr5U:-MhQHHfo5ceL8oqgtr5V:br4dkz) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/Messages.h#L120)):*
> ```objc
> ///       dtype=np.dtype(dic['type'])).reshape(dic['shape'])
> ///
> struct Array {
> ```

Making this a subclass of Tensor (composition should work too) may simplify some operations (eg: checkshape, convert to tensor, etc.)
___
*[cpp/open3d/io/rpc/Messages.h, line 256 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPoT1s4FWoxHgdNcPu:-MhPoT1s4FWoxHgdNcPv:b-37nks0) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/Messages.h#L256)):*
> ```objc
>     /// this field is empty Open3D will infer the type based on the presence of
>     /// lines and faces.
>     std::string o3d_type;
> ```

Should this be an `enum`?
___
*[cpp/open3d/io/rpc/Messages.h, line 278 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPqUvnAxPBnV2Vzn-6:-MhPqUvnAxPBnV2Vzn-7:b-2auck3) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/Messages.h#L278)):*
> ```
> veertices
> ```
typo
___
*[cpp/open3d/io/rpc/Messages.h, line 334 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPr0WeEzEjFVK6O7Oc:-MhPr0WeEzEjFVK6O7Od:b-e4117w) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/Messages.h#L334)):*
> ```objc
>     }
> 
>     bool CheckO3DType(std::string& errstr) const {
> ```

`enum` o3d_type will simplify this check.
___
*[cpp/open3d/io/rpc/MessageUtils.h, line 82 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQJCCN-nyQdl66vxus:-MhQJCCOB03dyhEf6JfS:bl0x2k1) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.h#L82)):*
> ```objc
> 
> std::shared_ptr<zmq::message_t> CreateStatusOKMsg();
> ```

See comment above about making Array a subclass of Tensor (or contain a Tensor). This should make the conversions simple. I think the keep-alive requirement may also go away.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 157 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQVpK-2gxRPtic0-K-:-MhQVpK-2gxRPtic0-K0:brgqvtg) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L157)):*
> ```cpp
> }
> 
> std::shared_ptr<t::geometry::Geometry> MeshDataToGeometry(
> ```

`static` ? Also any other functions that are not used outside this file.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 165 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQPkmiBNRwU4Cc633a:-MhQPkmj0GskEdjwt0a_:b-eghks7) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L165)):*
> ```cpp
>             if (mesh_data.faces.CheckShape({-1, 3}, errstr)) {
>                 std::shared_ptr<t::geometry::TriangleMesh> mesh(
>                         new t::geometry::TriangleMesh());
> ```

`make_shared` is simpler.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 181 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQRGHG7HQbEe1f7T7K:-MhQRGHG7HQbEe1f7T7L:b-2pda15) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L181)):*
> ```cpp
>             }
>         } else if (mesh_data.o3d_type == "LineSet" ||
>                    mesh_data.lines.CheckNonEmpty()) {
> ```

`LineSet` PR is merged.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 206 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQTQEO4f04-TUqKXFK:-MhQTQEO4f04-TUqKXFL:b-s25md9) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L206)):*
> ```cpp
> 
> std::tuple<messages::MeshData, std::vector<core::Tensor>>
> TriangleMeshToMeshData(const t::geometry::TriangleMesh& trimesh) {
> ```

Having a single name `GeometryToMeshData()` with different overloads for geometry types will be easier to use.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 212 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQS0hh7jORXEdq6_Y5:-MhQS0hh7jORXEdq6_Y6:bom4fci) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L212)):*
> ```cpp
>     // vertices
>     auto vertex_attributes = trimesh.GetVertexAttr();
>     // TODO switch to "positions" after the primary key has changed.
> ```

Primary keys are updated now.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 286 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQUDSwEAQt8yuAbY-S:-MhQUDSwEAQt8yuAbY-T:bglve5c) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L286)):*
> ```cpp
> 
> std::tuple<std::string, double, std::shared_ptr<t::geometry::Geometry>>
> GetDataFromSetMeshDataBuffer(std::string& data) {
> ```

Can we simplify the name? eg: `DataBufferToMetaGeometry()`
___
*[cpp/open3d/visualization/visualizer/GuiVisualizer.h, line 46 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQZil1ABmAUOpziqYd:-MhQZil1ABmAUOpziqYe:b-714ylc) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/visualization/visualizer/GuiVisualizer.h#L46)):*
> ```objc
> }
> 
> class GuiVisualizer : public gui::Window {
> ```

Add doxygen docs for class and functions.
___
*[cpp/pybind/io/rpc.cpp, line 200 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPk0F22o6qrnVhYqL0:-MhPk0F22o6qrnVhYqL1:b-omogip) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/pybind/io/rpc.cpp#L200)):*
> ```cpp
>             });
> 
>     m.def("get_data_from_set_mesh_data_buffer",
> ```

This name is awkward. Can we rename to `data_buffer_to_meta_geometry` or similar?
___
*[cpp/open3d/io/rpc/MessageProcessorBase.h, line 71 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPo3YJEyEc0Ov5MWx0:-MhPo3YJEyEc0Ov5MWx1:btes3wg) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageProcessorBase.h#L71)):*
> ```objc
>     /// \param msg  The message to be processed
>     ///
>     /// \param obj  The object from which the \p msg was unpacked. Can be
> ```

Handle to the object....

**Review by benjaminum — COMMENTED** [review]
- I added a python unit test which covers the new functionality.

- We should allow partial data. I am bit undecided about removing the checks completely. 
  - Pro removing
    - The receiver has to interpret and check the data anyway.
    - Simpler code on the serialization side
  - Contra
    - Immediate feedback before sending/writing data.
    - Only the receiving/reading side can report problems. Data must be sent first.

What do you think @ssheorey ?

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3821#-:-MhYeUVQ-utp6bOyaDdW:b-yhn71m)* status: 14 of 23 files reviewed, 15 unresolved discussions (waiting on @ssheorey)

___
*[cpp/open3d/io/rpc/MessageProcessorBase.cpp, line 61 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQR-vU8Fbm1TpFqf8n:-MhYca7R087be7SSgyub:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageProcessorBase.cpp#L61)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Are all the function bodies the same? Can we use a template here then?
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/Messages.h, line 120 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQHHfo5ceL8oqgtr5U:-MhYcbA7CFa_pZsdKS4P:bpdaibi) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/Messages.h#L120)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Making this a subclass of Tensor (composition should work too) may simplify some operations (eg: checkshape, convert to tensor, etc.)
</blockquote></details>

Done. Kept the operations because Array can reference raw pointers.
___
*[cpp/open3d/io/rpc/Messages.h, line 256 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPoT1s4FWoxHgdNcPu:-MhYcrrS1LXKKpPHqa82:b8wtka1) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/Messages.h#L256)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Should this be an `enum`?
</blockquote></details>

Sort of but it is implemented as a string to make it simple to create messages outside of o3d. I added helper functions for setting and checking the value.
___
*[cpp/open3d/io/rpc/Messages.h, line 278 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPqUvnAxPBnV2Vzn-6:-MhYdJbm5rA3V3cyaim1:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/Messages.h#L278)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> veertices
> ```
typo
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/Messages.h, line 334 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPr0WeEzEjFVK6O7Oc:-MhYdMSN6Mn82JlF1T9g:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/Messages.h#L334)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`enum` o3d_type will simplify this check.
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/MessageUtils.h, line 82 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQJCCN-nyQdl66vxus:-MhYdNvp964ZniOkc_2d:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.h#L82)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

See comment above about making Array a subclass of Tensor (or contain a Tensor). This should make the conversions simple. I think the keep-alive requirement may also go away.
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 157 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQVpK-2gxRPtic0-K-:-MhYdSaI7r_dh3dL2Iiw:bz22vnv) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L157)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`static` ? Also any other functions that are not used outside this file.
</blockquote></details>

Don't get this one.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 165 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQPkmiBNRwU4Cc633a:-MhYdYFp3g0BdPw4OAO7:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L165)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`make_shared` is simpler.
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 181 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQRGHG7HQbEe1f7T7K:-MhYdYzY4ut_xcn-jAUX:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L181)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`LineSet` PR is merged.
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 206 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQTQEO4f04-TUqKXFK:-MhYd_5e9EwJkhpE67SM:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L206)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Having a single name `GeometryToMeshData()` with different overloads for geometry types will be easier to use.
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 212 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQS0hh7jORXEdq6_Y5:-MhYd_jY0iBi4AjY930A:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L212)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Primary keys are updated now.
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 286 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQUDSwEAQt8yuAbY-S:-MhYdd5M0aFZNUcZs19f:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L286)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we simplify the name? eg: `DataBufferToMetaGeometry()`
</blockquote></details>

Done.
___
*[cpp/open3d/visualization/visualizer/GuiVisualizer.h, line 46 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQZil1ABmAUOpziqYd:-MhYdfM7DjGvhHJ7vjFq:b2o6w0r) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/visualization/visualizer/GuiVisualizer.h#L46)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add doxygen docs for class and functions.
</blockquote></details>

GuiVisualizer and O3DVisualizer will be merged in #3431 . Adding the missing docstrings would make more sense in that PR. I will add a comment to the PR.
___
*[cpp/pybind/io/rpc.cpp, line 200 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPk0F22o6qrnVhYqL0:-MhYeLyy7ck87fXPrg-B:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/pybind/io/rpc.cpp#L200)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

This name is awkward. Can we rename to `data_buffer_to_meta_geometry` or similar?
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/MessageProcessorBase.h, line 71 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhPo3YJEyEc0Ov5MWx0:-MhYcZO50gqqKAidJtBs:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageProcessorBase.h#L71)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Handle to the object....
</blockquote></details>

Done.

**Review by ssheorey — APPROVED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3821)* status: 15 of 23 files reviewed, 4 unresolved discussions (waiting on @benjaminum and @ssheorey)

___
*[cpp/open3d/io/rpc/Messages.h, line 286 at r3](https://reviewable.io/reviews/isl-org/open3d/3821#-MhZ_4wN-yKp7zReAufg:-MhZ_4wN-yKp7zReAufh:b9ol45t) ([raw file](https://github.com/isl-org/open3d/blob/e7f5fde9ca75eab828e8969bf701c363fbe93c69/cpp/open3d/io/rpc/Messages.h#L286)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     Array vertices;
>     /// stores arbitrary attributes for each vertex, hence the first dim must
>     /// be num_verts
>     std::map<std::string, Array> vertex_attributes;
> ```
</details>

[nit] For consistency with tGeometry types, we can keep `vertex_attr_["positions"]` instead of a separate `vertices` `Array`. Similar for `face_attr_["indices"]` and `line_attr_["indices"]` 
___
*[cpp/open3d/io/rpc/MessageUtils.h, line 111 at r3](https://reviewable.io/reviews/isl-org/open3d/3821#-MhZUSZMBJklyWLMjsOw:-MhZUSZMBJklyWLMjsOx:brc46jj) ([raw file](https://github.com/isl-org/open3d/blob/e7f5fde9ca75eab828e8969bf701c363fbe93c69/cpp/open3d/io/rpc/MessageUtils.h#L111)):*
> ```objc
> messages::MeshData GeometryToMeshData(const t::geometry::PointCloud& pcd);
> 
> /// Creates MeshData from a LinSet. This function returns the MeshData
> ```

typo: LineSet
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 157 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQVpK-2gxRPtic0-K-:-MhZUzIa--sQMD9NdCd2:b-vhcwx) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L157)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Don't get this one.
</blockquote></details>

Internal Open3D functions that we don't expect or want users to use directly should  use internal linkage. This may be a good candidate for either `static` (only available for use within this file) or `OPEN3D_LOCAL` (only available for use within the Open3D DSO). I think we use this one only through `DataBufferToMetaGeometry`.
___
*[python/test/io/rpc/test_serialization.py, line 42 at r3](https://reviewable.io/reviews/isl-org/open3d/3821#-MhZbUed-gYMNoPzkPWc:-MhZbUed-gYMNoPzkPWd:b-nugrm0) ([raw file](https://github.com/isl-org/open3d/blob/e7f5fde9ca75eab828e8969bf701c363fbe93c69/python/test/io/rpc/test_serialization.py#L42)):*
> ```Python
>         return o3d.io.rpc.data_buffer_to_meta_geometry(bc.get_buffer())
> 
>     rng = np.random.RandomState(123)
> ```

The pytest randomly plugin sets Numpy RNG state based on time. Reproducible results can be obtained through a command line argument. We should not set the RNG state inside tests to benefit from the test randomization. [Setting RNG state may also affect tests that run after this one].

**Review by ssheorey — COMMENTED** [review]
From a single responsibility perspective, it's sufficient for serialization to ensure that it's serializing what was given to it and deserializing it back identically. Validation beyond this should be the responsibilty of the caller, i.e. the sending side caller and the receiving side caller.

If we do decide to keep the extra validation, we can support the partial data use case by providing serialization for `TensorMap` directly.

[nit] Some documentation related warnings:
```
/home/runner/work/Open3D/Open3D/docs/python_api/open3d.io.rpc.rst.rst:16: WARNING: autosummary: failed to import get_data_from_set_mesh_data_buffer
/home/runner/work/Open3D/Open3D/docs/python_api/open3d.io.rpc.rst:28: WARNING: toctree contains reference to nonexisting document 'python_api/open3d.io.rpc.get_data_from_set_mesh_data_buffer'
docstring of open3d.io.rpc.set_mesh_data:18: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of open3d.io.rpc.set_mesh_data:27: WARNING: Block quote ends without a blank line; unexpected unindent.
...
```

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3821#-:-MhZfr7EC_tLyHc0Eajn:b-g54epr)* status: 15 of 23 files reviewed, 4 unresolved discussions (waiting on @benjaminum and @ssheorey)

**Review by benjaminum — COMMENTED** [review]
I will address this in another PR. doc problem should be fixed now.

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3821#-:-Mh_KrxiDge30f2fuUl-:b-8p6tp7)* status: 14 of 23 files reviewed, 4 unresolved discussions (waiting on @ssheorey)

___
*[cpp/open3d/io/rpc/Messages.h, line 286 at r3](https://reviewable.io/reviews/isl-org/open3d/3821#-MhZ_4wN-yKp7zReAufg:-Mh_AAJC5SpTUOl-fThE:b-wh1hol) ([raw file](https://github.com/isl-org/open3d/blob/e7f5fde9ca75eab828e8969bf701c363fbe93c69/cpp/open3d/io/rpc/Messages.h#L286)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>     Array vertices;
>     /// stores arbitrary attributes for each vertex, hence the first dim must
>     /// be num_verts
>     std::map<std::string, Array> vertex_attributes;
> ```
[nit] For consistency with tGeometry types, we can keep `vertex_attr_["positions"]` instead of a separate `vertices` `Array`. Similar for `face_attr_["indices"]` and `line_attr_["indices"]` 
</blockquote></details>

I know, it is a decision to keep messages simple if only a minimal set of features is used.
___
*[cpp/open3d/io/rpc/MessageUtils.h, line 111 at r3](https://reviewable.io/reviews/isl-org/open3d/3821#-MhZUSZMBJklyWLMjsOw:-Mh_EhFE5RxhwwcTpzN2:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/e7f5fde9ca75eab828e8969bf701c363fbe93c69/cpp/open3d/io/rpc/MessageUtils.h#L111)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

typo: LineSet
</blockquote></details>

Done.
___
*[cpp/open3d/io/rpc/MessageUtils.cpp, line 157 at r2](https://reviewable.io/reviews/isl-org/open3d/3821#-MhQVpK-2gxRPtic0-K-:-Mh_EiMyE7F3F1sUcUm5:b-nh059o) ([raw file](https://github.com/isl-org/open3d/blob/c85373ac99846a0f2b983b87b7beeec06e65986a/cpp/open3d/io/rpc/MessageUtils.cpp#L157)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Internal Open3D functions that we don't expect or want users to use directly should  use internal linkage. This may be a good candidate for either `static` (only available for use within this file) or `OPEN3D_LOCAL` (only available for use within the Open3D DSO). I think we use this one only through `DataBufferToMetaGeometry`.
</blockquote></details>

OK, got it
___
*[python/test/io/rpc/test_serialization.py, line 42 at r3](https://reviewable.io/reviews/isl-org/open3d/3821#-MhZbUed-gYMNoPzkPWc:-Mh_EkzZ27tCb4e4n1LC:bbfh2si) ([raw file](https://github.com/isl-org/open3d/blob/e7f5fde9ca75eab828e8969bf701c363fbe93c69/python/test/io/rpc/test_serialization.py#L42)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

The pytest randomly plugin sets Numpy RNG state based on time. Reproducible results can be obtained through a command line argument. We should not set the RNG state inside tests to benefit from the test randomization. [Setting RNG state may also affect tests that run after this one].
</blockquote></details>

pytest-randomly looks good.

**Pull request merged**
