### PR TITLE
Default Constructor for Tensor PointCloud and TriangleMesh Pybind

### PR DESCRIPTION
**Pull request by reyanshsolis**
- Default constructor for `Tensor` `PointCloud` and `TriangleMesh` `Pybind`.
- `TriangleMesh::ToString()`

Updated `ToString()` for pointcloud and lineset:
Previously for a `custom` attribute of `shape (4, 3, 2)` and type `Float32`, ToString for `pointcloud` and `lineset` printed: 
`Attribute: custom (Float32, 3)`, now it prints `Attribute: custom (dtype = Float32, shape = {4, 3, 2})`, which might be more clear.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3880)

### CODE REVIEW

**Review by ssheorey — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3880)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/t/geometry/TriangleMesh.cpp, line 65 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-Mgfg9FODY2Pz_XlC1aF:-Mgfg9FODY2Pz_XlC1aG:b3rwcey) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/open3d/t/geometry/TriangleMesh.cpp#L65)):*
> ```cpp
> }
> 
> std::string TriangleMesh::ToString() const {
> ```

Thanks. This was sorely needed. Can you give some examples of how the string rep. will look? Also add a C++ unit test. For e.g. see tLineSet
https://github.com/isl-org/Open3D/pull/3867/files#diff-18b9cb416f2e40486d3099f8b86ca5970641d8040c647fec3c4ae268ca54ea71R67-R70
https://github.com/isl-org/Open3D/pull/3867/files#diff-18b9cb416f2e40486d3099f8b86ca5970641d8040c647fec3c4ae268ca54ea71R132-R139
___
*[cpp/open3d/t/geometry/TriangleMesh.cpp, line 77 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-MgfiUEg6LhTM31xwK5d:-MgfiUEg6LhTM31xwK5e:bb0h0lk) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/open3d/t/geometry/TriangleMesh.cpp#L77)):*
> ```cpp
>             GetTriangles().GetDtype().ToString());
> 
>     std::string vertices_attr_str = "\n Vertices Attributes: ";
> ```

skip space as first char of new line.
`\nVertex attributes`
___
*[cpp/open3d/t/geometry/TriangleMesh.cpp, line 91 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-Mgfifwg0jpPRkQD5XT8:-Mgfifwg0jpPRkQD5XT9:b5s7zsc) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/open3d/t/geometry/TriangleMesh.cpp#L91)):*
> ```cpp
>     }
> 
>     std::string triangles_attr_str = "\n Triangles Attributes: ";
> ```

skip space as first char of new line.
`\nTriangle attributes`
___
*[cpp/pybind/t/geometry/pointcloud.cpp, line 70 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-MgffYN7A0CJvwTBXOmL:-MgffYN7A0CJvwTBXOmM:bumwqnx) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/pybind/t/geometry/pointcloud.cpp#L70)):*
> ```cpp
>     pointcloud
>             .def(py::init<const core::Device&>(),
>                  "device"_a = core::Device("CPU:0"))
> ```

Can you add docs for the function and `device`? Mostly we just need to copy them over from the C++ docs.
___
*[cpp/pybind/t/geometry/trianglemesh.cpp, line 48 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-Mgfg3vD6xgAoGFgnl5k:-Mgfg3vD6xgAoGFgnl5l:bumwqnx) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/pybind/t/geometry/trianglemesh.cpp#L48)):*
> ```cpp
>     triangle_mesh
>             .def(py::init<const core::Device&>(),
>                  "device"_a = core::Device("CPU:0"))
> ```

Can you add docs for the function and `device`? Mostly we just need to copy them over from the C++ docs.

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3880)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @ssheorey)

___
*[cpp/open3d/t/geometry/TriangleMesh.cpp, line 65 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-Mgfg9FODY2Pz_XlC1aF:-MgjHfO37FxjnAPCOb3h:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/open3d/t/geometry/TriangleMesh.cpp#L65)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Thanks. This was sorely needed. Can you give some examples of how the string rep. will look? Also add a C++ unit test. For e.g. see tLineSet
https://github.com/isl-org/Open3D/pull/3867/files#diff-18b9cb416f2e40486d3099f8b86ca5970641d8040c647fec3c4ae268ca54ea71R67-R70
https://github.com/isl-org/Open3D/pull/3867/files#diff-18b9cb416f2e40486d3099f8b86ca5970641d8040c647fec3c4ae268ca54ea71R132-R139
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TriangleMesh.cpp, line 77 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-MgfiUEg6LhTM31xwK5d:-MgjHfxLDCqiDv7WA_tB:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/open3d/t/geometry/TriangleMesh.cpp#L77)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

skip space as first char of new line.
`\nVertex attributes`
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TriangleMesh.cpp, line 91 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-Mgfifwg0jpPRkQD5XT8:-MgjHgRMDuHd7IO2YLx5:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/open3d/t/geometry/TriangleMesh.cpp#L91)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

skip space as first char of new line.
`\nTriangle attributes`
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/pointcloud.cpp, line 70 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-MgffYN7A0CJvwTBXOmL:-MgjHhAF7_Xu3dV1Fj3Y:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/pybind/t/geometry/pointcloud.cpp#L70)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can you add docs for the function and `device`? Mostly we just need to copy them over from the C++ docs.
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/trianglemesh.cpp, line 48 at r1](https://reviewable.io/reviews/isl-org/open3d/3880#-Mgfg3vD6xgAoGFgnl5k:-MgjHiF7A41JNxxGKwf3:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/8c51bef27b14599ce7e43d3e2d4d8bd4c5496e48/cpp/pybind/t/geometry/trianglemesh.cpp#L48)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can you add docs for the function and `device`? Mostly we just need to copy them over from the C++ docs.
</blockquote></details>

Done.

**Comment by reyanshsolis** [comment]
@ssheorey, 
I have modified the `ToString()` for `pointcloud` and `lineset`, as the previous one was not much clear to me, let me know your suggestions.

For a `custom` attribute of `shape (4, 3, 2)` and type `Float32`, 
ToString for `pointcloud` and `lineset` previously printed: 
```
Attributes: custom (Float32, 3)
```
now:
```
Attributes: custom (dtype = Float32, shape = {4, 3, 2})
```

**Review by ssheorey — APPROVED** [review]
Change looks good to me. In the original `ToString()`, the assumption was that the custom attribute shape would be `{N,d}` where  N is the length of the primary attribute, and only `d` was printed. This is more general.

In a later PR, we can add `ToString()`to `TensorMap` and re-use that code in all `Geometry` sub-classes to ensure consistency.

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3880#-:-MguzFUu8o6D7-UTKXWq:bl6h8av)* status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @ssheorey)

**Pull request merged**
