### PR TITLE
add add_voxel in pybind for VoxelGrid::AddVoxel

### PR DESCRIPTION
**Pull request by ohkwon718**
I hope this update doesn't make any conflict with other features.
Regarding issues https://github.com/isl-org/Open3D/issues/2660, https://github.com/isl-org/Open3D/issues/1101, and https://github.com/isl-org/Open3D/issues/3133, there are needs for people to manually control voxels in VoxelGrid. Although it is already implemented in c++, there are no corresponding lines in pybind.

```import numpy as np
import open3d as o3d

print('input')
N = 2000

armadillo = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo.path)
pcd = mesh.sample_points_poisson_disk(N)
# fit to unit cube
pcd.scale(1 / np.max(pcd.get_max_bound() - pcd.get_min_bound()),
          center=pcd.get_center())
pcd.colors = o3d.utility.Vector3dVector(np.random.uniform(0, 1, size=(N, 3)))
# o3d.visualization.draw_geometries([pcd])

print('voxelization')
voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(pcd,
                                                            voxel_size=0.05)
o3d.visualization.draw_geometries([voxel_grid])
voxel_grid.add_voxel(o3d.geometry.Voxel([20,0,13], [1.0,0.0,0.0]))
o3d.visualization.draw_geometries([voxel_grid])


```
image

More discussions
- Is AddVoxel a profer name? Since the voxel can be overwritten several times with the function, the name could be something else e.g. "SetVoxel"
- EraseVoxel(or RemoveVoxel) function would be useful. It must not be hard work with 'std::unordered_map::erase'.

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6023)

### CODE REVIEW

**Comment by ohkwon718** [comment]
More commit for remove_voxel

```import numpy as np
import open3d as o3d

print('input')
N = 2000

armadillo = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo.path)
pcd = mesh.sample_points_poisson_disk(N)
# fit to unit cube
pcd.scale(1 / np.max(pcd.get_max_bound() - pcd.get_min_bound()),
          center=pcd.get_center())
pcd.colors = o3d.utility.Vector3dVector(np.random.uniform(0, 1, size=(N, 3)))
# o3d.visualization.draw_geometries([pcd])

print('voxelization')
voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(pcd,
                                                            voxel_size=0.05)

for i in range(10):
    for j in range(10):       
        for k in range(20):
            voxel_grid.remove_voxel([i,j,k])
o3d.visualization.draw_geometries([voxel_grid])
```


image

**Comment by ssheorey** [comment]
Hi @ohkwon718 thanks for submitting this PR. Please update the code style to match Open3D code style by running:

`python util/check_style.py --apply`

**Comment by justdigi** [comment]
I could use this feature. I hope it can be submitted!

**Review by reyanshsolis — APPROVED** [review]
Re-triggering CI. LGTM, once all are passing.

**Review by ssheorey — APPROVED** [review]
Thanks @ohkwon718 for the useful feature! Thanks @reyanshsolis  for your review.

**Pull request merged**
