### PR TITLE
Update NNS docstrings, changing Int64 to Int32

### PR DESCRIPTION
**Pull request by reyanshsolis**
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3933)

### CODE REVIEW

**Comment by yxlao** [comment]
@reyanshsolis is int64 not supported anymore? Will we add support in the future?

**Comment by reyanshsolis** [comment]
Since, returns from nns such as `indices, distances, counts` are not dependent on the input (`query`, `target_dataset`) dtypes, it must be a fixed contract or we may need to add an optional parameter for users to request the data in certain dtype (which will complicate the interface). 
So, we need to either fix `indices, counts` as `Int64` or as `Int32` and `distances` as `Float32` or `Float64`, and user will need to convert it according to their use-cases. 

This is what my understanding is, waiting on @junha-l for confirmation.

**Review by junha-l — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reyanshsolis)

**Review by junha-l — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3933#-:-MiAFjBh2QSH_XtY9vzA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reyanshsolis)

**Pull request merged**
