### PR TITLE
Binary development package archive

### PR DESCRIPTION
**Pull request by ssheorey**
- Shared Ubuntu x86_64, Ubuntu x86_64 + CUDA, macOS, Windows.
- Ubuntu packages with MLops => GLIBCXX_USE_CXX11_ABI = OFF
- Ubuntu packages with GLIBCXX_USE_CXX11_ABI=ON. Update Ubuntu CUDA CI `4-ml-bionic` to `4-shared-bionic`
- macOS packages have MLops => macOS CI changed to SHARED when ML is enabled.
- Upload to Google cloud for master.
- Update `getting_started.rst` to include download links for development packages.
- Support DEVELOPER_BUILD=OFF for all cases for release packages.

New Ubuntu CUDA CI:
```
          - CI_CONFIG: 2-bionic
          - CI_CONFIG: 3-ml-shared-bionic
          - CI_CONFIG: 4-shared-bionic
          - CI_CONFIG: 5-ml-focal
```

**Future:** 
- Ubuntu ARM package.

### Docs excerpt

image

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4647)

### CODE REVIEW

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4647)* status: 13 of 14 files reviewed, 11 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[CMakeLists.txt, line 236 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuENH4W5TWMPQVx5-jm:-MuENH4W5TWMPQVx5-jn:b-f2zn2w) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/CMakeLists.txt#L236)):*
> ```CMake
> project(Open3D
>     VERSION ${OPEN3D_VERSION}
>     # set PROJECT_DESCRIPTION
> ```

nit: set -> Sets
___
*[CMakeLists.txt, line 238 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEN8IT3NjVyjrV5bPm:-MuEN8IT3NjVyjrV5bPn:b-44lz98) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/CMakeLists.txt#L238)):*
> ```CMake
>     # set PROJECT_DESCRIPTION
>     DESCRIPTION "Open3D: A Modern Library for 3D Data Processing."
>     HOMEPAGE_URL "http://www.open3d.org"  # sets PROJECT_HOMEPAGE_URL
> ```

nit: `sets -> Sets`
nit: move `# sets PROJECT_HOMEPAGE_URL` to the line above to be consistent with `PROJECT_DESCRIPTION`



_Code quote:_
```CMake
# sets PROJECT_HOMEPAGE_URL
```
___
*[.github/workflows/macos.yml, line 29 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuENPCiCAkBN21uewGf:-MuENPCiCAkBN21uewGg:b94htv4) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/.github/workflows/macos.yml#L29)):*
> ```YAML
>         BUILD_ML_OPS: [ON, OFF]
>     env:
>       SHARED: ${{ matrix.BUILD_ML_OPS }}
> ```

Why shall `SHARED` be conditioned on `BUILD_ML_OPS`?
___
*[.github/workflows/ubuntu-cuda.yml, line 137 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEO3ebC2g2kdB9G98f:-MuEO3ebC2g2kdB9G98g:btrwgmq) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/.github/workflows/ubuntu-cuda.yml#L137)):*
> ```YAML
>           gcloud compute ssh "${INSTANCE_NAME}" \
>             --zone="${GCE_ZONE}" \
>             --command="sudo Open3D/docker/docker_build.sh ${CI_BUILD_CONFIG}"
> ```

can we directly use `matrix.CI_CONFIG` here, and remove `CI_BUILD_CONFIG`?
___
*[.github/workflows/ubuntu-cuda.yml, line 139 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuENmKf1KA4c4KAuRSs:-MuENmKf1KA4c4KAuRSt:b-9lp0mu) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/.github/workflows/ubuntu-cuda.yml#L139)):*
> ```YAML
>             --command="sudo Open3D/docker/docker_build.sh ${CI_BUILD_CONFIG}"
>           if [ ${{ matrix.CI_CONFIG }} == '3-ml-shared-bionic' ]; then
>               gcloud compute scp --zone="${GCE_ZONE}" \
> ```

nit: keep the 2-space indentation.
___
*[cpp/pybind/CMakeLists.txt, line 163 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEOlzA7uTCrb0rV_0B:-MuEOlzA7uTCrb0rV_0C:bhgjz9w) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/cpp/pybind/CMakeLists.txt#L163)):*
> ```CMake
>             -DGUI_RESOURCE_DIR=${GUI_RESOURCE_DIR}
>             -DPROJECT_EMAIL=${PROJECT_EMAIL}
>             -DPROJECT_HOME=${PROJECT_HOMEPAGE_URL}
> ```

i would also rename the LHS to `PROJECT_HOMEPAGE_URL`. The corresponding file will also need to be changed.



_Code quote:_
```CMake
PROJECT_HOME
```
___
*[docker/docker_build.sh, line 55 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEP2HV4Pf2d39RKxKN:-MuEP2HV4Pf2d39RKxKO:brq2bgc) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/docker/docker_build.sh#L55)):*
> ```Shell
>     # ML CIs
>     2-bionic                    : CUDA CI, 2-bionic, developer mode
>     3-ml-shared-bionic-RELEASE  : CUDA CI, 3-ml-shared-bionic, release mode
> ```

nit: `RELEASE` -> `release` to be consistent with the rest
___
*[docker/docker_build.sh, line 270 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEQM5c0RtTbcbHRIHm:-MuEQM5c0RtTbcbHRIHn:bc3qsp6) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/docker/docker_build.sh#L270)):*
> ```Shell
> }
> 
> 3-ml-shared-bionic-RELEASE_export_env() {
> ```

nit: same, lower case release
___
*[docs/getting_started.rst.in, line 6 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEQTVQ3WfJpxElXMiV:-MuEQTVQ3WfJpxElXMiW:b-7ex9oc) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/docs/getting_started.rst.in#L6)):*
> ```
> ###############
> 
> .. _install_open3d_c++:
> ```

I would put the C++ after Python
___
*[docs/getting_started.rst.in, line 26 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEQW8T6SR_bXj0-cCc:-MuEQW8T6SR_bXj0-cCd:bk2oahw) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/docs/getting_started.rst.in#L26)):*
> ```
> binary package archives are provided here:
> 
> :Linux (glibc 2.27+):
> ```

We can say Ubuntu 18.04+ or glibc 2.27+.

Could we also show how to check the glibc version?
___
*[docs/getting_started.rst.in, line 31 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuFY9lq4egD5TjlX-4M:-MuFY9lq4egD5TjlX-4N:bcpb884) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/docs/getting_started.rst.in#L31)):*
> ```
> 
>         * `x86_64 <https://storage.googleapis.com/open3d-releases-master/devel/open3d-devel-linux-x86_64-@OPEN3D_VERSION_FULL@.tar.xz>`__
>         * `x86_64 with CUDA 11.x <https://storage.googleapis.com/open3d-releases-master/devel/open3d-devel-linux-x86_64-cuda-@OPEN3D_VERSION_FULL@.tar.xz>`__
> ```

Is it one `_` instead of two `__`? Same for all other hyperlinks.

**Review by ssheorey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4647)* status: 6 of 14 files reviewed, 7 unresolved discussions (waiting on @yxlao)

___
*[CMakeLists.txt, line 236 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuENH4W5TWMPQVx5-jm:-MuHd1l6973fvw5RR5-a:byica64) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/CMakeLists.txt#L236)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: set -> Sets
</blockquote></details>

All changed to `Set` to match "Set additional info".
___
*[CMakeLists.txt, line 238 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEN8IT3NjVyjrV5bPm:-MuHdEAU2qQUAXKCuZaX:bb6un1j) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/CMakeLists.txt#L238)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: `sets -> Sets`
nit: move `# sets PROJECT_HOMEPAGE_URL` to the line above to be consistent with `PROJECT_DESCRIPTION`
</blockquote></details>

Done
___
*[.github/workflows/macos.yml, line 29 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuENPCiCAkBN21uewGf:-MuHddvR6dbnq8KLTI1l:byg59d0) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/.github/workflows/macos.yml#L29)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Why shall `SHARED` be conditioned on `BUILD_ML_OPS`?
</blockquote></details>

`SHARED` -> `CONFIG` for clarity.
___
*[.github/workflows/ubuntu-cuda.yml, line 137 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEO3ebC2g2kdB9G98f:-MuHih7d1JoMeL6azQCw:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/.github/workflows/ubuntu-cuda.yml#L137)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

can we directly use `matrix.CI_CONFIG` here, and remove `CI_BUILD_CONFIG`?
</blockquote></details>

Done.
___
*[cpp/pybind/CMakeLists.txt, line 163 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEOlzA7uTCrb0rV_0B:-MuHeNgl57_InWAp6sHl:b-uk614c) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/cpp/pybind/CMakeLists.txt#L163)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

i would also rename the LHS to `PROJECT_HOMEPAGE_URL`. The corresponding file will also need to be changed.
</blockquote></details>

That was a bug. Updated. Thanks.
___
*[docs/getting_started.rst.in, line 6 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEQTVQ3WfJpxElXMiV:-MuHOtE96QDV2XPduMP7:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/docs/getting_started.rst.in#L6)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

I would put the C++ after Python
</blockquote></details>

Done.
___
*[docs/getting_started.rst.in, line 26 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuEQW8T6SR_bXj0-cCc:-MuH_wurB0PudjF1CF5k:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/docs/getting_started.rst.in#L26)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We can say Ubuntu 18.04+ or glibc 2.27+.

Could we also show how to check the glibc version?
</blockquote></details>

Done.
___
*[docs/getting_started.rst.in, line 31 at r2](https://reviewable.io/reviews/isl-org/open3d/4647#-MuFY9lq4egD5TjlX-4M:-MuH_yFP0Jc4cmupJi6s:b-dnxu5t) ([raw file](https://github.com/isl-org/open3d/blob/b5d7c4f16b9723a1b364c11cca761a098adfbef1/docs/getting_started.rst.in#L31)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Is it one `_` instead of two `__`? Same for all other hyperlinks.
</blockquote></details>

Two `__` means anonymous links. For single `_` sphinx complains if the same link is repeated.

**Comment by benjaminum** [comment]
Does the CI also upload the packages with CUDA?

**Comment by ssheorey** [comment]
> Does the CI also upload the packages with CUDA?

Yes (from Google cloud). For branches, packages will be on Github actions only. For master they are uploaded to Google cloud storage, like the python devel wheels.

**Review by benjaminum — APPROVED** [review]
This PR :lgtm: 

Would it make sense to add a test that is using the binary packages in a future PR?

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4647#-:-MujuYX58JzG_AA0sqDk:b-fczmu4)* status: 4 of 16 files reviewed, 7 unresolved discussions (waiting on @yxlao)

**Comment by ssheorey** [comment]
> This PR :lgtm:
> 
> Would it make sense to add a test that is using the binary packages in a future PR?

Yes, we can update the `TestVIsualizer` example build to use the binary package. [future PR]

**Review by yxlao — APPROVED** [review]

**Pull request merged**
