### PR TITLE
Refactor FixedRadiusSearch

### PR DESCRIPTION
**Pull request by junha-l**
This PR refactors the code related to FixedRadiusSearch.

1. Modify the file structures

```core/nns/FixedRadiusSearchImpl.{h,cuh}``` implements the underlying algorithm of hash-based fixed radius search
```core/nns/FixedRadiusSearchOps.{cpp,cu}``` implements the wrapper that connects Open3D's Tensors to fixed radius search kernel.
```ml/impl/misc/FixedRadiusSearch.{h,cuh}``` are removed. 

2. Move hash-based fixed radius search on CPU to ```core/nns``` namespace.

3. Connect pytorch & tensorflow wrappers with ```core/nns``` ones.

4. Add batch support in FixedRadiusSearch and HybridSearch (Replace #3670)

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3768)

### CODE REVIEW

**Comment by junha-l** [comment]
@benjaminum 
I have created a PR that replace Fixedradius search things in ml namespace with ones in core namepsace.
But there are CI issues on Windows, about ```AtomicFetchAddRelaxed``` function. 
Do you have any idea about this?

**Review by benjaminum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, 28 of 29 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3768)* status: all files reviewed, 4 unresolved discussions (waiting on @junha-l)

___
*[cpp/open3d/core/Atomic.h, line 49 at r4](https://reviewable.io/reviews/intel-isl/open3d/3768#-MfcPLtU77Se9QA1o6ZA:-MfcPLtU77Se9QA1o6ZB:b-qe1w47) ([raw file](https://github.com/intel-isl/open3d/blob/6a6a710624c4e8061d72d942b219814bff3f67bf/cpp/open3d/core/Atomic.h#L49)):*
> ```objc
> #elif _MSC_VER
>     return static_cast<uint32_t>(_InterlockedExchangeAdd(
>             reinterpret_cast<int32_t*>(address), static_cast<int32_t>(val)));
> ```

I added a docstring and casts for the 32 bit version too.
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 41 at r4](https://reviewable.io/reviews/intel-isl/open3d/3768#-MfcPh867VBBYWEyXSi4:-MfcPh867VBBYWEyXSi5:b28efnh) ([raw file](https://github.com/intel-isl/open3d/blob/6a6a710624c4e8061d72d942b219814bff3f67bf/cpp/open3d/core/nns/FixedRadiusIndex.h#L41)):*
> ```objc
> 
> template <class T>
> void BuildSpatialHashTableCPU(const Tensor& points,
> ```

Can you add docstrings for the functions in this file? Probably needs only a small amount of changes of the docstrings with the pointer args.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 42 at r4](https://reviewable.io/reviews/intel-isl/open3d/3768#-MfcSyV8AA7yrpoN2lur:-MfcSyV8AA7yrpoN2lus:b-tgkczl) ([raw file](https://github.com/intel-isl/open3d/blob/6a6a710624c4e8061d72d942b219814bff3f67bf/cpp/open3d/core/nns/NanoFlannIndex.cpp#L42)):*
> ```cpp
> namespace nns {
> 
> typedef int32_t index_t;
> ```

index_t is good but why do we change to 32 bit?
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 56 at r4](https://reviewable.io/reviews/intel-isl/open3d/3768#-MfcSMq9EKNGKHPfQ57C:-MfcSMq9EKNGKHPfQ57D:bp2wl24) ([raw file](https://github.com/intel-isl/open3d/blob/6a6a710624c4e8061d72d942b219814bff3f67bf/cpp/open3d/t/pipelines/registration/Registration.cpp#L56)):*
> ```cpp
>             target_nns.HybridSearch(source.GetPoints(),
>                                     max_correspondence_distance, 1);
>     result.correspondences_ = result.correspondences_.To(core::Int64);
> ```

Is this a bugfix or did the returned type change?

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3768)* status: 28 of 30 files reviewed, 4 unresolved discussions (waiting on @benjaminum)

___
*[cpp/open3d/core/Atomic.h, line 49 at r4](https://reviewable.io/reviews/isl-org/open3d/3768#-MfcPLtU77Se9QA1o6ZA:-MfmuILb3h8LbBJ2Dfq_:b-4ekr2z) ([raw file](https://github.com/isl-org/open3d/blob/6a6a710624c4e8061d72d942b219814bff3f67bf/cpp/open3d/core/Atomic.h#L49)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

I added a docstring and casts for the 32 bit version too.
</blockquote></details>

OK. Thanks!
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 41 at r4](https://reviewable.io/reviews/isl-org/open3d/3768#-MfcPh867VBBYWEyXSi4:-MfmuLml3bXmYptb8QAY:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/6a6a710624c4e8061d72d942b219814bff3f67bf/cpp/open3d/core/nns/FixedRadiusIndex.h#L41)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Can you add docstrings for the functions in this file? Probably needs only a small amount of changes of the docstrings with the pointer args.
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/NanoFlannIndex.cpp, line 42 at r4](https://reviewable.io/reviews/isl-org/open3d/3768#-MfcSyV8AA7yrpoN2lur:-MfmuMe_3jeQWt0XzPth:b-skfts5) ([raw file](https://github.com/isl-org/open3d/blob/6a6a710624c4e8061d72d942b219814bff3f67bf/cpp/open3d/core/nns/NanoFlannIndex.cpp#L42)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

index_t is good but why do we change to 32 bit?
</blockquote></details>

I changed the index type to int32 for every search function in NearestNeighborSearch module to make it compatible with pytorch and tensorflow wrappers. 

We might need to update the code to support both 32 bit and 64 bit integer for index type.
___
*[cpp/open3d/t/pipelines/registration/Registration.cpp, line 56 at r4](https://reviewable.io/reviews/isl-org/open3d/3768#-MfcSMq9EKNGKHPfQ57C:-MfmuhXsDBEF6u9EFsna:b3ozzw5) ([raw file](https://github.com/isl-org/open3d/blob/6a6a710624c4e8061d72d942b219814bff3f67bf/cpp/open3d/t/pipelines/registration/Registration.cpp#L56)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Is this a bugfix or did the returned type change?
</blockquote></details>

As stated above, this is intended. 
As Registration function requires Int64 types internally, I put this line of code to make it compatible.

**Review by benjaminum — CHANGES_REQUESTED** [review]
Only minor changes missing.

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3768#-:-Mfn5PNaAeAVNYEki5uV:b-82s0ld)* status: all files reviewed, 9 unresolved discussions (waiting on @benjaminum and @junha-l)

___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 123 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn3v3lErI9JMTuFUBY:-Mfn3v3lErI9JMTuFUBZ:b830y4x) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L123)):*
> ```objc
> ///        Note that for the L2 metric the squared distances will be returned!!
> ///
> /// \param sort                If true then sort the results in ascening order
> ```

ascending typo
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 153 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn3p8cDWunzPvnwY1f:-Mfn3p8cDWunzPvnwY1g:bh7hzr1) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L153)):*
> ```objc
>                           Tensor& neighbors_distance);
> 
> // Hybrid search. This function computes a list of neighbor indices
> ```

`//` -> `///`
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 195 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn5FuK8VdpnmsNM-Iu:-Mfn5FuK8VdpnmsNM-Iv:b-4vv895) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L195)):*
> ```objc
> ///        search.
> ///
> /// \param ignore_query_point    If true then points with the same position as
> ```

Too many parameters in the docstring. ignore_query_point, ...
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 313 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn4-kZ8OL2pBPgxZg0:-Mfn4-kZ8OL2pBPgxZg1:b830y4x) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L313)):*
> ```objc
> ///        Note that for the L2 metric the squared distances will be returned!!
> ///
> /// \param sort                If true then sort the results in ascening order
> ```

ascending typo
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 384 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn4hOi7SvAb2gsZSkU:-Mfn4hOi7SvAb2gsZSkV:b-4vv895) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L384)):*
> ```objc
> ///        search.
> ///
> /// \param ignore_query_point    If true then points with the same position as
> ```

Too many parameters in the docstring. ignore_query_point, ...

**Review by junha-l — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3768)* status: 29 of 30 files reviewed, 9 unresolved discussions (waiting on @benjaminum)

___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 123 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn3v3lErI9JMTuFUBY:-Mfor-WA1h3sxS8uBpN5:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L123)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

ascending typo
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 153 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn3p8cDWunzPvnwY1f:-Mfor0WEAluITMZ60HgR:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L153)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

`//` -> `///`
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 195 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn5FuK8VdpnmsNM-Iu:-Mfor1IYC5DbIW0pBOrU:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L195)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Too many parameters in the docstring. ignore_query_point, ...
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 313 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn4-kZ8OL2pBPgxZg0:-Mfor1z18L-oKmewDnG1:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L313)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

ascending typo
</blockquote></details>

Done.
___
*[cpp/open3d/core/nns/FixedRadiusIndex.h, line 384 at r6](https://reviewable.io/reviews/isl-org/open3d/3768#-Mfn4hOi7SvAb2gsZSkU:-Mfor2XQDUdD19Jo7Wu_:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/eff7de0fd7bd3cf0a3faa6d51a5441651d954f71/cpp/open3d/core/nns/FixedRadiusIndex.h#L384)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Too many parameters in the docstring. ignore_query_point, ...
</blockquote></details>

Done.

**Review by benjaminum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3768#-:-Mfq8Df7CPW4HIB-RxXm:bnfp4nl)* status: 29 of 30 files reviewed, 9 unresolved discussions (waiting on @benjaminum)

**Pull request merged**
