### PR TITLE
Add demo scene example

### PR DESCRIPTION
**Pull request by errissa**
The demo scene script requires this asset from the `open3d_downloads` project: https://github.com/isl-org/open3d_downloads/releases/download/o3d_demo_scene/demo_scene_assets.tgz

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4243)

### CODE REVIEW

**Review by yxlao — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4243)* status: all files reviewed, 2 unresolved discussions (waiting on @errissa and @ssheorey)

___
*[examples/python/gui/demo-scene.py, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/4243#-MniXd-b1dQr4ACrhWq_:-MniXd-b1dQr4ACrhWqa:b-ozk6fn) ([raw file](https://github.com/isl-org/open3d/blob/60d465f77931b35748cf94bc7ec3c64dc090d705/examples/python/gui/demo-scene.py#L43)):*
> ```Python
>         " the assets from here:"
>         " https://github.com/isl-org/open3d_downloads/releases/download/o3d_demo_scene/demo_scene_assets.tgz"
>         " and unpack into the examples/test_data directory")
> ```

We shall also mention the directory from which you should launch the script. 

Ideally, the full instructions shall be provided.
```bash
cd exmples/test_data
wget ...
tar -xzvf ...
cd ../../
python examples/python/gui/demo-scene.py
```

It would be much simpler after the dataset downloader is implemented.
___
*[examples/python/gui/demo-scene.py, line 72 at r2](https://reviewable.io/reviews/isl-org/open3d/4243#-MniYPUyEV8NuClLeVfX:-MniYPUyEV8NuClLeVfY:b5bu3nt) ([raw file](https://github.com/isl-org/open3d/blob/60d465f77931b35748cf94bc7ec3c64dc090d705/examples/python/gui/demo-scene.py#L72)):*
> ```Python
>     return mat
> ```

nit: i would put the code below under `if __name__ == "__main__":`

**Review by yxlao — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4243)* status: all files reviewed, 2 unresolved discussions (waiting on @errissa and @ssheorey)

___
*[examples/python/gui/demo-scene.py, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/4243#-MniXd-b1dQr4ACrhWq_:-MniZuf48ynFyZde3Lut:b8vp6kt) ([raw file](https://github.com/isl-org/open3d/blob/60d465f77931b35748cf94bc7ec3c64dc090d705/examples/python/gui/demo-scene.py#L43)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We shall also mention the directory from which you should launch the script. 

Ideally, the full instructions shall be provided.
```bash
cd exmples/test_data
wget ...
tar -cxvf ...
cd ../../
python examples/python/gui/demo-scene.py
```

It would be much simpler after the dataset downloader is implemented.
</blockquote></details>

typo: `tar -xzvf`

**Review by ssheorey — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4243)* status: all files reviewed, 3 unresolved discussions (waiting on @errissa)

___
*[examples/python/gui/demo-scene.py, line 165 at r2](https://reviewable.io/reviews/isl-org/open3d/4243#-MniaIplE8fsewgXm142:-MniaIplE8fsewgXm143:b4nlip5) ([raw file](https://github.com/isl-org/open3d/blob/60d465f77931b35748cf94bc7ec3c64dc090d705/examples/python/gui/demo-scene.py#L165)):*
> ```Python
>     "geometry": a_sphere,
>     "material": mat_sphere
> }]
> ```

Could you refactor all code above this as a function? So that you have:
```
def create_scene():
     ....

if __name__=="__main__":
    geoms = create_scene()
    vis.draw(geoms, ...)
```
This way, I can import the `create_scene()`  function into the TB plugin example from here and directly save the `geoms` as a 3D summary?

**Review by ssheorey — CHANGES_REQUESTED** [review]
Can you use `Material` instead of `MaterialRecord` in this example? I believe we plan to switch everything over to `Material` eventually, so we should avoid using it in examples. Also, we can only serialize `Material`, not `MaterialRecord`, and there is no Python API for conversion.

**Review by errissa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4243)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ssheorey and @yxlao)

___
*[examples/python/gui/demo-scene.py, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/4243#-MniXd-b1dQr4ACrhWq_:-MnwFHojAlspVVocQ-Zj:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/60d465f77931b35748cf94bc7ec3c64dc090d705/examples/python/gui/demo-scene.py#L43)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

typo: `tar -xzvf`
</blockquote></details>

Done.
___
*[examples/python/gui/demo-scene.py, line 165 at r2](https://reviewable.io/reviews/isl-org/open3d/4243#-MniaIplE8fsewgXm142:-MnwFKjxBoecVBn6m0Xq:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/60d465f77931b35748cf94bc7ec3c64dc090d705/examples/python/gui/demo-scene.py#L165)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Could you refactor all code above this as a function? So that you have:
```
def create_scene():
     ....

if __name__=="__main__":
    geoms = create_scene()
    vis.draw(geoms, ...)
```
This way, I can import the `create_scene()`  function into the TB plugin example from here and directly save the `geoms` as a 3D summary?
</blockquote></details>

Done.

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4243)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yxlao)

**Review by yxlao — APPROVED** [review]

**Comment by yxlao** [comment]
LGTM. I pushed a change to the helper message format.

**Pull request merged**
