### PR TITLE
Upgrade embree to 4.3.1

### PR DESCRIPTION
**Pull request by lumurillo**
Upgrade the `embree` version to 4.3.1.

## Type

-   [ ] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [x] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

Use of the version 4 of the embree API.

## Checklist:

-   [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

* Changed the `embree` tarball version to 4.3.1
* Adapt the use of embree API acording to this notes: https://github.com/embree/embree/tree/master?tab=readme-ov-file#upgrading-from-embree-3-to-embree-4

### CODE REVIEW

**Comment by ssheorey** [comment]
@lumurillo for style check:
```sh
pip install clang-format~=10.0
python util/check_style.py --apply
```

**Comment by ssheorey** [comment]
- Please update to the latest available embree (4.3.1).
- We will need to test GPU functionality.

**Comment by ssheorey** [comment]
Plan for embree upgrade:

- [x] Upgrade embree to latest and update API.
- [ ] Pass CI on CPU.
- [ ] Add iGPU (SYCL) support and pass CI on iGPU.
- [ ] Add dGPU (SYCL) support for Intel GPU and update / pass CI on dGPU.
- [ ] Add dGPU (SYCL) support for Nvidia GPU and pass CI on dGPU.

**Review by benjaminum — APPROVED** [review]

**Comment by ssheorey** [comment]
Hi @lumurillo did you notice any performance difference with the new embree, especially after the change in API (`rtcInterset1M` -> `rtcIntersect1`). It would be good to do a quick benchmark on a large mesh (~1M+ vertices).

**Pull request merged**
