### PR TITLE
add voting and ray jitter to compute the inside outside

### PR DESCRIPTION
**Pull request by benjaminum**
This PR addresses #5669

Functions like ComputeOccupancy and ComputeSignedDistance have a new argument `samples` for using multiple rays to determine the inside/outside.

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5797)

### CODE REVIEW

**Review by ssheorey — CHANGES_REQUESTED** [review]
Consider naming `samples` -> `nsamples`
Looks good after switching to the Open3D RNG wrapper.

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5797#-:-NJl7ttG6cL92OCOjbio:b-nq2ijr)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @benjaminum and @errissa)

___
*[`cpp/open3d/t/geometry/RaycastingScene.h` line 174 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl7GCq7HyXIFtZ3eeg:-NJl7GCrCPlSwnUoIX-H:bpsxp24) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.h#L174)):*
> ```objc
>     /// \param nthreads The number of threads to use. Set to 0 for automatic.
>     /// \param samples The number of rays used for determining the inside.
>     /// This must be an odd number. The default is 1.
> ```

Add guidance:
Use a higher value if you notice sign flipping at specific degenerate case pixels.
___
*[`cpp/open3d/t/geometry/RaycastingScene.h` line 199 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl7NrkAp_IFqfA1vPF:-NJl7NrkAp_IFqfA1vPG:bbu46at) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.h#L199)):*
> ```objc
>     /// \param nthreads The number of threads to use. Set to 0 for automatic.
>     /// \param samples The number of rays used for determining the inside.
>     /// This must be an odd number. The default is 1.
> ```

Add guidance:
Use a higher value if you notice errors at specific degenerate case pixels.
___
*[`cpp/open3d/t/geometry/RaycastingScene.cpp` line 777 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl2k_S26rdq313CoKM:-NJl2k_TBAxaUHMTq9m1:bgcjv8t) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.cpp#L777)):*
> ```cpp
>     size_t num_query_points = shape.NumElements();
> 
>     std::mt19937 gen(42);
> ```

Use Open3D RNG wrapper from util to ensure repeatability.
___
*[`cpp/pybind/t/geometry/raycasting_scene.cpp` line 278 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl6y2V2zYepaHGWnDj:-NJl6y2V2zYepaHGWnDk:bpsxp24) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/pybind/t/geometry/raycasting_scene.cpp#L278)):*
> ```cpp
> 
>     samples (int): The number of rays used for determining the inside.
>         This must be an odd number. The default is 1.
> ```

Add guidance:
Use a higher value if you notice sign flipping at specific degenerate case pixels.
___
*[`cpp/pybind/t/geometry/raycasting_scene.cpp` line 308 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl87rLBcnGfFWgRRtT:-NJl87rM3KubIikBVenp:bbu46at) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/pybind/t/geometry/raycasting_scene.cpp#L308)):*
> ```cpp
> 
>     samples (int): The number of rays used for determining the inside.
>         This must be an odd number. The default is 1.
> ```

Add guidance:
Use a higher value if you notice errors at specific degenerate case pixels.

**Review by benjaminum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5797)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @errissa and @ssheorey)

___
*[`cpp/open3d/t/geometry/RaycastingScene.h` line 174 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl7GCq7HyXIFtZ3eeg:-NJnkP7T5LIoxZYEix8E:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.h#L174)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Add guidance:
Use a higher value if you notice sign flipping at specific degenerate case pixels.
</blockquote></details>

Done.
___
*[`cpp/open3d/t/geometry/RaycastingScene.h` line 199 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl7NrkAp_IFqfA1vPF:-NJnkPggCXICK6dNPjgN:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.h#L199)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Add guidance:
Use a higher value if you notice errors at specific degenerate case pixels.
</blockquote></details>

Done.
___
*[`cpp/open3d/t/geometry/RaycastingScene.cpp` line 777 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl2k_S26rdq313CoKM:-NJnkSvy-FW8CJIImF4O:bwsrrx) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.cpp#L777)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Use Open3D RNG wrapper from util to ensure repeatability.
</blockquote></details>

Didn't know we had that :sweat_smile: . The rng in utility is global but here I want just this function to be deterministic. This would mean setting the global seed for every call, which does not seem right.
___
*[`cpp/pybind/t/geometry/raycasting_scene.cpp` line 278 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl6y2V2zYepaHGWnDj:-NJnkROxEPzRMnMg0iPg:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/pybind/t/geometry/raycasting_scene.cpp#L278)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Add guidance:
Use a higher value if you notice sign flipping at specific degenerate case pixels.
</blockquote></details>

Done.
___
*[`cpp/pybind/t/geometry/raycasting_scene.cpp` line 308 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl87rLBcnGfFWgRRtT:-NJnkRqoDlSqtn3Tnqwo:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/pybind/t/geometry/raycasting_scene.cpp#L308)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Add guidance:
Use a higher value if you notice errors at specific degenerate case pixels.
</blockquote></details>

Done.

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5797)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @benjaminum and @errissa)

___
*[`cpp/open3d/t/geometry/RaycastingScene.cpp` line 777 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl2k_S26rdq313CoKM:-NJpxBMl2AtruPDHncN1:b3mq36g) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.cpp#L777)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Didn't know we had that :sweat_smile: . The rng in utility is global but here I want just this function to be deterministic. This would mean setting the global seed for every call, which does not seem right.
</blockquote></details>

Looks like you don't need randomness here. Something fixed like 1 + 1e-3 * {cos(2pi/n), sin(2pi/n), 0} for n in range(3), etc. should work as well.
If you want to keep randomness, can you add your reply as a comment?

**Review by benjaminum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5797)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @errissa and @ssheorey)

___
*[`cpp/open3d/t/geometry/RaycastingScene.cpp` line 777 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl2k_S26rdq313CoKM:-NJqjxIr4gpqqvLMfMso:b2vap21) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.cpp#L777)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Looks like you don't need randomness here. Something fixed like 1 + 1e-3 * {cos(2pi/n), sin(2pi/n), 0} for n in range(3), etc. should work as well.
If you want to keep randomness, can you add your reply as a comment?
</blockquote></details>

I think we just want a deterministic generator of ray directions that avoids some very specific directions like [1,1,1], [1,0,0], ...
I will try your suggestion.
About the RNG wrapper, would it make sense to extend it to allow locally seeded RNGs?

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5797)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @benjaminum and @errissa)

___
*[`cpp/open3d/t/geometry/RaycastingScene.cpp` line 777 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl2k_S26rdq313CoKM:-NJvy5S35_ak5-WL7RDy:b2nezca) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.cpp#L777)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

I think we just want a deterministic generator of ray directions that avoids some very specific directions like [1,1,1], [1,0,0], ...
I will try your suggestion.
About the RNG wrapper, would it make sense to extend it to allow locally seeded RNGs?
</blockquote></details>

Something like an RNG with seed set / reset with a context manager? I think that's actually the same as just explicitly seeding a new RNG as you are doing here. Finally, it's about user expectation - if they would expect the Open3D global RNG to control randomness here or not. If we are using a local RNG, a comment to explain that should be sufficient.

**Review by benjaminum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5797)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @errissa and @ssheorey)

___
*[`cpp/open3d/t/geometry/RaycastingScene.cpp` line 777 at r1](https://reviewable.io/reviews/isl-org/open3d/5797#-NJl2k_S26rdq313CoKM:-NJxztxH3mvC2JkRzlhg:b-z7zrcs) ([raw file](https://github.com/isl-org/open3d/blob/0db10f1a30b7bf3517b92b6ea75a8713fbd355f8/cpp/open3d/t/geometry/RaycastingScene.cpp#L777)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Something like an RNG with seed set / reset with a context manager? I think that's actually the same as just explicitly seeding a new RNG as you are doing here. Finally, it's about user expectation - if they would expect the Open3D global RNG to control randomness here or not. If we are using a local RNG, a comment to explain that should be sufficient.
</blockquote></details>

Yes, I think in hindsight using a local RNG was ok. One more commit..

**Pull request merged**
