### PR TITLE
Fixed an issue in EstimateRange

### PR DESCRIPTION
**Pull request by jdavidberger**
This also gracefully handles the preallocated buffer being too small and adds a heuristic which estimates the number of fragments needed. 

This is the bug responsible for #5344 and fixes that issue absolutely:

From GPU:
image

The reason it didn't trigger on lower voxel sizes is that with a small enough voxel size, each reprojection only took 1 fragment anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5358)

### CODE REVIEW

**Comment by jdavidberger** [comment]
I also added a commit to store the allocated buffer to avoid a re-allocation for that fragment buffer each call into raycast

**Review by theNded — CHANGES_REQUESTED** [review]
Thanks for fixing the issue! Please see my review comments, any discussion is welcome. After reaching a consensus we can merge this PR.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5358#-:-N7vEQWb2eKSzNSfns1N:b76evfl)* status: all files reviewed, 2 unresolved discussions (waiting on @benjaminum and @jdavidberger)

___
*[`cpp/open3d/t/geometry/VoxelBlockGrid.h` line 256 at r1](https://reviewable.io/reviews/isl-org/open3d/5358#-N7vDtob8OrgWFNQjrc_:-N7vDtob8OrgWFNQjrca:bsfvvxi) ([raw file](https://github.com/isl-org/open3d/blob/d093c8b805108de6a90b31ac07b7c9f1643650c2/cpp/open3d/t/geometry/VoxelBlockGrid.h#L256)):*
> ```objc
> 
>     // Allocated fragment buffer for reuse in depth estimation
>     core::Tensor fragment_buffer_;
> ```

This seems a little bit ad hoc. Would be better to remove it as a member function
___
*[`cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h` line 331 at r1](https://reviewable.io/reviews/isl-org/open3d/5358#-N7vE6HIAeaKDQsMk4Uo:-N7vE6HIAeaKDQsMk4Up:bgb91gr) ([raw file](https://github.com/isl-org/open3d/blob/d093c8b805108de6a90b31ac07b7c9f1643650c2/cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h#L331)):*
> ```objc
>          float depth_min,
>          float depth_max,
>          core::Tensor& fragment_buffer) {
> ```

In general I would prefer to keep it as a static variable only presented in the function scope, like
```
static core::Tensor fragment_buffer;
if (fragment_buffer.GetDataPtr() == 0) ...
```

**Comment by jdavidberger** [comment]
The main issue with this is thread safety. As is it's not particularly thread safe but if you lock properly around the VoxelGrid it would be; here if you have two voxelgrids churning it'll have issues. So I'd say this is workable with ```thread_local``` and just let each thread have one. 

Are there CI checks for memory leaks? Because this would flag that there since it technically is a memory leak.

**Review by theNded — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @benjaminum)

**Comment by jdavidberger** [comment]
Is there anything more I need to do in this and #5304 to get them merged or is it still in review?

**Comment by theNded** [comment]
Could you please fix the style? `make apply-style` will automatically do the trick.

**Comment by theNded** [comment]
@yuecideng could you please take a look at what may have triggered the issue in unit test on windows, if you have the environment and bandwidth?

**Comment by yuecideng** [comment]
> @yuecideng could you please take a look at what may have triggered the issue in unit test on windows, if you have the environment and bandwidth?

Sure, I will try it.

**Comment by nfrankisrg** [comment]
Hi I'm facing a similar issue. will this solution (or any other) will be merged into the latest version?

**Comment by yuecideng** [comment]
@nfrankisrg I forget to submit my review. Sorry for the lately response. Now the ci is no problem, and I think it would be merged to master soom.

**Comment by nfrankisrg** [comment]
after the recent change I'm unable to create a VoxelBlockGrid with device =  CUDA:0 or transfer the CPU one to the GPU using .cuda or .to

**Pull request merged**
