### PR TITLE
automatically cancel concurrent workflows

### PR DESCRIPTION
**Pull request by yxlao**
- This works on PR
- This shall also work on master, as `github.event.pull_request.number` is undefined, and we'll fall back to `github.ref`
- `github.workflow` is needed since we have multiple workflows PR

Ref:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
https://github.com/TeamAmaze/AmazeFileManager/blob/release/3.7/.github/workflows/android-feature.yml

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4684)

### CODE REVIEW

**Comment by yxlao** [comment]
image

**Comment by yxlao** [comment]
image

**Comment by yxlao** [comment]
Seems to work well!

**Review by ssheorey — APPROVED** [review]
Looks good. Thanks for adding this in!

**Pull request merged**
