### PR TITLE
Geometry rename

### PR DESCRIPTION
**Pull request by yxlao**
Renamed:
- `point_attr_["positions"]`
- `vertex_attr_["positions"]`
- `triangle_attr_["indices"]`
- Corresponding getter, setter and "has()" checker
- Argument name of constructors

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3855)

### CODE REVIEW

**Review by ssheorey — COMMENTED** [review]
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3855)* status: all files reviewed, 11 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/PointCloud.h, line 57 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRadu87_oHofa05OIL:-MgRadu87_oHofa05OIM:b-noeunx) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L57)):*
> ```objc
> ///     - Usage
> ///         - PointCloud::GetPointPositions()
> ///         - PointCloud::SetPointPositions(positions)
> ```

`const core::Tensor &positions` for doxygen autolink to the function docs. Also below with `normals`, `colors`, etc.
___
*[cpp/open3d/t/geometry/PointCloud.h, line 81 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRbY5f7HsHB4oNcuvy:-MgRbY5f7HsHB4oNcuvz:b-j6tuti) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L81)):*
> ```objc
> ///         - PointCloud::SetPointAttr("labels", labels)
> ///         - PointCloud::HasPointAttr("labels")
> ///     - Not created by default. Users and add their own custom attributes.
> ```

Users can add...
___
*[cpp/open3d/t/geometry/PointCloud.h, line 86 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRkEKD1t-DwgoWz96_:-MgRkEKD1t-DwgoWz96a:b2gpxxy) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L86)):*
> ```
> work
> ```
typo
___
*[cpp/open3d/t/geometry/PointCloud.h, line 100 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRkUhW0Sli-G-yquEf:-MgRkUhW0Sli-G-yquEg:bf3dlhv) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L100)):*
> ```
> trianglemsh
> ```
typo
___
*[cpp/open3d/t/geometry/PointCloud.h, line 102 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRkWqF-HZ5I89MRO3t:-MgRkWqF-HZ5I89MRO3u:b2nigxs) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L102)):*
> ```objc
>     /// trianglemsh (no memory copy).
>     ///
>     /// \param points A tensor with element shape (3,).
> ```

{3}
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 63 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRpMZz9483g0wCdnhX:-MgRpMZz9483g0wCdnhY:b2liy5v) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.cpp#L63)):*
> ```cpp
>       point_attr_(TensorMap("positions")) {
>     if (map_keys_to_tensors.count("positions") == 0) {
>         utility::LogError("\"points\" attribute must be specified.");
> ```

"positions" attribute must be specified.
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 42 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRtqeK2Qr8lF_HjRuY:-MgRtqeK2Qr8lF_HjRuZ:b-9qlnu9) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/TriangleMesh.h#L42)):*
> ```
> by default
> ```
remove
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 64 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRu5L5B6qjGUJlTxZI:-MgRu5L5B6qjGUJlTxZJ:b-1vx1qg) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/TriangleMesh.h#L64)):*
> ```objc
> ///     - Vertex normals
> ///         - TriangleMesh::GetVertexNormals()
> ///         - TriangleMesh::SetVertexNormals(vertex_normals)
> ```

`const Tensor &vertex_normals` so doxygen can autolink
Also below with vertex_colors, triangle_normals, triangle_colors, etc.
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 101 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRuVlYCGhNP0oop_AM:-MgRuVlYCGhNP0oop_AN:by3ltn7) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/TriangleMesh.h#L101)):*
> ```objc
> ///     - Value tensor must be on the same device as the triangle mesh.
> ///
> /// Note that the level 0 and level 1 convenience functions can also be achieved
> ```

Level 0 / level 1 -> default / commonly used
___
*[cpp/pybind/t/geometry/pointcloud.cpp, line 65 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRw0mEA8FTNlI_tqwW:-MgRw0mEA8FTNlI_tqwX:b3s3gdy) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/pybind/t/geometry/pointcloud.cpp#L65)):*
> ```cpp
>                Geometry>
>             pointcloud(m, "PointCloud",
>                        "A pointcloud contains a set of 3D points.");
> ```

Can we add an explanation of the attributes, similar to the C++ docs? I've added it for tLineSet Python bindings.
___
*[cpp/pybind/t/geometry/trianglemesh.cpp, line 43 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRwWCLDD2d0kSy3uID:-MgRwWCLDD2d0kSy3uIE:b3s3gdy) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/pybind/t/geometry/trianglemesh.cpp#L43)):*
> ```cpp
>             triangle_mesh(
>                     m, "TriangleMesh",
>                     "A triangle mesh contains a set of 3d vertices and faces.");
> ```

Can we add an explanation of the attributes, similar to the C++ docs? I've added it for tLineSet Python bindings.

**Review by yxlao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3855)* status: 29 of 42 files reviewed, 11 unresolved discussions (waiting on @ssheorey)

___
*[cpp/open3d/t/geometry/PointCloud.h, line 57 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRadu87_oHofa05OIL:-MgUuaemC14OJ22hYzGR:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L57)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`const core::Tensor &positions` for doxygen autolink to the function docs. Also below with `normals`, `colors`, etc.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.h, line 81 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRbY5f7HsHB4oNcuvy:-MgUuq7y8bWqtMmX6OdM:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L81)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Users can add...
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.h, line 86 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRkEKD1t-DwgoWz96_:-MgUuyMK0sLvJC4tmcXV:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L86)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> work
> ```
typo
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.h, line 100 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRkUhW0Sli-G-yquEf:-MgUvFU15l7-anDtXeRY:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L100)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> trianglemsh
> ```
typo
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.h, line 102 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRkWqF-HZ5I89MRO3t:-MgUvNisA2Ag4-CicCDn:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.h#L102)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

{3}
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/PointCloud.cpp, line 63 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRpMZz9483g0wCdnhX:-MgUzDaCA4hIQMRgL3jd:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/PointCloud.cpp#L63)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

"positions" attribute must be specified.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 42 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRtqeK2Qr8lF_HjRuY:-MgUzSq47vpxUVZP5fM4:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/TriangleMesh.h#L42)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> by default
> ```
remove
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 64 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRu5L5B6qjGUJlTxZI:-MgUzTOIBJmUkZa9xmIC:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/TriangleMesh.h#L64)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`const Tensor &vertex_normals` so doxygen can autolink
Also below with vertex_colors, triangle_normals, triangle_colors, etc.


</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TriangleMesh.h, line 101 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRuVlYCGhNP0oop_AM:-MgUznMm4f96rctTpqOQ:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/open3d/t/geometry/TriangleMesh.h#L101)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Level 0 / level 1 -> default / commonly used
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/pointcloud.cpp, line 65 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRw0mEA8FTNlI_tqwW:-Mgdw0s1EKVvq5qC8YcQ:b58sbu7) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/pybind/t/geometry/pointcloud.cpp#L65)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we add an explanation of the attributes, similar to the C++ docs? I've added it for tLineSet Python bindings.
</blockquote></details>

Done. Added Python example.
___
*[cpp/pybind/t/geometry/trianglemesh.cpp, line 43 at r1](https://reviewable.io/reviews/isl-org/open3d/3855#-MgRwWCLDD2d0kSy3uID:-Mgdw3045JmKbE718PKP:b-qaiu8t) ([raw file](https://github.com/isl-org/open3d/blob/659f8f42b8d320b4402147792b0c6379f7a8c7e7/cpp/pybind/t/geometry/trianglemesh.cpp#L43)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we add an explanation of the attributes, similar to the C++ docs? I've added it for tLineSet Python bindings.
</blockquote></details>

Done. Added Python example.

Will add mesh unit tests in a separate PR.

**Review by ssheorey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3855)* status: 29 of 42 files reviewed, all discussions resolved (waiting on @ssheorey)

**Comment by ssheorey** [comment]
This test failure may be related to the test randomization.

```
> [ RUN      ] RemoteFunctions.SendReceiveUnpackMessages
> [Open3D DEBUG] ReceiverBase: started
> [Open3D DEBUG] Connection::send() received answer with 27 bytes
> [Open3D DEBUG] ReceiverBase: stopped
> [Open3D DEBUG] ReceiverBase: already stopped
> [Open3D DEBUG] ReceiverBase: started
> [Open3D DEBUG] Connection::send() received answer with 27 bytes
> [Open3D DEBUG] ReceiverBase: stopped
> [Open3D DEBUG] ReceiverBase: already stopped
> [Open3D DEBUG] ReceiverBase: started
> [Open3D DEBUG] Connection::send() received answer with 27 bytes
> [Open3D DEBUG] ReceiverBase: stopped
> [Open3D DEBUG] ReceiverBase: already stopped
> [Open3D Error] (void __cdecl open3d::io::rpc::ReceiverBase::Start(void)) D:\a\Open3D\Open3D\cpp\open3d\io\rpc\ReceiverBase.cpp:89: ReceiverBase::Mainloop: Failed to bind address, Address in use
> [Open3D DEBUG] ReceiverBase: stopped
> 
> unknown file: error: C++ exception with description "[Open3D Error] (void __cdecl open3d::io::rpc::ReceiverBase::Start(void)) D:\a\Open3D\Open3D\cpp\open3d\io\rpc\ReceiverBase.cpp:89: ReceiverBase::Mainloop: Failed to bind address, Address in use
> " thrown in the test body.
> [  FAILED  ] RemoteFunctions.SendReceiveUnpackMessages (3038 ms)
> [----------] 2 tests from RemoteFunctions (4056 ms total)
> [Open3D Error] (auto __cdecl open3d::core::nns::NanoFlannIndex::SearchRadius::<lambda_68587503c05f53ae8f3ca4b11c915d95>::()::<lambda_ec62e64619bdff00a002b09c3e020213>::operator ()(void) const) D:\a\Open3D\Open3D\cpp\open3d\core\nns\NanoFlannIndex.cpp:221: [NanoFlannIndex::SearchRadius] radius should be larger than 0.
```

**Comment by yxlao** [comment]
> This test failure may be related to the test randomization.

Yes, probably. Or it can be due to the randomness in the test itself.

**Pull request merged**
