### PR TITLE
Add Tensor AxisAlignedBoundingBox

### PR DESCRIPTION
**Pull request by yuecideng**
This PR implements the tensor based `AxisAlignedBoundingBox` with the summary as follow:
1. Use three tensors (3, ) to represent `min_bound`, `max_bound` and `color`, which are only supported float32.
2. There is no `Transform` and `Rotate` functions implemented (or may be implemented with exception like legacy)?
3. Add valid check for min and max bound as #5087 mentioned.
4. The implemented methods follow the legacy version and tensor geometry specific functions.
5. pybind and unit test are also implemented.
6. The method `GetPointIndicesWithinBoundingBox` is implemented using kernel.
7. Add `GetAxisAlignedBoundingBox` in tensor `PointCloud`, `TriangleMesh` and `LineSet`.

In addition to these, I think it should be added to support `Draw` for visualization.  

This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5267)

### CODE REVIEW

**Review by reyanshsolis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5267)* status: 0 of 22 files reviewed, all discussions resolved (waiting on @benjaminum, @errissa, @ssheorey, and @yxlao)

___
*[`cpp/open3d/t/geometry/BoundingVolume.h` line 73 at r3](https://reviewable.io/reviews/isl-org/open3d/5267#-N7ZwpZLBZ4YfRFyPL6q:-N7ZwpZLBZ4YfRFyPL6r:b-5nxv0m) ([raw file](https://github.com/isl-org/open3d/blob/9e8b88c75bb14fb90b50367612692ae9e4f7e6a7/cpp/open3d/t/geometry/BoundingVolume.h#L73)):*
> ```objc
>     /// bound tensor, which must be on the same device and have the same data
>     /// type.
>     /// \param min_bound Lower bounds of the bounding box for all axes. Tensor
> ```

update: Added tensor dtype info in docstring for functions in this file.
___
*[`cpp/open3d/t/geometry/BoundingVolume.h` line 224 at r3](https://reviewable.io/reviews/isl-org/open3d/5267#-N7ZwxHqD331wboamUzS:-N7ZwxHqD331wboamUzT:b-yq2env) ([raw file](https://github.com/isl-org/open3d/blob/9e8b88c75bb14fb90b50367612692ae9e4f7e6a7/cpp/open3d/t/geometry/BoundingVolume.h#L224)):*
> ```objc
> protected:
>     core::Device device_ = core::Device("CPU:0");
>     core::Dtype dtype_ = core::Float32;
> ```

Since we are restricting the dtype behavior to: All attributes (max/min bound, color) must have same dtype (f32 or f64), I have added dtype_ member and GetDtype func.
___
*[`cpp/open3d/t/geometry/BoundingVolume.cpp` line 206 at r2](https://reviewable.io/reviews/isl-org/open3d/5267#-N7Zyy23Eb8t3yip8wzK:-N7Zyy23Eb8t3yip8wzL:bxruz2s) ([raw file](https://github.com/isl-org/open3d/blob/ee567b2e7cbb28ed3926e925dc9a1d6034cc6c3b/cpp/open3d/t/geometry/BoundingVolume.cpp#L206)):*
> ```cpp
> 
> std::string AxisAlignedBoundingBox::ToString() const {
>     const core::Dtype dtype = min_bound_.GetDtype();
> ```

update: moved this globally [dtype_ as member function].
___
*[`cpp/open3d/t/geometry/BoundingVolume.cpp` line 262 at r2](https://reviewable.io/reviews/isl-org/open3d/5267#-N7Zz6Y8E4I4qzqb8_aJ:-N7Zz6Y8E4I4qzqb8_aK:b1ps4c7) ([raw file](https://github.com/isl-org/open3d/blob/ee567b2e7cbb28ed3926e925dc9a1d6034cc6c3b/cpp/open3d/t/geometry/BoundingVolume.cpp#L262)):*
> ```cpp
> }
> 
> bool AxisAlignedBoundingBox::CheckValid(bool exception) const {
> ```

see the above comment related to `CheckValid`
___
*[`cpp/open3d/t/geometry/BoundingVolume.cpp` line 62 at r3](https://reviewable.io/reviews/isl-org/open3d/5267#-N7ZxFOJCRU9SB3KZ3c7:-N7ZxFOJCRU9SB3KZ3c8:b-ncfp60) ([raw file](https://github.com/isl-org/open3d/blob/9e8b88c75bb14fb90b50367612692ae9e4f7e6a7/cpp/open3d/t/geometry/BoundingVolume.cpp#L62)):*
> ```cpp
> 
>     // Check if the bounding box is valid.
>     if (Volume() < 0) {
> ```

update: We can check Volume directly, the CheckValid function was not required. When the error is thrown, the traceback is more clear coming from the function directly, so prefer having error statements in the main function over helper/util functions.
___
*[`cpp/open3d/t/geometry/BoundingVolume.cpp` line 204 at r3](https://reviewable.io/reviews/isl-org/open3d/5267#-N7ZxkVY2QJZs58z32tI:-N7ZxkVY2QJZs58z32tJ:bsvb4r1) ([raw file](https://github.com/isl-org/open3d/blob/9e8b88c75bb14fb90b50367612692ae9e4f7e6a7/cpp/open3d/t/geometry/BoundingVolume.cpp#L204)):*
> ```cpp
> }
> 
> core::Tensor AxisAlignedBoundingBox::GetBoxPoints() const {
> ```

previously:
```cpp
core::Tensor AxisAlignedBoundingBox::GetBoxPoints() const {
    const core::Tensor extent = GetExtent().To(core::Float32);
    core::Tensor points =
            core::Tensor::Zeros({8, 3}, core::Float32, GetDevice());
    const float *extent_data = extent.GetDataPtr<float>();

    points[0] = min_bound_;
    points[1] = min_bound_ +
                core::Tensor::Init<float>({extent_data[0], 0, 0}, GetDevice());
    points[2] = min_bound_ +
                core::Tensor::Init<float>({0, extent_data[1], 0}, GetDevice());
    points[3] = min_bound_ +
                core::Tensor::Init<float>({0, 0, extent_data[2]}, GetDevice());
    points[4] = max_bound_;
    points[5] = max_bound_ +
                core::Tensor::Init<float>({-extent_data[0], 0, 0}, GetDevice());
    points[6] = max_bound_ +
                core::Tensor::Init<float>({0, -extent_data[1], 0}, GetDevice());
    points[7] = max_bound_ +
                core::Tensor::Init<float>({0, 0, -extent_data[2]}, GetDevice());
    return points;
}
```

update:
```cpp
core::Tensor AxisAlignedBoundingBox::GetBoxPoints() const {
    const core::Tensor extent_3x3 =
            core::Tensor::Eye(3, GetDtype(), GetDevice())
                    .Mul(GetExtent().Reshape({3, 1}));

    return core::Concatenate({min_bound_.Reshape({1, 3}),
                              min_bound_.Reshape({1, 3}) + extent_3x3,
                              max_bound_.Reshape({1, 3}),
                              max_bound_.Reshape({1, 3}) - extent_3x3});
}
```

Avoid working with pointers, if tensor ops can be used. The previous implementation will also not work when the Tensor is on GPU, as you can't work with a pointer to GPU memory on CPU directly.

**Review by reyanshsolis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5267)* status: 0 of 22 files reviewed, 5 unresolved discussions (waiting on @benjaminum, @errissa, @ssheorey, @yuecideng, and @yxlao)

___
*[`cpp/open3d/t/geometry/BoundingVolume.h` line 173 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7ulJjxBYpV-CPhoR2-:-N7ulJjxBYpV-CPhoR20:b-3k8plm) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/open3d/t/geometry/BoundingVolume.h#L173)):*
> ```objc
> 
>     double GetXPercentage(double x) const;
>     double GetYPercentage(double y) const;
> ```

leave one line space between function declaration.
___
*[`cpp/pybind/t/geometry/boundingvolume.cpp` line 63 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7unFHr72UAlOYP2rgi:-N7unFHsC5iT1vFFZs3S:b-s4518w) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/pybind/t/geometry/boundingvolume.cpp#L63)):*
> ```cpp
>         - AxisAlignedBoundingBox::GetColor()
>         - AxisAlignedBoundingBox::SetColor(const core::Tensor &color)
>     - Value tensor must have shape {3}.
> ```

update the constructor description from the updated cpp docstrings. Mention the supported dtypes and range for color values.
___
*[`cpp/pybind/t/geometry/boundingvolume.cpp` line 174 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7umbvTDE_7Z2HcaRES:-N7umbvTDE_7Z2HcaRET:b-gcr7aj) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/pybind/t/geometry/boundingvolume.cpp#L174)):*
> ```cpp
>             {{"translation",
>               "Transformation [Tensor of shape (4,4)].  Should be on "
>               "the same "
> ```

It should be Translation, not Transformation and the translation tensor must be {3,} not {4, 4}.
___
*[`cpp/pybind/t/geometry/boundingvolume.cpp` line 180 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7umpuF72WZzhgk0dLG:-N7umpuF72WZzhgk0dLH:b-nqbe4w) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/pybind/t/geometry/boundingvolume.cpp#L180)):*
> ```cpp
>             m, "AxisAlignedBoundingBox", "scale",
>             {{"scale", "The scale parameter."},
>              {"center", "Center used for the scaling operation."}});
> ```

mention the supported dtype and shape for `center` and other parameters. (in most of the cases the `dtype must be same as bounding box dtype`.
___
*[`cpp/tests/t/geometry/BoundingVolume.cpp` line 73 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7uncNoCSdveKSPZK9a:-N7uncNoCSdveKSPZK9b:by987gj) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/tests/t/geometry/BoundingVolume.cpp#L73)):*
> ```cpp
>     EXPECT_EQ(aabb.GetDevice(), core::Device("CPU:0"));
> 
>     // ToString
> ```

Change comment `ToString` to `Print Information.`. (add the `.`).

**Comment by reyanshsolis** [comment]
LGTM after minor changes.

**Review by yuecideng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5267)* status: 0 of 22 files reviewed, 5 unresolved discussions (waiting on @benjaminum, @errissa, @reyanshsolis, @ssheorey, and @yxlao)

___
*[`cpp/open3d/t/geometry/BoundingVolume.h` line 173 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7ulJjxBYpV-CPhoR2-:-N7yeaeS-ikSE3tQugxe:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/open3d/t/geometry/BoundingVolume.h#L173)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

leave one line space between function declaration.
</blockquote></details>

Done.
___
*[`cpp/pybind/t/geometry/boundingvolume.cpp` line 63 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7unFHr72UAlOYP2rgi:-N7yehMJ4eEjy_qkRlct:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/pybind/t/geometry/boundingvolume.cpp#L63)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

update the constructor description from the updated cpp docstrings. Mention the supported dtypes and range for color values.
</blockquote></details>

Done.
___
*[`cpp/pybind/t/geometry/boundingvolume.cpp` line 174 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7umbvTDE_7Z2HcaRES:-N7yeiwB3DrY2F0C8PgY:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/pybind/t/geometry/boundingvolume.cpp#L174)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

It should be Translation, not Transformation and the translation tensor must be {3,} not {4, 4}.
</blockquote></details>

Done.
___
*[`cpp/pybind/t/geometry/boundingvolume.cpp` line 180 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7umpuF72WZzhgk0dLG:-N7yelLE4ReMDHy_Nt4r:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/pybind/t/geometry/boundingvolume.cpp#L180)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

mention the supported dtype and shape for `center` and other parameters. (in most of the cases the `dtype must be same as bounding box dtype`.
</blockquote></details>

Done.
___
*[`cpp/tests/t/geometry/BoundingVolume.cpp` line 73 at r4](https://reviewable.io/reviews/isl-org/open3d/5267#-N7uncNoCSdveKSPZK9a:-N7yemrP8-XZ-Uu5qkp4:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/9b6c8dd8ea3dea7640ed711b7c140c324f56b657/cpp/tests/t/geometry/BoundingVolume.cpp#L73)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

Change comment `ToString` to `Print Information.`. (add the `.`).
</blockquote></details>

Done.

**Pull request merged**
