### PR TITLE
Add batch support in voxelize op

### PR DESCRIPTION
**Pull request by sanskar107**
Added batch support in voxelize op (CPU and CUDA).
Added unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3694)

### CODE REVIEW

**Review by benjaminum — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3694)* status: 10 of 11 files reviewed, 11 unresolved discussions (waiting on @sanskar107)

___
*[cpp/open3d/ml/impl/misc/Voxelize.h, line 125 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejhjVi79lsMk7c4hDl:-MejhjVi79lsMk7c4hDm:b360ylw) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.h#L125)):*
> ```objc
>     }
>     const int64_t batch_hash = strides[NDIM - 1] * extents[NDIM - 1];
>     const int64_t invalid_hash = batch_hash * MAX_BATCH_SIZE;
> ```

using `batch_size` instead of `MAX_BATCH_SIZE` would work too for defining the invalid value, right?
___
*[cpp/open3d/ml/impl/misc/Voxelize.h, line 174 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejhGJ_EdM9pG9EP9yM:-MejhGJ_EdM9pG9EP9yN:b-yqld2l) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.h#L174)):*
> ```objc
>                 for (int64_t i = r.begin(); i != r.end(); ++i) {
>                     int64_t batch_id = hashes_indices[i].first / batch_hash;
>                     if (batch_id >= batch_size) break;
> ```

This `break` is good. Better than the previous solution.
___
*[cpp/open3d/ml/impl/misc/Voxelize.h, line 201 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejhRys7ETIFqmGTKi4:-MejhRys7ETIFqmGTKi5:b-o9vmr) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.h#L201)):*
> ```objc
>     out_batch_splits[0] = 0;
> 
>     tbb::parallel_scan(
> ```

`batch_size` is rather small. single thread would have been fine too.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 102 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-Meji5-8EoGDeQNDATfW:-Meji5-8EoGDeQNDATfX:bb7phvt) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L102)):*
> ```Cuda
> }
> 
> /// This funciton computes batch_id from hash value.
> ```

typo
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 141 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-Mejiv9b9Umj_a2nHmC2:-Mejiv9b9Umj_a2nHmC3:bb7phvt) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L141)):*
> ```Cuda
> }
> 
> /// This funciton computes number of voxels per batch element.
> ```

typo
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 238 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejjFZ933YciR6FHh8P:-MejjFZ933YciR6FHh8Q:bvyun1l) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L238)):*
> ```Cuda
>         int64_t h = coords.dot(strides);
>         h += indices_batches[linear_idx] * batch_hash;  // add hash for batch_id
>         hashes[linear_idx] = h;  // add 1 and use 0 as invalid
> ```

My mistake. This comment is wrong. An early version used 0 to mark points outside the range but this is not true anymore.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 240 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejjYSR20niSRgDyMS-:-MejjYSR20niSRgDyMS0:bkoym9r) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L240)):*
> ```Cuda
>         hashes[linear_idx] = h;  // add 1 and use 0 as invalid
>     } else {
>         hashes[linear_idx] = invalid_hash;  // 0 means invalid
> ```

Again my mistake.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 244 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejjcOF12RGVvQExNb7:-MejjcOF12RGVvQExNb8:buahy5a) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L244)):*
> ```Cuda
> }
> 
> /// This function computes the a hash (linear index+1) for each point.
> ```

and again (no +1)
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 645 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejkXbQ37evYEyfOKnI:-MejkXbQ37evYEyfOKnJ:b9mx5yz) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L645)):*
> ```Cuda
>     }
>     const int64_t batch_hash = strides[NDIM - 1] * extents[NDIM - 1];
>     const int64_t invalid_hash = batch_hash * MAX_BATCH_SIZE;
> ```

Same here. `batch_size` should work and then we don't need the definition.
___
*[cpp/open3d/ml/pytorch/misc/VoxelizeOps.cpp, line 102 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-Mejm8Cr6we3hOptbR9T:-Mejm8Cr6we3hOptbR9U:bhme3wt) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/pytorch/misc/VoxelizeOps.cpp#L102)):*
> ```cpp
> 
> static auto registry_batch = torch::RegisterOperators(
>         "open3d::voxelize_batch(Tensor points, Tensor row_splits, "
> ```

Would it be OK to keep the name `voxelize` or will this cause problems?
___
*[cpp/open3d/ml/tensorflow/misc/VoxelizeOps.cpp, line 35 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejmRex3QmEUkuaPMPY:-MejmRex3QmEUkuaPMPZ:b-omjh80) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/tensorflow/misc/VoxelizeOps.cpp#L35)):*
> ```cpp
> using namespace tensorflow;
> 
> REGISTER_OP("Open3DVoxelizeBatch")
> ```

Same for tf.

**Review by sanskar107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3694)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @benjaminum and @sanskar107)

___
*[cpp/open3d/ml/impl/misc/Voxelize.h, line 125 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejhjVi79lsMk7c4hDl:-MfCsXcgCZU_buHJt6Cg:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.h#L125)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

using `batch_size` instead of `MAX_BATCH_SIZE` would work too for defining the invalid value, right?
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Voxelize.h, line 201 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejhRys7ETIFqmGTKi4:-MfCsZK46koHWPvYGweI:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.h#L201)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

`batch_size` is rather small. single thread would have been fine too.
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 102 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-Meji5-8EoGDeQNDATfW:-MfCs_EI8eebcbwvvwh7:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L102)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 141 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-Mejiv9b9Umj_a2nHmC2:-MfCs_eE84N7_U2ywTLU:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L141)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 238 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejjFZ933YciR6FHh8P:-MfCsaOx4aRiCCyZvSEQ:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L238)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

My mistake. This comment is wrong. An early version used 0 to mark points outside the range but this is not true anymore.
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 240 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejjYSR20niSRgDyMS-:-MfCsadI4DTDEXYWk5La:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L240)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Again my mistake.
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 244 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejjcOF12RGVvQExNb7:-MfCsb-d7HNNurO-dOkV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L244)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

and again (no +1)
</blockquote></details>

Done.
___
*[cpp/open3d/ml/impl/misc/Voxelize.cuh, line 645 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejkXbQ37evYEyfOKnI:-MfCscGs0wZ_dWrvQsj1:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/impl/misc/Voxelize.cuh#L645)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Same here. `batch_size` should work and then we don't need the definition.
</blockquote></details>

Done.
___
*[cpp/open3d/ml/pytorch/misc/VoxelizeOps.cpp, line 102 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-Mejm8Cr6we3hOptbR9T:-MfCseti3wfO19jnSBUV:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/pytorch/misc/VoxelizeOps.cpp#L102)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Would it be OK to keep the name `voxelize` or will this cause problems?
</blockquote></details>

Done.
___
*[cpp/open3d/ml/tensorflow/misc/VoxelizeOps.cpp, line 35 at r2](https://reviewable.io/reviews/intel-isl/open3d/3694#-MejmRex3QmEUkuaPMPY:-MfCsidc8LR_kJnALTqo:b-896fix) ([raw file](https://github.com/intel-isl/open3d/blob/c0bb16f4748e81b1761340561c97888428762241/cpp/open3d/ml/tensorflow/misc/VoxelizeOps.cpp#L35)):*
<details><summary><i>Previously, benjaminum (Benjamin Ummenhofer) wrote…</i></summary><blockquote>

Same for tf.
</blockquote></details>

Done.

**Review by benjaminum — CHANGES_REQUESTED** [review]
Looks good. After a minor change to the unit test and making CI pass we can merge.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3694#-:-MfEWbmg0A5l4egrpqo9:b-ewdaud)* status: 1 of 11 files reviewed, 12 unresolved discussions (waiting on @benjaminum and @sanskar107)

___
*[python/test/ml_ops/test_voxelize.py, line 168 at r3](https://reviewable.io/reviews/intel-isl/open3d/3694#-MfEWR-L1ugLLJslMxr_:-MfEWR-L1ugLLJslMxra:bcn9rnm) ([raw file](https://github.com/intel-isl/open3d/blob/e9eade358d531c4c82c51ae21789eabaafd891dd/python/test/ml_ops/test_voxelize.py#L168)):*
> ```Python
> @point_dtypes
> @ndims
> @pytest.mark.parametrize('batch_size', [2, 3, 8, 16])
> ```

Let's add batch_size==1 here

**Review by benjaminum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3694#-:-MfIaL9e8thL3ynoAcVd:bnfp4nl)* status: 1 of 11 files reviewed, 12 unresolved discussions (waiting on @benjaminum and @sanskar107)

**Pull request merged**
