### PR TITLE
Refactor HashMap and backends

### PR DESCRIPTION
**Pull request by theNded**
- Change Block and BlockHash to MiniVec and MiniVecHash
- Remove duplicate functions in DeviceHashBackends and collect shared code snippets in the HashMap caller
- Dispatch value pointers to vectorize copy of value chunks

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3986)

### CODE REVIEW

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3986)* status: 10 of 16 files reviewed, 4 unresolved discussions (waiting on @stotko and @theNded)

___
*[cpp/open3d/core/hashmap/DeviceHashBackend.h, line 110 at r2](https://reviewable.io/reviews/isl-org/open3d/3986#-Mi5tfrm3ax1PelIxvG1:-Mi9YcqZ0eKaUEVIhkep:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/3664084418fb9213f5a7151dab50f1f6e7e2f987/cpp/open3d/core/hashmap/DeviceHashBackend.h#L110)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

I think only providing `capacity` as the argument and infer `bucket_count` as some implementation-specific detail would be better. TBB and stdgpu infer the value internally, and Slab uses `bucket_count = 2 * capacity`. Also see the discussion about `Rehash()` below.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Dispatch.h, line 103 at r2](https://reviewable.io/reviews/isl-org/open3d/3986#-Mi5ngUtEG9AnK0Wsbmg:-Mi9X7k12fDHzFL6oUPw:b-v6s1o3) ([raw file](https://github.com/isl-org/open3d/blob/3664084418fb9213f5a7151dab50f1f6e7e2f987/cpp/open3d/core/hashmap/Dispatch.h#L103)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

These typedefs only seem to be used in the dispatch macro above. Could we remove them?
</blockquote></details>

Removed. 
___
*[cpp/open3d/core/hashmap/HashMap.cpp, line 66 at r2](https://reviewable.io/reviews/isl-org/open3d/3986#-Mi5sBQD58GF_owZjOLs:-Mi9YFU8AedyJLFXE7od:b-yzcct8) ([raw file](https://github.com/isl-org/open3d/blob/3664084418fb9213f5a7151dab50f1f6e7e2f987/cpp/open3d/core/hashmap/HashMap.cpp#L66)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

I think `Rehash()` makes more sense with specifying the new expected *capacity* rather than *buckets*. The latter could be some implementation-specific detail that is inferred from the requested capacity.

Since that is likely a larger change (with some implications), we could discuss this first. Deferring to a future PR would also be okay.
</blockquote></details>

I agree, but the std unordered_map takes the bucket count as input: https://en.cppreference.com/w/cpp/container/unordered_map/rehash.
Maybe we can rename it as resize, and revisit the functionalities for rehash?

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3986)* status: all files reviewed, 3 unresolved discussions (waiting on @theNded)

___
*[cpp/open3d/core/hashmap/Dispatch.h, line 79 at r3](https://reviewable.io/reviews/isl-org/open3d/3986#-MiLG6XU-fd-2agQS7k4:-MiLG6XV4v8-97Vs58AZ:b47ynj1) ([raw file](https://github.com/isl-org/open3d/blob/59ae9c94311d3ce4a2c07948c214f71326ddf023/cpp/open3d/core/hashmap/Dispatch.h#L79)):*
> ```objc
>     [&] {                                              \
>         if (DIVISOR == 16) {                           \
>             using block_t = int4;                      \
> ```

Here, the removed typedefs are still used. Note that theses are the CUDA vector types and may also work here. But we should definitely use `MiniVec<T, N>` here instead.
___
*[cpp/open3d/core/hashmap/HashMap.cpp, line 66 at r2](https://reviewable.io/reviews/isl-org/open3d/3986#-Mi5sBQD58GF_owZjOLs:-MiLGmbp0YylcP6hLGiH:b-38hpqa) ([raw file](https://github.com/isl-org/open3d/blob/3664084418fb9213f5a7151dab50f1f6e7e2f987/cpp/open3d/core/hashmap/HashMap.cpp#L66)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

I agree, but the std unordered_map takes the bucket count as input: https://en.cppreference.com/w/cpp/container/unordered_map/rehash.
Maybe we can rename it as resize, and revisit the functionalities for rehash?
</blockquote></details>

I think `reserve` is a better name as it is also exposed in `std::unordered_map` for exactly this purpose of specifying the new capacity: https://en.cppreference.com/w/cpp/container/unordered_map/reserve. I am leaning towards dropping `Rehash` and replace it by a `Reserve` function.

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3986)* status: 8 of 20 files reviewed, 3 unresolved discussions (waiting on @stotko and @theNded)

___
*[cpp/open3d/core/hashmap/Dispatch.h, line 79 at r3](https://reviewable.io/reviews/isl-org/open3d/3986#-MiLG6XU-fd-2agQS7k4:-MiMM2V31rXdu2LN_kSL:b-97g9bn) ([raw file](https://github.com/isl-org/open3d/blob/59ae9c94311d3ce4a2c07948c214f71326ddf023/cpp/open3d/core/hashmap/Dispatch.h#L79)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Here, the removed typedefs are still used. Note that theses are the CUDA vector types and may also work here. But we should definitely use `MiniVec<T, N>` here instead.
</blockquote></details>

They are used here https://github.com/isl-org/Open3D/blob/wei/hashmap-upgrade/cpp/open3d/core/hashmap/CUDA/StdGPUHashBackend.h#L391, https://github.com/isl-org/Open3D/blob/wei/hashmap-upgrade/cpp/open3d/core/hashmap/CUDA/StdGPUHashBackend.h#L360
in CUDA to increase the performance of copy -- this is because memcpy or byte-by-byte copying is slow in CUDA kernels, and int4 is a built-in primitive that allows fast copying. 
We can use MiniVec instead, but the underlying copy operation might be reduced to smaller primitives (int).
This dispatch pattern is not used in C++ since memcpy in C++ is relatively fast. 
https://github.com/isl-org/Open3D/blob/wei/hashmap-upgrade/cpp/open3d/core/hashmap/CPU/TBBHashBackend.h#L225

Do you think it is reasonable to wrap this dispatch in the CUDACC macro and keep it as it is?
___
*[cpp/open3d/core/hashmap/HashMap.cpp, line 66 at r2](https://reviewable.io/reviews/isl-org/open3d/3986#-Mi5sBQD58GF_owZjOLs:-MiMNl03-sIuW2jbE5FS:b-4t9upe) ([raw file](https://github.com/isl-org/open3d/blob/3664084418fb9213f5a7151dab50f1f6e7e2f987/cpp/open3d/core/hashmap/HashMap.cpp#L66)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

I think `reserve` is a better name as it is also exposed in `std::unordered_map` for exactly this purpose of specifying the new capacity: https://en.cppreference.com/w/cpp/container/unordered_map/reserve. I am leaning towards dropping `Rehash` and replace it by a `Reserve` function.
</blockquote></details>

Sounds reasonable, upgraded with interface and doc changes.

**Review by stotko — COMMENTED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3986)* status: all files reviewed, 3 unresolved discussions (waiting on @theNded)

___
*[cpp/open3d/core/hashmap/Dispatch.h, line 79 at r3](https://reviewable.io/reviews/isl-org/open3d/3986#-MiLG6XU-fd-2agQS7k4:-MiMcCe18LH2kzHbgkRe:bfinpmb) ([raw file](https://github.com/isl-org/open3d/blob/59ae9c94311d3ce4a2c07948c214f71326ddf023/cpp/open3d/core/hashmap/Dispatch.h#L79)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

They are used here https://github.com/isl-org/Open3D/blob/wei/hashmap-upgrade/cpp/open3d/core/hashmap/CUDA/StdGPUHashBackend.h#L391, https://github.com/isl-org/Open3D/blob/wei/hashmap-upgrade/cpp/open3d/core/hashmap/CUDA/StdGPUHashBackend.h#L360
in CUDA to increase the performance of copy -- this is because memcpy or byte-by-byte copying is slow in CUDA kernels, and int4 is a built-in primitive that allows fast copying. 
We can use MiniVec instead, but the underlying copy operation might be reduced to smaller primitives (int).
This dispatch pattern is not used in C++ since memcpy in C++ is relatively fast. 
https://github.com/isl-org/Open3D/blob/wei/hashmap-upgrade/cpp/open3d/core/hashmap/CPU/TBBHashBackend.h#L225

Do you think it is reasonable to wrap this dispatch in the CUDACC macro and keep it as it is?
</blockquote></details>

I see. Wrapping them by `__CUDACC__` and adding a comment somewhere (probably above `DISPATCH_DIVISOR_SIZE_TO_BLOCK_T`) should be sufficient.
___
*[cpp/open3d/core/hashmap/HashMap.cpp, line 69 at r4](https://reviewable.io/reviews/isl-org/open3d/3986#-MiMcnYv2g12RD54SOWF:-MiMcnYv2g12RD54SOWG:by3cuzn) ([raw file](https://github.com/isl-org/open3d/blob/8a66cfe91e7fd4e490f75e3e9857336248117e9a/cpp/open3d/core/hashmap/HashMap.cpp#L69)):*
> ```cpp
>     int64_t count = Size();
>     if (capacity <= count) {
>         utility::LogDebug("Target capacity smaller then current size, abort.");
> ```

There is no `return` statement here, but the message indicates that we should stop at this point. Where is this handled?

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3986)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @stotko and @theNded)

___
*[cpp/open3d/core/hashmap/Dispatch.h, line 79 at r3](https://reviewable.io/reviews/isl-org/open3d/3986#-MiLG6XU-fd-2agQS7k4:-MiMhAVa-QinkxjTMzE6:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/59ae9c94311d3ce4a2c07948c214f71326ddf023/cpp/open3d/core/hashmap/Dispatch.h#L79)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

I see. Wrapping them by `__CUDACC__` and adding a comment somewhere (probably above `DISPATCH_DIVISOR_SIZE_TO_BLOCK_T`) should be sufficient.
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/HashMap.cpp, line 69 at r4](https://reviewable.io/reviews/isl-org/open3d/3986#-MiMcnYv2g12RD54SOWF:-MiMhBF_1850eOX_rH1C:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/8a66cfe91e7fd4e490f75e3e9857336248117e9a/cpp/open3d/core/hashmap/HashMap.cpp#L69)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

There is no `return` statement here, but the message indicates that we should stop at this point. Where is this handled?
</blockquote></details>

Done.

**Review by stotko — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3986)* status: all files reviewed, 1 unresolved discussion (waiting on @theNded)

**Pull request merged**
