### PR TITLE
Fix typos in NearestNeighborSearch.h

### PR DESCRIPTION
**Pull request by mone27**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Checklist:

-   [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

Fix typos in NearestNeighborSearch.h docstrings

### CODE REVIEW

**Review by ssheorey — COMMENTED** [review]
Hi @mone27 thanks for fixing the typos. You can find other identical typos with this:
```sh
$ git grep indicecs # from repo main folder
cpp/open3d/core/nns/NNSIndex.h:    /// - indicecs: Tensor of shape {total_num_neighbors,}, dtype Int32.
cpp/open3d/core/nns/NNSIndex.h:    /// - indicecs: Tensor of shape {total_num_neighbors,}, dtype Int32.
cpp/open3d/core/nns/NanoFlannIndex.h:    /// - indicecs: Tensor of shape {total_num_neighbors,}, dtype Int32.
cpp/open3d/core/nns/NanoFlannIndex.h:    /// - indicecs: Tensor of shape {total_num_neighbors,}, dtype Int32.
cpp/open3d/core/nns/NearestNeighborSearch.h:    /// - indicecs: Tensor of shape {total_number_of_neighbors,}, with dtype
cpp/open3d/core/nns/NearestNeighborSearch.h:    /// - indicecs: Tensor of shape {total_number_of_neighbors,}, with dtype
``` 
Would you be able to fix those as well? (Also for `distainces`...)

**Comment by mone27** [comment]
Yes sure! Didn't realized that there are similar issues in also other files

**Comment by mone27** [comment]
I should have fixed now all indices and distances typos in `core/nns`

**Review by ssheorey — APPROVED** [review]
Thanks @mone27 !

**Pull request merged**
