### PR TITLE
Make plane segmentation from point cloud deterministic

### PR DESCRIPTION
**Pull request by jkuck**
This change makes the results deterministic when a random seed is set.

## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [ ] I will follow up and update the code if CI fails.
    
-   [ ] For fork PRs, I have selected **Allow edits from maintainers**.

### CODE REVIEW

**Review by ssheorey — APPROVED** [review]

**Comment by ssheorey** [comment]
Thanks @jkuck !

**Comment by jkuck** [comment]
Thanks for updating the title @ssheorey! Would you please help me fix the failing style check?

**Comment by yuecideng** [comment]
Hi @jkuck, please check the style guide: https://www.open3d.org/docs/release/contribute/styleguide.html

**Comment by jkuck** [comment]
Thanks @yuecideng! I fixed the formatting using your instructions.

**Comment by jkuck** [comment]
@ssheorey, @yuecideng it looks like we are waiting on workflows to complete before merging.  Do you know what needs to be done to kick the workflows off? Thanks.

**Comment by jkuck** [comment]
@ssheorey I see that all checks have passed now.  Are we waiting on anything else to merge?

**Comment by ssheorey** [comment]
Thanks @jkuck ! Merged.

**Comment by jkuck** [comment]
Thank you!

**Pull request merged**
