### PR TITLE
Batch Radius Search and Hybrid Search

### PR DESCRIPTION
**Pull request by junha-l**
Done
- Enable batch search for GPU fixed radius search & GPU hybrid search
- Add unit test for batch fixed radius search & hybrid search

TODO
- [x] Replace  FixedRadiusSearch  inside ml/misc namespace with core/nns one  (#3768)
- [x] Move CPU version of hash-based FixedRadiusSearch to core/nns namespace (#3768)
- [ ] Add new batch search function. using  *_row_splits tensors

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3670)

### CODE REVIEW

**Review by benjaminum — CHANGES_REQUESTED** [review]
Can you remove `cpp/open3d/ml/impl/misc/FixedRadiusSearch.x` and make the ml ops work with the nns in core?

It is OK to use internal functions of the nns core since the building of the hash map is a separate op in the ml module.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3670#-:-MdqZ29CBNnS5MHwRXL_:b-op71rv)* status: 0 of 4 files reviewed, all discussions resolved

**Comment by junha-l** [comment]
@benjaminum 
I'm trying to replace ```cpp/open3d/ml/impl/misc/FixedRadiusSearch.cuh``` with core/nns/FixedRadiusSearch and there are some problems that i'm facing now. 

1. We don't have CPU implementation of hash-based FixedRadiusSearch in core/nns. So we can not remove ```cpp/open3d/ml/imp/misc/FixedRadiusSearch.h```.

2. There are some linking errors while compiling pybind. 
```
Namespace(input_ops_py_in='/root/code/Open3D/python/open3d/ml/torch/python/ops.py.in', input_return_types_py_in='/root/code/Open3D/python/open3d/ml/torch/python/return_types.py.in', lib='/root/code/Open3D/build/lib/RelWithDebInfo/cuda/open3d_torch_ops.so', output_dir='/root/code/Open3D/build/lib/ml/torch/python/', tensorflow_ops_dir='/root/code/Open3D/cpp/pybind/../open3d/ml/tensorflow')
Traceback (most recent call last):
  File "generate_torch_ops_wrapper.py", line 195, in <module>
    sys.exit(main())
  File "generate_torch_ops_wrapper.py", line 131, in main
    torch.ops.load_library(args.lib)
  File "/opt/anaconda3/envs/open3d/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/opt/anaconda3/envs/open3d/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/code/Open3D/build/lib/RelWithDebInfo/cuda/open3d_torch_ops.so: undefined symbol: _Z25BuildSpatialHashTableCUDAIfEvRKN2at6TensorEdS3_RKSt6vectorIjSaIjEERS1_S9_
cpp/pybind/CMakeFiles/python-package.dir/build.make:74: recipe for target 'lib/ml/torch/python/ops.py' failed
make[3]: *** [lib/ml/torch/python/ops.py] Error 1
CMakeFiles/Makefile2:3847: recipe for target 'cpp/pybind/CMakeFiles/python-package.dir/all' failed
make[2]: *** [cpp/pybind/CMakeFiles/python-package.dir/all] Error 2
CMakeFiles/Makefile2:3801: recipe for target 'cpp/pybind/CMakeFiles/install-pip-package.dir/rule' failed
make[1]: *** [cpp/pybind/CMakeFiles/install-pip-package.dir/rule] Error 2
Makefile:1053: recipe for target 'install-pip-package' failed
make: *** [install-pip-package] Error 2
```
Do we have to modify cmake chain to use ```core/nns``` code inside the ```ml/pytorch``` namespace?

**Comment by benjaminum** [comment]
@junha-l 
1. Can we move the CPU code to `core/nns`?
2. I see that we link the open3d library in the cmake file for pytorch. Did you check if the function arguments match? Maybe the function signature is slightly different.

**Comment by benjaminum** [comment]
@junha-l Is this PR still relevant after merging #3768 ? Can we close it?

**Comment by junha-l** [comment]
Closed since it is duplicated with the merged PR #3768

**Pull request closed without merging**
