### PR TITLE
Upgrade stdgpu to latest version

### LINKED ISSUE #6743: `stdgpu` target fails the CMake configure step with CUDA 12.4 due to changes in Thrust version header
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Windows 11 with VS2022, latest MSVC, with CUDA 12.4) with:
```
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CUDA_MODULE=ON -DBUILD_WEBRTC=OFF ..
# Then Open Visual Studio 2022 and build Open3D (or just the stdgpu target).
```

### Error message

```shell
[13/148] Performing configure step for 'ext_stdgpu'
  CMake Error at cmake/Findthrust.cmake:17 (math):
  math cannot parse the expression: "200301 // macro expansion with ##
  requires this to be a single value / 100000": syntax error, unexpected
  exp_DIVIDE (9).
Call Stack (most recent call first):
  src/stdgpu/CMakeLists.txt:7 (find_package)
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find thrust: Found unsuitable version "ERROR.ERROR.ERROR", but
    required is at least "1.9.2" (found C:/Program Files/NVIDIA GPU Computing
    Toolkit/CUDA/v12.4/include)
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 11 64-bit
- Python version: not applicable
- Open3D version: latest main (8 Apr 2024)
- System architecture: x64
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64
```

### Additional information

This error occurs because `cmake/Findthrust.cmake` extracts the Thrust version from Thrust's header file. In CUDA 12.3 (and presumably earlier), the line in the Thrust header looks like:

`#define THRUST_VERSION 200200`

And in CUDA 12.4 it is:

`#define THRUST_VERSION 200301 // macro expansion with ## requires this to be a single value`

Thus, CMake's regexp in `cmake/Findthrust.cmake` fails as it encounters the unexpected trailing comment on that line.

### PR DESCRIPTION
**Pull request by stotko**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6743
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

See detailed description below.

## Checklist:

-   [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

Compilation with CUDA 12.4 and newer will fail due to breaking changes in thrust 2.3.0 (bundled with CUDA 12.4). In particular, there are 2 independent changes in thrust that broke compatibility with stdgpu:

1. The previous hand-crafted and limited implementation of `thrust::pair` has been replaced by the more compliant `cuda::std::pair` implementation (see https://github.com/NVIDIA/cccl/releases/tag/v2.3.0). This has been fixed upstream in https://github.com/stotko/stdgpu/pull/425 via a custom `pair` implementation.

2. The implementation of thrust's namespace has been changed to include an ABI identifier which fixes linkage issues between different versions of thrust (see https://github.com/NVIDIA/cccl/releases/tag/v2.3.0 again). Since stdgpu needs to specialize some of thrust's internal classes to enable interoperability, this also broke compatibility. The issue has since also been fixed upstream in https://github.com/stotko/stdgpu/pull/428. However, the fix **requires CUDA 11.5 or newer** and has been advertised in https://github.com/stotko/stdgpu/pull/429.

Thus, upgrade stdgpu to the latest version to enable support for CUDA 12.4 and newer. This also includes moving from `thrust::pair` to `stdgpu::pair` in the respective hash map backend and should be more future-proof. However, this also means that Open3D would need to bump its CUDA requirements in alignment with stdgpu to at least CUDA 11.5. I would argue that this is acceptable since:

- Ubuntu 20.04 reaches EOL in < 6 months. The oldest CUDA version supporting Ubuntu 22.04 is CUDA 11.7.
- The most recent MSVC compiler bumped the minimum required CUDA even from 11.6 to 12.4 (see https://github.com/microsoft/STL/pull/4475).
- New GPU generations need the most recent CUDA toolkit at the time of their release anyways, e.g. RTX 30XX --> 11.1, RTX 40XX --> 11.8, and the upcoming RTX 50XX --> 12.7/12.8 ?!

I only focused on the fix itself and have not yet updated the documentation or the CUDA version checks in CMake. This needs to be added if the proposed fix is deemed acceptable.

Further discussion and respective user bug reports (mostly on Windows) can be found here:
- https://github.com/isl-org/Open3D/issues/6743
- https://github.com/isl-org/Open3D/discussions/7055
- https://github.com/stotko/stdgpu/issues/417

### CODE REVIEW

**Comment by stotko** [comment]
Failing CI runs look unrelated to this PR. Furthermore, the more relevant CUDA runs were skipped since this PR is from my fork. But I got positive replies from Windows users and tested the fix myself on Ubuntu 22.04, so I hope that's fine.

**Comment by patrikhuber** [comment]
Big +1 from me for this PR - this is critical. Without it, Open3D doesn't compile on a recent CUDA version on MSVC. Can this be merged please?

@stotko I think you may also want to put `#include <stdgpu/utility.h>` at the top of the header with the changes?

**Comment by stotko** [comment]
> @stotko I think you may also want to put `#include <stdgpu/utility.h>` at the top of the header with the changes?

Good catch, thanks. Should be included now.

**Comment by ssheorey** [comment]
Thanks @stotko !

**Comment by stotko** [comment]
> Thanks @stotko ! Are you also planning to update the docs / CUDA version checks?

I can update them if you would like to have that in this PR as well. I first wanted some feedback on the fix itself before going too deep. Because, technically, this breaks compatibility with very old CUDA versions < 11.5.

**Comment by ssheorey** [comment]
Upgrading to CUDA 11.5+ sounds good. Please go ahead with the docs / cmake updates and we will gladly merge it.

**Comment by stotko** [comment]
Done. While updating the main CUDA version check within CMake, I have also checked for further occurrences and simplified some code that now does not need a version check anymore. Furthermore, I have set the "recommended" CUDA version to 12+ since PyTorch and TensorFlow require it (or at least recommend it as well).

**Pull request merged**
