### PR TITLE
NNS Benchmark

### PR DESCRIPTION
**Pull request by junha-l**
Python scripts for NNS benchmark.

There are two benchmarks. 

1. `examples/python/benchmark/benchmark_nns.py`
It compares the execution time of search methods (i.e. Knn, Radius, Hybrid) of `NearestNeighborSearch` module on CPU and GPU with both real-world and synthetic datasets.

2. `python/benchmarks/core/test_nns.py`
`pytest-benchmark` style benchmark following #4117.

We keep 1 for convenience.

#### `examples/python/benchmark/benchmark_nns.py`

```bash
(in `examples/python/benchmark`)
python benchmark_nns.py --search_type {knn,radius,hybrid}
```

#### `python/benchmarks/core/test_nns.py`
```bash
pip install pytest-benchmark
(in root dir)
pytest python/benchmarks/core/test_nns.py --benchmark-sort=name
```

TODO:
- [x] Upload benchmark data to `open3d_donwload`.
- [x] Automatic download benchmark data.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3866)

### CODE REVIEW

**Comment by junha-l** [comment]
Hi @reyanshsolis, could you share the results of the benchmark on your machine?

You can use the following command
```
cd examples/python/benchmark
python benchmark_nns.py
```

**Comment by junha-l** [comment]
2080Ti, CUDA 10.1
```
CUDA version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


OS
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

CPU
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz

                                 O3DKnn_setup    O3DFaiss_setup    O3DKnn_search    O3DFaiss_search
-----------------------------  --------------  ----------------  ---------------  -----------------
small_tower.ply n=999766 k=1       9.04e-06           0.0860213       2.87904           17.9639
small_tower.ply n=99977 k=1        9.418e-06          0.0850432       0.037345           0.172075
small_tower.ply n=9998 k=1         9.35e-06           0.0843127       0.00129009         0.00188861
small_tower.ply n=999766 k=37      9.0125e-06         0.0862409       3.49937           22.1008
small_tower.ply n=99977 k=37       9.351e-06          0.0843452       0.100539           0.217918
small_tower.ply n=9998 k=37        9.409e-06          0.0845197       0.00364503         0.00275777
small_tower.ply n=999766 k=64      9.256e-06          0.0863909       4.23619           21.9955
small_tower.ply n=99977 k=64       9.362e-06          0.0849103       0.21869            0.220034
small_tower.ply n=9998 k=64        9.3505e-06         0.0845221       0.00663426         0.00300688
random n=999766 k=1                9.0445e-06         0.0863092       3.11598           17.9854
random n=99977 k=1                 9.4375e-06         0.084914        0.0384183          0.172104
random n=9998 k=1                  9.3375e-06         0.0847216       0.00131387         0.00189533
random n=999766 k=37               8.992e-06          0.0866912       3.76913           22.307
random n=99977 k=37                9.334e-06          0.0850463       0.13933            0.220647
random n=9998 k=37                 9.351e-06          0.0849147       0.0042894          0.00294493
random n=999766 k=64               8.9415e-06         0.0868012       4.86126           22.2982
random n=99977 k=64                9.276e-06          0.0851473       0.280077           0.225574
random n=9998 k=64                 9.384e-06          0.0850994       0.00904128         0.00321946
```

Titan RTX, CUDA 10.1
```
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


OS
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

CPU
model name      : Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz

                                 O3DKnn_setup    O3DFaiss_setup    O3DKnn_search    O3DFaiss_search
-----------------------------  --------------  ----------------  ---------------  -----------------
small_tower.ply n=999766 k=1      1.89855e-05          0.197316       2.83947           16.5443
small_tower.ply n=99977 k=1       2.4452e-05           0.19517        0.0335835          0.157475
small_tower.ply n=9998 k=1        2.4624e-05           0.195061       0.00141308         0.00185937
small_tower.ply n=999766 k=37     1.91215e-05          0.19741        3.3097            20.6586
small_tower.ply n=99977 k=37      2.4377e-05           0.195261       0.0946953          0.198034
small_tower.ply n=9998 k=37       2.44625e-05          0.19508        0.00354918         0.00282025
small_tower.ply n=999766 k=64     1.90875e-05          0.197438       3.90461           20.9376
small_tower.ply n=99977 k=64      2.4475e-05           0.195326       0.195781           0.196667
small_tower.ply n=9998 k=64       2.44765e-05          0.194398       0.00615909         0.00299955
random n=999766 k=1               1.9082e-05           0.196841       2.83551           16.6121
random n=99977 k=1                2.44815e-05          0.194661       0.0328403          0.158084
random n=9998 k=1                 2.446e-05            0.194367       0.00127421         0.0018587
random n=999766 k=37              1.9097e-05           0.196856       3.47563           20.8512
random n=99977 k=37               2.44515e-05          0.194669       0.127378           0.200564
random n=9998 k=37                2.4379e-05           0.19443        0.00455083         0.00295635
random n=999766 k=64              1.9004e-05           0.196793       4.45722           21.2729
random n=99977 k=64               2.4383e-05           0.194726       0.252819           0.201176
random n=9998 k=64                2.4501e-05           0.194485       0.00856065         0.00305025
```

**Comment by reyanshsolis** [comment]
```
CUDA version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0


OS
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


CPU
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
model name	: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

                                 O3DKnn_setup    O3DFaiss_setup    O3DKnn_search    O3DFaiss_search
-----------------------------  --------------  ----------------  ---------------  -----------------
small_tower.ply n=999766 k=1      1.1249e-05           0.1089        26.3079            82.5646
small_tower.ply n=99977 k=1       1.61725e-05          0.10672        0.28144            0.832507
small_tower.ply n=9998 k=1        1.56455e-05          0.106426       0.00278232         0.00869105
small_tower.ply n=999766 k=37     1.21615e-05          0.110713      32.986             93.8945
small_tower.ply n=99977 k=37      1.25065e-05          0.123809       0.482907           0.945196
small_tower.ply n=9998 k=37       1.24575e-05          0.123283       0.0241638          0.0119115
small_tower.ply n=999766 k=64     1.213e-05            0.129623      36.211             95.8148
small_tower.ply n=99977 k=64      1.216e-05            0.108034       0.803097           0.971234
small_tower.ply n=9998 k=64       1.2138e-05           0.10945        0.0472074          0.0129342
random n=999766 k=1               1.1224e-05           0.113705      26.3729            82.569
random n=99977 k=1                1.5719e-05           0.108721       0.28196            0.83256
random n=9998 k=1                 1.2382e-05           0.108432       0.00276723         0.00868353
random n=999766 k=37              1.11225e-05          0.114307      34.3504            93.3562
random n=99977 k=37               1.2446e-05           0.112728       0.704474           0.957899
random n=9998 k=37                1.24065e-05          0.115029       0.0319894          0.0128759
random n=999766 k=64              1.12715e-05          0.116665      39.8562            96.3701
random n=99977 k=64               1.25245e-05          0.121116       1.22134            1.00614
random n=9998 k=64                1.5652e-05           0.131501       0.0640807          0.014624
```

**Comment by yxlao** [comment]
GTX 1080Ti
```
CUDA version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0


OS
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


CPU
model name      : Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz

                                 O3DKnn_setup    O3DFaiss_setup    O3DKnn_search    O3DFaiss_search
-----------------------------  --------------  ----------------  ---------------  -----------------
small_tower.ply n=999766 k=1      8.156e-06            0.119418       6.09679           26.4076
small_tower.ply n=99977 k=1       9.168e-06            0.115865       0.0672223          0.259509
small_tower.ply n=9998 k=1        9.2185e-06           0.115992       0.00180079         0.0027204
small_tower.ply n=999766 k=37     8.078e-06            0.120421       8.49766           29.1477
small_tower.ply n=99977 k=37      9.0825e-06           0.11719        0.186161           0.294065
small_tower.ply n=9998 k=37       9.0955e-06           0.116811       0.00850673         0.00342969
small_tower.ply n=999766 k=64     8.044e-06            0.121023      10.2521            28.9777
small_tower.ply n=99977 k=64      9.172e-06            0.117066       0.381379           0.295737
small_tower.ply n=9998 k=64       9.1645e-06           0.116571       0.0156683          0.00358635
random n=999766 k=1               8.0565e-06           0.120587       6.55336           26.3947
random n=99977 k=1                1.23125e-05          0.116516       0.0697197          0.259449
random n=9998 k=1                 1.21915e-05          0.116231       0.0019806          0.00272116
random n=999766 k=37              8.1105e-06           0.120638       9.24094           29.2972
random n=99977 k=37               1.23015e-05          0.118218       0.265982           0.297414
random n=9998 k=37                1.2305e-05           0.118648       0.0107564          0.00356912
random n=999766 k=64              7.837e-06            0.123094      11.7298            29.2655
random n=99977 k=64               1.2217e-05           0.116779       0.504067           0.301776
random n=9998 k=64                1.22725e-05          0.117923       0.02163            0.00392281
```

**Comment by benjaminum** [comment]
I added bufferkdtree to the comparison

2080 Ti, CUDA 11.0
```
                        knn_gpu_setup    faiss_gpu_setup    bufkd_setup    knn_gpu_search    faiss_gpu_search    bufkd_search
--------------------  ---------------  -----------------  -------------  ----------------  ------------------  --------------
sfm n=999766 k=1          1.123e-05            0.0599312      0.185606         2.6703             17.9122           0.147551
sfm n=99977 k=1           1.0843e-05           0.0592191      0.0852472        0.0316688           0.178125         0.0299441
sfm n=9998 k=1            1.1639e-05           0.0595557      0.0709565        0.00121634          0.0020799        0.0111091
sfm n=999766 k=37         1.13545e-05          0.0593562      0.183164         3.32898            22.191            0.73495
sfm n=99977 k=37          2.04745e-05          0.0586406      0.086492         0.0915719           0.22469          0.083245
sfm n=9998 k=37           1.2154e-05           0.0586502      0.0701425        0.00376394          0.00294235       0.0264544
sfm n=999766 k=64         1.16225e-05          0.0600194      0.182431         4.05315            22.4089           1.10856
sfm n=99977 k=64          1.605e-05            0.0595196      0.0866012        0.193743            0.229653         0.13542
sfm n=9998 k=64           2.0265e-05           0.0591613      0.0710932        0.00741498          0.0033651        0.0342437
random n=999766 k=1       1.14235e-05          0.0603787      0.239865         3.25123            18.442            0.171136
random n=99977 k=1        1.1068e-05           0.0596719      0.0918346        0.0403381           0.181201         0.030766
random n=9998 k=1         1.19315e-05          0.0594302      0.0721116        0.00123665          0.00201116       0.0119139
random n=999766 k=37      1.1365e-05           0.0598296      0.239562         4.02462            22.666            0.532418
random n=99977 k=37       1.16645e-05          0.059481       0.091829         0.14063             0.225697         0.0673354
random n=9998 k=37        1.1657e-05           0.0595529      0.0711284        0.00490048          0.00301484       0.0266703
random n=999766 k=64      1.45555e-05          0.0602808      0.247066         5.06882            23.0197           0.851341
random n=99977 k=64       1.2107e-05           0.0596063      0.0920174        0.279873            0.231822         0.130733
random n=9998 k=64        1.17865e-05          0.0597702      0.0712988        0.00979369          0.00340512       0.0326173
```

**Comment by junha-l** [comment]
I added CPU knn search of open3d

```
======System Info======
[CUDA]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

[OS]
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

[CPU]
model name      : Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz

[GPU]
Thu Aug 12 20:16:08 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 30%   45C    P2    67W / 250W |   1149MiB / 11016MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
======System Info [End]=
                                 O3DKnn_setup    O3DFaiss_setup    O3DKnnCPU_setup    O3DKnn_search    O3DFaiss_search    O3DKnnCPU_search
-----------------------------  --------------  ----------------  -----------------  ---------------  -----------------  ------------------
small_tower.ply n=999766 k=1       8.3245e-06         0.0898473         0.194779         2.84979           17.8544              0.208479
small_tower.ply n=99977 k=1        8.681e-06          0.0888882         0.0157481        0.0360724          0.1732              0.0218698
small_tower.ply n=9998 k=1         8.7325e-06         0.0890421         0.00133613       0.00123466         0.0018989           0.00322514
small_tower.ply n=999766 k=37      8.702e-06          0.0899763         0.192638         3.43283           21.9553              1.03724
small_tower.ply n=99977 k=37       8.652e-06          0.0890888         0.0159415        0.102207           0.217613            0.177232
small_tower.ply n=9998 k=37        8.6855e-06         0.0889828         0.0013393        0.00378847         0.00276668          0.0342208
small_tower.ply n=999766 k=64      8.445e-06          0.0899653         0.196477         4.2203            22.107               1.71389
small_tower.ply n=99977 k=64       8.7365e-06         0.0894103         0.0157327        0.227419           0.219971            0.217881
small_tower.ply n=9998 k=64        8.6905e-06         0.0893664         0.00133478       0.00700521         0.00293801          0.0167631
random n=999766 k=1                8.531e-06          0.0901951         0.222958         3.09874           17.8788              0.229137
random n=99977 k=1                 8.6805e-06         0.0894613         0.0155906        0.0384605          0.173292            0.019383
random n=9998 k=1                  8.673e-06          0.0890402         0.00121837       0.00133712         0.00190108          0.00281831
random n=999766 k=37               8.7325e-06         0.0895269         0.226241         3.76868           22.1639              1.6088
random n=99977 k=37                8.624e-06          0.088996          0.0153263        0.145189           0.219948            0.163612
random n=9998 k=37                 8.6795e-06         0.0887217         0.00121787       0.00458492         0.00291021          0.0117443
random n=999766 k=64               8.323e-06          0.0895886         0.222594         4.87119           22.4181              2.62468
random n=99977 k=64                8.679e-06          0.0900486         0.0154087        0.290863           0.224957            0.273969
random n=9998 k=64                 8.677e-06          0.0894287         0.00121654       0.0100404          0.00325986          0.0269491
```

**Comment by junha-l** [comment]
Results on new datasets
```
                                 O3DKnn_setup    O3DFaiss_setup    O3DKnnCPU_setup    O3DKnn_search    O3DFaiss_search    O3DKnnCPU_search
-----------------------------  --------------  ----------------  -----------------  ---------------  -----------------  ------------------
small_tower.ply n=999766 k=1       5.407e-06          0.0514212        0.192098         2.92444           17.7256              0.205025
small_tower.ply n=99977 k=1        5.482e-06          0.0531975        0.0156659        0.0379669          0.170627            0.0251216
small_tower.ply n=9998 k=1         5.525e-06          0.0530684        0.00133646       0.00125742         0.00187993          0.00236134
small_tower.ply n=999766 k=37      5.62e-06           0.0534706        0.19399          3.57187           21.9829              1.01833
small_tower.ply n=99977 k=37       5.472e-06          0.0527395        0.0156273        0.102681           0.217586            0.116439
small_tower.ply n=9998 k=37        5.509e-06          0.0526059        0.00133405       0.0034705          0.00276973          0.0112947
small_tower.ply n=999766 k=64      5.408e-06          0.053153         0.19195          4.30663           22.2252              1.69105
small_tower.ply n=99977 k=64       5.568e-06          0.052785         0.0157003        0.22937            0.219447            0.209763
small_tower.ply n=9998 k=64        5.5165e-06         0.0526715        0.00133534       0.00661325         0.00294567          0.0168677
kitti_1.ply n=128252 k=1           5.333e-06          0.0528831        0.0179561        0.0578113          0.317871            0.0269099
kitti_1.ply n=12826 k=1            5.4595e-06         0.0530922        0.00169495       0.00167365         0.00296343          0.00247937
kitti_1.ply n=1283 k=1             5.5355e-06         0.053073         0.000137488      0.000194231        9.1166e-05          0.000533239
kitti_1.ply n=128252 k=37          5.444e-06          0.0531487        0.0178733        0.181896           0.379438            0.152695
kitti_1.ply n=12826 k=37           5.454e-06          0.0529289        0.00169477       0.00537276         0.00419633          0.0116901
kitti_1.ply n=1283 k=37            5.498e-06          0.0527391        0.000137496      0.0014711          0.000163687         0.00147098
kitti_1.ply n=128252 k=64          5.561e-06          0.0528997        0.0179823        0.393242           0.383564            0.268681
kitti_1.ply n=12826 k=64           5.465e-06          0.0527849        0.00169478       0.00941951         0.00444893          0.0204591
kitti_1.ply n=1283 k=64            5.525e-06          0.0527685        0.000137548      0.00222124         0.000169332         0.00223404
kitti_2.ply n=121146 k=1           5.2115e-06         0.0528657        0.015797         0.045646           0.268439            0.0253288
kitti_2.ply n=12115 k=1            5.5045e-06         0.0526996        0.00146386       0.00149229         0.00264151          0.00274004
kitti_2.ply n=1212 k=1             5.4705e-06         0.0527783        0.000119639      0.000169387        8.7191e-05          0.000716901
kitti_2.ply n=121146 k=37          5.5645e-06         0.0530368        0.0158097        0.118153           0.328931            0.131481
kitti_2.ply n=12115 k=37           5.498e-06          0.0524738        0.00146506       0.00494029         0.00402575          0.011843
kitti_2.ply n=1212 k=37            5.52e-06           0.0525123        0.000119961      0.00157026         0.000155789         0.00213286
kitti_2.ply n=121146 k=64          5.5195e-06         0.0532098        0.0157868        0.299409           0.33356             0.237233
kitti_2.ply n=12115 k=64           5.4585e-06         0.0531776        0.00146491       0.00867245         0.00425421          0.0184456
kitti_2.ply n=1212 k=64            5.489e-06          0.052698         0.000119611      0.00226674         0.000159487         0.00210737
fluid_1000.ply n=63198 k=1         5.2405e-06         0.0525831        0.00935577       0.0149865          0.0705191           0.0150609
fluid_1000.ply n=6320 k=1          5.441e-06          0.0526884        0.000753444      0.000908629        0.000792339         0.00225957
fluid_1000.ply n=632 k=1           5.438e-06          0.0526921        4.9376e-05       0.00011389         5.1896e-05          0.0006562
fluid_1000.ply n=63198 k=37        5.554e-06          0.0527434        0.00936059       0.0873515          0.0931991           0.0923906
fluid_1000.ply n=6320 k=37         5.424e-06          0.0526053        0.000753833      0.00340888         0.00156933          0.00692935
fluid_1000.ply n=632 k=37          5.445e-06          0.0525105        4.96615e-05      0.000816413        7.35515e-05         0.00114328
fluid_1000.ply n=63198 k=64        5.582e-06          0.0525576        0.00928934       0.183292           0.0961323           0.156763
fluid_1000.ply n=6320 k=64         5.5715e-06         0.0524886        0.000753617      0.00542171         0.00170919          0.0102283
fluid_1000.ply n=632 k=64          5.4655e-06         0.0525061        4.8969e-05       0.00126451         7.35745e-05         0.00118761
s3dis_1.ply n=3840664 k=1          5.583e-06          0.0541205        0.5906          46.9111           263.902               0.692961
s3dis_1.ply n=384067 k=1           5.4495e-06         0.0532817        0.0495565        0.48224            2.66005             0.109903
s3dis_1.ply n=38407 k=1            5.4605e-06         0.0525352        0.00413794       0.00650419         0.0268451           0.0114115
s3dis_1.ply n=3840664 k=37         5.3445e-06         0.0538865        0.603322        49.3663           325.895               4.74904
s3dis_1.ply n=384067 k=37          5.41e-06           0.052926         0.0495071        0.587962           3.31281             0.665915
s3dis_1.ply n=38407 k=37           5.4945e-06         0.0527608        0.00410685       0.02104            0.0344573           0.0800618
s3dis_1.ply n=3840664 k=64         5.3565e-06         0.0541455        0.604132        50.8853           329.431               7.97215
s3dis_1.ply n=384067 k=64          5.4845e-06         0.0528591        0.0494618        1.02744            3.35219             0.965915
s3dis_1.ply n=38407 k=64           5.452e-06          0.0528452        0.00408304       0.0484049          0.0350073           0.0698871
s3dis_2.ply n=804674 k=1           5.3755e-06         0.0532994        0.11302          2.04581           11.7093              0.142035
s3dis_2.ply n=80468 k=1            5.512e-06          0.0529944        0.00923748       0.0300416          0.116864            0.0129425
s3dis_2.ply n=8047 k=1             5.5085e-06         0.0527527        0.000785172      0.00106958         0.00126732          0.00152889
s3dis_2.ply n=804674 k=37          5.534e-06          0.0530813        0.11306          2.36171           14.8421              0.765365
s3dis_2.ply n=80468 k=37           5.4735e-06         0.052743         0.00924466       0.102002           0.145797            0.0939581
s3dis_2.ply n=8047 k=37            5.483e-06          0.0526203        0.000786222      0.00263064         0.00179303          0.00725037
s3dis_2.ply n=804674 k=64          5.2555e-06         0.0529379        0.112957         3.29546           15.301               1.27572
s3dis_2.ply n=80468 k=64           5.403e-06          0.0525655        0.00924367       0.24911            0.145993            0.167751
s3dis_2.ply n=8047 k=64            5.4515e-06         0.0530767        0.000786062      0.00390724         0.00188             0.014337
random n=804674 k=1                5.315e-06          0.0535532        0.171366         2.05498           11.714               0.190074
random n=80468 k=1                 5.4885e-06         0.0528218        0.011532         0.0303584          0.116846            0.0166791
random n=8047 k=1                  5.5145e-06         0.0526933        0.000922857      0.00107907         0.00127199          0.00185501
random n=804674 k=37               5.486e-06          0.0533956        0.168887         2.59687           14.5773              1.19661
random n=80468 k=37                5.4465e-06         0.0526578        0.0115278        0.118103           0.148145            0.129437
random n=8047 k=37                 5.4795e-06         0.0525156        0.000921083      0.00431573         0.00204531          0.0105963
random n=804674 k=64               5.313e-06          0.0529133        0.16878          3.54473           15.1594              1.9558
random n=80468 k=64                5.431e-06          0.0526288        0.0117159        0.236653           0.150715            0.232694
random n=8047 k=64                 5.4355e-06         0.0525884        0.000921104      0.00725541         0.00228307          0.0188549
```

**Review by yxlao — APPROVED** [review]

**Pull request merged**
