### PR TITLE
UV MAPS Tutorial 

### PR DESCRIPTION
**Pull request by samliozge**
UV Maps tutorial added in the geometry section. 

- uvmaps.rst includes the tutorial.
- geometry/uvmaps  includes the images.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3538)

### CODE REVIEW

**Comment by reyanshsolis** [comment]
Hi @samliozge, thanks for the documentation. 
We are having a vertical arrangement of pictures in this PR like:
Screenshot from 2021-06-03 18-19-29

May we have something like this:
image

also, it might be better to resize the images to the same dim. 

Thanks.

**Comment by samliozge** [comment]
Some screenshots of the tutorial:

Screen Shot 2021-06-03 at 15 02 15

Screen Shot 2021-06-03 at 15 04 11

**Review by benjaminum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3538)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @germanros1987, @reyanshsolis, and @samliozge)

___
*[docs/tutorial/geometry/uvmaps.rst, line 20 at r1](https://reviewable.io/reviews/intel-isl/open3d/3538#-MbH93rCCFGsSbxpzYdW:-MbH93rD9BaEfcIfF1YH:bpo6pmc) ([raw file](https://github.com/intel-isl/open3d/blob/e4b2589ebd47eb27085be4b913d451c01736f6ef/docs/tutorial/geometry/uvmaps.rst#L20)):*
> ```reStructuredText
> * UV Map coordinates ``(U, V)`` are stored as ``std::vector<Eigen::Vector2d>`` of length ``3 x number of triangles``. So, there is a set of 3 (U, V) coordinates for each triangle, each associated with it's vertices.
> * One may assume the UV map, maps a texture image of height and width of length 1.0 to the geometry. So, the range of U and V is from 0.0 to 1.0 (both inclusive).
> ```

Can you add one or more python code examples here?
They should show how to manually assign the coordinates or modify the default uv maps.

**Comment by reyanshsolis** [comment]
@benjaminum Yes that would be great, but it is a bit non-trivial. I was thinking about explaining the `.cpp` source code I wrote to add these UV_maps for each object. But it will take some time. 

Also, @errissa is there a way to add texture images to geometry having the uv_map by using any function from the code itself? 
Currently, I am setting UV maps from code, and then editing the `.mtl` file by adding `map_Kd texture.png`, but some users might wanna do it from the code itself to automate their application.

**Review by benjaminum — COMMENTED** [review]
@reyanshsolis I was thinking about the "Custom UV Maps" section. Just a simple textured triangle example would help.

> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3538#-:-Mbb7itt0YEFlETY-7Kj:bioc2un)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @germanros1987, @reyanshsolis, and @samliozge)

**Comment by sharoseali** [comment]
> Some screenshots of the tutorial:
> 
> Screen Shot 2021-06-03 at 15 02 15
> 
> Screen Shot 2021-06-03 at 15 04 11

Can you share the link to this topic? I didn't find this tutorial in official open 3D documentation on a webpage

**Comment by yxlao** [comment]
This python example might be relevant: https://github.com/yxlao/exchange/tree/master/o3d_texture

**Review by errissa — APPROVED** [review]

**Review by benjaminum — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3538#-:-NOhgJK19FDONDxam_LP:bg7igkv)* status: 1 of 26 files reviewed, 1 unresolved discussion (waiting on @samliozge)

**Pull request merged**
