### PR TITLE
TSDF IO

### PR DESCRIPTION
**Pull request by theNded**
- Introduce hashmap IO from disk
- Implement TSDF IO from disk
- TODO
- [x] CWD and filename organization
- [x] Example and test

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/3750)

### CODE REVIEW

**Comment by yxlao** [comment]
@theNded I merged `master`, and also merged #3796 to this PR.

#3796's implementation might be updated due to review comments, but the API should be stable. It should make this PR simpler.

**Review by yxlao — CHANGES_REQUESTED** [review]
@theNded Merged `master` and #3796 to this PR.

#3796's implementation might be updated due to review comments, but the API should remain the same. So #3796 should be safe to use in this PR, so we may update this PR accordingly.

**Review by yxlao — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r2, 2 of 3 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3750)* status: 15 of 19 files reviewed, 10 unresolved discussions (waiting on @theNded)

___
*[cpp/open3d/core/hashmap/Hashmap.h, line 108 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg04hra7ldkaxnMYmaY:-Mg04hra7ldkaxnMYmaZ:bw6dhj5) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/core/hashmap/Hashmap.h#L108)):*
> ```objc
>     void Clear();
> 
>     /// Save active key and value to filename.key.npy and filename.value.npy
> ```

Update docstring. Do we require filename to end with `.npz`?
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 111 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg04mkx0dPHwOTlcy0Z:-Mg04mkx0dPHwOTlcy0_:b8coktr) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/core/hashmap/Hashmap.h#L111)):*
> ```objc
>     void Save(const std::string& filename);
> 
>     /// Load active key and value from .npy
> ```

Update docstring. Mention the k/v are loaded from .npz and the expected names of the tensors inside npz. 
___
*[cpp/open3d/t/geometry/TSDFVoxelGrid.h, line 47 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0ChiG4kh3_iALnmpU:-Mg0ChiG4kh3_iALnmpV:b-piopdd) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/geometry/TSDFVoxelGrid.h#L47)):*
> ```objc
> 
> namespace io {
> class TSDFVoxelGridMetadata;
> ```

I believe we should make TSDFVoxelGrid`'s expose all necessary attributes via public functions. This way, we don't need to make `TSDFVoxelGridMetadata` a friend class of `TSDFVoxelGrid`. It doesn't make sense for some attributes to be only visible via I/O but not via some APIs. 
___
*[cpp/open3d/t/io/CMakeLists.txt, line 13 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0E5kjBUOZYO3LCH-r:-Mg0E5kjBUOZYO3LCH-s:biq10k0) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/CMakeLists.txt#L13)):*
> ```CMake
> 
> target_sources(tio PRIVATE
>     file_format/FileXYZI.cpp
> ```

This is duplicated. Let's sort them and remove duplicates:

```
target_sources(tio PRIVATE
    file_format/FileJPG.cpp
    file_format/FilePLY.cpp
    file_format/FilePNG.cpp
    file_format/FilePTS.cpp
    file_format/FileXYZI.cpp
)
```
___
*[cpp/open3d/t/io/HashmapIO.h, line 42 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0EaUvBdtyJ-SZG-lR:-Mg0EaUvBdtyJ-SZG-lS:byuop87) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/HashmapIO.h#L42)):*
> ```objc
> /// TODO: change to .npz when supported.
> ///
> /// \param filename File name to read from.
> ```

update docstring
___
*[cpp/open3d/t/io/HashmapIO.h, line 45 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0EcRz7d3tLx_K3D7e:-Mg0EcRz7d3tLx_K3D7f:byuop87) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/HashmapIO.h#L45)):*
> ```objc
> core::Hashmap ReadHashmap(const std::string& filename);
> 
> /// Save a hash map's keys and values to a .npy files.
> ```

update docstring
___
*[cpp/open3d/t/io/HashmapIO.cpp, line 61 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg3lQf050-xiL_SHlxW:-Mg3lQf050-xiL_SHlxX:bb94snk) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/HashmapIO.cpp#L61)):*
> ```cpp
>     int length_value = values.GetLength();
>     if (length_key != length_value) {
>         utility::LogError("Incompatible key value length.");
> ```

print out the corresponding lenths
___
*[cpp/open3d/t/io/HashmapIO.cpp, line 73 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg3lMtA24NlpAKwWKR-:-Mg3lMtA24NlpAKwWKR0:b-8iwtb7) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/HashmapIO.cpp#L73)):*
> ```cpp
>     core::SizeVector element_shape_value(shape_value.begin() + 1,
>                                          shape_value.end());
>     utility::LogInfo("{} {}", dtype_key.ToString(), dtype_value.ToString());
> ```

remove prints
___
*[cpp/open3d/t/io/TSDFVoxelGridIO.h, line 44 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg3mP0h2hlPqcCsvlPu:-Mg3mP0h2hlPqcCsvlPv:byuop87) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/TSDFVoxelGridIO.h#L44)):*
> ```objc
> /// The general entrance for reading a TSDFVoxelGrid from a file.
> /// The entry is a json file, storing metadata and the path to .key.npy and
> /// .value.npy for a hashmap.
> ```

update docstring
___
*[cpp/open3d/t/io/TSDFVoxelGridIO.cpp, line 60 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg3m_KY4BOt2NgpyP4L:-Mg3m_KY4BOt2NgpyP4M:b-88q001) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/TSDFVoxelGridIO.cpp#L60)):*
> ```cpp
>         value["block_count"] = block_count_;
>         value["device"] = device_;
>         value["hashmap_file_name"] = hashmap_file_name_;
> ```

Now we have `npz`, shall we store all these attributes inside `.npz`? We store it as a scalar tensor. 

Having a pointer path can be inconvenient sometimes, e.g. 1) it can be an absolute path, a relative path, and if it is a relative path, it depends on the caller's path; 2) it is inconvenient to copy two files, so sometimes you missed the other file. 

Also, it has the added benefit that 1) will simplify the I/O code quite a bit here since we don't need to deal with json; 2) it can be loaded by anyone with numpy.

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3750)* status: 9 of 19 files reviewed, 10 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/core/hashmap/Hashmap.h, line 108 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg04hra7ldkaxnMYmaY:-Mg8JpsO0LYo2XR5icW2:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/core/hashmap/Hashmap.h#L108)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Update docstring. Do we require filename to end with `.npz`?
</blockquote></details>

Done.
___
*[cpp/open3d/core/hashmap/Hashmap.h, line 111 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg04mkx0dPHwOTlcy0Z:-Mg8K3FLESYqpw1DFQzH:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/core/hashmap/Hashmap.h#L111)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Update docstring. Mention the k/v are loaded from .npz and the expected names of the tensors inside npz. 
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/TSDFVoxelGrid.h, line 47 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0ChiG4kh3_iALnmpU:-Mg8KBe40eKQkwB-fkOM:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/geometry/TSDFVoxelGrid.h#L47)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

I believe we should make TSDFVoxelGrid`'s expose all necessary attributes via public functions. This way, we don't need to make `TSDFVoxelGridMetadata` a friend class of `TSDFVoxelGrid`. It doesn't make sense for some attributes to be only visible via I/O but not via some APIs. 
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/CMakeLists.txt, line 13 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0E5kjBUOZYO3LCH-r:-Mg8KO8z8kHCMFwfx3ni:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/CMakeLists.txt#L13)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

This is duplicated. Let's sort them and remove duplicates:

```
target_sources(tio PRIVATE
    file_format/FileJPG.cpp
    file_format/FilePLY.cpp
    file_format/FilePNG.cpp
    file_format/FilePTS.cpp
    file_format/FileXYZI.cpp
)
```
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/HashmapIO.h, line 42 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0EaUvBdtyJ-SZG-lR:-Mg8Kyr-6oDwHys4qERr:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/HashmapIO.h#L42)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

update docstring
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/HashmapIO.h, line 45 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0EcRz7d3tLx_K3D7e:-Mg8LOkq5yX3JLaSSN0s:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/HashmapIO.h#L45)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

update docstring
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/HashmapIO.cpp, line 61 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg3lQf050-xiL_SHlxW:-Mg8LZP8ByintXQQNlaL:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/HashmapIO.cpp#L61)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

print out the corresponding lenths
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/HashmapIO.cpp, line 73 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg3lMtA24NlpAKwWKR-:-Mg8Lb0K5FwvoGqD_hMR:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/HashmapIO.cpp#L73)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove prints
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/TSDFVoxelGridIO.h, line 44 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg3mP0h2hlPqcCsvlPu:-Mg8NCDI-ZorNDBANfFU:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/TSDFVoxelGridIO.h#L44)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

update docstring
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/TSDFVoxelGridIO.cpp, line 60 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg3m_KY4BOt2NgpyP4L:-Mg8NrpXBey-TYhSZivx:b4l61md) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/io/TSDFVoxelGridIO.cpp#L60)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Now we have `npz`, shall we store all these attributes inside `.npz`? We store it as a scalar tensor. 

Having a pointer path can be inconvenient sometimes, e.g. 1) it can be an absolute path, a relative path, and if it is a relative path, it depends on the caller's path; 2) it is inconvenient to copy two files, so sometimes you missed the other file. 

Also, it has the added benefit that 1) will simplify the I/O code quite a bit here since we don't need to deal with json; 2) it can be loaded by anyone with numpy.
</blockquote></details>

I agree that npz is a better format, but 1) we don't support string format in our Tensors, and 2) our npz (at least in cpp) does not support storing dict as an entry. We can use UInt8 Tensor to store strings, but that might cause confusion from a pure numpy loader. Shall we proceed with npz in this PR or revisit later?

**Review by yxlao — APPROVED** [review]
> Reviewed 8 of 9 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3750)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)

___
*[cpp/open3d/t/geometry/TSDFVoxelGrid.h, line 47 at r6](https://reviewable.io/reviews/isl-org/open3d/3750#-Mg0ChiG4kh3_iALnmpU:-MgOXSzD4UCcB-4tTWIH:becnaic) ([raw file](https://github.com/isl-org/open3d/blob/d1e18a6f74b6d2686807a7a7110ae0e3482a0df2/cpp/open3d/t/geometry/TSDFVoxelGrid.h#L47)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I've added read-only getter functions for them.

**Comment by yxlao** [comment]
Approved.

Pushed some changes to make the variables private, like other geometry data types.

Yes. agreed that we can revisit the Json v.s. NPZ issue, as we need to store strings.

Make sure to delete all commit messages when "Squash and merge", otherwise, we'll get a very long commit message in `git log`.

**Pull request merged**
