### PR TITLE
New voxel grid

### PR DESCRIPTION
**Pull request by theNded**
- Change the voxel grid from array of structures (AoS) to structure of arrays (SoA)
- Support string-based attribute map
- Initially support customized integration
- Complete tests enumerating different tensormap combinations
- SLAM with this new backend

in next PRs
- Tutorial

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4067)

### CODE REVIEW

**Review by stotko — CHANGES_REQUESTED** [review]
> Reviewed 10 of 22 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4067)* status: all files reviewed, 21 unresolved discussions (waiting on @theNded and @yxlao)

___
*[cpp/open3d/t/geometry/VoxelBlockGrid.h, line 31 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLmYtV1oBvYqnPuy1r:-MkLmYtV1oBvYqnPuy1s:bwm8f3n) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.h#L31)):*
> ```objc
> #include <string>
> #include <unordered_map>
> #include <unordered_set>
> ```

nit: Header not needed.
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.h, line 74 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLn17G7qDUMGkWftPe:-MkLn17G7qDUMGkWftPf:b-anaqct) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.h#L74)):*
> ```objc
> 
>     /// Default destructor.
>     ~VoxelBlockGrid() = default;
> ```

nit: Could be removed such that it will be implicitly defined.
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.h, line 147 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM2-eL0I1mH_3Vq7UB:-MkM2-eL0I1mH_3Vq7UC:b9fm0or) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.h#L147)):*
> ```objc
>     /// Obtain active block coordinates from a point cloud.
>     core::Tensor GetUniqueBlockCoordinates(const PointCloud &pcd,
>                                            float trunc_voxel_multiplier = 3.0);
> ```

The default value is different than in the function above. Is this intended?
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.h, line 226 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLow8B2xSZ-f1sLp8M:-MkLow8B2xSZ-f1sLp8N:b-uyfook) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.h#L226)):*
> ```
>     float voxel_size_ = -1;
>     int64_t block_resolution_ = -1;
> ```
Are these some invalid values for initialization with the 0-argument default constructor? What happens when a user does:
```
VoxelBlockGrid g;
g.Integrate(...);
```
Will this silently crash at some point or is a proper error message via `utility::LogError` thrown?
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.cpp, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLqZICDcDUdTM2C5XU:-MkLqZICDcDUdTM2C5XV:bfkgm3a) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.cpp#L43)):*
> ```cpp
> 
> ////////////////////
> /// Local functions
> ```

Make the local functions `static` and remove this comment.
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.cpp, line 79 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLr-0oCsqvczM9DY25:-MkLr-0oCsqvczM9DY26:b-cit2t4) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.cpp#L79)):*
> ```cpp
>         std::unordered_map<std::string, int> name_attr_map) {
>     TensorMap tensor_map("tsdf");
>     for (auto it : name_attr_map) {
> ```

nit: This is not an iterator, but the value of the map. `v` (or `value`) might be a better name here. Also use `auto&` to avoid copies.
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.cpp, line 195 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLsGCdEkxhLRTO8HjX:-MkLsGCdEkxhLRTO8HjY:b1u20ky) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.cpp#L195)):*
> ```cpp
> std::pair<core::Tensor, core::Tensor>
> VoxelBlockGrid::GetVoxelCoordinatesAndFlattenedIndices() {
>     core::Tensor active_buf_indices = block_hashmap_->GetActiveIndices();
> ```

nit: Local variable could be inlined in function call like in `GetVoxelIndices()` above.
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.cpp, line 501 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLuVw_1qXgGZD2M0iw:-MkLuVw_1qXgGZD2M0ix:b-z42v7s) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.cpp#L501)):*
> ```cpp
>     std::string ext =
>             utility::filesystem::GetFileExtensionInLowerCase(file_name);
>     std::string postfix = ext != "npz" ? ".npz" : "";
> ```

The `Load()` function does not explicitly apply the postfix. It could also be confusing if the filename is silently changed, so throwing an error or at least a warning instead would be better.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLw0_j0Faj3L3ij_9g:-MkLw0_j0Faj3L3ij_9h:b-glr7o6) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L43)):*
> ```cpp
> namespace voxel_grid {
> 
> using index_t = int;
> ```

Already defined in header.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 215 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLweia5dLGokTSkRaE:-MkLweia5dLGokTSkRaF:b-n5o5br) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L215)):*
> ```cpp
>         DISPATCH_VALUE_DTYPE_TO_TEMPLATE(
>                 block_weight_dtype, block_color_dtype, [&] {
>                     IntegrateDeviceDispatcher<input_depth_t, input_color_t,
> ```

The naming convention for the variables is very consistent and straightforward here. Could we inline this template function since it is only used here?
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 287 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLwy2FCAKnqnzOhKlj:-MkLwy2FCAKnqnzOhKlk:b-q64pkt) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L287)):*
> ```cpp
>     DISPATCH_VALUE_DTYPE_TO_TEMPLATE(
>             block_weight_dtype, block_color_dtype, [&] {
>                 RayCastDeviceDispatcher<tsdf_t, weight_t, color_t>(
> ```

See above.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 352 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLwzK21UiYXzgjoHnC:-MkLwzK21UiYXzgjoHnD:b-q64pkt) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L352)):*
> ```cpp
>     DISPATCH_VALUE_DTYPE_TO_TEMPLATE(
>             block_weight_dtype, block_color_dtype, [&] {
>                 ExtractPointCloudDeviceDispatcher<tsdf_t, weight_t, color_t>(
> ```

See above.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 423 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLx-wM5GoVlMmRN_Gn:-MkLx-wM5GoVlMmRN_Go:b-q64pkt) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L423)):*
> ```cpp
>     DISPATCH_VALUE_DTYPE_TO_TEMPLATE(
>             block_weight_dtype, block_color_dtype, [&] {
>                 ExtractTriangleMeshDeviceDispatcher<tsdf_t, weight_t, color_t>(
> ```

See above.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGridCPU.cpp, line 51 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLxTGa85l4OAkTFXLn:-MkLxTGa85l4OAkTFXLo:b-xi9e8n) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGridCPU.cpp#L51)):*
> ```cpp
> using index_t = int;
> 
> struct Coord3i {
> ```

Question: This seems like the equivalent to `TSDFVoxelGridCPU`. Will the latter the deprecated/dropped in favor of this new version? Would it make sense to share common code between these two?

Same applies to the CUDA version below.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h, line 102 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLyNO74I8uhMbCVbqB:-MkLyNO74I8uhMbCVbqC:bxhetzn) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h#L102)):*
> ```objc
> 
> inline OPEN3D_DEVICE index_t
> DeviceGetLinearIdx(index_t xo,
> ```

This is also defined in `TSDFVoxel.h` above. Could we have a shared implementation or is there a reason to keep them separate?
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h, line 780 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLzeHkEJyfcjHAYfLJ:-MkLzeHkEJyfcjHAYfLK:b-yk819e) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h#L780)):*
> ```objc
> 
>             if (sum_r > 0) {
>                 sum_r *= 255.0;
> ```

Is the color always in the range `[0,255]` even when `color_t` is `float`?
___
*[cpp/open3d/t/pipelines/slam/Model.cpp, line 55 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM0qbR5ENgFRTsYx0K:-MkM0qbR5ENgFRTsYx0L:b-sckopf) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/pipelines/slam/Model.cpp#L55)):*
> ```cpp
>                   est_block_count,
>                   device) {
>     T_frame_to_world_ = (T_init.To(core::Device("CPU:0")));
> ```

nit: Why is this moved from the initializer list to the constructor body?
___
*[cpp/pybind/t/geometry/voxel_block_grid.cpp, line 52 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM1HXi4Ael1QZkdXMS:-MkM1HXi4Ael1QZkdXMT:bv5rjkp) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/pybind/t/geometry/voxel_block_grid.cpp#L52)):*
> ```cpp
>                      int64_t, const core::Device&>(),
>             "attr_names"_a, "attr_dtypes"_a, "attr_channels"_a,
>             "voxel_size"_a = 0.0058, "block_resolution"_a = 8,
> ```

There is no default `voxel_size` in the C++ version and the default `block_resolution` is `16`. Is this choice consistent with the older `TSDFVoxelGrid` approach? Should we make it consistent with the C++ version instead?
___
*[cpp/pybind/t/geometry/voxel_block_grid.cpp, line 137 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM1eMi02MtZGhTKO5z:-MkM1eMi02MtZGhTKO6-:b-gx27pw) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/pybind/t/geometry/voxel_block_grid.cpp#L137)):*
> ```cpp
>             "voxel block. They need to be inserted in the hash map.",
>             "depth"_a, "intrinsic"_a, "extrinsic"_a, "depth_scale"_a = 1000.0f,
>             "depth_max"_a = 3.0f, "trunc_voxle_multiplier"_a = 4.0);
> ```

`trunc_voxle_multiplier` -> `trunc_voxel_multiplier`
___
*[cpp/pybind/t/geometry/voxel_block_grid.cpp, line 143 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM1pXsDvDzkwv5FOf-:-MkM1pXsDvDzkwv5FOf0:b80tafm) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/pybind/t/geometry/voxel_block_grid.cpp#L143)):*
> ```cpp
>                     &VoxelBlockGrid::GetUniqueBlockCoordinates),
>             "Obtain active block coordinates from a point cloud.", "pcd"_a,
>             "trunc_voxel_multiplier"_a = 3.0);
> ```

The default value of the `trunc_voxel_multiplier` is different than above. Is this intended?  
___
*[cpp/tests/t/geometry/VoxelBlockGrid.cpp, line 37 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM2FMpCoKTwZZpSlwR:-MkM2FMpCoKTwZZpSlwS:b-6kied) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/tests/t/geometry/VoxelBlockGrid.cpp#L37)):*
> ```cpp
> #include "open3d/t/io/NumpyIO.h"
> #include "open3d/visualization/utility/DrawGeometry.h"
> // #include "tests/UnitTest.h"
> ```

Comment this in?! Is this header not needed here?

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4067)* status: 20 of 28 files reviewed, 17 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/open3d/t/geometry/VoxelBlockGrid.h, line 147 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM2-eL0I1mH_3Vq7UB:-MkN-7Tx2NNYpGZk3-hN:b29hzah) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.h#L147)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

The default value is different than in the function above. Is this intended?
</blockquote></details>

Yes for minor performance improvement, changed to the same to be consistent -- users can tune it anyways.
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.h, line 226 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLow8B2xSZ-f1sLp8M:-MkN-Oq58s5MkCeXmQoW:b-gzz4c6) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.h#L226)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

> ```
>     float voxel_size_ = -1;
>     int64_t block_resolution_ = -1;
> ```
Are these some invalid values for initialization with the 0-argument default constructor? What happens when a user does:
```
VoxelBlockGrid g;
g.Integrate(...);
```
Will this silently crash at some point or is a proper error message via `utility::LogError` thrown?
</blockquote></details>

Fixed by adding an AssertInitialized function. Also added brief test code.
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.cpp, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLqZICDcDUdTM2C5XU:-MkN5s1O6sje1BzYSejr:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.cpp#L43)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Make the local functions `static` and remove this comment.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/VoxelBlockGrid.cpp, line 501 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLuVw_1qXgGZD2M0iw:-MkN70Cn1ZW26vgIwrKA:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/VoxelBlockGrid.cpp#L501)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

The `Load()` function does not explicitly apply the postfix. It could also be confusing if the filename is silently changed, so throwing an error or at least a warning instead would be better.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 43 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLw0_j0Faj3L3ij_9g:-MkN7sdm3_faBaxtDh6J:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L43)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Already defined in header.
</blockquote></details>

Done.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 215 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLweia5dLGokTSkRaE:-MkN8K2420V2A0OnH4P2:bowzogx) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L215)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

The naming convention for the variables is very consistent and straightforward here. Could we inline this template function since it is only used here?
</blockquote></details>

Windows CI seems to be unhappy with the macro expansion if I inline the functions, see https://github.com/isl-org/Open3D/runs/3659351138. 
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 287 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLwy2FCAKnqnzOhKlj:-MkN8n7576_P2u0ZVHQs:b-3cz4ey) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L287)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Same above.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 352 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLwzK21UiYXzgjoHnC:-MkN8nmzAUr_ReLkUlBT:b-3cz4ey) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L352)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Same above.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 423 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLx-wM5GoVlMmRN_Gn:-MkN8o_A4vgMzOqudtqD:b-3cz4ey) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L423)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Same above.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGridCPU.cpp, line 51 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLxTGa85l4OAkTFXLn:-MkN9IIX7ljYLOc-y17O:bnn0mpb) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGridCPU.cpp#L51)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Question: This seems like the equivalent to `TSDFVoxelGridCPU`. Will the latter the deprecated/dropped in favor of this new version? Would it make sense to share common code between these two?

Same applies to the CUDA version below.
</blockquote></details>

Yes, `TSDFVoxelGrid` will be deprecated after this PR is merged. The duplicates will be cleaned up in a following PR.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h, line 102 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLyNO74I8uhMbCVbqB:-MkN9T3lAvLTLfttK9Yz:b-3cz4ey) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h#L102)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

This is also defined in `TSDFVoxel.h` above. Could we have a shared implementation or is there a reason to keep them separate?
</blockquote></details>

Same above.
___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h, line 780 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLzeHkEJyfcjHAYfLJ:-MkN9Tyw9e5uwNWjCH24:b-qnixpp) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGridImpl.h#L780)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Is the color always in the range `[0,255]` even when `color_t` is `float`?
</blockquote></details>

Fixed by adding a multiplier to float input during integration.
___
*[cpp/open3d/t/pipelines/slam/Model.cpp, line 55 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM0qbR5ENgFRTsYx0K:-MkNB5xv8SG4wUiRDmEi:b-zosvp) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/pipelines/slam/Model.cpp#L55)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

nit: Why is this moved from the initializer list to the constructor body?
</blockquote></details>

Forgot to clean up. Fixed.
___
*[cpp/pybind/t/geometry/voxel_block_grid.cpp, line 52 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM1HXi4Ael1QZkdXMS:-MkNBMaw1jd2zf-2yhR_:bnoqk7g) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/pybind/t/geometry/voxel_block_grid.cpp#L52)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

There is no default `voxel_size` in the C++ version and the default `block_resolution` is `16`. Is this choice consistent with the older `TSDFVoxelGrid` approach? Should we make it consistent with the C++ version instead?
</blockquote></details>

Fixed, thanks!!
___
*[cpp/pybind/t/geometry/voxel_block_grid.cpp, line 137 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM1eMi02MtZGhTKO5z:-MkNBhJS3gZezKKlIKqp:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/pybind/t/geometry/voxel_block_grid.cpp#L137)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`trunc_voxle_multiplier` -> `trunc_voxel_multiplier`
</blockquote></details>

Done.
___
*[cpp/pybind/t/geometry/voxel_block_grid.cpp, line 143 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM1pXsDvDzkwv5FOf-:-MkNBhgh8rtwES0_V9zC:bx1gsvk) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/pybind/t/geometry/voxel_block_grid.cpp#L143)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

The default value of the `trunc_voxel_multiplier` is different than above. Is this intended?  
</blockquote></details>

Same as above. Fixed.
___
*[cpp/tests/t/geometry/VoxelBlockGrid.cpp, line 37 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkM2FMpCoKTwZZpSlwR:-MkNBlww-rmNWoKY323W:bt2vr1b) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/tests/t/geometry/VoxelBlockGrid.cpp#L37)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Comment this in?! Is this header not needed here?
</blockquote></details>

Fixed.

**Review by stotko — COMMENTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4067)* status: all files reviewed, 2 unresolved discussions (waiting on @stotko, @theNded, and @yxlao)

___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 215 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLweia5dLGokTSkRaE:-MkNIWwf8oAYgwqWLKon:bralc3e) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L215)):*
<details><summary><i>Previously, theNded (Wei Dong) wrote…</i></summary><blockquote>

Windows CI seems to be unhappy with the macro expansion if I inline the functions, see https://github.com/isl-org/Open3D/runs/3659351138. 
</blockquote></details>

After looking at this again, this is related to using macro logic within the dispatched function, i.e. using macros in a macro which is not allowed. What about switching the order, i.e. having separate `DISPATCH_VALUE_DTYPE_TO_TEMPLATE` invocations for CPU and CUDA?

**Review by theNded — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4067)* status: 27 of 28 files reviewed, 2 unresolved discussions (waiting on @stotko and @yxlao)

___
*[cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp, line 215 at r2](https://reviewable.io/reviews/isl-org/open3d/4067#-MkLweia5dLGokTSkRaE:-MkNNZeb023AyO2Z-RYQ:b-nzjblg) ([raw file](https://github.com/isl-org/open3d/blob/e69c22ef05a73c696ccace05763b8f25cdb632d0/cpp/open3d/t/geometry/kernel/VoxelBlockGrid.cpp#L215)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

After looking at this again, this is related to using macro logic within the dispatched function, i.e. using macros in a macro which is not allowed. What about switching the order, i.e. having separate `DISPATCH_VALUE_DTYPE_TO_TEMPLATE` invocations for CPU and CUDA?
</blockquote></details>

Done, let's see if CI is happy.

**Review by stotko — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4067)* status: all files reviewed, 1 unresolved discussion (waiting on @theNded and @yxlao)

*[a discussion](https://reviewable.io/reviews/isl-org/open3d/4067#-MkNY4kY4vSHj3-5LE7l:-MkNY4k_27AZI7rBgFzJ:b-ia392) (no related file):*
LGTM, subject to any upcoming CI issues to be fixed.

---

**Comment by theNded** [comment]
@yxlao could you please double-check and merge this?

**Comment by yxlao** [comment]
> @yxlao could you please double-check and merge this?

Yes, I'll do that before tomorrow.

**Review by yxlao — APPROVED** [review]
> Reviewed 7 of 22 files at r1, 2 of 18 files at r2, 2 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4067)* status: 26 of 28 files reviewed, 1 unresolved discussion (waiting on @stotko and @theNded)

**Pull request merged**
