### PR TITLE
Added interaction methods for Python ImageWidget

### PR DESCRIPTION
**Pull request by MartinEekGerhardsen**
Adds and implements methods for setting MouseEvent
and KeyEvent callback functions for the ImageWidget in
Python. They are implemented identically to how this
feature is implemented for SceneWidget.

A PyImageWidget class is created similarly to PySceneWidget.
The required constructors are implemented, and the pybindings
are defined using this new class. This is only implemented for
Python, as the Mouse- and Key-methods from Widget
can already be implemented by inheriting from ImageWidget,
similarly to how this is implemented in SceneWidget.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4939)

### CODE REVIEW

**Comment by cow8** [comment]
ImageWidget is useful for reconstruction methods that require interaction to debug or annotation. looking forward to see this   feature in open3d

**Comment by MartinEekGerhardsen** [comment]
Agreed, that is why I wished to implement this feature. This is a pretty simple implementation that won't interfere with any other part of the Python bindings. Even though it is simple enough to implement this by inheriting from the ImageWidget in C++, it is as far as I know impossible in Python without some implementation such as this.

**Comment by MartinEekGerhardsen** [comment]
@errissa I don't really understand the error which caused the headless-docs check to fail, it seems to be something relating to the master branch. Should I not merge into the master branch, or should one perhaps not exist for my fork?

**Comment by MartinEekGerhardsen** [comment]
@errissa @ssheorey Any updates on this?

**Comment by MartinEekGerhardsen** [comment]
@errissa @ssheorey?

**Review by errissa — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4939)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MartinEekGerhardsen)

**Comment by MartinEekGerhardsen** [comment]
> > Reviewed 2 of 2 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4939)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MartinEekGerhardsen)

@errissa Sorry, not entirely sure what I'm supposed to do, I'm pretty new to this

**Pull request merged**
