### PR TITLE
[WIP] Tensor reconstruction system upgrade: global registration

### PR DESCRIPTION
**Pull request by theNded**
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/5183)

### CODE REVIEW

**Review by reyanshsolis — CHANGES_REQUESTED** [review]
TODO: Add unit tests. 

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5183#-:-NCzPnW2CA19FoDhDVYN:b79kmef)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @reyanshsolis and @theNded)

___
*[`cpp/open3d/t/pipelines/registration/Registration.h` line 246 at r2](https://reviewable.io/reviews/isl-org/open3d/5183#-NCzP_YYCsloU8M1x8Ht:-NCzP_YYCsloU8M1x8Hu:b-trn8yf) ([raw file](https://github.com/isl-org/open3d/blob/3071085a034a2ba3e14090038571c0655f6c14a8/cpp/open3d/t/pipelines/registration/Registration.h#L246)):*
> ```objc
> };
> 
> RegistrationResult RANSACBasedOnFeatureMatching(
> ```

add docstring. Move shape information to `\param` docstring. Same for the rest of this file.
___
*[`cpp/open3d/t/pipelines/registration/Registration.cpp` line 494 at r2](https://reviewable.io/reviews/isl-org/open3d/5183#-NCzPxE66mrppSsbrrwK:-NCzPxE66mrppSsbrrwL:b-ayc8c1) ([raw file](https://github.com/isl-org/open3d/blob/3071085a034a2ba3e14090038571c0655f6c14a8/cpp/open3d/t/pipelines/registration/Registration.cpp#L494)):*
> ```cpp
>         }
> 
>         // Estimate RANSAC result, on device
> ```

add `.` at the end of the comments. Same for rest of this file.

**Comment by reyanshsolis** [comment]
We may limit the scope of this PR to RANSAC implementation in tensor.

**Comment by ssheorey** [comment]
Hi @theNded are you planning for this PR to be ready for v0.17?

**Comment by theNded** [comment]
> Hi @theNded are you planning for this PR to be ready for v0.17?

Not likely, I will close is for now.

**Pull request closed without merging**
